### ISSUE TITLE
vrmonitor gui corrupted when started by VR application

### ISSUE THREAD

**Issue by ChristophHaag** [ValveSoftware/SteamVR-for-Linux#100]
Known issue since the beginning but it was not reported and tracked here.
![screenshot_20180406_211540](https://user-images.githubusercontent.com/781076/38439944-d7924b1a-39df-11e8-8c7a-ffbcd57adcee.png)
To reproduce: Start a VR application like hellovr_vulkan without SteamVR running.

**Comment by Zamundaaa** [comment]
I'm having the same issue but even worse. Today I started Pavlov VR without SteamVR running and all the textures were looking like randomly picked chunks of GPU memory

**Comment by ChristophHaag** [comment]
Do you run KDE/Plasma? I heard (but haven't tested) that it works on Gnome and it's possible that this is a kde specific issue.

I mean SteamVR packages an incompatible qt version, so maybe something with the qt theme or something...

**Comment by Zamundaaa** [comment]
Yes I am running KDE Plasma

**Comment by Lyle-Tafoya** [comment]
I am also able to reproduce this issue running Plasma desktop 5.14-4 on Arch Linux.

**Comment by ChristophHaag** [comment]
As per #229: This also happens after restarting SteamVR from the SteamVR menu. This was not in my initial issue report because restarting SteamVR did not work at the time

**Comment by Zamundaaa** [comment]
I don't have this issue anymore. The window appears and is all around fine when started by an application or by pressing one of the hardware buttons.

**Comment by Termuellinator** [comment]
For me, it is not as frequent anymore, but still happens often enough

**Comment by Goofybud16** [comment]
This still happens for me, even on 1.12.5.

When SteamVR is started by, at the very least, Proton VR applications, or by hardware turning on, SteamVR is very unhappy and has black squares.

![image](https://user-images.githubusercontent.com/669915/83572811-18dcb080-a4df-11ea-9669-dfa862d00c43.png)

Created a [system report](https://gist.github.com/Goofybud16/4ce6bece71bd504286907dc34ec27932)

When I launch SteamVR directly from Steam via the "Play" button, it works fine.

**Comment by Goofybud16** [comment]
On the latest, non-beta 1.12.5, activating SteamVR from a hardware device seems to work properly. It no longer loads with a broken GUI.

It also works properly when launched by Beat Saber.

I think that counts my issues as resolved, at least on the stable branch of SteamVR.

**Comment by ChristophHaag** [comment]
I think this is mostly solved now.
