### ISSUE TITLE
RX 480 GPU hang with Locomancer since Unity 2017.3 update

### ISSUE THREAD

**Issue by ChristophHaag** [ValveSoftware/SteamVR-for-Linux#101]
Back [in february](https://steamcommunity.com/app/490250/discussions/0/135513901709001238/?ctp=7#c1693788202024743416) Locomancer was updated to use Unity 2017.3. Since then it causes a GPU hang immediately when rendering the first frame after the Unity logo. The Unity Logo shows fine in SteamVR, then in SteamVR it switches to the loading animation for Locomancer, it renders a frame in the preview window and then the GPU locks up.

It happens with my RX 480 with all the recent kernels and radv git versions since then, extended and direct mode.

```
Apr 11 18:28:49 c-pc kernel: amdgpu 0000:08:00.0: GPU fault detected: 147 0x00204801
Apr 11 18:28:49 c-pc kernel: amdgpu 0000:08:00.0:   VM_CONTEXT1_PROTECTION_FAULT_ADDR   0x0FF02C04
Apr 11 18:28:49 c-pc kernel: amdgpu 0000:08:00.0:   VM_CONTEXT1_PROTECTION_FAULT_STATUS 0x02048001
Apr 11 18:28:49 c-pc kernel: amdgpu 0000:08:00.0: VM fault (0x01, vmid 1, pasid 32806) at page 267398148, read from 'TC4' (0x54433400) (72)
Apr 11 18:29:00 c-pc kernel: [drm:amdgpu_job_timedout [amdgpu]] *ERROR* ring gfx timeout, last signaled seq=6768213, last emitted seq=6768215
```

**Comment by kisak-valve** [comment]
Hello @ChristophHaag, this issue should also be brought to the attention of the video driver vendor.

**Comment by ChristophHaag** [comment]
Forgot to mention that someone told me some unity bugs are worked around with the environment variable `RADV_DEBUG=zerovram`.

Locomancer does indeed work with RADV_DEBUG=zerovram. So there's a good chance Locomancer just has to upgrade to a better Unity version in the future and this will go away.

**Comment by ChristophHaag** [comment]
Probably an old driver bug.
