### ISSUE TITLE
vrcompositor segfault causing error 306

### ISSUE THREAD

**Issue by Goofybud16** [ValveSoftware/SteamVR-for-Linux#102]
#### System information
* Steam client version (build number or date): Apr 12 2018, at 12:13:32
* Distribution (e.g. Ubuntu): Debian Testing
* Graphics driver version: radv/radeonsi Mesa 17.8.3 Kernel 4.15 AMDGPU
* Gist for SteamVR System Information: https://gist.github.com/Goofybud16/0451f4df5aabf4421f8b84c1eb92cf2f
* Opted into Steam client beta?: Yes
* Opted into SteamVR beta?: No
* Have you checked for system updates?: Yes
* CPU: Ryzen R7 1700
* System RAM: 32GiB
* GPU: R9 Fury Nitro

#### Please describe your issue in as much detail as possible:
I attached my Vive to my system, configured it in KDE's Displays menu, then ran SteamVR. It did not work, and failed with error 306. DMESG has the line `vrcompositor[17747]: segfault at 0 ip 0000000000000000 sp 00007ffea3887aa8 error 14 in vrcompositor[400000+2e4000]` repeated twice per execution of SteamVR. I have a core file available if needed. I have tried Steam beta and non-beta, SteamVR beta and non-beta, as well as `STEAM_RUNTIME_PREFER_HOST_LIBRARIES=0`, `STEAM_RUNTIME_PREFER_HOST_LIBRARIES=1`, and no `STEAM_RUNTIME_PREFER_HOST_LIBRARIES=` at all.

#### Steps for reproducing this issue:
1. Open Steam
2. Run SteamVR
3. Observe that SteamVR does not function correctly, producing error code 306 or 307.

**Comment by kisak-valve** [comment]
Hello @Goofybud16, can you move/remove `/usr/share/vulkan/icd.d/intel_icd.x86_64.json` and see if it makes a difference? On my test box, I've renamed it to `intel_icd.x86_64.json.disabled`.

**Comment by Goofybud16** [comment]
I have moved the file:
```
$ ls /usr/share/vulkan/icd.d
intel_icd.x86_64.json.disabled  nvidia_icd.json  radeon_icd.x86_64.json
```

vrcompositor still appears to be crashing and the GUI application still shows error 306/307.

**Comment by Goofybud16** [comment]
I was successfully able to complete the tutorial.

I have some performance issues, but those are expected. I was noticing intermittent rendering bugs in Steam Home, but thats another issue.
