### ISSUE TITLE
OpenGL not composed correctly (weird squares) on amdgpu

### ISSUE THREAD

**Issue by valentindavid** [ValveSoftware/SteamVR-for-Linux#106]
#### Your system information
* Steam client version (build number or date): 1522709999
* Distribution (e.g. Ubuntu): Debian sid
* Graphics driver version (run nvidia-settings): Mesa 18.0.3
* Gist for SteamVR System Information: https://gist.github.com/valentindavid/10b6b40c2dc826b6b92f842d7f24fd78
* Opted into Steam client beta?: [Yes/No] Same result
* Opted into SteamVR beta?: [Yes/No] Same result
* Have you checked for system updates?: [Yes/No] Yes

#### Please describe your issue in as much detail as possible:
With AMD GPU (Vega 64), any OpenGL surface composed onto the vrcompositor ends up with a lot of weird squares. This includes both OpenGL VR application and OpenGL VR layers (like the dashboard).

Vulkan applications work great.

I have tested in on both Debian and Gentoo. Though Gentoo tend to have noisy squares on both sides, and Debian has one eye with repetitive patterns.

Here as some pictures:

![The dashboard](https://user-images.githubusercontent.com/432830/39939713-6c53219c-5557-11e8-9c52-ee2b36bb3459.png)

![EVERSPACE](https://user-images.githubusercontent.com/432830/39939728-7920dac2-5557-11e8-9323-ab21a1a8fb63.png)

![Zaccaria Pinball](https://user-images.githubusercontent.com/432830/39939735-8028d662-5557-11e8-93c8-c32f0413492a.png)

Note: Mesa 18.0.3 does not work well with SteamVR, room setup and tutorial do not run. I have a minor 1 line patch to disable debug assertions where it should not be enabled. I will send this patch to Mesa. But this should not affect this issue.

**Comment by valentindavid** [comment]
The first was the dashboard. The second is EVERSPACE. The third is Zaccaria Pinball.

**Comment by lostgoat** [comment]
This is a problem with radv which has been recently fixed in master:
https://patchwork.freedesktop.org/patch/221793/

Grabbing the latest tip should fix that issue for vega.

**Comment by lostgoat** [comment]
Let me know if the above fixes the issue for you, or whether we are looking at a different issue.

**Comment by valentindavid** [comment]
Now: Dashboard works, OpenGL applications work. But bring the dashboard when using an OpenGL application causes the same issue on the application and you have to restart it.

**Comment by valentindavid** [comment]
I will take a screenshot tomorrow.

**Comment by valentindavid** [comment]
Here is Zaccaria Pinball in the intro room. What you should see in front should be a big logo. We can only see dots of it. Yesterday I got it to work where nearly all was shown, and only a corner was broken.

![zaccaria_intro](https://user-images.githubusercontent.com/432830/39956013-af51083e-55d8-11e8-94dc-7300780f340c.png)

If you open the dashboard, then disaster. Same after closing it. The game has to be restarted.

![zaccaria_dashboard](https://user-images.githubusercontent.com/432830/39956029-df4838fa-55d8-11e8-86ed-24aea1ce54e3.png)

If you do not get in the dashboard and click randomly on the menu, you might get into the game.

![zaccaria_ingame](https://user-images.githubusercontent.com/432830/39956035-08796c12-55d9-11e8-8679-324f5456a86b.png)

Note that textures seem missing. And there are weird squares.

Again in game, if you open the dashboard, disater:

![zaccaria_ingame_after_dashboard](https://user-images.githubusercontent.com/432830/39956041-266b7c6a-55d9-11e8-9d52-16b053e9aa74.png)

**Comment by h1z1** [comment]
You know, I never put these two together but that looks an awfully lot like what I hit.  Unfortunately I don't have screenshots of games but one I did take before rebooting:

https://user-images.githubusercontent.com/17220053/46580113-b0c58680-c9ec-11e8-9648-3226ef9d44e8.png

1080TI.  Started after a bit of testing with CrazyJustice, assumed it was related to that.  Some games like TF2 were fine.

**Comment by valentindavid** [comment]
I have not seen this issue for a while. I am now using Mesa 18.3 branch. I think it can be closed.

**Comment by kisak-valve** [comment]
Closing per the last comment.
