### ISSUE TITLE
Room setup won't launch

### ISSUE THREAD

**Issue by yaomtc** [ValveSoftware/SteamVR-for-Linux#109]
#### Your system information
* Steam client version (build number or date): May 21 2018
* Distribution (e.g. Ubuntu): Kubuntu 17.10
* Graphics driver version (run nvidia-settings): Mesa 18.2
* Gist for SteamVR System Information: https://gist.github.com/yaomtc/9c5a3649171dbdd60f108ac30e8a0f60
* Opted into Steam client beta?: Yes
* Opted into SteamVR beta?: Yes
* Have you checked for system updates?: Yes

#### Please describe your issue in as much detail as possible:
While the Vive seems to work properly on my system (display, controllers, sensors), Room Setup fails to launch. I can see the window border appear for a second before it disappears. Here's the output:

https://gist.github.com/yaomtc/05aec92b79ea144764d4a470e38c4fe8

#### Steps for reproducing this issue:
1. Launch Steam
2. Launch SteamVR
3. Try to launch Room Setup

**Comment by kisak-valve** [comment]
This is the same issue as #105.

**Comment by yaomtc** [comment]
I've since tested on Solus, and Room Setup works there. However, Budgie does not allow the compositor to be disabled, so it's not optimal. I may test their KDE Plasma ISO next...

**Comment by yaomtc** [comment]
Update: SteamVR works decently well in the Plasma ISO of Solus, and room setup works there too. Maybe it has something to do with some older libraries Ubuntu uses.

**Comment by Datamats** [comment]
I can confirm this issue on my setup, but it is working fine if I change my branch to stable.

**Comment by ChristophHaag** [comment]
The stable branch has been updated since the last comment.

If you *need* to set up your room settings you can go to the SteamVR Settings and in the developer tab use the quick calibrate function.

It's more limited and I believe you need to put the HMD on the floor to calibrate because there's no height setting, but at least you get the play space center and the height from the floor set up.

**Comment by ernstp** [comment]
I did a "quick calibrate" but that worked quite bad in my room, even on the smallest setting.

However I saved the universeID from my chaperone_info.vrchap and copied the rest from my Windows install to Linux, so that's a workaround...

**Comment by valentindavid** [comment]
The application fails to requests the following extensions: `VK_KHR_external_semaphore_fd`, `VK_KHR_external_memory_fd`, `VK_KHR_get_memory_requirements_2`.

Here is a temporary work-around to apply to Mesa for those who need to configure their room:

```
Index: mesa/src/amd/vulkan/radv_entrypoints_gen.py
===================================================================
--- mesa.orig/src/amd/vulkan/radv_entrypoints_gen.py	2018-08-27 10:36:22.174078386 +0200
+++ mesa/src/amd/vulkan/radv_entrypoints_gen.py	2018-08-27 10:53:49.011613813 +0200
@@ -207,6 +207,8 @@
    % endif
    % if e.name == 'vkCreateInstance' or e.name == 'vkEnumerateInstanceExtensionProperties' or e.name == 'vkEnumerateInstanceLayerProperties' or e.name == 'vkEnumerateInstanceVersion':
       return !device;
+   % elif e.name in ['vkGetSemaphoreFdKHR', 'vkImportSemaphoreFdKHR', 'vkGetMemoryFdKHR', 'vkGetBufferMemoryRequirements2KHR', 'vkGetImageMemoryRequirements2KHR']:
+      return instance;
    % elif e.core_version:
       return instance && ${e.core_version.c_vk_version()} <= core_version;
    % elif e.extensions:
```

**Comment by Zamundaaa** [comment]
Works fine now with the latest beta. SteamVR tutorial doesn't ever show in VR though
