### ISSUE TITLE
Steam VR, Compositor is not fullscreen

### ISSUE THREAD

**Issue by Datamats** [ValveSoftware/SteamVR-for-Linux#113]
*Note:* Creating this as a seperate issue from #112 due to this being a complete different internal crash

#### Your system information
* Steam client version (build number or date): Jun 8 2018, 22:22:39
* Distribution (e.g. Ubuntu): Arch Linux
* Graphics driver version: mesa-dev (To get the newest vulkan extensions required for 
* Gist for SteamVR System Information: https://gist.github.com/Datamats/c26e96c05d28e8f2d6c6c672af9e3f40
* Opted into Steam client beta?: Yes
* Opted into SteamVR beta?: Tried both
* Have you checked for system updates?: Yes

#### Please describe your issue in as much detail as possible:
I installed the newest mesa version with the patches from @keith-packard adding all the vulkan extensions required for direct mode. When launching I get vrmonitor complaining about the compositor is not fullscreen and it basically just crashed, I tried both the stable and beta version of steamvr just to get the exact same result.

Checking out dmesg it was a segmentation fault in vrcompositor
`[ 2734.959634] vrcompositor[10023]: segfault at 0 ip 0000000000000000 sp 00007ffd3c6dceb8 error 14 in vrcompositor[400000+24d000]`

#### Steps for reproducing this issue:
1. Run SteamVR with mesa using the vulkan patches on a RX480

Various logs: https://gist.github.com/Datamats/f3360ab3a254a5cf3de1618ccbdd7b8f
Dump files: [dumps.zip](https://github.com/ValveSoftware/SteamVR-for-Linux/files/2146623/dumps.zip)

**Comment by kisak-valve** [comment]
Hello @Datamats, can you check if you have `/usr/share/vulkan/icd.d/intel_icd.x86_64.json`, move it somewhere out of the way and see if that makes a difference?

For reference, the attached minidump is a null pointer SIGSEGV crash in vrcompositor.

**Comment by Datamats** [comment]
I currently only have two ICD's `radeon_icd.i686.json` and `radeon_icd.x86_64.json`

**Comment by Datamats** [comment]
After recompiling mesa with the vulkan loader and messing a bit around I was able to get it working. I assume this error was not SteamVR's fault.
