### ISSUE TITLE
SteamVR assert(image->state == WSI_IMAGE_DRAWING); in radv

### ISSUE THREAD

**Issue by ChristophHaag** [ValveSoftware/SteamVR-for-Linux#114]
Issue is sorta known but not tracked I believe.

The assert is this one https://github.com/mesa3d/mesa/blob/6cbbd5b4f8c0fac468476ae19c5a02b42800f816/src/vulkan/wsi/wsi_common_display.c#L1669

I believe it usually happens when the HMD is not tracking (doesn't see a base station).

I patched in a workaround that prints a warning and continues: https://github.com/ChristophHaag/mesa-mesa/commit/17c987f8bf8a81065d31ec32d7bed3727849618e

With this workaround steamvr prints ~3 of these warnings per second while the HMD is outside the tracking volume of the base stations and everything recovers fine when the HMD comes back into it.

**Comment by lostgoat** [comment]
Should be fixed with:
https://steamcommunity.com/games/250820/announcements/detail/1723075465319557338
