### ISSUE TITLE
Stuttering in Vive

### ISSUE THREAD

**Issue by Zamundaaa** [ValveSoftware/SteamVR-for-Linux#116]
#### Your system information
* Steam client version (build number or date):  latest beta build as of 26th Juli 2018
* Distribution (e.g. Ubuntu): (K)Ubuntu
* Graphics driver version (run nvidia-settings): Using RX 580 with Mesa 18.1.4 from the padoka PPA
* Gist for SteamVR System Information: https://gist.github.com/Zamundaaa/d8d86a5b7aef0f88341f27d865428656
* Opted into Steam client beta?: [Yes/No] Yes
* Opted into SteamVR beta?: [Yes/No] Yes
* Have you checked for system updates?: [Yes/No] Yes

#### Please describe your issue in as much detail as possible:
There's often the issue of many missed frames. Only happening in SteamVR home, not before it launches. But even if that issue is temporarily gone, or if SteamVR home isn't started yet or if I exit it, if I move my head, most stuff looks double, as if it was jumping between the new image and older ones. This can't be seen on the display mirror though

#### Steps for reproducing this issue:
1. Start SteamVR
2. Move the headset

**Comment by Zamundaaa** [comment]
Do the chaperone bounds show those 'ghost frames' for you, too? And games? Because I tested Dota 2 yesterday and it has the same issue, although no missed frames like SteamVR home

**Comment by hjri** [comment]
it's quite hard to figure out what is even happening during that frame, i can only realize that it shows wrong camera angle i think and maybe wrong resolution? I didn't quite test it with with serious sam tho. I'll post more when i try it again.

**Comment by ChristophHaag** [comment]
I did a recording of the SteamVR compositor in extended mode of this bad frame: https://github.com/ValveSoftware/SteamVR-for-Linux/issues/68
Note that you can use `,` and `.` to navigate frame by frame on youtube.
I think it's pretty clearly an issue in SteamVR Home, or one that specifically SteamVR Home triggers specifically when reprojection starts or stops.

**Comment by Zamundaaa** [comment]
That video makes me pretty sure that we have two different issues here. As far as I remember, I didn't have such an issue. At least I don't have it now
I'll record a video of my problem to make it clearer, what my issue actually is

**Comment by hjri** [comment]
i think your issue with "seeing double" is actually slight delay between left and right eye, i think i had it too once or twice in SteamVR home i think. The very same issue is persistent on Payday 2 VR on Windows.

**Comment by Zamundaaa** [comment]
Yes that would make a lot of sense. Especially as I couldn't spot any issues with the video I recorded. But then again the issue doesn't arise if I don't move my head but only the controllers. They don't look double then

**Comment by Zamundaaa** [comment]
Okay it's not that. When I close one eye, the issue is stil very apparent. Also I have to correct myself, I've just not noticed the controllers having that problem, but they do, too. It's also more or less noticable on every other object

**Comment by Zamundaaa** [comment]
I've invesigated this further and it seems like it overestimates (and maybe underestimates, too) how far I'll have rotated my head in the next frame. Same for the controllers. Then it jumps back, maybe to correct itself, and all of that happens in the next frame again, too. And it seems to just be angular velocity, normal velocity doesn't seem to have such an issue

**Comment by Zamundaaa** [comment]
Okay this was 100% my fault. Sorry.
A year or so ago I disabled applications from blocking the system compositor because something crashed it too often. I thought I had enabled it again, but that wasn't the case. Now SteamVR Home isn't running buttersmooth either, but at least the really headache inducing lags are gone.

**Comment by skestle** [comment]
Hey @Zamundaaa, how is that setting changed in [K]Ubuntu? I seem to be having the same issue, but I not aware of where the settings are...

Mesa 19.1.2 padoka PPA, Vulkan 1.1.97, AMD Vega M GPU

**Comment by Zamundaaa** [comment]
This issue was only because of the extended display mode, where the system compositor can have an effect. With direct mode display, this will not be the same issue. For the slim chance you are still somehow using extended display: allowing the compositor to be disabled by apps is under Display and Monitor->Compositor->Allow applications to block compositing
However, I have noticed some weird artifacts in SteamVR Home lately as well. But only in SteamVR Home, and only sometimes.

**Comment by skestle** [comment]
Well, when I boot, the login screen is in the Vive. Rather annoying 😉.
So I think it's extending in strange ways...

**Comment by kisak-valve** [comment]
Hello @skestle, https://github.com/ValveSoftware/SteamVR-for-Linux/issues/156#issuecomment-441242811 may interest you.
