### ISSUE TITLE
SteamVR room setup crashes instantly on startup

### ISSUE THREAD

**Issue by Zamundaaa** [ValveSoftware/SteamVR-for-Linux#118]
#### Your system information
* Steam client version (build number or date): latest Steam beta as of 02.08.2018
* Distribution (e.g. Ubuntu): (K)Ubuntu 18.04
* Graphics driver version (run nvidia-settings): Using RX 580 with Mesa 18.1.4 from the padoka PPA
* Gist for SteamVR System Information: https://gist.github.com/Zamundaaa/23a3c6d23d5ed0da00a160c2b3422693
* Opted into Steam client beta?: [Yes/No] Yes
* Opted into SteamVR beta?: [Yes/No] Yes
* Have you checked for system updates?: [Yes/No] Yes

#### Please describe your issue in as much detail as possible:
Read the description. There isn't really more to say here

#### Steps for reproducing this issue:
1. Start SteamVR
2. Start Room Setup

here's the log from ~/.steam/steam/logs/

[vrclient_steamvr_room_setup.txt](https://github.com/ValveSoftware/SteamVR-for-Linux/files/2255186/vrclient_steamvr_room_setup.txt)

If you need more logs or testing or something, just request for it

**Comment by kisak-valve** [comment]
Hello @Zamundaaa, this issue is already being tracked at #105 / #109. Closing as a duplicate.
