### ISSUE TITLE
Big Screen VR menu not available

### ISSUE THREAD

**Issue by CodeMichael** [ValveSoftware/SteamVR-for-Linux#12]
#### Your system information
* Steam client version (build number or date): Jan 19 2017, at 01:23:20
* Distribution (e.g. Ubuntu): Archlinux
* Graphics driver version (run nvidia-settings): 375.27.10
* Gist for SteamVR System Information: https://gist.github.com/CodeMichael/bf039a65ac9b121d80465fd32f7a8a2e
* Opted into Steam client beta?: Yes
* Opted into SteamVR beta?: Yes
* Have you checked for system updates?: Yes

#### Please describe your issue in as much detail as possible:
The VR Big Screen menu doesn't appear when hitting the menu button on the controllers.  The system bar does appear: Clock, Volume, Settings, System.

#### Steps for reproducing this issue:
1. Launch Steam VR
2. Press the menu button on the controller
3. No Big Screen game menu apppears.

**Comment by aronschatz** [comment]
Can confirm @CodeMichael findings. The latest SteamVR beta (1487886215) doesn't show loading screens or any steam menus.

**Comment by serk7** [comment]
oh.. it's strange because after last patch it works now on me, didnt before.

**Comment by aronschatz** [comment]
@serk7 As of 1487904548, the menu now appears again.

**Comment by ErikBjare** [comment]
This issue should be closed.

**Comment by CodeMichael** [comment]
I'm still having the issue, but it's likely due to the fact that I'm not able to run with the runtime without crashing.  I'll close and reopen if the runtime doesn't ultimately fix it.
