### ISSUE TITLE
Dashboard "Exit VR" not working

### ISSUE THREAD

**Issue by Zamundaaa** [ValveSoftware/SteamVR-for-Linux#121]
#### Your system information
* Steam client version (build number or date): 13.8.18
* Distribution (e.g. Ubuntu): (K)Ubuntu 18.04
* Graphics driver version (run nvidia-settings): RX 580 with Mesa 18.3.0-devel
* Gist for SteamVR System Information: https://gist.github.com/Zamundaaa/62266d95a5ea55edc1eeb2f36c510660
* Opted into Steam client beta?: [Yes/No] Yes
* Opted into SteamVR beta?: [Yes/No] Yes
* Have you checked for system updates?: [Yes/No] Yes

#### Please describe your issue in as much detail as possible:
"Exit VR" should work. It doesn't do anything. As described in #119

#### Steps for reproducing this issue:
1.  start SteamVR
2.  try to exit from within the headset

**Comment by ryao** [comment]
#### Your system information
* Steam client version (build number or date): 1538437695
* Distribution (e.g. Ubuntu): Gentoo
* Graphics driver version (run nvidia-settings): Nvidia 396.54.06
* Gist for SteamVR System Information: https://gist.github.com/ryao/fe8d42b52fe3bb9df3f8ccdce8451cac
* Opted into Steam client beta?: [Yes/No] Yes
* Opted into SteamVR beta?: [Yes/No] No
* Have you checked for system updates?: [Yes/No] Yes

I have this issue too. When I try to exit VR, I get an error dialog on the desktop from kioslave saying "Could not find any application or handler for vrmonitor://quit".

**Comment by Plagman** [comment]
Need to register a vrmonitor:// URI handler like we do with steam://

**Comment by ryao** [comment]
@Plagman You do have a handler for vrmonitor, but it is called steamvr, not vrmonitor:

```
$ cat ~/.local/share/applications/valve-steamvr.desktop
[Desktop Entry]
Name=SteamVR
Comment=Application for managing and playing games on SteamVR
Exec="/home/richard/.local/share/Steam/steamapps/common/SteamVR/bin/vrmonitor.sh" %U
Icon=steamvr
Terminal=false
Type=Application
Categories=Game;
MimeType=x-scheme-handler/steamvr
```

**Comment by h1z1** [comment]
Can confirm this is still an issue.

**Comment by Lyle-Tafoya** [comment]
I am also able to reproduce this issue.

**Comment by Zamundaaa** [comment]
So now kio client pops up for me when pressing Quit VR, too. Calling vrmonitor://quit manually through xdg-open of course fails, too. Calling steamvr://quit, which actually executes the vrmonitor program prints out a lot of stuff into my terminal after returning (perhaps that's normal (?)) including it not finding a folder runtime but still executing the right binary in the end with the argument steamvr://quit. But that does apparently nothing. At least SteamVR doesn't quit

**Comment by Zamundaaa** [comment]
This seems to be fixed in the latest beta. Haven't had any problems with it anymore!
