### ISSUE TITLE
No sound output on the vive

### ISSUE THREAD

**Issue by Zamundaaa** [ValveSoftware/SteamVR-for-Linux#124]
#### Your system information
* Steam client version (build number or date): latest beta as of 26.08.18
* Distribution (e.g. Ubuntu): (K)Ubuntu
* Graphics driver version (run nvidia-settings): using RX 580 with Mesa 18.1.6 - padoka PPA
* Gist for SteamVR System Information: https://gist.github.com/Zamundaaa/39d863759c3dab10afa6e7230e7e20b6
* Opted into Steam client beta?: [Yes/No] Yes
* Opted into SteamVR beta?: [Yes/No] Yes
* Have you checked for system updates?: [Yes/No] Yes

#### Please describe your issue in as much detail as possible:
I expected a sound ouput for the vive headphone jack. Instead none of the HDMI outputs exposed by pulseaudio have a corresponding output on the vive

**Comment by Zamundaaa** [comment]
This seems like the same: https://askubuntu.com/questions/982883/htc-vive-usb-audio-not-detected

**Comment by kisak-valve** [comment]
Hello @Zamundaaa, double check pavucontrol while the vive's display is active. If the Vive is listed as an option, then set it as the default or fallback device.

**Comment by ChristophHaag** [comment]
Some people have said that the Vive has both, USB and HDMI audio. Personally I have only found HDMI audio on my Vive. (the microphone is an USB audio device, but I have not seen an USB audio output device)

So for HDMI audio on amdgpu AMD's "new" DAL/Display Core abstraction layer needs to be enabled.
If you run `dmesg | grep "Display Core"` and do **not** get output like `[drm] Display Core initialized with v3.1.62!` you likely won't get any HDMI audio at all. In that case it can be enabled by the linux kernel boot parameter `amdgpu.dc=1`. In rare cases it can cause issues with recognizing monitors or resolutions, if it's not enabled by default, then that's the reason.

And as kisak says, at least with HDMI audio, the audio output will only work as long as the Vive's display is on.

**Comment by Zamundaaa** [comment]
pavucontrol only lists a single HDMI output and that's probably just my VGA monitor that I connected via an adapter to HDMI. @ChristophHaag I added the kernel parameter amdgpu.dc=0 as my old crappy TV wouldn't display colors correctly otherwise. As I have a replacement display now I'll set it to 1 and try again

**Comment by Zamundaaa** [comment]
Works perfectly now. Thanks for the help!
