### ISSUE TITLE
Unable to find direct display

### ISSUE THREAD

**Issue by Datamats** [ValveSoftware/SteamVR-for-Linux#125]
#### Your system information
* Steam client version (build number or date): Aug 23 2018, 19:47:27
* Distribution (e.g. Ubuntu): Arch Linux
* Graphics driver version: tried both mesa-18.2.0-rc4 and [this fork](https://github.com/ChristophHaag/mesa-mesa)
* Gist for SteamVR System Information: https://gist.github.com/Datamats/99404bbe349ccffe042154e43691adac
* Opted into Steam client beta?: Yes
* Opted into SteamVR beta?: Tried both
* Have you checked for system updates?: Yes

#### Please describe your issue in as much detail as possible:
The SteamVR compositor is unable to run in direct mode, checking the logs it shows
```
Tried to find direct display through RandR: (nil)
Tried to find direct display through Vulkan WSI: (nil)
```

Checking xrandr the HMD shows up fine as a non-desktop monitor

```
HDMI-A-0 disconnected (normal left inverted right x axis y axis)
        EDID:
                00ffffffffffff0022d201aa00000000
                ff1a0103800000780260bcaa5540b623
                0c4c5200000001010101010101010101
                0101010101010474706a80b008412814
                c2047a44000000180474706a80b00841
                2814c2047a4400000018000000fc0048
                54432d564956450a20202020000000fd
                00147801ff1d010a20202020202001de
                02031540420102230907018301000065
                030c0010000474706a80b008412814c2
                04c078000000180474706a80b0084128
                14c204c078000000180474706a80b008
                412814c204c078000000180474706a80
                b008412814c204c07800000018000000
                00000000000000000000000000000000
                000000000000000000000000000000b1
        TearFree: on
                supported: off, on, auto
        dither: off
                supported: off, on
        audio: auto
                supported: off, on, auto
        scaling mode: None
                supported: None, Full, Center, Full aspect
        underscan vborder: 0
                range: (0, 128)
        underscan hborder: 0
                range: (0, 128)
        underscan: off
                supported: off, on, auto
        coherent: 1
                range: (0, 1)
        link-status: Good
                supported: Good, Bad
        non-desktop: 1
                range: (0, 1)
   2160x1200     89.53 +
   720x480       60.00    59.94
   640x480       60.00    59.94
```

Compositor / Server logs https://gist.github.com/Datamats/7ad656c4aec031dd11315928a52b2d57

**Comment by kisak-valve** [comment]
Hello @Datamats, what DDX are you using? SteamVR direct mode currently needs either xf86-video-modesetting from xorg server 1.20.1 or a git master build of xf86-video-amdgpu which is newer than 2018-07-10.

**Comment by Datamats** [comment]
Thanks @kisak-valve! After compiling the master of xf86-video-amdgpu and installing it everything started working.

**Comment by Zamundaaa** [comment]
@Datamats how would you go about compiling and installing it? Because I tried to and obviously did something wrong as it bricked by system
