### ISSUE TITLE
Camera not available

### ISSUE THREAD

**Issue by rcpoison** [ValveSoftware/SteamVR-for-Linux#126]
#### System information
* Steam client version: Aug 27 2018, at 19:03:23
* Distribution: Archlinux
* Graphics driver version: nvidia-396.54
* Gist for SteamVR System Information: https://gist.github.com/rcpoison/46bbbe4bc2336542e485da70c69ed4ec
* Opted into Steam client beta?: Yes
* Opted into SteamVR beta?: Yes
* Have you checked for system updates?: Yes

#### Please describe your issue in as much detail as possible:
SteamVR beta -> Settings -> Camera:
Simply shows an error: Camera Not Available.

Camera device exists and can be viewed with any uvc clivent:
```
Aug 28 18:37:37 draco kernel: uvcvideo: Found UVC 1.00 device HTC Vive (0bb4:2c87)
Aug 28 18:37:37 draco kernel: uvcvideo 1-11.1.2:1.0: Entity type for entity Extension 2 was not initialized!
Aug 28 18:37:37 draco kernel: uvcvideo 1-11.1.2:1.0: Entity type for entity Extension 6 was not initialized!
Aug 28 18:37:37 draco kernel: uvcvideo 1-11.1.2:1.0: Entity type for entity Extension 5 was not initialized!
Aug 28 18:37:37 draco kernel: uvcvideo 1-11.1.2:1.0: Entity type for entity Processing 3 was not initialized!
Aug 28 18:37:37 draco kernel: uvcvideo 1-11.1.2:1.0: Entity type for entity Camera 1 was not initialized!
Aug 28 18:37:37 draco kernel: usbcore: registered new interface driver uvcvideo
```
Error spotted in vrserver log:
```
vrserver.txt:Tue Aug 28 2018 19:19:29.934518 -   driver gamepad implements interfaces IVRSettings_002 ITrackedDeviceServerDriver_005 IVRDisplayComponent_002 IVRDriverDirectModeComponent_005 IVRCameraComponent_002 IServerTrackedDeviceProvider_004 IVRWatchdogProvider_001 IVRVirtualDisplay_002 IVRDriverManager_001 IVRResources_001 IVRCompositorPluginProvider_001 
vrserver.txt:Tue Aug 28 2018 19:19:29.960709 - lighthouse: InitTrackedCamera(): Failed to find expected interface on (LHR-51C87715). Camera services not available.
vrserver.txt:Tue Aug 28 2018 19:19:29.960728 -   driver lighthouse implements interfaces IVRSettings_002 ITrackedDeviceServerDriver_005 IVRDisplayComponent_002 IVRDriverDirectModeComponent_005 IVRCameraComponent_002 IServerTrackedDeviceProvider_004 IVRWatchdogProvider_001 IVRVirtualDisplay_002 IVRDriverManager_001 IVRResources_001 IVRCompositorPluginProvider_001
```

#### Steps for reproducing this issue:
1. Start SteamVR and try to enable camera.

**Comment by wolftype** [comment]
I can confirm we are experiencing the same "Camera Not Available" message when using SteamVR Beta with the Vive Pro.  When using SteamVR (not beta) the camera works, but we cannot fetch the Undistorted image, only the Distorted image.  Here is a related issue that was filed in OpenVR repo itself: https://github.com/ValveSoftware/openvr/issues/815

**Comment by ChristophHaag** [comment]
Bumping with a non-update: Still not working for me.

**Comment by kisak-valve** [comment]
With SteamVR beta (1.2.1), the Vive (non-pro) camera is usable on my testbox from vrdashboard.

**Comment by ChristophHaag** [comment]
Camera works for me too. Thanks.

**Comment by rcpoison** [comment]
Yay, it's working :) Thanks

**Comment by wolftype** [comment]
Can you confirm this is working with vive pro as well?  If so, can you let me know what version graphics driver you are on?  I am able to click "enable camera" but that causes my computer to hang (and no preview).   Note this behavior is with a vive pro on ubuntu 16.04 which nvidia driver 415.18 (I cannot upgrade to 18.04 yet for unrelated reasons).
