### ISSUE TITLE
Error code 306

### ISSUE THREAD

**Issue by Zamundaaa** [ValveSoftware/SteamVR-for-Linux#133]
#### Your system information
* Steam client version (build number or date): 21.09.2018
* Distribution (e.g. Ubuntu):  (K)Ubuntu
* Graphics driver version (run nvidia-settings): RX 580 with Mesa 18.3.0-devel from Oibaf PPA
* Gist for SteamVR System Information: https://gist.github.com/Zamundaaa/7b8b627fffa67167600bc12f8e30f6c2
* Opted into Steam client beta?: [Yes/No] Yes
* Opted into SteamVR beta?: [Yes/No] Yes
* Have you checked for system updates?: [Yes/No] Yes

#### Please describe your issue in as much detail as possible:
It seems like #122 is now fixed, but the fix comes with an error that's very much worse:
Connect Failed
A key component of SteamVR isn't working properly.
Error code 306
I think the fix is responsible for the error because of this in the log of the VRCompositor:
Fri Sep 21 2018 13:19:36.271449 - Found bad mirror window settings: 
Fri Sep 21 2018 13:19:36.271462 - Creating CHmdWindowSDL!
and the display mirror button is greyed out.

#### Steps for reproducing this issue:
1. Start SteamVR beta
2. be unable to play because of the error stopping the compositor from starting

**Comment by Zamundaaa** [comment]
I tested the latest Beta in Manjaro and it's working there. Must be something about Ubuntu or my system

**Comment by Zamundaaa** [comment]
It's now not putting the compositor on the Vive but just showing it as a borderless window but that could just be my fault as I tampered with the steam folder. But no crashes anymore in Ubuntu!

**Comment by jackleson** [comment]
How do you get no more crashed in Ubuntu? I still have the same issue.

**Comment by Zamundaaa** [comment]
I just downloaded the latest SteamVR beta and it worked, I don't know any fix other than that

**Comment by Zamundaaa** [comment]
I see that you wrote your vulkan install may have not worked. Why do you think so?

**Comment by jackleson** [comment]
My graphics card is the R9 390. Supposedly, Kernal 4.15 does not address it according to how the libvulcan needs it. The R9 series in general is not well supported on linux. I may try moving to kernal 14.18 or something see if that works. I don't really know if my card is the issue but this is what I have taken into consideration at the moment.

**Comment by Zamundaaa** [comment]
Is your system using radeon or amdgpu? I'd try to blacklist the one you're not using currently and look if it changes something. And I'd also try the latest (stable) kernel using ukuu, perhaps it could help

**Comment by jackleson** [comment]
When I install amdgpu (for R9 390 on ubuntu 18.04 from the AMD website) the system crashes on startup after a restart or shutdown and must be removed to allow ubuntu to boot. It also causes programs like steam to break/crash. This is probably also why Vulkan doesn't work. I have not tried black listing, but I don't see how that would help given that amdgpu doesn't even install correctly. People say on ubuntu 18.10 (having kernal 4.18) amdgpu and vulkan work like a charm.

**Comment by kisak-valve** [comment]
Hello @jackleson, mesa/radv needs amdgpu to work. If you're feeling adventurous, you could give https://launchpad.net/~kisak/+archive/ubuntu/steamvr a try.

**Comment by Zamundaaa** [comment]
@jackleson You shouldn't install the proprietary amdgpu-pro driver from the website. amdgpu is already installed, but it may not be used. To ensure your system's using amdgpu you have to blacklist radeon (if that gives you a black screen or something on login you'll have to use the terminal to change it back again. Or use a live install to do it
And installing a newer kernel is really fast&easy with ukuu, so just try it

**Comment by jackleson** [comment]
moved to Kernal 4.18.11 everything fine. I did the blacklist on radeon now my monitors are unrecognized and are only operating in mirror mode with weird graphical glitches during startup. ran lsmod to confirm radeon didn't show up only amdgpu. nothing changed Steamvr and Vulkan do not work. Going back now. Worth a try.

**Comment by Zamundaaa** [comment]
You shouldn't have to install amdgpu nor do I remember a download for it on the AMD website... Whatever
Those possible missing firmware things pop up for me most times, too. Doesn't really matter.
Are you running Ubuntu on Wayland? If so, you could try it on X. And of course you should try to reinstall libwayland-egl1 if you haven't already
