### ISSUE TITLE
Starting any VR app leads to indefinite loading screen or system freeze

### ISSUE THREAD

**Issue by yasarabio** [ValveSoftware/SteamVR-for-Linux#134]
#### Your system information
* Steam client version (build number or date):  1487886215 
* Distribution (e.g. Ubuntu):  Ubuntu 18.08
* Graphics driver version (run nvidia-settings): 390.87
* Gist for SteamVR System Information:  https://gist.github.com/yasarabio/786c9e3101be97c20310a9323862ea29
* Opted into Steam client beta?: [Yes/No] Yes
* Opted into SteamVR beta?: [Yes/No] Yes
* Have you checked for system updates?: [Yes/No] Yes

#### Please describe your issue in as much detail as possible:
Since update on 09/21:
1. SteamVR Home is very laggy
2. Starting VR tutorial in Home or Steam leads to indefinite loading screen
3. Starting a game (eg Serious Sam 3 VR) leads to system freeze

all three bugs did not occure before 09/21

#### Steps for reproducing this issue:
1. Update Steam beta (1487886215)
2. Start SteamVR
3. Try to start any app (like VR tutorial or a game)

**Comment by Vash63** [comment]
After you load into SteamVR home could you try moving your mouse around and seeing if your desktop is working OK? This may be a duplicate of #123

**Comment by yasarabio** [comment]
UPDATE: SteamVR beta 1537887867

Issues unchanged.

During start up of SteamVR and loading of Home occurrence of sporadic desktop freezes and no mouse movement.
Loading of home and snapping in of movement tracking takes quiet long.

When Home finally is loaded and movement tracking works (still very laggy), then desktop is ok and mouse movement possible without interruptions.

**Comment by yasarabio** [comment]
SOLVED

Installing the 410.57 - BETA driver downloaded from:
https://www.geforce.com/drivers/results/137935
following the instructions for manual install from:
https://linuxconfig.org/how-to-install-the-nvidia-drivers-on-ubuntu-18-04-bionic-beaver-linux
solved all issues. Movement tracking is now very smooth, all apps/games load quickly and mouse movement on the desktop is undisturbed.

Note: For now the 410 driver is not available over ppa.
