### ISSUE TITLE
Cannot quit VR when using KDE5 as my desktop environment

### ISSUE THREAD

**Issue by ryao** [ValveSoftware/SteamVR-for-Linux#135]
#### Your system information
* Steam client version (build number or date): 1538437695
* Distribution (e.g. Ubuntu): Gentoo
* Graphics driver version (run nvidia-settings): Nvidia 396.54.06
* Gist for SteamVR System Information: https://gist.github.com/ryao/fe8d42b52fe3bb9df3f8ccdce8451cac
* Opted into Steam client beta?: [Yes/No] Yes
* Opted into SteamVR beta?: [Yes/No] No
* Have you checked for system updates?: [Yes/No] Yes

#### Please describe your issue in as much detail as possible:
Describe what you _expected_ should happen and what _did_ happen. Please link any large code pastes as a [Github Gist](https://gist.github.com/)
I am unable to exit VR from inside the VR headset. I should have been able to exit. Coincidentially, I cannot start VR by pressing the button on the side of the headset either.

#### Steps for reproducing this issue:
1. Start VR.
2. Put on headset
3. Try to exit VR and get an error dialog on the desktop from kioslave saying "Could not find any application or handler for vrmonitor://quit"

**Comment by ryao** [comment]
This is a duplicate issue of #121. There is more detail here, so I'll repost it there.

**Comment by Zamundaaa** [comment]
hmm I can start VR by pressing the button on the Vive. And I never got an error dialog
