### ISSUE TITLE
Opening the dashboard in Space Pirate Trainer causes it to stop working

### ISSUE THREAD

**Issue by ryao** [ValveSoftware/SteamVR-for-Linux#136]
#### Your system information
* Steam client version (build number or date): 1538437695
* Distribution (e.g. Ubuntu): Gentoo
* Graphics driver version (run nvidia-settings): Nvidia 396.54.06
* Gist for SteamVR System Information: https://gist.github.com/ryao/fe8d42b52fe3bb9df3f8ccdce8451cac
* Opted into Steam client beta?: Yes
* Opted into SteamVR beta?: No
* Have you checked for system updates?: Yes

#### Please describe your issue in as much detail as possible:
I expected to be able to resume playing Space Pirate Trainer. Instead, it refused to resume and if I recall correclty, I got a black screen. Coincidentally, if you open the dashboard while Space Pirate Trainer is loading, it will fail to load.

#### Steps for reproducing this issue:
1. Start Steam.
2. Start SteamVR.
3. Start Space Pirate Trainer.
4. Put on VR Headset
5. Open dashboard.
6. Close dashboard and it never resumes. You get a black screen if I recall correctly.

Alternatively, you can 

1. Start Steam.
2. Start SteamVR.
3. Start SteamVR Home
4. Put on VR Headset
5. Start Space Pirate Trainer.
6. Open dashboard before it loads.
7. Close dashboard and it never loads.

**Comment by beniwtv** [comment]
I can reproduce this on Manajaro with Steam and SteamVR and Proton 3.16 (all betas) for Space Pirate Trainer. Can't test job simulator, as it seems to crash for me.

**Comment by Zamundaaa** [comment]
This happens for me in space pirate trainer, too.

**Comment by ryao** [comment]
There is no longer an issue with proton 4.11-2 and SteamVR beta 1.7.4. I don't know when it was fixed.
