### ISSUE TITLE
Steam Home and the dashboard do not start with SteamVR

### ISSUE THREAD

**Issue by ryao** [ValveSoftware/SteamVR-for-Linux#137]
#### Your system information
* Steam client version (build number or date): 1538437695
* Distribution (e.g. Ubuntu): Gentoo
* Graphics driver version (run nvidia-settings): Nvidia 396.54.06
* Gist for SteamVR System Information: https://gist.github.com/ryao/fe8d42b52fe3bb9df3f8ccdce8451cac
* Opted into Steam client beta?: Yes
* Opted into SteamVR beta?: No
* Have you checked for system updates?: Yes

#### Please describe your issue in as much detail as possible:
When I start SteamVR, Steam Home should start, the dashboard should start and I should see hands with power indicators on the Steam controllers. Instead, I am in a white space with some lines, there are no hands on the steam controller, there are no power indicators and I cannot access the dashboard because it did not work.

#### Steps for reproducing this issue:
1. Start Steam.
2. Start SteamVR
3. Put on HMD.
4. Start steam controllers.
5. Try to open dashboard.

If I manually start Steam Home, then things work.

**Comment by kisak-valve** [comment]
Hello @ryao, you can also start vrdashboard with
```
cd ~/.local/share/Steam/steamapps/common/SteamVR/bin/linux64
LD_LIBRARY_PATH="." ./vrdashboard
```
This issue occurs on Gentoo, but not Ubuntu 18.04.

**Comment by ryao** [comment]
@kisak-valve That is what I sometimes do, although I figured out that I can just start SteamVR Home and the dashboard starts with it.

**Comment by kisak-valve** [comment]
Hello @ryao, please retest this issue with the SteamVR beta (1.2.1).

**Comment by kisak-valve** [comment]
Closing pending feedback.
