### ISSUE TITLE
Desktop view crashes steam

### ISSUE THREAD

**Issue by Zamundaaa** [ValveSoftware/SteamVR-for-Linux#144]
#### Your system information
* Steam client version (build number or date): latest beta 12.10.2018
* Distribution (e.g. Ubuntu): Manjaro KDE
* Graphics driver version (run nvidia-settings): RX 580 with Mesa 18.2.2
* Gist for SteamVR System Information: https://gist.github.com/Zamundaaa/750aef9f4e60c6d0336b82cb0033f19d
* Opted into Steam client beta?: [Yes/No] Yes
* Opted into SteamVR beta?: [Yes/No] Yes
* Have you checked for system updates?: [Yes/No] Yes

#### Please describe your issue in as much detail as possible:
When opening desktop view the steam client and the dashboard seem to crash. The dashboard doesn't react anymore (I can still close it though) and like 5 seconds later the app I've been playing closes. SteamVR is still running. If I now click on the steam icon on the desktop it opens steam again with updating etc, so it crashed.

#### Steps for reproducing this issue:
1. Open Dashboard
2. Open desktop view

**Comment by kisak-valve** [comment]
Hello @Zamundaaa, was there a 3d rendered window on the desktop (like the mirrored output of a VR game)? Does it work with a VR game that does not have a mirrored output like SteamVR Home?

**Comment by h1z1** [comment]
Had this happen yesterday, was just sitting in Home.  Crashed a few seconds after.   Mirrored output was on.

**Comment by lostgoat** [comment]
Fixed on the following steam client beta update:
https://steamcommunity.com/groups/SteamClientBeta#announcements/detail/1694935665148459873

**Comment by h1z1** [comment]
@lostgoat  Is that the same code behind adding a panel with it in vrhome?  Dashboard works but home doesn't, not sure if they are related

**Comment by h1z1** [comment]
Bump?
