### ISSUE TITLE
Room Setup Crashes while idle

### ISSUE THREAD

**Issue by lostgoat** [ValveSoftware/SteamVR-for-Linux#150]
Room Setup segfaults after being idle for a few minutes.

Separating this issue from #105

**Comment by FictionX** [comment]
Not necessarily idle. It crashes no matter what I do. In my case it crashes 30 seconds in every time, no matter how far I've gotten in the process.

Thanks for creating a new issue.

**Comment by lostgoat** [comment]
Fixed in the following steam beta release:
https://steamcommunity.com/games/250820/announcements/detail/1697188731109135045
