### ISSUE TITLE
Issues with some proton games & async reprojection (radv)

### ISSUE THREAD

**Issue by ChristophHaag** [ValveSoftware/SteamVR-for-Linux#152]
Using RX 480 with latest mesa git: [sysinfo.txt](https://github.com/ValveSoftware/SteamVR-for-Linux/files/2544565/sysinfo.txt)

This affects some games. One of them is Senza Peso. Here's a video: https://www.youtube.com/watch?v=fV6IuRvNrPk
If you watch the frame time graph, you'll see the issues. There's this stair effect where some bad effects accumulate and then some massive CPU usage happens.

Using enableLinuxVulkanAsync" : false, makes the frame timings a lot better though there are still issues sometimes like this:
![screenshot_20181103_033635](https://user-images.githubusercontent.com/781076/47947260-b776e900-df19-11e8-8d6f-b11ec12c954b.png)

**Comment by ChristophHaag** [comment]
Updated to the newest SteamVR beta https://steamcommunity.com/games/250820/announcements/detail/3038136886322358281 and now vrcompositor stops rendering altogether.
Video, it happens at 0:51: https://youtu.be/oQyWnGKRP_g

Side notes:
The beginning works much better than in my first video because I upgraded from RX 480 to Vega 64.
On the Vega 64 I still noticed the same bad async reprojection effects later on in Senza Peso.
I also updated llvm&mesa since my last try, so I can't say for sure that the freeze is SteamVR beta's fault.

**Comment by ChristophHaag** [comment]
Somewhat good news: With async reprojection *disabled*, Senza Peso runs much better now, example:
![screenshot_20181231_005724](https://user-images.githubusercontent.com/781076/50552677-8f490380-0c98-11e9-8e70-ac514cc48601.png)
Sound crackling is almost completely gone too.

With async reprojection enabled I can't really test because it still freezes after a short while, and I also see #166 now.
With some luck it will work better already with async reprojection, once it's fixed.

**Comment by lostgoat** [comment]
I think this should be fixed with the 1.7.2, but can you confirm. I want to track down any remaining perf issues with async.

**Comment by ChristophHaag** [comment]
These specific issues are so old, I am sure they are irrelevant now.
