### ISSUE TITLE
Display not working in Vive on Ubuntu 18.04. Compositor shows Vive output but is running very slow with lag

### ISSUE THREAD

**Issue by ghost** [ValveSoftware/SteamVR-for-Linux#157]
**System Information**
System Report: https://gist.github.com/winsteadworks/b6c46d6cd2bc2097ce5b9fd1ff6715e5

    Steam client version (build number or date): Most Recent version download on 11.14.18
    Distribution (e.g. Ubuntu): Ubuntu 18.04
    Graphics driver version (run nvidia-settings): amdgpu-pro 18.40 for Rx 580
    Gist for SteamVR System Information:
    Opted into Steam client beta?: [Yes/No] Tried beta and non-beta
    Opted into SteamVR beta?: [Yes/No] Tried both beta and non-beta
    Have you checked for system updates?: [Yes/No] Yes

Cannot get Vive display working correctly. It is currently display a distorted picture of my desktop inside the headset. The compositor shows the display correctly on my desktop when I pick up the headset and look around. 

Dual monitor setup (HDMI + VGA)
Rx 580 AMD GPU

#### Steps for reproducing this issue:
Launch SteamVR in Ubuntu 18.04 with HTC Vive original headset

**Comment by kisak-valve** [comment]
Closing because the reporting user has turned into a ghost.
