### ISSUE TITLE
Vive is only displaying white

### ISSUE THREAD

**Issue by SketchStick** [ValveSoftware/SteamVR-for-Linux#166]
#### Your system information
* Steam client version (build date): Dec 14 2018, at 22:19:08
* Distribution: Arch (kernel 4.19.8.arch1-1 patched to enable VK_EXT_global_priority)
* Graphics driver version: Mesa 18.3.1-1 (AMD RX 480 via. amdgpu, vulkan-radeon)
* Gist for SteamVR System Information: https://gist.github.com/SketchStick/9f5af6efc984396cc94cbdb51a87cbac
* Opted into Steam client beta?: Yes
* Opted into SteamVR beta?: Yes
* Have you checked for system updates?: Yes

#### Please describe your issue in as much detail as possible:
With the recent update to SteamVR beta 1.2.3, my Vive only displays white. The display-mirror shows the image correctly and previous versions (stable, rolled-back beta) appear to display fine on the HMD.

#### Steps for reproducing this issue:
1. HMD displays white immediately upon starting SteamVR.

**Comment by kisak-valve** [comment]
I'm seeing the same on a similarly spec test box. As noted, for now you can workaround the issue by opting out of the beta branch to use SteamVR 1.1.4. SteamVR 1.2.1 did not have this issue.

Tested with an RX 480 on Ubuntu 18.04.1 + SteamVR Experimental Graphics PPA and Gentoo with 18.3.1/7.0.1 and mesa git + llvm svn.

**Comment by Pyrarrows** [comment]
Same issue here as well.  Looks like something is borked on AMD hardware at the moment.

Tested on Ubuntu 18.04 + SteamVR Experimental Graphics PPA with RX Vega 64

**Comment by SketchStick** [comment]
Appears to be fixed in SteamVR beta 1.2.5, displays normally and says "Reprojection On" in the settings.
