### ISSUE TITLE
Camera not available, but works when enabled

### ISSUE THREAD

**Issue by SketchStick** [ValveSoftware/SteamVR-for-Linux#169]
#### Your system information
* Steam client version (build date): Dec 14 2018 at 22:19:08
* Distribution: Arch (kernel 4.19.8.arch1-1 patched to enable VK_EXT_global_priority)
* Graphics driver version: Mesa 18.3.1-1 (AMD RX 480 via. amdgpu, vulkan-radeon)
* Gist for SteamVR System Information: [Camera Not Available](https://gist.github.com/SketchStick/bc8f8113200655fa9d3f7ce001ce1edf) - [Enabled via. steamvr.vrsettings](https://gist.github.com/SketchStick/3224eab2cc80c5d1fbb0a64cc446272a)
* Opted into Steam client beta?: Yes
* Opted into SteamVR beta?: Yes
* Have you checked for system updates?: Yes

#### Please describe your issue in as much detail as possible:
In the settings it says "Camera Not Available" and there's no option to enable it, but upon adding the below snippet to steamvr.vrsettings it works without issue.

   "camera" : {
      "enableCamera" : true,
      "enableCameraForCollisionBounds" : false,
      "enableCameraForRoomView" : false,
      "enableCameraInDashboard" : false
   },

#### Steps for reproducing this issue:
1. Remove the existing steamvr.vrsettings file
2. Start SteamVR
3. Go to Settings -> Camera, you should see "Camera Not Available"
4. Close SteamVR
5. Add above snippet to steamvr.vrsettings
6. Start SteamVR
5. Camera should now be working

Possible duplicate of #126

**Comment by Zamundaaa** [comment]
can confim. adding the snippet enabled the camera and the fitting menus and it works just fine

**Comment by Zamundaaa** [comment]
It seems like this issue has been resolved in the latest beta

**Comment by kisak-valve** [comment]
Closing as fixed in SteamVR 1.2.8 (https://github.com/ValveSoftware/VR-Community-Bugs/issues/93#issuecomment-456054204).
