### ISSUE TITLE
Compositor freezes with async reprojection enabled

### ISSUE THREAD

**Issue by SketchStick** [ValveSoftware/SteamVR-for-Linux#172]
#### Your system information
* Steam client version (build date): Jan 19 2019, at 02:01:59
* Distribution: Arch (kernel 4.20.0-arch1-1 patched to enable VK_EXT_global_priority)
* Graphics driver version: Mesa 18.3.1-1 (AMD RX 480 via. amdgpu, vulkan-radeon)
* Gist for SteamVR System Information: https://gist.github.com/SketchStick/67c64dc360a97809c9c3016a4919c252
* Opted into Steam client beta?: Yes
* Opted into SteamVR beta?: Yes
* Have you checked for system updates?: Yes

#### Please describe your issue in as much detail as possible:
With async reprojection enabled, many of the VR games I'm trying under Proton are causing the compositor to freeze. Disabling it or running the game in a way that it doesn't trigger the reprojection avoids the issue. I was unable to reproduce the issue with Talos Principle, so it might be specific to Unity/Proton?

GORN seems to display this behaviour the most consistently, usually causing the freeze in the middle or just after the intro scene with the logo, chanting and torches. To reproduce you'll need to crank the resolution up to a level where reprojection will be enabled constantly during the intro sequence.

Upon freezing the HMD will have a frame frozen on it, the Display Mirror will stop updating and take on the image of any overlapping window, GORN continues to run but no longer tracks the headset, the frame graph in the settings window displays some obscenely large numbers and will no longer update. (included a screenshot with the gist)

#### Steps for reproducing this issue:
1. Startup SteamVR with async reprojection enabled.
2. Set the resolution for GORN in the Applications settings to 200% (or higher depending on your hardware)
3. Start GORN and check that the frame graph is getting thrashed and reprojection is on consistently. 
4. Before the next scene loads, the HMD and graph should freeze.

**Comment by SketchStick** [comment]
Bug still reproducible in SteamVR beta 1.2.10

**Comment by ChristophHaag** [comment]
Indeed. I described it with a demo video in a follow up comment in #152 but having it in its own issue is good.

Senza Peso is the go to demo where I try it because it always happens when you go "through" the tree in the beginning.

**Comment by SketchStick** [comment]
Unable to reproduce with GORN as of SteamVR Beta 1.3.7 and Proton 3.16-7, closing for now...
