### ISSUE TITLE
Connecting Steam Controller destroys performance

### ISSUE THREAD

**Issue by Zamundaaa** [ValveSoftware/SteamVR-for-Linux#173]
#### Your system information
* Steam client version (build number or date): Steam beta January 24th 2019
* Distribution (e.g. Ubuntu): Manjaro KDE
* Graphics driver version (run nvidia-settings): rx 580 with Mesa 18.3.2
* Gist for SteamVR System Information: https://gist.github.com/Zamundaaa/933cf94593afc2dd65944310f92d7f54
* Opted into Steam client beta?: [Yes/No] Yes
* Opted into SteamVR beta?: [Yes/No] Yes
* Have you checked for system updates?: [Yes/No] Yes

#### Please describe your issue in as much detail as possible:
Once I have the Steam Controller on and connected performance suffers drastically. SteamVR Home is basically headache inducing, BallisticNG works somewhat fine in the menu but lags like hell when the game is un-paused. I'll go and test other games soon.
It's not just the current running game or VR that is affected but even the SteamVR settings menu is horribly lagging. It feels like 3 fps or so. And not far much more in VR.
Oddly enough this behaviour stops (or at least almost stops) when opening the "Advanced Frame Timing" window. Then everything works just fine.
this is about how it looks when the Frame Timing Window is not open & the steam controller is connected
![screenshot_20190124_215852](https://user-images.githubusercontent.com/20477130/51708724-de2e5280-2024-11e9-906d-3782cec7b160.png)
The weirdest thing about this whole thing is though that it doesn't go away once the controller is turned off. Restarting Steam & SteamVR doesn't resolve the issue, it takes a full reboot.

#### Steps for reproducing this issue:
1. Start Steam Controller with SteamVR on or the other way around
2. Everything will lag

**Comment by rstrube** [comment]
Hi everyone,

I was going to open up a separate issue, but I believe my problem is related.  I've noticed a couple of regression issues with the new 1.29 steam vr beta release.

1. Asynch Re-projection is always Off, it was previously enabled with 1.27 and 1.28 beta
2. Pressing the system button on the HTC vive wand will cause the internal VR dash to pop up, but then almost immediately after everything goes haywire.  You can close the dash once, but then you're never able to open it again, and performance tanks.

I wonder if there's a regression with input devices that causes this really hard drop in performance.  Plugging in the Steam Controller, pressing the system button on the vive controller, etc.

I can confirm that with 1.27 stable, and 1.28 beta I did not have this problem.

**Comment by rstrube** [comment]
The issue related to the VTC wand + the dashboard was fixed with Steam VR Beta 1.210, I'm not sure if it also fixes the issue that was reported in the OP.

**Comment by Zamundaaa** [comment]
No it doesn't. At first SteamVR Home didn't want to finish starting & the dashboard didn't work, then with the latest Steam Client Beta that worked again. But once the controller has been connected once to the system performance is still very miserable. In Beat Saber for example it worked a lot better though... with sudden half second hangs every 5 seconds or so. Instead of all the time

**Comment by Zamundaaa** [comment]
I don't recall this happening for a long time, so I'd say the issue is solved.
