### ISSUE TITLE
Direct Mode stopped functioning with beta (1549646760)

### ISSUE THREAD

**Issue by usrtrv** [ValveSoftware/SteamVR-for-Linux#176]
* Steam client version (build number or date): 1549672548
* Distribution (e.g. Ubuntu): Fedora 29
* Graphics driver version (run nvidia-settings): Vega 56 with mesa-git (19.1.0)
* Gist for SteamVR System Information: https://gist.github.com/usrtrv/8533b45753bf7be8a6ffb1dc8b6dc7b0
* Opted into Steam client beta?: Yes
* Opted into SteamVR beta?: Yes
* Have you checked for system updates?: Yes

#### Please describe your issue in as much detail as possible:
Direct Mode does not work, previous beta worked, gpu drivers did not change.
Stable does not function for me any more (error 306).

#### Steps for reproducing this issue:
1. Starting SteamVR
2. Enabling Direct Mode
3. Restart SteamVR, still not enabled

**Comment by Gephorian** [comment]
:+1: on this one, same issue.

* Steam client version (build number or date): 1549672548
* Distribution (e.g. Ubuntu): Ubuntu 18.04
* Graphics driver version (run nvidia-settings): Vega 64 with mesa-git (19.1~git190203171100.808bf59~b~padoka0)
* Gist for SteamVR System Information: https://gist.github.com/usrtrv/8533b45753bf7be8a6ffb1dc8b6dc7b0
* Opted into Steam client beta?: Yes
* Opted into SteamVR beta?: Yes
* Have you checked for system updates?: Yes

#### Please describe your issue in as much detail as possible:
Fresh system install, vulkan drivers

#### Steps for reproducing this issue:
1. Starting SteamVR
2. Enabling Direct Mode
3. Restart SteamVR, still not enabled

**Comment by kisak-valve** [comment]
`The VR status window isn't currently aware of direct mode being enabled or not, so the "enable direct mode" and "disable direct mode" buttons should not be used; direct mode is automatically enabled where supported` noted at https://github.com/ValveSoftware/SteamVR-for-Linux#known-issues.

If SteamVR works and your desktop environment is not extended onto the HMD (you can move your mouse onto the HMD when in extended mode), then you're using direct mode.

**Comment by usrtrv** [comment]
> direct mode is automatically enabled where supported
But it was supported, this is a regression.

**Comment by usrtrv** [comment]
Seems to be functioning again.
