### ISSUE TITLE
controller bindings wrong

### ISSUE THREAD

**Issue by Zamundaaa** [ValveSoftware/SteamVR-for-Linux#178]
#### Your system information
* Steam client version (build number or date): 1550534751
* Distribution (e.g. Ubuntu): Manjaro KDE
* Graphics driver version (run nvidia-settings): rx 580 with Mesa 18.3.3-2
* Gist for SteamVR System Information: https://gist.github.com/Zamundaaa/4bbfbc4f1f6586848722e0c2240bcb6e
* Opted into Steam client beta?: [Yes/No] yes
* Opted into SteamVR beta?: [Yes/No] yes
* Have you checked for system updates?: [Yes/No] yes

#### Please describe your issue in as much detail as possible:
when opening the game Hex Defense there's no controllers showing up. Upon a little research I found that whilst they are not using legacy bindings that is what the controller binding web interface shows me, no other options. They are submitting it correctly as it works on Windows just fine. This may be a bug with Proton (although I never encountered this with any other game).
What is very unlikely a bug with proton is that when I try to carry over the correct bindings from Windows by saving the official bindings under a different name the personal bindings I saved do reappear on Linux as expected but they're shown as "Legacy Bindings (Handed)" with nothing at all assigned. The file ~/steamvr/input/steam.app.10139900_vive_controller.json (I checked the app ID, it's correct) has the correct contents, same as on Windows.
![screenshot_20190220_144634](https://user-images.githubusercontent.com/20477130/53096496-974a5480-351f-11e9-9986-c342350f3fed.png)
This is what I get if I try to select the official bindings in Windows and then boot it up on Linux:
![screenshot_20190220_144652](https://user-images.githubusercontent.com/20477130/53096544-afba6f00-351f-11e9-9abf-a769b2d1e5da.png)

#### Steps for reproducing this issue:
1. Start Hex Defense on Linux, no bindings
2. try to carry over bindings from Windows, SteamVR pretends the saved bindings are legacy & empty

**Comment by h1z1** [comment]
Was about to open a ticket for it but this might be related?

```
Mon Apr 01 2019 04:16:55.729593 - App openvr.component.vrcompositor (vive) loaded default binding file:///home/vrvm1/.local/share/Steam/steamapps/common/SteamVR/resources/config/vrcompositor_bindings_vive.json
Mon Apr 01 2019 04:16:55.729647 - App openvr.component.vrcompositor (vive_controller) loaded default binding file:///home/vrvm1/.local/share/Steam/steamapps/common/SteamVR/resources/config/vrcompositor_bindings_vive_controller.json
Mon Apr 01 2019 04:16:55.731211 - App system.generated.steam (vive) loaded default binding file:///home/vrvm1/.local/share/Steam/steamapps/common/SteamVR/resources/config/legacy_bindings_generic_hmd.json
Mon Apr 01 2019 04:16:55.731246 - App system.generated.steam (vive_controller) loaded default binding file:///home/vrvm1/.local/share/Steam/steamapps/common/SteamVR/drivers/htc/resources/input/legacy_bindings_vive_controller.json
Mon Apr 01 2019 04:16:55.786176 - Invalid input type click for controller (/user/head/input/system)
Mon Apr 01 2019 04:16:55.786239 - Invalid input type double for controller (/user/head/input/system)
Mon Apr 01 2019 04:16:55.786252 - Invalid input type long for controller (/user/head/input/system)
Mon Apr 01 2019 04:16:55.787026 - Couldn't find action /actions/lasermouse/in/TrackpadScroll. Ignoring it.
Mon Apr 01 2019 04:16:55.787263 - Controller (/user/hand/left/input/system) not available for input to chord, ignoring chord
Mon Apr 01 2019 04:16:55.787910 - Invalid input type click for controller (/user/head/proximity)
Mon Apr 01 2019 04:16:55.789508 - Unable to read language file /home/vrvm1/.local/share/Steam/steamapps/common/SteamVR/resources/vrcompositor_actions_en_us.json from index block
Mon Apr 01 2019 04:16:55.789960 - Invalid input type click for controller (/user/head/input/system)
Mon Apr 01 2019 04:16:55.789986 - Invalid input type double for controller (/user/head/input/system)
Mon Apr 01 2019 04:16:55.790002 - Invalid input type long for controller (/user/head/input/system)
Mon Apr 01 2019 04:16:55.790455 - Couldn't find action /actions/lasermouse/in/TrackpadScroll. Ignoring it.
Mon Apr 01 2019 04:16:55.790623 - Controller (/user/hand/left/input/system) not available for input to chord, ignoring chord
Mon Apr 01 2019 04:16:55.811044 - Invalid input type click for controller (/user/head/proximity)
Mon Apr 01 2019 04:16:56.738533 - Removing focus flag SystemBehaviorFlag_SystemButtonDown
```

Vrcompositor and vrserver logs.

**Comment by Zamundaaa** [comment]
So I now tried Hex Defense again and it's working fine. The bindings are now all correct.
My issue has been solved, if your errors are still there I'd suggest you do go and make a seperate Issue for this :)
