### ISSUE TITLE
SteamVR Tutorial: Trackpad click not detected

### ISSUE THREAD

**Issue by leinardi** [ValveSoftware/SteamVR-for-Linux#18]
#### Your system information
* Steam client version (build number or date): 1487812945
* Distribution (e.g. Ubuntu): Ubuntu 16.10 (64 bit)
* Graphics driver version (run nvidia-settings):  4.5.0 NVIDIA 375.27.10
* Gist for SteamVR System Information: https://gist.github.com/leinardi/92f4ce3e986209d752c383791c16ef08
* Gist for Steam System Information: https://gist.github.com/leinardi/7f9cc3f021a3ef546a884260b8a14f78
* Opted into Steam client beta?: Yes
* Opted into SteamVR beta?: Yes
* Have you checked for system updates?: Yes

#### Please describe your issue in as much detail as possible:
Vive Controllers track button click not detected. This make impossible to complete the tutorial.

Perhaps related to #17.

#### Steps for reproducing this issue:
1. Start SteamVR Tutorial
2. Follow the Tutorial
3. Press the trackpad button when asked

**Comment by aronschatz** [comment]
I can confirm this behavior. However, my left eye became too fatigued before I moved further in. #13

**Comment by EndeavourAccuracy** [comment]
I can also confirm this.
The track pads light up and the controllers slightly rumble, but pressing them has no effect.
Also, before this moving around over them didn't seem to do anything.

**Comment by valentindavid** [comment]
I have the same problem. I only affects the tutorial. Trackpads work correctly in Destinations and in Serious Sam.

**Comment by kisak-valve** [comment]
Per some discussion on irc, please retest this issue.

**Comment by leinardi** [comment]
The click is now detected.

**Comment by valentindavid** [comment]
However it is said we can see where our finger touches the trackpad. I suppose it show show a dot. And we do not see it.
