### ISSUE TITLE
setpcap/getpcap unavailable, causes SteamVR to fail to launch

### ISSUE THREAD

**Issue by Goofybud16** [ValveSoftware/SteamVR-for-Linux#180]
#### Your system information
* Steam client version (build number or date): Feb 18 2019, at 22:09:18, API v018, Package Versions 1550534751
* Distribution (e.g. Ubuntu): Debian Testing
* Graphics driver version (run nvidia-settings): Mesa 18.3.2
* Gist for SteamVR System Information: [System Info](https://gist.github.com/Goofybud16/e03a3066ab029dc80e663412749acb88)
* Opted into Steam client beta?: No
* Opted into SteamVR beta?: Yes
* Have you checked for system updates?: Yes

#### Please describe your issue in as much detail as possible:
SteamVR 1.3.4 Beta will fail to launch due to the vrstartup.sh file failing. If I change the launch arguments in Steam to `konsole --hold -e %command%`, I get the following output:

```/home/goofybud16/.steam/steam/steamapps/common/SteamVR/bin/vrstartup.sh: line 22: getcap: command not found
+ '[' '' == '' ']'
+ pkexec setcap CAP_SYS_NICE=eip /home/goofybud16/.steam/steam/steamapps/common/SteamVR/bin/linux64/vrcompositor-launcher
Cannot run program setcap: No such file or directory
+ '[' 127 -ne 0 ']'
+ zenity --question '--text=Failed to finalize SteamVR setup. Continue anyway?'

** (zenity:13652): WARNING **: 15:37:15.456: Could not load ui file /usr/share/zenity/zenity.ui: /usr/share/zenity/zenity.ui: required gtk+ version 3.0, cur

(zenity:13652): Gtk-CRITICAL **: 15:37:15.456: IA__gtk_builder_get_object: assertion 'GTK_IS_BUILDER (builder)' failed

(zenity:13652): Gtk-CRITICAL **: 15:37:15.456: IA__gtk_builder_get_object: assertion 'GTK_IS_BUILDER (builder)' failed
+ exit
```

If I manually comment out the zenity lines in the vrstartup.sh file, SteamVR will function properly.

My system DOES have getcap and setcap, but they are in sbin, and unavailable to the vrstartup script. 

```
~$ which getcap
~$ sudo which getcap
/sbin/getcap
```

#### Steps for reproducing this issue:
1. Update to SteamVR Beta 1.3.4
2. Launch SteamVR
3. Observe that SteamVR does not launch.

**Comment by Goofybud16** [comment]
I just tested with Beta 1.3.7 and this issue no longer appears to be present. SteamVR properly starts up with no additional modifications necessary.

**Comment by dromer** [comment]
On debian buster I have to manually do a `sudo setcap CAP_SYS_NICE=eip ~/.steam/debian-installation/steamapps/common/SteamVR/bin/linux64/vrcompositor-launcher`

**Comment by dromer** [comment]
> On debian buster I have to manually do a `sudo setcap CAP_SYS_NICE=eip ~/.steam/debian-installation/steamapps/common/SteamVR/bin/linux64/vrcompositor-launcher`

Still needed, btw.

**Comment by JacekJagosz** [comment]
Can confirm, still an issue.

**Comment by stickmanism** [comment]
Yes, I have this issue right now in Debian on my avl-mxe linux setup.

**Comment by Foxy6670** [comment]
Can someone re-open this? STILL an issue to this day.
Devuan (SysV) 5.10.140-1, kernel 5.10.0-18-amd64

**Comment by Kame03** [comment]
Have you solved this issue, I'm also on devuan?
