### ISSUE TITLE
SteamVR Home corruption on first start

### ISSUE THREAD

**Issue by ChristophHaag** [ValveSoftware/SteamVR-for-Linux#181]
#### Your system information
* Steam client version (build number or date): Feb 18 2019
* Distribution (e.g. Ubuntu): Archlinux
* Graphics driver version (run nvidia-settings): mesa git cb4e3e3ef6e
* Opted into Steam client beta?: Yes
* Opted into SteamVR beta?: Yes

#### Please describe your issue in as much detail as possible:
I have seen this on my Vega 64 twice with two different user accounts.
On the very first start of SteamVR (at least the first time in a while) there is visual corruption visible in SteamVR Home.
![screenshot_20190303_230126](https://user-images.githubusercontent.com/781076/53702788-06bb2080-3e0b-11e9-9860-c68586bd2ab8.png)
On subsequent startups of SteamVR Home, this corruption is completely gone and everything looks perfect.
It looks like this corruption even casts a shadow!

**Comment by ChristophHaag** [comment]
Actually the first start after deleting ~/.cache/mesa_shader_cache works without corruption, but when I restart steamvr home a couple of times, often random textures are corrupted. Here is another example:

![Screenshot_20190309_231716](https://user-images.githubusercontent.com/781076/54078034-86d8fe80-42c1-11e9-9054-36a5f7bf4085.png)

**Comment by hakzsam** [comment]
Should be fixed with https://cgit.freedesktop.org/mesa/mesa/commit/?id=ae77f1236862e73c1ac250898924c648d481bda4
Thanks for reporting this!

**Comment by ChristophHaag** [comment]
Indeed fixed upstream
