### ISSUE TITLE
Async reprojection doesn't work

### ISSUE THREAD

**Issue by Zamundaaa** [ValveSoftware/SteamVR-for-Linux#187]
#### Your system information
* Steam client version (build number or date): Mar 28 2019, at 23:49:54
* Distribution (e.g. Ubuntu): Manjaro KDE
* Graphics driver version (run nvidia-settings): rx 580 with Mesa 18.3.4
* Gist for SteamVR System Information: https://gist.github.com/Zamundaaa/0106022a0be777b47e125c1c42fddb7f
* Opted into Steam client beta?: [Yes/No] yes
* Opted into SteamVR beta?: [Yes/No] yes
* Have you checked for system updates?: [Yes/No] yes

#### Please describe your issue in as much detail as possible:
I reinstalled my system (keeping the data). When I started SteamVR after that it, async reprojection wouldn't work anymore. A reinstall of SteamVR didn't help.
It did not ask again for the SYS_CAP_NICE, so it could be that.

#### Steps for reproducing this issue:
1. Reinstall the OS
2. Async Reprojection doesn't work anymore

**Comment by floturcocantsee** [comment]
Can confirm this on Ubuntu 18.04 on a GTX 1080 using the latest 418 nvidia drivers.

**Comment by Zamundaaa** [comment]
@floturcocantsee yeah AFAIK it's not implemented (or at least not working) for NVidia in general.
It did work for me though. Just now after reinstallation not anymore.

**Comment by Zamundaaa** [comment]
Soo I now tried a complete reinstall of Steam and SteamVR, deleting all the associated folders etc (because of a different issue), and as that didn't help here I suspect that it doesn't have anything to do with my system. And again, no asking for SYS_CAP_NICE.

**Comment by Zamundaaa** [comment]
Ok with kernel 5.2 rc.something at least it does work again. It asked for superuser permission and async reprojection (although not shown in the settings, one can find it in the vrcompositor log) works perfectly fine. The performance difference looks like night and day to me...
