### ISSUE TITLE
SteamVR Tutorial: The robotic core is facing the wrong direction

### ISSUE THREAD

**Issue by leinardi** [ValveSoftware/SteamVR-for-Linux#19]
#### Your system information
* Steam client version (build number or date): 1487812945
* Distribution (e.g. Ubuntu): Ubuntu 16.10 (64 bit)
* Graphics driver version (run nvidia-settings):  4.5.0 NVIDIA 375.27.10
* Gist for SteamVR System Information: https://gist.github.com/leinardi/92f4ce3e986209d752c383791c16ef08
* Gist for Steam System Information: https://gist.github.com/leinardi/7f9cc3f021a3ef546a884260b8a14f78
* Opted into Steam client beta?: Yes
* Opted into SteamVR beta?: Yes
* Have you checked for system updates?: Yes

#### Please describe your issue in as much detail as possible:
When the robotic core moves across the room, before asking you to press the Controller buttons, it keep the original orientation and gives you his back.

What I'm seeing:
![schermata del 2017-02-24 22-06-22](https://cloud.githubusercontent.com/assets/273338/23322093/b7fb34de-fae2-11e6-9d27-44a4ea047340.png)

Expected result:
![image](https://cloud.githubusercontent.com/assets/273338/23322101/c0e0db30-fae2-11e6-8d5d-2dba679dceee.png)

#### Steps for reproducing this issue:
1. Start SteamVR Tutorial
2. Follow the Tutorial until you are asked to press the trigger button

**Comment by kisak-valve** [comment]
Per some discussion on irc, please retest this issue.

**Comment by leinardi** [comment]
Confirm, I can't reproduce the issue anymore.

**Comment by cyrhinka** [comment]
You might want to reopen this I had the same issue 3 days ago and I tried again today.
After the robot goes on the other side of the chaperone, it is stuck turning its back.

![2018-06-02-robot-not-looking-player](https://user-images.githubusercontent.com/39858595/40877544-124401fc-6683-11e8-96ac-7649c107cbdc.png)


**Your system information**

- Steam client version (build number or date): 1527879669
- Distribution (e.g. Ubuntu): Ubuntu 18.04 (64 bit)
- Graphics driver version (glxinfo | grep "OpenGL version"): Mesa 18.0.0-rc5
- Gist for SteamVR System Information: https://gist.github.com/cyrhinka/b36324030c8886b2657671e0ed3a9f45
- Opted into Steam client beta?: Yes
- Opted into SteamVR beta?: Yes
- Have you checked for system updates?: Yes
