### ISSUE TITLE
Direct mode doesn't work on linux 5.1-rc

### ISSUE THREAD

**Issue by ChristophHaag** [ValveSoftware/SteamVR-for-Linux#192]
Vega 64 with newest mesa git etc (not important I think).

With linux 5.0 direct mode works fine, with 5.1-rc direct mode fails to initialize, but SteamVR does not seem to notice, the logs say direct mode is enabled: [SteamVR-2019-04-12-_11_19_13.txt](https://github.com/ValveSoftware/SteamVR-for-Linux/files/3072526/SteamVR-2019-04-12-_11_19_13.txt)

However, the HMD shows nothing and the mirror window is just red: ![Screenshot_20190412_111736](https://user-images.githubusercontent.com/781076/56026525-99a57f80-5d14-11e9-939b-2a0649fcf9df.png)

If I got it right, the issue is that `vkAcquireXlibDisplayEXT()` returns `VK_ERROR_INITIALIZATION_FAILED`, which our monado runtime also didn't handle properly before https://gitlab.freedesktop.org/monado/monado/merge_requests/3

**Comment by lostgoat** [comment]
Bisected to 8059add0478e29cb641936011a8fcc9ce9fd80be, and a future update of SteamVR will better handle this failure case as well.
