### ISSUE TITLE
Dashboard Exit VR doesn't work again

### ISSUE THREAD

**Issue by Zamundaaa** [ValveSoftware/SteamVR-for-Linux#201]
#### Your system information
* Steam client version (build number or date): 1559784175
* Distribution (e.g. Ubuntu): Manjaro KDE
* Graphics driver version (run nvidia-settings): rx580 with Mesa 19.0.6
* Gist for SteamVR System Information: https://gist.github.com/Zamundaaa/76ec211cfeb26b0c7a41b111c14bcb3f
* Opted into Steam client beta?: [Yes/No] Yes
* Opted into SteamVR beta?: [Yes/No] Yes
* Have you checked for system updates?: [Yes/No] Yes

Dashboard Exit VR doesn't work anymore. No kio popups like in #121 yet but otherwise the same.

**Comment by rpavlik** [comment]
confirming here, Debian Buster, rx580, steamvr 1.5.8 beta, on Gnome.

**Comment by yaomtc** [comment]
Also occurring here on Solus (Plasma) with an RX 580 and the latest SteamVR beta (3966064).

Can someone with a different graphics card test this?

**Comment by SlickMcRunFast** [comment]
Index HMD, Ubuntu 19.04 64 bit, nvidia 2070 super 430.26 (430.34 has issues)

I can't exit from in HMD dashboard. Controller turn off works.

**Comment by Goofybud16** [comment]
Index HMD, Debian Testing, Kernel 5.2.3

https://gist.github.com/Goofybud16/e41842b0fa4181707d477d039a770aa3

I can reproduce the issue. I don't know that I've ever successfully used the "Exit VR" button.

**Comment by rpavlik** [comment]
It did actually used to work, a few months ago.

**Comment by ryao** [comment]
@Goofybud16 It worked last year on the Vive. It does not work anymore.

**Comment by Zamundaaa** [comment]
I just noticed the launch feedback from KDE one can see after pressing the button in VR. 
So the command is definitely sent from the dashboard but ignored by the vrmonitor / doesn't work.

**Comment by fabiankranewitter** [comment]
Also in the version 1.9.1 the complete quit does not work over the drop down in vr.

**Comment by Zamundaaa** [comment]
Yeah, the drop down (or up?) menu is a nice change but Quit VR still doesn't work.

**Comment by Zamundaaa** [comment]
This seems to be exactly the same issue as #291 now. As with #291 calling the executable vrmonitor directly with "vrmonitor vrmonitor://quit" (or pressing the button in the dashboard) won't work with "error while loading shared libraries: libsteam_api.so: cannot open shared object file: No such file or directory".
Calling "vrmonitor.sh vrmonitor://quit" works without a problem

**Comment by rpavlik** [comment]
ah, so it's a shared library search issue. Thanks for digging into this - maybe we'll get a fix then :) (maybe even another patch on the 1.8 branch? I can dream...)

**Comment by Zamundaaa** [comment]
Works again with 1.10.8 :smile:
