### ISSUE TITLE
Controller bindings wrong in B&S

### ISSUE THREAD

**Issue by Zamundaaa** [ValveSoftware/SteamVR-for-Linux#204]
#### Your system information
* Steam client version (build number or date): 15461580940
* Distribution (e.g. Ubuntu): Manjaro KDE
* Graphics driver version (run nvidia-settings): Vega 64 with Mesa 19.1.1
* Gist for SteamVR System Information:  https://gist.github.com/Zamundaaa/6fa7c5550b6718bb42f84d764c1e1370
* Opted into Steam client beta?: [Yes/No] Yes
* Opted into SteamVR beta?: [Yes/No] Yes
* Have you checked for system updates?: [Yes/No] Yes

Blade&Sorcery has legacy controller bindings even though they switched to the IVR input system. Exactly the same issue as #178.

**Comment by Zamundaaa** [comment]
Well, seemingly not exactly the same issue as #178 anymore.
It now shows the right bindings with the latest beta, but it doesn't actually translate to the game. I can't do anything in it. No controller positions and nothing.
I also can't go back to the default bindings anymore after trying other ones, but that seems  to be a known bug already, judging by another editable binding.

**Comment by kisak-valve** [comment]
Hello @Zamundaaa, this reads like https://github.com/ValveSoftware/Proton/issues/2836. Please add a note to https://github.com/ValveSoftware/Proton/issues/2620 with a current Proton Log.

**Comment by Zamundaaa** [comment]
This issue appears to be the same for Windlands 2, the game itself says that the version of SteamVR input is too low and thus the game cannot be run. That's presumably because it only gets legacy bindings assigned, too.

**Comment by Zamundaaa** [comment]
This may be of help: Everytime a binding is wrong (I've had that in Sairento VR now, too... But after restarting the game it worked) SteamVR seems to not get the name of the app somehow. The "Exit appname" button in the VR dashboard then just shows "Exit ".

**Comment by aeikum** [comment]
We updated our openvr support in Proton 4.11. Can you please retest with 4.11 and see if this is working now?

**Comment by Zamundaaa** [comment]
Blade and Sorcery works just fine now (except for performance, that issue is already tracked in another issue). Thanks!
