### ISSUE TITLE
Stuttering in Vive (Ubuntu/AMD)

### ISSUE THREAD

**Issue by skestle** [ValveSoftware/SteamVR-for-Linux#219]
#### Your system information
* Steam client version (build number or date): 
* Distribution (e.g. Ubuntu): 
* Graphics driver version (run ~nvidia-settings~ vulkaninfo): 1.1.97
* Gist for SteamVR System Information: https://gist.github.com/skestle/38b0444c24e6de2bd77835d0768eeb53
* Opted into Steam client beta?: Yes
* Opted into SteamVR beta?: Yes
* Have you checked for system updates?: Yes

#### Please describe your issue in as much detail as possible:
It's basically the same problem as #116, but Ubuntu and AMD. I've found that Gnome 3 "automatically" disables compositing, but don't know how to verify it.

It very much seems like the framebuffer: when I move, the new correct position is shown, but then it shows flashes of the original position. 
It does seem to depend on load: when in SteamVR Home, the performance display shows that frames are taking 20ms - but then the mirror view on the desktop is perfect. Tracking is perfect (as checked on the desktop). In the loading view (grid + mountains) it's better, but still can show these glitches.
It affects all applications I've tried so far.
I've turned on direct mode, but when VR opens, the desktop still "adjusts" as if a new monitor has been detected. `vrcompositor` is running in the System Monitor.

#### Steps for reproducing this issue:
1. Setup steam VR on Ubuntu 18.10 (https://github.com/ValveSoftware/SteamVR-for-Linux)
2. Launch VR (Home, or any other)
3. Move head

**Comment by Goofybud16** [comment]
I have a similar problem with my Index.

If I give SteamVR the CAP_SYS_NICE=EIP like it wants, I get frametimes like this: 

![image](https://user-images.githubusercontent.com/669915/61997513-61257980-b057-11e9-8a1d-b4f4ecbe5d32.png)

It even stutters in the "grid" that shows up between games.

If I take it away by setting CAP_SYS_NICE=, I get frametimes like this: 

![image](https://user-images.githubusercontent.com/669915/61997540-b497c780-b057-11e9-8bab-9244065dfe80.png)

While I'm constantly in reprojection territory (in SteamVR home, in this case), it at least runs "smoothly".

System report: https://gist.github.com/Goofybud16/e41842b0fa4181707d477d039a770aa3

**Comment by kwahoo2** [comment]
> It very much seems like the framebuffer: when I move, the new correct position is shown, but then it shows flashes of the original position.

I have the same issue with Valve Index. Steam system report https://gist.github.com/kwahoo2/97124f00f3e01405a14d430e4de88f9f

The issue does not happen in The Lab demos (tested Longbow and Postcards). They run bit slow (10-12 with 100% scaling) but without any stuttering.

**Comment by skestle** [comment]
I played around with CAP_SYS_NICE and if I turn it off, compositing takes around 9ms on my Intel® Core™ i7-8809G CPU @ 3.10GHz × 8. That's pretty bad, and I _think_ my processor is capable :p. This makes frequent stutters.

On the other hand, with EIP on, the GPU seems to suffer load - the application timings are off the charts (above 22ms). When I turn the resolution down to 20%, it still doesn't improve. The AMD Vega M is marginal, but shouldn't be that marginal.
The stutters are less frequent, but much larger.

**Comment by Goofybud16** [comment]
Try this again with 1.7.2 beta. It mostly fixed the problems I'd been having. Still not perfect, but a huge improvement over what it was before (actually playable now)

**Comment by lostgoat** [comment]
Thanks @Goofybud16 and everyone who contributed system reports. They helped track down the issues.

Closing this one for now, and if you have some data on other scenarios that cause bad perf new issues are welcome.

**Comment by kwahoo2** [comment]
Upgrade to 1.7.2 beta actually made the issue much more visible for me. SteamVR Home is flashing (as @skestle described) constantly.

**Comment by reinux** [comment]
Having this same situation with Index on Linux.

**Comment by skestle** [comment]
@reinux While I like the ressurection of the dead, sufficient time has passed to open a new issue (with link to this issue/my comment) and any new information/debugging you can provide...
It sucks - I just ended up with a Windows gaming machine for a few hundred

**Comment by reinux** [comment]
> I just ended up with a Windows gaming machine for a few hundred

That's a bummer.
