### ISSUE TITLE
vrcmd bash-script contains ms-dos CR

### ISSUE THREAD

**Issue by Seegras** [ValveSoftware/SteamVR-for-Linux#22]
/SteamVR/bin$ ./vrcmd
bash: ./vrcmd: /bin/bash^M: bad interpreter: No such file or directory
That's a ms-dos carriage return there. Yuck! 
It's fixed easily enough, tough: 
SteamVR/bin$ flip -ub vrcmd

**Comment by Goofybud16** [comment]
It looks to me like vrcmd is now a native binary within SteamVR/bin/linux64

All of the shell scripts I see [within SteamVR/bin] appear to have correct, Unix line-endings.

**Comment by kisak-valve** [comment]
Closing per the last comment.
