### ISSUE TITLE
Linux 5.2.3 includes patches for Index audio with AMD gpu

### ISSUE THREAD

**Issue by dlpierce** [ValveSoftware/SteamVR-for-Linux#221]
With the release of version 5.2.3, the Linux kernel now includes both of the patches listed here needed for audio support on the Index when using an AMD graphics. README.md needs to be updated with this information.

https://git.kernel.org/pub/scm/linux/kernel/git/stable/linux.git/commit/?h=v5.2.3&id=0a71cb0fb4ef792705eab23ad2e8e4c1a740edf1

**Comment by kwahoo2** [comment]
I can confirm that the patch works. Kubuntu 19.04, RX 580 and kernel 5.2.4. Note: I had to set HDMI/Displayport audio device as default in the system mixer (not Steam).

**Comment by lostgoat** [comment]
The readme has been updated with the kernel requirements for Index audio.
