### ISSUE TITLE
Valve Index HMD No Longer Recognized After a few Hours Plugged In

### ISSUE THREAD

**Issue by Goofybud16** [ValveSoftware/SteamVR-for-Linux#222]
#### Your system information
* Steam client version (build number or date): Jul 17 2019, 06:14:18
* Distribution (e.g. Ubuntu): Debian Testing
* Graphics driver version (run nvidia-settings): Mesa 18.3.6
* Gist for SteamVR System Information: https://gist.github.com/Goofybud16/a5962f131b298023e4bb0c616537f149
* Opted into Steam client beta?: No
* Opted into SteamVR beta?: Yes
* Have you checked for system updates?: Yes

#### Please describe your issue in as much detail as possible:
After leaving the Valve Index HMD plugged in for a few hours and idle, it will no longer be recognized by SteamVR. It is still receiving power, as the lights on the front are blue. So far, the only way I've found to fix it is to restart the entire system, as plugging/unplugging the headset (both DP/USB/power and/or at the quick-release trident cable connector) doesn't seem to do anything. Leaving it unplugged after the issue has occurred doesn't seem to help either. Unplugging/replugging does result in DMESG showing events about USB connecting. It only appears to happen when idle and SteamVR is not running, I played for a solid 9 hours straight with zero problems.

#### Steps for reproducing this issue:
1. Plug in Valve Index HMD
2. Start SteamVR
3. Exit SteamVR
4. Wait for the headset lights to turn blue (or a few hours)
5. Start SteamVR
6. Observe that the headset is not detected.

**Comment by Goofybud16** [comment]
Update:

I rebooted my PC, didn't start SteamVR, and after ~45 minutes, the headset was no longer detected by SteamVR.

**Comment by Goofybud16** [comment]
![image](https://user-images.githubusercontent.com/669915/62017272-e188cf00-b16a-11e9-878a-fd2385c424bd.png)

After a reboot, SteamVR is quite happy to detect my Index.

**Comment by lostgoat** [comment]
Hi @Goofybud16 

the system report you pasted seems to be truncated, all the log information is missing. Can I trouble you to paste a new system report when the issue happens again.

Also, when the HMD gets into a bad state, can you capture the output of `xrandr --verbose`

**Comment by Goofybud16** [comment]
D'oh.

Full system report (with the headset connected and working): https://gist.github.com/Goofybud16/123cf7a7d70122876bd80873cf38f4d3

XRandr with just the Trident connected (headset d/c at breakaway): https://gist.github.com/Goofybud16/13a37872bef9b93f9e41ff4cc8560a29

XRandr with the headset connected and SteamVR _not_ running: https://gist.github.com/Goofybud16/11904bc3ed6ff24a86c8f2bf3e9cf1c5

XRandr with the headset connected and SteamVR Running: https://gist.github.com/Goofybud16/fd6b37d731fe3f5cf38b40e32764b15f

I'll try and grab the xrandr output and System report with the issue occurring as soon as it occurs.

**Comment by Goofybud16** [comment]
Since writing that last post (~30 minutes ago) I let the headset sit, and it is once again not showing up in SteamVR.

XRandr --verbose: https://gist.github.com/Goofybud16/afd9c5774593984b8ef08da868f99aff

System report: https://gist.github.com/Goofybud16/85ebb7e4c268c007a924ddccacb14a89

The lights on the headset are green, and I can play audio through the headphones if I direct another app there through Pulseaudio Volume Control.

This is persistent even if I reconnect the headset.

**Comment by lostgoat** [comment]
@Goofybud16 afaics, from the X point of view your headset is still being detected correctly.

vrcompositor also seems to find the headset:
```
Mon Jul 29 2019 17:58:16.185950 - HMD deviceUUID is 2900000000
Mon Jul 29 2019 17:58:16.186007 - Looking for direct display through RandR
Mon Jul 29 2019 17:58:16.186026 -  - Root 0x6dd
Mon Jul 29 2019 17:58:16.188183 -    - Output 0x55 - 15 modes, 1 preferred
Mon Jul 29 2019 17:58:16.188220 -      - Mode 0 0x5a 2880x1600 (looking for 2880x1600)
Mon Jul 29 2019 17:58:16.188237 -        - Found matching output 85
Mon Jul 29 2019 17:58:16.188253 - Found candidate direct display as RandR output 0x55
Mon Jul 29 2019 17:58:16.192289 - Tried to find direct display through RandR: 0x2ab8b50
Mon Jul 29 2019 17:58:16.192310 - Trying to match desired rate of 120.017006Hz.
Mon Jul 29 2019 17:58:16.192324 - 15 modes on display:
Mon Jul 29 2019 17:58:16.192337 -  - 0: 2880x1600@90.001007Hz
Mon Jul 29 2019 17:58:16.192350 -  - 1: 2880x1600@143.998001Hz
Mon Jul 29 2019 17:58:16.192362 -  - 2: 2880x1600@120.017006Hz
Mon Jul 29 2019 17:58:16.192375 -  - 3: 2880x1600@79.998001Hz
Mon Jul 29 2019 17:58:16.192387 -  - 4: 1920x1200@90.001007Hz
Mon Jul 29 2019 17:58:16.192406 -  - 5: 1920x1080@90.001007Hz
Mon Jul 29 2019 17:58:16.192418 -  - 6: 1600x1200@90.001007Hz
Mon Jul 29 2019 17:58:16.192430 -  - 7: 1680x1050@90.001007Hz
Mon Jul 29 2019 17:58:16.192442 -  - 8: 1280x1024@90.001007Hz
Mon Jul 29 2019 17:58:16.192454 -  - 9: 1440x900@90.001007Hz
Mon Jul 29 2019 17:58:16.192466 -  - 10: 1280x800@90.001007Hz
Mon Jul 29 2019 17:58:16.192479 -  - 11: 1280x720@90.001007Hz
Mon Jul 29 2019 17:58:16.192491 -  - 12: 1024x768@90.001007Hz
Mon Jul 29 2019 17:58:16.192503 -  - 13: 800x600@90.001007Hz
Mon Jul 29 2019 17:58:16.192515 -  - 14: 640x480@90.001007Hz
Mon Jul 29 2019 17:58:16.192529 - Selected mode 2.
Mon Jul 29 2019 17:58:16.197150 - Direct mode surface: 0x3289750
Mon Jul 29 2019 17:58:16.197302 - Requesting 10 device extensions:
Mon Jul 29 2019 17:58:16.197319 -  - VK_KHR_swapchain
Mon Jul 29 2019 17:58:16.197332 -  - VK_KHR_maintenance1
Mon Jul 29 2019 17:58:16.197343 -  - VK_KHR_dedicated_allocation
Mon Jul 29 2019 17:58:16.197355 -  - VK_KHR_get_memory_requirements2
Mon Jul 29 2019 17:58:16.197366 -  - VK_KHR_external_memory
Mon Jul 29 2019 17:58:16.197378 -  - VK_KHR_external_semaphore
Mon Jul 29 2019 17:58:16.197389 -  - VK_EXT_display_control
Mon Jul 29 2019 17:58:16.197400 -  - VK_KHR_external_memory_fd
Mon Jul 29 2019 17:58:16.197411 -  - VK_KHR_external_semaphore_fd
Mon Jul 29 2019 17:58:16.197422 -  - VK_EXT_global_priority
Mon Jul 29 2019 17:58:16.197434 - Attempting to enable async support...
Mon Jul 29 2019 17:58:16.197445 - Enabling async support!
Mon Jul 29 2019 17:58:16.197767 - Failed to create VkDevice with high priority queue.
Mon Jul 29 2019 17:58:16.197784 - Disabling async support and retrying.
Mon Jul 29 2019 17:58:17.265942 - m_pVkInstance : 0x3291a20
Mon Jul 29 2019 17:58:17.265988 - m_pVkPhysicalDevice : 0x2b3c140
Mon Jul 29 2019 17:58:17.266003 - m_pVkDevice : 0x3226fc0
Mon Jul 29 2019 17:58:17.266016 - m_pVkGraphicsQueue : 0x2a824c0
Mon Jul 29 2019 17:58:17.266027 - m_pVkComputeQueue : (nil)
Mon Jul 29 2019 17:58:17.266047 - HMD swapchain mode:2 count:3
Mon Jul 29 2019 17:58:17.266294 - Direct mode: enabled
Mon Jul 29 2019 17:58:17.267169 - Mirror swapchain mode:0 count:3
Mon Jul 29 2019 17:58:17.297841 - Initializing generic graphics device resources...
Mon Jul 29 2019 17:58:17.310225 - Headset is using direct mode
Mon Jul 29 2019 17:58:17.310237 - Initializing timing resources
Mon Jul 29 2019 17:58:17.310296 - Initializing CVulkanVRRenderer
```

So vrcompositor is finding the display correctly for your HMD.

The problem seems to be USB related since vrserver can't enumerate the Index:
```
Mon Jul 29 2019 18:26:53.996864 - lighthouse: version 1.6.10
Mon Jul 29 2019 18:26:53.996993 - lighthouse: Add Json firmware manifest from {htc}/firmware/manifest.vrfirmware
Mon Jul 29 2019 18:26:53.997099 - lighthouse: Add Json firmware manifest from {indexcontroller}/firmware/manifest.vrfirmware
Mon Jul 29 2019 18:26:53.997197 - lighthouse: Add Json firmware manifest from {indexhmd}/firmware/manifest.vrfirmware
Mon Jul 29 2019 18:26:53.997398 - lighthouse: Add Json firmware manifest from {lighthouse}/firmware/manifest.vrfirmware
Mon Jul 29 2019 18:26:54.000869 - lighthouse: Attached HID Devices:
Mon Jul 29 2019 18:26:54.000901 - lighthouse:     28DE, 1142: s/n /dev/hidraw9: Steam Controller (interface 0)
Mon Jul 29 2019 18:26:54.000917 - lighthouse:     28DE, 1142: s/n /dev/hidraw10: Steam Controller (interface 1)
Mon Jul 29 2019 18:26:54.000931 - lighthouse:     28DE, 1142: s/n /dev/hidraw11: Steam Controller (interface 2)
Mon Jul 29 2019 18:26:54.000945 - lighthouse:     28DE, 1142: s/n /dev/hidraw12: Steam Controller (interface 3)
Mon Jul 29 2019 18:26:54.000960 - lighthouse:     28DE, 1142: s/n /dev/hidraw13: Steam Controller (interface 4)
Mon Jul 29 2019 18:26:54.000975 - lighthouse:     28DE, 2101: s/n CF3C5CFF56: Watchman Dongle (interface 0)
Mon Jul 29 2019 18:26:54.000990 - lighthouse:     28DE, 2101: s/n E641083BA2: Watchman Dongle (interface 0)
Mon Jul 29 2019 18:26:54.001014 - lighthouse:     28DE, 2101: s/n 6BCBB634CD: Watchman Dongle (interface 0)
Mon Jul 29 2019 18:26:54.002193 - lighthouse: Attempting HID Open IMU: CF3C5CFF56
Mon Jul 29 2019 18:26:54.002275 - lighthouse: Lighthouse IMU HID opened
Mon Jul 29 2019 18:26:54.215190 - lighthouse: Attempting HID Open IMU: E641083BA2
Mon Jul 29 2019 18:26:54.215262 - lighthouse: Lighthouse IMU HID opened
Mon Jul 29 2019 18:26:54.428562 - lighthouse: Attempting HID Open IMU: 6BCBB634CD
Mon Jul 29 2019 18:26:54.428611 - lighthouse: Lighthouse IMU HID opened
Mon Jul 29 2019 18:26:54.429611 -   driver lighthouse implements interfaces IVRSettings_002 ITrackedDeviceServerDriver_005 IVRDisplayComponent_002 IVRDriverDirectModeComponent_005 IVRCameraComponent_003 IServerTrackedDeviceProvider_004 IVRWatchdogProvider_001 IVRVirtualDisplay_002 IVRDriverManager_001 IVRResources_001 IVRCompositorPluginProvider_001 
Mon Jul 29 2019 18:26:54.429670 - Loaded server driver lighthouse (IServerTrackedDeviceProvider_004) from /home/goofybud16/.steam/steam/steamapps/common/SteamVR/drivers/lighthouse/bin/linux64/driver_lighthouse.so
Mon Jul 29 2019 18:26:54.429689 - Driver lighthouse has no suitable devices.
Mon Jul 29 2019 18:26:54.430030 - Unable to load driver oculus from /home/goofybud16/.steam/steam/steamapps/common/SteamVR/drivers/oculus/bin/linux64/driver_oculus.so.
Mon Jul 29 2019 18:26:54.430047 - Unable to load driver oculus because of error VRInitError_Init_FileNotFound(103). Skipping.
Mon Jul 29 2019 18:26:54.430269 - Unable to load driver oculus_legacy from /home/goofybud16/.steam/steam/steamapps/common/SteamVR/drivers/oculus_legacy/bin/linux64/driver_oculus_legacy.so.
Mon Jul 29 2019 18:26:54.430286 - Unable to load driver oculus_legacy because of error VRInitError_Init_FileNotFound(103). Skipping.
Mon Jul 29 2019 18:26:54.430298 - Not loading driver null because it is disabled in settings
Mon Jul 29 2019 18:26:54.430334 - No connected devices found. Returning best error VRInitError_Init_HmdNotFound
Mon Jul 29 2019 18:26:54.430348 - Refusing connect from vrstartup (21350) because VRInitError_Init_HmdNotFound
```

**Comment by lostgoat** [comment]
If you have any different USB controllers could you try moving your index to one of those.

Are there any dmesg errors regarding USB devices? There have been some Index firmware updates to improve USB compatibility, can you confirm you are running the latest firmware?

**Comment by Goofybud16** [comment]
I was running the latest firmware for 1.6.9. I have not had a chance to get a Windows machine to flash firmware for 1.6.10 (which I can't do on Linux because #206).

As for available ports, I believe all of the USB 3 ports on my board (x370 SLI PLUS) are run off the same controller. I can try a USB 2 port.

As for dmesg errors, there is:

```
22612.172228] xhci_hcd 0000:26:00.0: ERROR unknown event type 15
[22617.290885] xhci_hcd 0000:26:00.0: xHCI host not responding to stop endpoint command.
[22617.290921] xhci_hcd 0000:26:00.0: xHCI host controller not responding, assume dead
[22617.290949] xhci_hcd 0000:26:00.0: HC died; cleaning up
[22617.290968] usb 3-2: USB disconnect, device number 2
[22617.290970] usb 3-2.3: USB disconnect, device number 3
[22617.290973] usb 3-2.3.1: USB disconnect, device number 4
[22617.291134] usb 4-2: USB disconnect, device number 3
[22617.291136] usb 4-2.1: USB disconnect, device number 4
[22617.291716] usb 3-2.3.2: USB disconnect, device number 5
[22617.292102] usb 3-2.3.3: USB disconnect, device number 6
[22617.292556] usb 3-2.3.5: USB disconnect, device number 7
```

In addition to a bunch of 

```
[44460.121236] pcieport 0000:00:03.1: AER: PCIe Bus Error: severity=Corrected, type=Data Link Layer, (Transmitter ID)
[44460.121237] pcieport 0000:00:03.1: AER:   device [1022:1483] error status/mask=00001100/00006000
[44460.121239] pcieport 0000:00:03.1: AER:    [ 8] Rollover              
[44460.121240] pcieport 0000:00:03.1: AER:    [12] Timeout               
[45481.120121] pcieport 0000:00:03.1: AER: Multiple Corrected error received: 0000:00:03.1
[45481.120140] pcieport 0000:00:03.1: AER: PCIe Bus Error: severity=Corrected, type=Data Link Layer, (Transmitter ID)
[45481.120142] pcieport 0000:00:03.1: AER:   device [1022:1483] error status/mask=00001100/00006000
[45481.120144] pcieport 0000:00:03.1: AER:    [ 8] Rollover              
[45481.120146] pcieport 0000:00:03.1: AER:    [12] Timeout               
[47013.156590] pcieport 0000:00:03.1: AER: Corrected error received: 0000:00:03.1
[47013.156602] pcieport 0000:00:03.1: AER: PCIe Bus Error: severity=Corrected, type=Data Link Layer, (Transmitter ID)
[47013.156604] pcieport 0000:00:03.1: AER:   device [1022:1483] error status/mask=00001000/00006000
[47013.156606] pcieport 0000:00:03.1: AER:    [12] Timeout               
[47013.156611] pcieport 0000:00:03.1: AER: Corrected error received: 0000:00:03.1
[47013.157088] pcieport 0000:00:03.1: AER: can't find device of ID0019
[47013.157090] pcieport 0000:00:03.1: AER: Multiple Corrected error received: 0000:00:03.1
[47013.157102] pcieport 0000:00:03.1: AER: PCIe Bus Error: severity=Corrected, type=Data Link Layer, (Transmitter ID)
[47013.157104] pcieport 0000:00:03.1: AER:   device [1022:1483] error status/mask=00001100/00006000
[47013.157106] pcieport 0000:00:03.1: AER:    [ 8] Rollover              
[47013.157107] pcieport 0000:00:03.1: AER:    [12] Timeout    
```

(although I believe the PCIe errors are related to my GPU, as it is the only PCIe device plugged into the motherboard. I believe it's related to running Ryzen 3000, and these are basically equivalent to the WHEA errors. They all say "corrected", so I don't think they're the source of the problem.

**Comment by Goofybud16** [comment]
Switching to a USB 2.0 port seems to have made the headset be detected again.

**Comment by edwin-v** [comment]
I've had one issue a week ago where my entire USB system failed (as in all connected USB devices stopped working and newly connected devices weren't picked up). I was able to verify this because I still had keyboard control due to it being PS/2. On investigated the log, I had a very long list of v4l messages in my system log related to the camera device. A reboot was needed to bring everything back. Since then I unplug the headset when I don't use it.

Could this be related?

**Comment by jug007** [comment]
I am having exactly the same problem as Goofybud16.
I am not getting any USB errors for the HMD and switching USB controllers did not help (tried 5 different ones). Kernel 4.18 and 5.0.0-28 both show the same behaviour.
It also seems like USB is generally behaving a bit weird when the Index is connected ; As in, some particular devices need a long time to connect.(like my mouse and keyboard)

**Comment by Goofybud16** [comment]
I updated to the latest 1.6.10 firmware today while connected to a Windows system.

I'll report back if I continue to have the problem.

**Comment by jug007** [comment]
I have been having the problem with the newest firmware. (firmware update works perfectly fine for me on Linux)

**Comment by Goofybud16** [comment]
Error 108 again.

Another

```
[112992.220406] xhci_hcd 0000:26:00.0: ERROR unknown event type 15
[112997.223153] xhci_hcd 0000:26:00.0: xHCI host not responding to stop endpoint command.
[112997.223189] xhci_hcd 0000:26:00.0: xHCI host controller not responding, assume dead
[112997.223208] xhci_hcd 0000:26:00.0: HC died; cleaning up
[112997.223234] usb 3-2: USB disconnect, device number 2
[112997.223237] usb 3-2.3: USB disconnect, device number 3
[112997.223239] usb 3-2.3.1: USB disconnect, device number 4
[112997.223326] usb 4-2: USB disconnect, device number 2
[112997.223327] usb 4-2.1: USB disconnect, device number 3
[112997.224054] usb 3-2.3.2: USB disconnect, device number 5
[112997.224585] usb 3-2.3.3: USB disconnect, device number 6
[112997.225143] usb 3-2.3.5: USB disconnect, device number 7
```

Something I've noticed that may be related to the issue: When SteamVR shuts down, the lights on the headset stay green. When plugged into a Windows machine, and when plugged into a USB 2 port on my computer, the lights seem to turn blue as soon as SteamVR exits.

**Comment by lologarithm** [comment]
Got my headset working yesterday after upgrading kernel to 5.3 and adding the 60-steam-vr.rules to my udev rules.d. 

Today I booted up computer and now headset lights stay blue instead of turning green. SteamVR reports error 108.  Here is my system report: https://gist.github.com/lologarithm/f0e73168d723594e2c7a5d65098ec1b1

Let me know anything I can try or any other info needed.

**Comment by Goofybud16** [comment]
Somewhere in the range of 4.2.3 to 4.2.6 there were some AMD USB controller fixes. I'll test this again on a USB 3 port tonight and see if my Index works in the morning.

**Comment by Goofybud16** [comment]
With kernel 5.2.0-1-amd64 #1 SMP Debian 5.2.6-1 (2019-08-05) x86_64 GNU/Linux, this is still an issue. Used my headset on USB 3 last night, left it plugged in (and system running overnight) and now SteamVR is giving an error 108 again.

The previous dmesg errors were repeated again.

**Comment by Goofybud16** [comment]
I've noticed that previously, in worst-case scenarios, the refusal to reconnect could happen as quickly as 20-30 minutes.

Since I last tried using USB 3 (I've been using USB 2), SteamVR has updated several times, and I've upgraded my kernel to 5.2.9. I switched my headset back to the USB 3 port last night, and have yet to have any issues. I'm going to leave it on USB 3 and I'll report if I have any further issues with it.

**Comment by Goofybud16** [comment]
I've still had zero issues with the USB 3 connection since my last post.

I'm going to say a new SteamVR/Kernel fixed whatever the bug was, and if nobody else has any problems, I'm going to say this issue is safe to close. I'm not sure what the problem was exactly, but it seems to have been resolved, at least on my system.

**Comment by Goofybud16** [comment]
I reinstalled my OS on a new SSD on Saturday and still have no issues. It's been over a week with no comments, and over a month since anyone else has even commented.

At this point I'm going to say SteamVR or a Linux kernel update fixed whatever the issue was and close this.

**Comment by jug007** [comment]
I haven't had the issue for ages now as well.
Only need to sometimes restart my computer because of sound problems now.
