### ISSUE TITLE
Reprojection is on and cannot be turned off

### ISSUE THREAD

**Issue by jug007** [ValveSoftware/SteamVR-for-Linux#227]
**Describe the bug**
Reprojection is on and cannot be deactivated.
Reprojection turns on even though it is not needed on OpenHMD and on Valve Index and never turns off again.
Reprojection cannot be disabled in settings and the Shift + A shortcut in the VR View doesn't work anymore (since the new VR View was added which shows no picture for me)

**To Reproduce**
-Start a game
-See reprojection turn on

**Expected behavior**
Have reprojection only turn on when needed and have it turn off if prefered.
I personally don't even want reprojection to turn on when I cannot hit the frametarget.

**Screenshot:**
![1Auswahl_574](https://user-images.githubusercontent.com/11144627/62816166-70aac500-bb23-11e9-9f5b-4ed794129be7.png)

**System Information:**
- Distribution: Linux Mint 19.2 (Ubuntu 18.04 based)
- SteamVR version: 1.7.3
- Steam client version:  August 6th 2019
- Opted into Steam client beta?: Yes
- Graphics driver version:  430.40
- Gist for SteamVR System Information: https://gist.github.com/jug007/f4d072ba51cf089439250a17c19220ec

**Performance Data (optional, but very helpful):**
- CPU: Intel i7-7800X
- GPU: Nvidia GTX 1080
- Gist for perf top: [See [instructions](https://github.com/ValveSoftware/SteamVR-for-Linux/blob/master/CapturingPerfData.md)]
- Link to gpuvis trace: [See [instructions](https://github.com/ValveSoftware/SteamVR-for-Linux/blob/master/CapturingPerfData.md)]

**Additional context**
This has been a problem for over a year now. Not being able to turn off reprojection even thought it (apparently arguably) only makes things worse.
Maybe related: Async reprojection is off and I don't see any obvious way to enable it.

**Comment by lostgoat** [comment]
Hi @jug007,

On linux async reprojection can be disabled in the steamvr settings file (located at `~/.steam/steam/config/steamvr.vrsettings`):

```
{
   "steamvr" : {
      "enableLinuxVulkanAsync" : true
   }
}
```

**Comment by jug007** [comment]
Async reprojection isn't the problem (and is disabled anyway) . Reprojection is the problem.

**Comment by lostgoat** [comment]
Hi @jug007,

The shift+a shortcut enabled/disabled async reprojection. Pressing it is equivalent to the setting I posted above.

**Comment by lostgoat** [comment]
Note, there is no non-reprojecting mode in SteamVR (on Linux or on Windows).

**Comment by jug007** [comment]
@lostgoat 
The reprojection that I am refering to is the reprojection according to the SteamVR settings:
![1Auswahl_575](https://user-images.githubusercontent.com/11144627/62890366-a4fccc00-bd43-11e9-99c0-27787d45f32e.png)
It was possible to turn off this reprojection with the Shift+a shortcut. According to the beta news, the shortcut does the following: "Pressing Shift+A has the same effect as disabling async, disabling interleaved reprojection, and enabling “always-on reprojection” (which just gives a full frame of running start to the app) in older versions of SteamVR." [Article here](https://steamcommunity.com/games/250820/announcements/detail/1696061565053940372)
When Shift+a was pressed, "Reprojection" would not turn on in the SteamVR settings and the framerates would no be capped at half the HMDs display refreshrate.
