### ISSUE TITLE
SteamVR window artifacts[BUG]

### ISSUE THREAD

**Issue by kwahoo2** [ValveSoftware/SteamVR-for-Linux#229]
SteamVR icons and buttons are invisible if SteamVR was started by an app or restarted.

1. Start a game, eg. The Lab
2. wait for SteamVR Window to appear.

**Screenshots**
![Corrupted window](https://i.imgur.com/jwxRsZn.png)

**System Information (please complete the following information):**
- Distribution: Kubuntu 19.04 64-bit
- SteamVR version: 1.7.3
- Steam client version: Aug 10 2019
- Opted into Steam client beta?: Yes
- Graphics driver version:  driverInfo = Mesa 19.2.0-devel (LLVM 8.0.0)
- Gist for SteamVR System Information: [SteamVR Info](https://gist.github.com/kwahoo2/a00398efea44148ba7d1081243208fc3)

**Comment by Goofybud16** [comment]
I've seen this issue as well.

I usually just restart SteamVR.

https://gist.github.com/Goofybud16/7ccac2eede54cb79f86b6ff3cb792122

Debian Testing with a kernel pulled from experimental/unstable.

**Comment by ChristophHaag** [comment]
I also reported this at #100.

**Comment by kwahoo2** [comment]
> I also reported this at #100.

Closing this as your is older issue.
