### ISSUE TITLE
radv performance issues

### ISSUE THREAD

**Issue by ChristophHaag** [ValveSoftware/SteamVR-for-Linux#23]
Hardware: i5 6500, RX 480

I've made a thread here, but didn't really get a definite reply:
https://steamcommunity.com/app/250820/discussions/5/133257959064945402/

tl;dr: Everything runs bad and has missed frames.

Examples:
Destinations: https://i.imgur.com/Gj7ly7U.png
Dota 2 VR Hub: https://i.imgur.com/Ai7ST5M.png
SteamVR Unity example scene from the plugin: https://i.imgur.com/aa2sryH.png
edit: These screenshots show interleaved reprojection off, but turning it on makes no difference.

Only the SteamVR environment itself shows no missing frames, but it isn't all smooth either.

Serious Sam VR TFE with default setting runs at ~45 FPS and is not smooth either.

According to Plagman it ran better in development but something regressed.

I hope this gets fixed soon, because as it is now it doesn't really feel usable.

**Comment by Plagman** [comment]
If you build the trivial example scene with the standalone player, it might be a good test case to start with for the radv developers. Performance problems are to be expected in this initial developer release phase, but we're working on it.

**Comment by kleinerm** [comment]
Out of interest, has somebody tried running it on a dual-X-Screen setup, where you create a /etc/X11/xorg.conf file to setup 2 X-Screens, using the ZaphodHeads option to assign X-Screen 0 to the output of the regular display monitor, and X-Screen 1 to the output driving the Vive? That should probably allow the driver to use page-flipping for presenting on the Vive and eliminate at least one source of latency.

**Comment by ChristophHaag** [comment]
Hm, I haven't commented with updates here. The update https://steamcommunity.com/games/250820/announcements/detail/261611816896118133 a while ago considerably improved things (interleaved reprojection should work now), and for example the Atlas Demo Scene in Destinations works pretty much perfectly now.

Still, there are performance issues. For example the tutorial has missed frames:
![screenshot_20170314_180013](https://cloud.githubusercontent.com/assets/781076/23943662/7a4a18e8-0970-11e7-9219-3652e5c09b19.png)
(Missed frames means that even the reprojection can't keep up, right?)

From the frametime monitor it looks like it is entirely CPU limited
![screenshot_20170314_180538](https://cloud.githubusercontent.com/assets/781076/23943678/8cc305e8-0970-11e7-9bed-46ad1f4e09ec.png)

but the i5 6500 should have more than enough power for this.

**Comment by johnv-valve** [comment]
adaptive quality renderer is currently disabled in the tutorial because it is broken in current Unity builds.

**Comment by ChristophHaag** [comment]
Steam Home has really long GPU frame times:
![screenshot_20170526_084642](https://cloud.githubusercontent.com/assets/781076/26495152/9352c8cc-4222-11e7-9576-8a5a2355b859.png)
surprisingly it runs somewhat okay with reprojection.

Recently there were two threads about Doom with Vulkan (in wine): https://www.reddit.com/r/linux_gaming/comments/6d74bk/doom_running_on_patched_radv_1710_driver_at_1440p/
and a closer look at its performance compared to amdgpu-pro: https://www.reddit.com/r/linux_gaming/comments/6denrx/radv_vs_amdgpupro_1710_performance_in_doom/

With the frame times with amdgpu-pro being just about half of those with radv it looks like there is a lot of room for improving the frame times in radv.

**Comment by beniwtv** [comment]
Yep, can report the same issue on an RX 480 and AMD FX8350 CPU.
Most things do micro-stutter.

**Comment by ChristophHaag** [comment]
I think I can close this now. While performance is still not perfect, it's really a lot better than in the beginning.
