### ISSUE TITLE
[BUG] Extreme latency when "Advanced Supersample Filtering" is enabled

### ISSUE THREAD

**Issue by Vash63** [ValveSoftware/SteamVR-for-Linux#232]
**Describe the bug**
Very noticeable latency when the 'Advanced Supersample Filtering" from the developer tab is enabled. Not sure if this was default or copied from my Windows install (where it doesn't cause issues) but either way disabling it and then restarting SteamVR mostly resolves the issue. It still feels like there is slight lag compared to Windows 10 but this may be the lack of async reprojection - the massive instantly sickness inducing lag is removed when this button is unchecked.

**To Reproduce**
Open SteamVR Settings
Developer tab
Check 'Enabled advanced supersample filtering'
Restart SteamVR
Test

**System Information (please complete the following information):**
- Distribution: Arch
- SteamVR version: 1.7.4
- Steam client version: Aug 12 2019 at 23:59:32
- Opted into Steam client beta?: Yes
- Graphics driver version:  435.17
- Gist for SteamVR System Information: [supersamplesteamvr.txt](https://github.com/ValveSoftware/SteamVR-for-Linux/files/3499163/supersamplesteamvr.txt)

**Note:** Commenters who are also experiencing this issue are encouraged to include the "System Information" section in their replies.

**Comment by Vash63** [comment]
So I'm not sure when this changed but I can no longer tell the difference in latency with the setting enabled or disabled. I _do_ still feel a frame or two of latency vs Windows 10 though. It's subtle but I'm easily affected by motion sickness and it makes me feel a bit sick. Easiest way to tell is to move my head in quick circles and try to focus on a stationary object, it looks like it's swimming around a bit while in Windows it's completely locked in place.

**Comment by Vash63** [comment]
Closing this, can no longer reproduce a difference due to this setting toggle. I think the remaining latency problems are #21

**Comment by XDjackieXD** [comment]
I can reproduce this issue again with the current steam vr beta (1.15.1) and the current nvidia drivers (455.23.04).
Disabling Advanced Supersampling Filter reduces latency extremely (from "causes motion sickness after 2 minutes of playtime in beatsaber" to "I can play for hours without problems"). On Windows with the same Hardware, the latency is perfectly fine.

Hardware is a GTX970 with a HTC Vive Pre.
Steam VR System Information (base stations and controllers where turned off while doing the dump): 
[SteamVR-2020-10-02-PM_10_46_01.txt](https://github.com/ValveSoftware/SteamVR-for-Linux/files/5320189/SteamVR-2020-10-02-PM_10_46_01.txt)
