### ISSUE TITLE
[BUG] Error: setcap of vrcompositor-launcher failed.

### ISSUE THREAD

**Issue by DanielHeath** [ValveSoftware/SteamVR-for-Linux#234]
After updating steamVR beta last week, I'm getting warned to check my logfile, which leads me to
`Error: setcap of vrcompositor-launcher failed.`

Any chance you could get it to log what exact capability it's trying to set? That way, instead of chasing up support, I could just check the logfile and add the capability myself.

**Comment by lostgoat** [comment]
Hi Daniel,

There should be a zenity popup with an error message and the error log location?

Are you launching vrsartup.sh from the cli through ssh?

P.S. we try so acquire CAP_SYS_NICE for vrcompositor-launcher

**Comment by DanielHeath** [comment]
The popup tells me an error occurred (not what it is) and the log location. The logfile contains the message I referred to. 

Adding CAP_SYS_NICE by hand seems to have done it.

**Comment by mDuo13** [comment]
I'm seeing this error message now as well.

After a recent update, Steam says, "superuser is required to finish setup" or something to that effect, then (regardless of what I click in the modal) gives me an error message pointing to a log file with the following contents:

```
Sun Aug 18 16:49:09 PDT 2019 - Error: user declined superuser request.
Wed Aug 21 14:19:08 PDT 2019 - Error: setcap of vrcompositor-launcher failed.
```

(I'm on Arch Linux, not Ubuntu, so maybe it's trying to use some graphical sudo equivalent I don't have installed?)

After launching the monitor has a little popup over it with an error:

> SteamVR Fail
> Oh no! SteamVR has encountered an unexpected problem.
> _Restart SteamVR_ (416)

Surprisingly, this does not seem to interfere at all with my ability to play Beat Saber in VR.

**Comment by mcourteaux** [comment]
This resolves the issue for me.

    sudo setcap CAP_SYS_NICE+ep .local/share/Steam/steamapps/common/SteamVR/bin/linux64/vrcompositor-launcher

**Comment by podiki** [comment]
This still happens on install of SteamVR. A dialog pops up saying superuser is needed to complete setup, but then the same error and log as reported above. Could be Steam doesn't know how to ask for sudo password on my system (just a WM, no DE)?

**Comment by cjxgm** [comment]
Looking into `vrstartup.sh`, I found my suspect at line 39:

```bash
	pkexec setcap CAP_SYS_NICE=eip $STEAMVR_TOOLSDIR/bin/linux64/vrcompositor-launcher
```

By manually invoking `pkexec` (e.g. `pkexec ls`), I got an error:

```
The value for the SHELL variable was not found the /etc/shells file

This incident has been reported.
```

And

```
$ cat /etc/shells
#
# /etc/shells
#

/bin/sh
/bin/bash
/usr/bin/fish
/bin/zsh
/usr/bin/git-shell
/bin/fish
```
```
$ echo $SHELL
/home/XXX/bin/local/fish.sh
```

which shows the root cause of the problem.
Adding my `/home/XXX/bin/local/fish.sh` to `/etc/shells` solves the `pkexec` problem, and a password popup has shown.

Then I tried to launch SteamVR, accept the superuser prompt, then a password popup shows asking for sudo password.
Eveyrhing has worked as expected.

This was my situation, your mileage may vary but try `pkexec ls` and see what errors are shown.

**Comment by ardishco-the-great** [comment]
> This resolves the issue for me.
> 
> ```
> sudo setcap CAP_SYS_NICE+ep ~/.local/share/Steam/steamapps/common/SteamVR/bin/linux64/vrcompositor-launcher
> ```

I did this, It got rid of the popup but the issue still remains. I can't launch it.

**Comment by mwestphal** [comment]
Same issue here:

System Information (please complete the following information):

    Distribution: ArchLinux
    SteamVR version: 1.24.7
    Steam client version: Dec 15 2022
    Opted into Steam client beta?: No
    Graphics driver version: nvidia  525.78.01 
    Gist for SteamVR System Information: https://gist.github.com/dbgasaway/688e7823c53f62e6357b3787dd313501
