### ISSUE TITLE
[BUG] Valve Index turns on again

### ISSUE THREAD

**Issue by Zamundaaa** [ValveSoftware/SteamVR-for-Linux#235]
**System Information (please complete the following information):**
- Distribution: [Arch/Manjaro/Ubuntu/etc.] Manjaro KDE
- SteamVR version: [E.g. 1.7.2] 1.7.6
- Steam client version: [build number or date] 1565918000
- Opted into Steam client beta?: [Yes/No] Yes
- Graphics driver version: Mesa 19.1.4 (LLVM 8.0.1)
- Gist for SteamVR System Information: https://gist.github.com/Zamundaaa/3b8a6e7552ced5487a629261957f240f

When exiting VR the display turns on again if it was off (on standby). That happens seconds before the "Exiting VR" window disappears. It then displays the gray from the headset not seeing the base stations, or a dark grey image instead. I have updated the firmware on a Windows install.

**Note:** Commenters who are also experiencing this issue are encouraged to include the "System Information" section in their replies.

**Comment by Goofybud16** [comment]
I've seen this as well.

As we speak, my Index is sitting with two (dim) green lights, even though I shut down SteamVR several hours ago. When shutting it down, the lights appear to stay green.

Eventually, if it sits long enough (overnight), it turns blue.

I suspect this could be related to #222.

[System Report](https://gist.github.com/Goofybud16/d684b2e3043b01024c002c47aaf784e7)

**Comment by Zamundaaa** [comment]
Still happening with 1.7.7

**Comment by lostgoat** [comment]
Has anyone seen this behaviour a non-index headset?

**Comment by Zamundaaa** [comment]
The display still turns on like before, but it turns off again, too, so this is fixed for me. @Goofybud16  can you confirm?

**Comment by Goofybud16** [comment]
Tested again with 1.7.12 and Debian's 5.2.9 kernel.

When I close SteamVR, the displays seem to turn off.

I'm not sure that the headset shuts down properly, though. The lights remain dim green (which I believe indicates "on but display inactive"), and the audio output device is still present in Pulse and able to play audio.

**Comment by h1z1** [comment]
Bit confused, is this only affecting the Index because I've had it happen with the Vive.  No idea if it's the same core issue though.

**Comment by Goofybud16** [comment]
Just tested again. Index stayed on, and the last image displayed on the screen was still displayed after SteamVR closed.

In this case, I just opened SteamVR, generated a System Report, and closed it.

**Comment by kisak-valve** [comment]
Hello @zamundaaa, can you check if reverting [drm/amd/display: Allow commits with no planes active](https://git.kernel.org/pub/scm/linux/kernel/git/stable/linux.git/commit/?id=bc92c06525e5865c94256ef0227bfe870c095823) fixes your issue?

**Comment by Zamundaaa** [comment]
Well I could try but I'm not sure it'll give any usable information. As of SteamVR 1.7.11 I don't have the issue anymore. The lights stay green though.
I don't know where the difference to @Goofybud16 lies. Maybe in the Mesa version? I'm on Mesa-git right now, although I don't know how up-to-date the repo is I'm using.
@h1z1 then #220 might not have been random or a crash at all.

**Comment by Goofybud16** [comment]
It almost seems like if I turn off SteamVR while the headset is in standby (dark green LEDs) the screens turn back on, but if I turn it off while it's on (bright green) it turns the screens off and leaves it in standby (Dark green LEDs)

**Comment by Zamundaaa** [comment]
Happening for me again. And the screen goes into standby if the display was on before, too.  When I then start SteamVR again I have to wait until it puts the headset to standby again or the display won't enable.
@kisak-valve I'm currently not able to compile Mesa-git myself because of LLVM 10 incompatibillity, and I need it for my new 5700 XT to work. Should probably be fixed the next week or something.

**Comment by Zamundaaa** [comment]
@kisak-valve 
> not able to compile Mesa-git

Just now noticed that is a kernel patch...
I tried reverting it in kernel 5.3 but it fails apparently because another patch has been applied on top of it, those lines have changed. I can't go down to kernel 5.2 or earlier.

**Comment by Goofybud16** [comment]
I've noticed that if I close SteamVR, and it _does_ shut down the headset, it won't start it back up. The screens go off and won't come back on.

I have to either wait a while or replug the headset for it to work again.

**Comment by lostgoat** [comment]
I forgot to link to the xserver side fix for this issue.

https://gitlab.freedesktop.org/xorg/xserver/commit/5aadaac9499c71ebf88c0e5fc658d9d56c8a7e16

Thanks kisak for reminding me on irc.

**Comment by Zamundaaa** [comment]
So once the patch hits distro packages, so once it updates to 1.20.6(?) the headset should actually turn off properly, right?

**Comment by Zamundaaa** [comment]
xorg-server 1.20.6 just landed in Manjaro testing and it works like expected :smile:

**Comment by Goofybud16** [comment]
Just wanted to confirm that with 1.9.8 and the latest updates in Debian Testing, this seems to be working.
