### ISSUE TITLE
[BUG] Can't open "Display Settings"

### ISSUE THREAD

**Issue by Zamundaaa** [ValveSoftware/SteamVR-for-Linux#237]
**System Information (please complete the following information):**
- Distribution: [Arch/Manjaro/Ubuntu/etc.] Manjaro KDE
- SteamVR version: [E.g. 1.7.2] 1.7.11
- Steam client version: [build number or date] 1567041311
- Opted into Steam client beta?: [Yes/No] Yes
- Graphics driver version:  [run `nvidia-settings` or `vulkaninfo | grep driverInfo`: Mesa 19.2.0 ACO
- Gist for SteamVR System Information: https://gist.github.com/Zamundaaa/6f5327062b5f4b84a3cb5d6ec70e4b1b

The title says it all. Nothing happens when I press that button.

**Note:** Commenters who are also experiencing this issue are encouraged to include the "System Information" section in their replies.

**Comment by FictionX** [comment]
Same.

System Information (please complete the following information):

- Distribution: [Arch/Manjaro/Ubuntu/etc.] Ubuntu 19.04
- SteamVR version: 1.7.11
- Steam client version: [build number or date] 1567041311
- Opted into Steam client beta?: [Yes/No] Yes
- Graphics driver version: [run nvidia-settings or vulkaninfo | grep driverInfo: Nvidia 430.40
- Gist for SteamVR System Information: https://gist.github.com/FictionX/7a0594df3108836af53add0986dcda92

Note: It works in Windows on the same PC

**Comment by Goofybud16** [comment]
Same problem here as well.

System Information (please complete the following information):

    Distribution: [Arch/Manjaro/Ubuntu/etc.] Debian Testing
    SteamVR version: 1.7.12
    Steam client version: [build number or date] 1566431379
    Opted into Steam client beta?: [Yes/No] No
    Graphics driver version: [run nvidia-settings or vulkaninfo | grep driverInfo: Mesa 19.1.4 (LLVM 8.0.1)
    Gist for SteamVR System Information: https://gist.github.com/Goofybud16/b032e537339fa964e1909705bbc743e8

**Comment by Goofybud16** [comment]
Still can't open it in 1.7.14.

**Comment by Zamundaaa** [comment]
Works now. :smile:

**Comment by Zamundaaa** [comment]
Doesn't work anymore (with 1.8.9, possibly before already)

**Comment by Zamundaaa** [comment]
Works again :smile:

**Comment by Zamundaaa** [comment]
Aand... doesn't work again with SteamVR 1.8.19. If I have the controller settings (/bindings) open on the desktop then the display settings appear there, not in VR though.

**Comment by Zamundaaa** [comment]
With 1.9.2 it shows that in order to enable Display Settings customisations I have to upgrade the headsets firmware. There is no firmware update available though...
Just to make sure I started Windows and it's exactly the same there.

**Comment by kisak-valve** [comment]
Per "Fixed Display Settings regression (which prevented it from being displayed)" in the [SteamVR 1.9.3](https://steamcommunity.com/games/250820/announcements/detail/2754443176874420379) update, please retest this issue.

**Comment by Zamundaaa** [comment]
Works again. Thanks! :)
