### ISSUE TITLE
Settings/Status window often black

### ISSUE THREAD

**Issue by Termuellinator** [ValveSoftware/SteamVR-for-Linux#242]
**Describe the bug**
The SteamVR status window sometimes has black squares instead of the icons for HMD, Controllers, LH. The settings window also often is just a black rectangle with grey border - it seems its just a display-issue as you can click on the "x"-location and the window closes.

**To Reproduce**
Start SteamVR and open the settings-dialogue  

**Expected behavior**
Having a usable settings window

**System Information (please complete the following information):**
- Distribution: Manjaro KDE
- SteamVR version: 1.7.15
- Steam client version: 1567553954 from Aug 30
- Opted into Steam client beta?: yes
- Graphics driver version: driverInfo = Mesa 19.3.0-devel (git-3664a6600e) (LLVM 10.0.0)
- Gist for SteamVR System Information: https://gist.github.com/Termuellinator/e7a7d27c2ebaad492c0c82ade1035981

**Screenshots**
will take some the next time it occurs

**Additional context**
i think this might probably be related to: https://github.com/ValveSoftware/steam-for-linux/issues/6451
It happend on my last rig (i5 3550 with rx580), too.

**Comment by kisak-valve** [comment]
Hello @Termuellinator, I've intermittently seen this with Gentoo for a long time, but not on Ubuntu 18.04 LTS. It is not related to libcef, possibly libpng related.

**Comment by Goofybud16** [comment]
Possibly related to #100?

**Comment by Termuellinator** [comment]
yeah, that's the issue - haven't searched for "corrupted" ^^
