### ISSUE TITLE
[BUG] Steam and Desktop Overlays Not Appearing

### ISSUE THREAD

**Issue by Goofybud16** [ValveSoftware/SteamVR-for-Linux#244]
**Describe the bug**
When I open the SteamVR Overlay interface, the "Steam" and "Desktop" buttons appear, but are just blank when selected. Settings, and Advanced Settings, both work. This started happening after reinstalling my OS onto a new drive. Previously, it was working.

**To Reproduce**
1. Open SteamVR from Steam
2. Open the overlay with the system button
3. Observe that nothing is shown for "Steam"
4. Select Desktop
5. Observe nothing is shown for Desktop.

**Expected behavior**
Steam and Desktop show the Steam Big Picture view and Desktop view.

**System Information (please complete the following information):**
- Distribution: [Arch/Manjaro/Ubuntu/etc.] Debian
- SteamVR version: [E.g. 1.7.2] Beta 1.7.15
- Steam client version: [build number or date] Aug 21 2019, 21:56:33
- Opted into Steam client beta?: [Yes/No] No
- Graphics driver version:  [run `nvidia-settings` or `vulkaninfo | grep driverInfo`: driverInfo = Mesa 19.1.4 (LLVM 8.0.1)
- Gist for SteamVR System Information: https://gist.github.com/Goofybud16/2bf16cf429795a572bee03f3f81b2466

**Screenshots**
![image](https://user-images.githubusercontent.com/669915/64914001-1511bf80-d6ff-11e9-81d3-45a66c32a262.png)
![image](https://user-images.githubusercontent.com/669915/64914008-383c6f00-d6ff-11e9-8705-b264ff361d7d.png)

**Additional context**
This worked on my previous OS install, but stopped working on a fresh install of Debian Testing. Possibly a missing package?

**Note:** Commenters who are also experiencing this issue are encouraged to include the "System Information" section in their replies.

**Comment by kisak-valve** [comment]
Hello @Goofybud16, please verify you have the `mesa-vulkan-drivers:i386` package installed with something like `apt policy mesa-vulkan-drivers:i386`.

**Comment by Goofybud16** [comment]
That package was not installed.

After installing it, it appears that the Steam and Desktop overlays are now working as expected.

Looks like mesa-vulkan-drivers:i386 is referenced in the README-- I'd just missed it. That's my bad. Everything seems to work great now. Thanks!
