### ISSUE TITLE
[BUG] "The Cubicle." window

### ISSUE THREAD

**Issue by Zamundaaa** [ValveSoftware/SteamVR-for-Linux#249]
**System Information (please complete the following information):**
- Distribution: [Arch/Manjaro/Ubuntu/etc.] Manjaro KDE
- SteamVR version: [E.g. 1.7.2] 1.8.2
- Steam client version: [build number or date] 1568741045 
- Opted into Steam client beta?: [Yes/No] Yes
- Graphics driver version: Mesa 19.3.0-devel (git-99c186fbbe) (LLVM 10.0.0)
- Gist for SteamVR System Information: https://gist.github.com/Zamundaaa/685d0fa20150a49e8f38b264b74b877e

This window, apparently named "The Cubicle." appears every time SteamVR is started.

**Screenshots**
![Screenshot_20190919_000907](https://user-images.githubusercontent.com/20477130/65189722-12ea9080-da72-11e9-9c65-f79dfb68a851.png)

**Note:** Commenters who are also experiencing this issue are encouraged to include the "System Information" section in their replies.

**Comment by Goofybud16** [comment]
I've been seeing this since 1.8.2.

Sometimes I get two of them.

![image](https://user-images.githubusercontent.com/669915/65209075-cd1ad180-da4b-11e9-8efc-a03cb91627c1.png)

https://gist.github.com/Goofybud16/e1203c3bd7399c0c93026642fad5e1c0

**Comment by Zamundaaa** [comment]
Opening debug commands spawns another "The Cubicle." window like you have it, but with the actual debug commands in it. There is a second actual "Debug Commands" window that doesn't even get cleared.
![Screenshot_20190919_205804](https://user-images.githubusercontent.com/20477130/65273010-7cc17380-db20-11e9-8ade-8223ed296e6a.png)
The debug commands at http://localhost:8998/dashboard/debugcommands.html don't seem to work anymore, I get a white page. The controller binding page still works (and I'm happy to say that the controller binding page in the dashboard seems to work now as well, although I am kind of lost on how to get to that page unless the application is missing bindings and it pops up automatically)

**Comment by l33tlinuxh4x0r** [comment]
I get one of these windows too, but on Gnome is shows up as "Unknown" I have included a screenshot of the window.
![Screenshot from 2019-09-20 21-53-06](https://user-images.githubusercontent.com/1632838/65366474-671c7e80-dbf2-11e9-8ff5-b6b4d21acf6f.png)

**Comment by Goofybud16** [comment]
I've found that setting STEAMVR_WEBHELPER=0 gets rid of the window.

**Comment by l33tlinuxh4x0r** [comment]
Is there an easy way to set this variable other than /etc/environment or changing the .desktop file? Is there a "proper" way to set this in steam?

**Comment by Goofybud16** [comment]
Set the launch options to

STEAMVR_WEBHELPER=0 %command%

in Steam.

**Comment by l33tlinuxh4x0r** [comment]
That doesn't work for me... Especially since I usually launch Steam VR via the VR button and not as a game/app. Setting it in my Environment file fixes it though wish that there was a better fix :/

**Comment by Zamundaaa** [comment]
Now I'm seeing a second window with the controller bindings. Not what I wished for with #264 but better than not having easy access to the controller bindings at all I guess.
The empty window is still there.

**Comment by Goofybud16** [comment]
Same experience as Zamundaaa. After the latest grabbing changes, I had to adjust some stuff, and I noticed the same problem.

**Comment by Goofybud16** [comment]
With 1.8.19, this appears to be fixed. There are no longer extra windows popping up.

The controller binding interface, however, does not appear to be working. Just get an empty gradient filled window.

**Comment by Zamundaaa** [comment]
Can confirm. The extra windows are gone :)
The controller pairing interface stays blank for me, too.
The display settings seem to not work again (#237).
