### ISSUE TITLE
[BUG] starting SteamVR crashes Steam

### ISSUE THREAD

**Issue by Zamundaaa** [ValveSoftware/SteamVR-for-Linux#251]
**System Information (please complete the following information):**
- Distribution: [Arch/Manjaro/Ubuntu/etc.] Manjaro KDE
- SteamVR version: [E.g. 1.7.2] 1.8.2
- Steam client version: [build number or date] 1568741045 
- Opted into Steam client beta?: [Yes/No] Yes
- Graphics driver version: Mesa 19.3.0-devel (git-99c186fbbe) (LLVM 10.0.0)
- Gist for SteamVR System Information: https://gist.github.com/Zamundaaa/685d0fa20150a49e8f38b264b74b877e

Sometimes when starting SteamVR, Steam crashes.
~~Or rather crashed, as #250 seems to "prevent" it from happening now - I'm not entirely sure how reproducable this is but it happened multiple times for me until the graphics hangs began.~~
Happened again just now. System report directly after Steam crashing: https://gist.github.com/Zamundaaa/00013cdc2b47a9dfb1b2487b6a5d2da4

**Note:** Commenters who are also experiencing this issue are encouraged to include the "System Information" section in their replies.

**Comment by rstrube** [comment]
Wouldn't it make more sense to close one of the bug reports (#250 or #251) since they seem closely related?
This way you can update your original report with new information as it comes to light, and you can keep the conversation in a single place.

**Comment by Zamundaaa** [comment]
Maybe. But I would guess that the hang is amdgpu related and the Steam bug is likely due to some communication failure between Steam and SteamVR. Maybe I can ssh into the machine when it hangs and find out if Steam has crashed or not. If it did (or is taking lots of CPU or whatever) then it's probably the cause. If so then I'll close one of them.
There's no need to apologize for wanting to help.

**Comment by Goofybud16** [comment]
I have this issue too. While debugging on 1.8.2, I noticed Steam often crashed when starting SteamVR.

I just had it happen on 1.8.3 as well.

https://gist.github.com/Goofybud16/e1203c3bd7399c0c93026642fad5e1c0 <-- Taken after I launched SteamVR. This was the first time I'd launched SteamVR today, and the first time launching 1.8.3.

If it matters, I am on the Steam Beta client.

**Comment by KibaGasteiz** [comment]
Affected too, Steam beta.
My PC info: https://gist.github.com/KibaGasteiz/f90ab0f1bd5509e4139fa99b79c1c067

**Comment by Zamundaaa** [comment]
I'll wait for a few more days to make sure but this seems to be fixed with the latest Steam Beta update

**Comment by DreamingRaven** [comment]
Hey I used to have the exact same problem on Archlinux mainline, but after a system update SteamVR wont even start anymore, it used to freeze the system for a good 10-15 seconds and then crash steam just like you are describing but now its not even getting far enough to crash.

Tested on:
SteamVR beta &
Steam beta client
and seperateley on:
SteamVR non beta
Steam non beta client

System info + Console log
https://pastebin.com/vDYyr55S

**Comment by Zamundaaa** [comment]
Hmmm I've never had any freezes and then a crash - I only had a graphics freeze until I reset the system OR Steam crashing.
You can upload SteamVR logs even if you can't launch it. They should be in ~/.local/share/Steam/logs/ (everything with vr at the beginning)

**Comment by Zamundaaa** [comment]
@DreamingRaven if the issue you're experiencing is still happening then you should open a new bug report. As I've had no Steam crash again aifter the Steam update I mentioned I'm closing this issue now.

**Comment by DreamingRaven** [comment]
Cheers @Zamundaaa will open a bug report later, been a busy week.
