### ISSUE TITLE
[BUG] Dashboard graphic bugs

### ISSUE THREAD

**Issue by fabiankranewitter** [ValveSoftware/SteamVR-for-Linux#253]
**Describe the bug**
The dashboard is torn or distorted. This makes it really not possible to use the dashboard.

**To Reproduce**
1. Start SteamVR
2. Click on System Button
3. See error

**Expected behavior**
The dashboard should not be distorted

**System Information:**
- Distribution: Kubuntu 19.04
- SteamVR version: 1.8.6
- Steam client version: Sep 23 2019,at 16:07:56
- Opted into Steam client beta?: Yes
- Graphics driver version:  Nvidia 435.21
- Gist for SteamVR System Information:
https://gist.github.com/fabiankranewitter/a5b1e9769b70ca7e84337a5fa8b48969

**Screenshots**
![Screenshot_20190926_163832](https://user-images.githubusercontent.com/6630450/65699306-2b643780-e07e-11e9-838e-5b0d7ccbdb0e.png)

**Note:** Commenters who are also experiencing this issue are encouraged to include the "System Information" section in their replies.

**Comment by rstrube** [comment]
I'm experiencing the same graphical corruption.

My Specs are almost identical.

Distribution: Ubuntu 19.04
SteamVR version: 1.8.6
Steam client version: Sep 23 2019,at 16:07:56
Opted into Steam client beta?: Yes
Graphics driver version: Nvidia 435.21

**Comment by Goofybud16** [comment]
I've seen similar behavior.

Sometimes the dashboard just won't show up, and sometimes it does but is distorted in weird ways.

https://gist.github.com/Goofybud16/cc14f06b748826913e970d8ec1eb486c

**Comment by geefr** [comment]
Same here, similar specs (mint instead of ubuntu)

Display of ipd adjustment is also corrupted, if I had to guess looks like the stride/texture format is wrong when handing off to the compositor.

(Sadly can't get a screenshot of that, vr view isn't working for me either)

**Comment by Lyle-Tafoya** [comment]
I experience this issue exclusively in the SteamVR beta, but not in the stable version.

System information: https://pastebin.com/Q8ch0JER

**Comment by kisak-valve** [comment]
Hello, per "Fixed Dashboard and IPD slider being corrupted on Nvidia drivers" in the SteamVR [1.8.8](https://steamcommunity.com/games/250820/announcements/detail/1592510390766386557) beta update, please retest this issue.

**Comment by geefr** [comment]
Dashboard and IPD issues working for me now (Nice IPD update, also doesn't stay visible for 30 odd seconds any more)

![Screenshot from 2019-10-04 20-18-38](https://user-images.githubusercontent.com/11091460/66233952-63a1f080-e6e4-11e9-91db-354d8213627c.png)

**Comment by fabiankranewitter** [comment]
the dashboard works for me again
