### ISSUE TITLE
[PERF] horrible Performance in Google Earth VR (348250)

### ISSUE THREAD

**Issue by Termuellinator** [ValveSoftware/SteamVR-for-Linux#257]
**Describe the bug**
I'm getting really bad FPS in Google Earth VR. It starts out fine and buttery smooth, even though the welcome tour starts in a city close to the ground. Shortly after, the FPS feel like being around 10-20 if you are close to the ground, its OK when zoomed out to see the earth as a globe.
https://www.protondb.com/app/348250 has several people reporting bad performance, too - i can't see a common denominator though.

**To Reproduce**
Start Google Earth VR and jump to a few locations

**Expected behavior**
Maintaining the good performance that is seen right after startup.

**System Information (please complete the following information):**
- Distribution: Manjaro KDE
- SteamVR version: 1.8.6
- Steam client version: 1569883362 from Sep 30
- Opted into Steam client beta?: yes
- Graphics driver version:  Mesa 19.3.0-devel (git-3c966fd688) (LLVM 10.0.0) on 5700XT
- Gist for SteamVR System Information: https://gist.github.com/Termuellinator/be41f6abf92575447f03f01b48c4df0b

**Performance Data (optional, but very helpful):**
- CPU: Ryzen 3800x
- GPU: Powercolor 5700xt Red Devil
- Gist for perf top: [See [instructions](https://github.com/ValveSoftware/SteamVR-for-Linux/blob/master/CapturingPerfData.md)]
- Link to gpuvis trace: [See [instructions](https://github.com/ValveSoftware/SteamVR-for-Linux/blob/master/CapturingPerfData.md)]
I can capture perf top/gpuvis next time i have it all set up if it helps to track down?

**Note:** Commenters who are also experiencing this issue are encouraged to include the "System Information" and "Perf Data" sections in their replies.

**Comment by kisak-valve** [comment]
Hello @Termuellinator, what version of Proton is being used with Google Earth VR (whitelist version is Proton 3.7-8)? In Steam, if you right click on Google Earth VR -> Properties -> Check `Force the use of a specific Steam Play compatibility tool` and select Proton 4.11-6 from the drop down list, does that have a significant effect?

**Comment by Zamundaaa** [comment]
Google Earth VR doesn't work properly for me at all with Proton 3.7-8, it just crashes after a short while. No performance problems up to that point though. With Proton 4.11-6 it works flawlessly, neither crashes nor performance problems.

**System Information (please complete the following information):**
- Distribution: [Arch/Manjaro/Ubuntu/etc.] Manjaro KDE
- SteamVR version: [E.g. 1.7.2] 1.8.6
- Steam client version: [build number or date] 1569883362
- Opted into Steam client beta?: [Yes/No] Yes
- Graphics driver version: Mesa 19.3.0-devel (git-34be977f80) (LLVM 10.0.0)
- Gist for SteamVR System Information: https://gist.github.com/Zamundaaa/37d5780b568d62b045d9058278a493ab

**Comment by Termuellinator** [comment]
> Hello @Termuellinator, what version of Proton is being used with Google Earth VR (whitelist version is Proton 3.7-8)? In Steam, if you right click on Google Earth VR -> Properties -> Check `Force the use of a specific Steam Play compatibility tool` and select Proton 4.11-6 from the drop down list, does that have a significant effect?

You are right! I didn't realize that it is whitelisted and using an old version of proton ^^
With 4.11-6 it runs perfectly.
That's one of the issues with the new library not showing if/what version of proton is used...

**Comment by Zamundaaa** [comment]
@kisak-valve I read on reddit and protondb that more people have this problem and that Proton 4.11 solves it for them. As this title is whitelisted, can you set the default Proton version to 4.11 so it works out of the box?

**Comment by kisak-valve** [comment]
Hello @Zamundaaa, you can fill out the [Whitelist Request](https://github.com/ValveSoftware/Proton/issues/new?template=whitelist-request.md) on the Proton issue tracker and I'll mark it as a whitelist update request to be evaluated.

**Comment by Zamundaaa** [comment]
Thanks! Here it is: https://github.com/ValveSoftware/Proton/issues/3408
