### ISSUE TITLE
[BUG] Steam and Desktop view corrupted

### ISSUE THREAD

**Issue by Zamundaaa** [ValveSoftware/SteamVR-for-Linux#262]
**System Information (please complete the following information):**
- Distribution: [Arch/Manjaro/Ubuntu/etc.] Manjaro KDE
- SteamVR version: [E.g. 1.7.2] 1.8.13
- Steam client version: [build number or date] 1571182697
- Opted into Steam client beta?: [Yes/No] Yes
- Graphics driver version:  Mesa 19.3.0-devel (git-2f23d925b8) (LLVM 9.0.0)
- Gist for SteamVR System Information: https://gist.github.com/Zamundaaa/f6352bc04cf4b031f627b033af51cb45

When using mesa-aco-git the Steam and Desktop view are corrupted / apparently display some GPU memory or something. It's probably connected that if I move the Steam window from my main display to the left or right one, resizing Steam in the process, the library (nothing else) gets weird as well. It's still reactive but the textures seem shifted:
![Screenshot_20191017_230414](https://user-images.githubusercontent.com/20477130/67047581-e12d1e00-f132-11e9-989c-7a99b4d86b85.png)
Resizing it makes it look fine again. That is, until I shift it to the main screen and back. I'll create a seperate issue on the Steam for Linux issue tracker as well.
If some logs or something would help, let me know which ones you need.

**Note:** Commenters who are also experiencing this issue are encouraged to include the "System Information" section in their replies.

**Comment by kisak-valve** [comment]
Hello @Zamundaaa, two things to check, if you completely close Steam and SteamVR, then run `RADV_PERFTEST=llvm steam` from a terminal, does that have an effect? Separately, do you have GPU accelerated rendering in web views enabled or disabled in Steam's settings (`Steam` -> `Settings` -> `Interface`) and does switching it have an effect?

**Comment by Zamundaaa** [comment]
Thanks for the quick response.
I just switched back to Mesa 19.2.1 and the bug is there, too, but it only happens every few times I put the window on the other screens. So it's not ACO. I'm not even sure if ACO even does anything at all on my 5700 XT yet.
The steam and desktop view in SteamVR work fine with Mesa 19.2.1 though.

I have GPU accelerated rendering enabled. Disabling it makes the issue go away. I'll have to retest the situation in SteamVR though.

**Comment by Zamundaaa** [comment]
Ok, disabling GPU accelerated rendering doesn't do anything for the SteamVR dashboard.
I see some lines with "assertion failed" in the Steam log, so maybe it's of use to you: https://gist.github.com/Zamundaaa/20cbd469e66996df426e96273d6ddb10
Some (or all of it) might just be the crash of Steam like in #255 though.

**Comment by Zamundaaa** [comment]
As I noticed I haven't added a screenshot of the actual problem, here's what it looks like in VR:
![Screenshot_20191121_002646](https://user-images.githubusercontent.com/20477130/69287205-b896b900-0bf5-11ea-8463-c24f4ea6f2a0.png)
If I point at where UI elements would usually be then the texture changes in some places but it never stops looking scrambled.

**Comment by Zamundaaa** [comment]
I reinstalled my system, keeping the home partition (and thus all Steam and SteamVR configs). Same packages as yesterday (mesa and vulkan git from the lcarlier repo) and now the Steam and Desktop tabs look like they're supposed to. As noone else seemed to have such a problem I'll just close this.

**Comment by cursedastronaut** [comment]
I have this problem, and reinstalling didn't work.
