### ISSUE TITLE
VR Button in top right of Steam does nothing

### ISSUE THREAD

**Issue by anoadragon453** [ValveSoftware/SteamVR-for-Linux#27]
#### Your system information
* Steam client version (build number or date): Feb 23, 2017
* Distribution (e.g. Ubuntu): Arch Linux (Seems to be distro agnostic)
* Graphics driver version (run nvidia-settings): 375.27.10
* Gist for SteamVR System Information: N/A
* Opted into Steam client beta?: Yes
* Opted into SteamVR beta?: Yes
* Have you checked for system updates?: Yes

#### Please describe your issue in as much detail as possible:
Clicking the [VR] button in the top right of Steam does nothing. I see no output generated in the console output either when it is clicked. Going to Library>SteamVR>Play DOES work.

Issue is experienced by many other users. [Discussion thread here](http://steamcommunity.com/app/250820/discussions/5/133257959064879358/).

#### Steps for reproducing this issue:
1. Plug in HMD
2. Click newly appeared VR button in top right
3. Nothing Happens
4. Shed a single tear :(

**Comment by kisak-valve** [comment]
Per "Fix launching SteamVR from the VR button." in the [2017-05-31](https://steamcommunity.com/groups/SteamClientBeta/announcements/detail/1267048039666098326) steam beta client, this issue should be fixed.
