### ISSUE TITLE
[BUG] Controller Pairing UI is blank

### ISSUE THREAD

**Issue by lostgoat** [ValveSoftware/SteamVR-for-Linux#270]
**Describe the bug**
Opening the controller pairing UI ( VR Monitor->Devices->Pair Controller ) opens a new window, but that window only shows a background

**To Reproduce**
1. Click on VR Monitor->Devices->Pair Controller

**Expected behavior**
Window has pairing UI content.

**Screenshots**
See the window on the left
![Image](https://i.imgur.com/Vc1tXVT.png)

**Note:** Commenters who are also experiencing this issue are encouraged to include the "System Information" section in their replies.

**Comment by lostgoat** [comment]
Workaround: open 'Pairing UI' twice (without closing the previous window).

**Comment by Zamundaaa** [comment]
Works with SteamVR 1.9.4 on the first time opening it.

**Comment by lostgoat** [comment]
Thanks for the reminder to close this issue :)
