### ISSUE TITLE
[BUG] Please plug in your VR headset on Arch Linux

### ISSUE THREAD

**Issue by amberkowalski** [ValveSoftware/SteamVR-for-Linux#272]
**Describe the bug**
I am using a Vive Pro (I have also tested an original Vive with my system with the same results). Steam detects the presence of a SteamVR device and shows the VR button, however, SteamVR does not detect my headset and says "Please plug in your VR headset." I have installed the 60-steam-vr.rule udev rule and I do have usbutils installed (from pacman). My attempts to read the crash dump it sometimes generates have resulted in me seeing `error accessing device 0` and the steam logs say `Initialize() is failed!!!`

**To Reproduce**
1. Open steam with a SteamVR device plugged in
2. Click on the VR button
3. See SteamVR say "Please plug in your VR headset"

**Expected behavior**
My VIve Pro should be recognized.

**System Information (please complete the following information):**
- Distribution: Steam
- SteamVR version: 1.8.21
- Steam client version: [build number or date] 
- Opted into Steam client beta?: Yes
- Graphics driver version:  440.31
- [Gist for SteamVR System Information](https://gist.github.com/amberkowalski/67e2020f2387a9c150fd350dcb1743ed)

**Additional context**
My setup worked fine on Windows.

**Note:** Commenters who are also experiencing this issue are encouraged to include the "System Information" section in their replies.

**Comment by amberkowalski** [comment]
Looksl like my computer did not like me mentioning giving it a blood sacrifice, SteamVR has decided it wants to work now.

**Comment by Hubro** [comment]
Well damn, I'm having this exact same issue... Steam detects that I have a VR headset connected (HTC Vive), but when I start SteamVR is just displays "Please plug in your VR headset".

I have reconnected the headset and rebooted my computer to no avail.
