### ISSUE TITLE
NVIDIA driver v375.27.12 breaks rendering the SteamVR default environment

### ISSUE THREAD

**Issue by kkriehl** [ValveSoftware/SteamVR-for-Linux#28]
#### Your system information
* Steam client version (build number or date): 1484790260 (Jan 19 2017, at 01:23:20)
* Distribution (e.g. Ubuntu): Arch Linux
* Graphics driver version (run nvidia-settings): 375.27.12
* Gist for SteamVR System Information: https://gist.github.com/kkriehl/97a63ccee6b8aec20506d68aba672b8f
* Opted into Steam client beta?: No
* Opted into SteamVR beta?: Yes
* Have you checked for system updates?: Yes

#### Steps for reproducing this issue:
1. Install the new NVIDIA beta drivers from https://developer.nvidia.com/vulkan-driver
2. Start SteamVR and put on your HMD
3. See a black screen with colored lines in the center instead of the SteamVR environment (see attached picture)

Destinations works ok but does sometimes show the visually also broken SteamVR loading environment. A Unity test build shows the same visual glitches in the Unity loading screen. After the scene has been loaded it renders correctly.

![01c0ce27-d384-453c-86ef-845e249273d3](https://cloud.githubusercontent.com/assets/560363/23364167/29d1e11c-fcfe-11e6-9fe4-a8087649c387.jpg)

**Comment by danginsburg** [comment]
Confirmed.  We are looking into this.  Recommend not using the NVIDIA 375.27.12 driver (stay on 375.27.10) until we can figure out what regressed.

**Comment by Plagman** [comment]
We got word from NVIDIA that they have found the problem and are working on a new driver release. Thanks for the report!

**Comment by damienleone** [comment]
We released new drivers (375.27.13) that should address this issue.

https://developer.nvidia.com/vulkan-driver

**Comment by kkriehl** [comment]
I can confirm that the new drivers fix this. I also have the feeling that the new driver reduces the perceived delay/distortion on rotational transformation a bit. I see the distortions mainly at the edges of the view so it could be linked to a difference in running the lense distortion shader?
