### ISSUE TITLE
[BUG] Unable to enter pairing mode

### ISSUE THREAD

**Issue by Nickson72** [ValveSoftware/SteamVR-for-Linux#281]
**Describe the bug**
When I try to enter pairing mode blank window is opened. There is no text or buttons.

**To Reproduce**
1. Open SteamVR monitor
2. Hoover on unpaired controller icon
3. Click on Pair Controller
4. Blank window open. After few second I got defaul violet background. No text or button for couple of minutes. Tried many times.

**Expected behavior**
There should be describing text and two buttons

**System Information**
- Distribution: Linux Mint 19.2 Cinnamon 4.2.4
- SteamVR version: 1.8.21
- Steam client version: Dec 11 2019
- Opted into Steam client beta?: Yes
- Graphics driver version:  nvidia 435.21
- Gist for SteamVR System Information: https://gist.github.com/Nickson72/440b051bd66561ce540618904c39271b

**Screenshots**
![screenshot_2019-12-12-13:26:13](https://user-images.githubusercontent.com/7840692/70717143-0df25180-1cee-11ea-90fa-802d15b6d669.png)

**Additional context**
Using 4K monitor 

**Note:** Commenters who are also experiencing this issue are encouraged to include the "System Information" section in their replies.

**Comment by kisak-valve** [comment]
Hello @Nickson72, please opt into SteamVR's beta branch and retest. This issue should already be resolved in the 1.9 beta (https://github.com/ValveSoftware/SteamVR-for-Linux/issues/270#issuecomment-556460963).

**Comment by Nickson72** [comment]
Under the 1.9.10 it works without flaw.

Sorry, I didn't notice there is "beta" under the "development release" :-)
Now I can use Unreal Engine in VR on linux, which is awesome and makes me happy! Thank you!
