### ISSUE TITLE
[BUG] SteamVR Settings doesn't load

### ISSUE THREAD

**Issue by yaomtc** [ValveSoftware/SteamVR-for-Linux#285]
**Describe the bug**
After the SteamVR Settings window opens, it never gets past "Loading..."

**To Reproduce**
1. Go to SteamVR Status
2. Click on the hamburger menu
3. Click on Settings 
4. See "Loading..."

**Expected behavior**
The SteamVR Settings window loads.

**System Information (please complete the following information):**
- Distribution: Arch Linux
- SteamVR version: Beta 1.9.15
- Steam client version: Dec 16 2019, at 16:49:05
- Opted into Steam client beta?: Yes
- Graphics driver version: Mesa 19.3.1 (LLVM 9.0.0)
- Gist for SteamVR System Information: https://gist.github.com/yaomtc/66071afca304d66caaa1ba84206b9444

**Screenshots**
![Screenshot_20191220_233039](https://user-images.githubusercontent.com/5534045/71303078-ebada300-2381-11ea-9186-7da43d8cee13.png)

**Additional context**
Sometimes it tells me to connect a VR headset (the Vive is always connected), even though it is. Usually it just says "Loading..." though. I also am currently experiencing #255, which may or may not be related.

**Note:** Commenters who are also experiencing this issue are encouraged to include the "System Information" section in their replies.

**Comment by TacticalTux** [comment]
Same issue on my end. Manjaro system here.
Also, it's always displaying into not-Direct Display mode, and I'm not getting Vive output.


    Distribution: Manjaro
    SteamVR version: Beta 1.9.15
    Steam client version: Dec 19 2019, at 00:33:07
    Opted into Steam client beta?: Yes
    Graphics driver version: NVIDIA 435.21
    Gist for SteamVR System Information: https://gist.github.com/TacticalTux/16df99e7f437c775e35d6d6fc5c4ac03

**Comment by TacticalTux** [comment]
Switching to the linux_temp beta seems to fix the issue for now. Probably a better idea to get the actual problem solved first, though.

**Comment by zaggynl** [comment]
Same for me:
```
SteamVR Version 1.9.15 (1576799282)
Steam:	Public (Public)
Tracking:	lighthouse
OS:	Ubuntu 18.04 with kisak PPA and Linux version 5.4.5-050405-generic (kernel@kathleen) (gcc version 9.2.1 20191130 (Ubuntu 9.2.1-21ubuntu1)) #201912181630 SMP Wed Dec 18 16:33:40 UTC 2019 (0.0.0.0)
Direct Mode Graphics:	AMD (79704065)

System
Admin:	Yes
Async Reprojection:	Enabled
Performance drops:	21/1 3/2 1/3 1/4 1945/1974
User IPD (m):	0.0648554

Displays - Direct Mode
```

**Comment by Zamundaaa** [comment]
Same for me as well.
**System Information:**
- Distribution: Manjaro KDE
- SteamVR version: 1.9.15
- Steam client version: 1576908998
- Opted into Steam client beta?: Yes
- Graphics driver version:  Mesa 19.3.1 (LLVM 9.0.0)
- Gist for SteamVR System Information: https://gist.github.com/Zamundaaa/44ed604c513387c3e16594cde2b1033e

**Comment by mnn** [comment]
I am experiencing same issue (Manjaro with i3).

<details>
  <summary>sys info</summary>
<pre>
Computer Information:
    Manufacturer:  Unknown
    Model:  Unknown
    Form Factor: Desktop
    No Touch Input Detected

Processor Information:
    CPU Vendor:  AuthenticAMD
    CPU Brand:  AMD Ryzen 7 3800X 8-Core Processor             
    CPU Family:  0x17
    CPU Model:  0x71
    CPU Stepping:  0x0
    CPU Type:  0x0
    Speed:  3900 Mhz
    16 logical processors
    8 physical processors
    HyperThreading:  Supported
    FCMOV:  Supported
    SSE2:  Supported
    SSE3:  Supported
    SSSE3:  Supported
    SSE4a:  Supported
    SSE41:  Supported
    SSE42:  Supported
    AES:  Supported
    AVX:  Supported
    AVX2:  Unsupported
    AVX512F:  Unsupported
    AVX512PF:  Unsupported
    AVX512ER:  Unsupported
    AVX512CD:  Unsupported
    AVX512VNNI:  Unsupported
    SHA:  Unsupported
    CMPXCHG16B:  Supported
    LAHF/SAHF:  Supported
    PrefetchW:  Unsupported

Operating System Version:
    "Manjaro Linux" (64 bit)
    Kernel Name:  Linux
    Kernel Version:  5.4.2-1-MANJARO
    X Server Vendor:  The X.Org Foundation
    X Server Release:  12006000
    X Window Manager:  i3
    Steam Runtime Version:  steam-runtime_0.20191210.1

Video Card:
    Driver:  NVIDIA Corporation GeForce RTX 2080 Ti/PCIe/SSE2
    Driver Version:  4.6.0 NVIDIA 440.36
    OpenGL Version: 4.6
    Desktop Color Depth: 24 bits per pixel
    Monitor Refresh Rate: 59 Hz
    VendorID:  0x10de
    DeviceID:  0x1e07
    Revision Not Detected
    Number of Monitors:  3
    Number of Logical Video Cards:  1
    Primary Display Resolution:  3840 x 2160
    Desktop Resolution: 5760 x 2160
    Primary Display Size: 24.45" x 13.43" (27.87" diag)
                                            62.1cm x 34.1cm (70.8cm diag)
    Primary Bus: PCI Express 16x
    Primary VRAM: 11264 MB
    Supported MSAA Modes:  2x 4x 8x 16x 

Sound card:
    Audio device: Nvidia GPU 91 HDMI/DP

Memory:
    RAM:  32043 Mb

Miscellaneous:
    UI Language:  English
    LANG:  en_US.UTF-8
    Total Hard Disk Space Available:  224535 Mb
    Largest Free Hard Disk Block:  24558 Mb
    VR Headset: None detected

Runtime information tool temporarily disabled.
</pre>
</details>

**Comment by mimattr** [comment]
> After the SteamVR Settings window opens, it never gets past "Loading..."

Confirmed, also experiencing the same issue including #255 

**System Information:**
- Distribution: **Ubuntu 18.04 LTS**
- SteamVR version: **1.9.16**
- Steam client version: **Dec 20 2019, at 23:41:30**
- Opted into Steam client beta?: **Yes**
- Graphics driver version:  **NVIDIA 440.44**
- [Link to Gist for SteamVR System Information](https://gist.github.com/mimattr/ae9cf0fd358e3a7abf667bc6814cd11f)

**Note:** Commenters who are also experiencing this issue are encouraged to include the "System Information" section in their replies.

**Comment by adde0109** [comment]
Have the same issue ass well as #255 

**System Information:**

- Distribution: **Ubuntu 19.10**
- SteamVR version: **1.9.16**
- Steam client version: **Dec 16 2019, at 16:49:05**
- Opted into Steam client beta?: **No**
- Graphics driver version: **NVIDIA 440.44**
- [Link to Gist for SteamVR System Information](https://gist.github.com/adde0109/349531c41bc4a8484320286122cfe382)

**Comment by ZarathustraDK** [comment]
Same problem here
- Distribution: Ubuntu 19.10
- SteamVR version: 1.9.16
- Steam client version: Dec 16 2019, at 16:49:05
- Opted into Steam client beta?: Yes
- Graphics driver version: NVIDIA 435.21

I also get the missing menu-overlay bug. Neither controller or headset menu-button work.

**Comment by Zamundaaa** [comment]
no change with 1.10.1

**Comment by Zamundaaa** [comment]
Seems to be fixed with 1.10.2!

**Comment by ZarathustraDK** [comment]
Confirming that it's fixed in 1.10.2.

Now we just need some features to enable ^^

**Comment by mimattr** [comment]
> Seems to be fixed with 1.10.2!

Agreed, this issue now appears to be resolved, many thanks to all involved!

**System Information:**
- Distribution: **Ubuntu 18.04 LTS**
- SteamVR version: **1.10.3**
- Steam client version: **Jan 18 2020, at 03:34:03**
- Opted into Steam client beta?: **Yes**
- Graphics driver version:  **NVIDIA 440.48**
- [Link to Gist for SteamVR System Information](https://gist.github.com/mimattr/ae9cf0fd358e3a7abf667bc6814cd11f)

**Note:** Commenters who are also experiencing this issue are encouraged to include the "System Information" section in their replies.

**Comment by Zamundaaa** [comment]
1.10.4 - "please connect headset"

**Comment by ZarathustraDK** [comment]
@Zamundaaa Same for me. I can, though, bring up the Dashboard in VR, go into desktop-view and bring up the settings from the SteamVR-app that way. Only once though, once I dismiss the dash the desktop-view freezes if I try to bring it up again.

**Comment by Zamundaaa** [comment]
Well, that was quick. Works again in 1.10.5 :+1:

**Comment by ZarathustraDK** [comment]
Confirmed working again here too.

**Comment by Zamundaaa** [comment]
In 1.10.6 (perhaps before that, too) it seems to sometimes work & sometimes "please connect headset"

**Comment by eiswuerfel** [comment]
Still not working for me.

- Distribution: Manjaro KDE
- SteamVR version:  1.9.16
- Steam client version:  Feb 15 2020 at 01:17:48
- Opted into Steam client beta?: Yes
- Graphics driver version: Nvidia 440.59
- Gist for SteamVR System Information: https://gist.github.com/eiswuerfel/bc5125d68c716e7ef4a22e6a17f05f25

**Comment by Zamundaaa** [comment]
I haven't had this problem in a while now :)

**Comment by yaomtc** [comment]
Forgot I was the one who reported this issue, oops! I can also confirm that this doesn't happen anymore. Thanks everyone
