### ISSUE TITLE
[BUG] Missing overlay/Unable to launch games when more than one Library Folder

### ISSUE THREAD

**Issue by GilgameshofUT** [ValveSoftware/SteamVR-for-Linux#288]
**Describe the bug**
When more than one Library folder is configured (in my testing it was always on a different drive) Steam seems to have trouble communicating with SteamVR. The SteamVR home is fine. The default panels of recently played games and trending games/rooms are all populated as expected. However if I launch a game from the recently played games list, the home fades out and in the grid I see the "Up Next" sign for the game and it hangs there for a while. Eventually it closes and I am just left in the grid with nothing happening.
If I try to call up the overlay bigscreen/desktop/settings menu, I cannot. NOthing happens when I use the button below the touch circle. If I try to call it up before launching the game, in the home setting, it also does not work. When I check Steam it has no indication the game is running. I have some success if I launch the game from the regular Steam interface (not in VR) then put on the VR headset. Again I cannot call up the overlay. This is without any special launch parameters. I have no issue with non vr games.

**To Reproduce**
1. Configure a second Steam Library Folder (in my testing it was on a different drive, but I don't know that is required. It did have games installed I am not sure if it will fail if there are no games)
2. Enter SteamVR in the default home
3. Attempt to start the overlay menu
4. Observe the zen like nothingness that happens
5. Attempt to launch a game (stored in either Steam Library Folder) from the recent games panel
6. Watch as it thinks about launching but never does
7. Remove the second folder (need to empty it, or better just rename it)
8. Try again...It works properly

Now if you want some added fun, while you are in the Default home open the Home Customization menu or whatever it is called (button above the touch circle) and select Items/Panels and attempt to add a Big Picture panel. It instantly crashes with a -203 error. I believe this is unrelated so I commented in a separate ticket on the -203 error that already existed but was a couple of months old. This crash is independent of having multiple Steam Library Folders.

**Expected behavior**
Call up the overlay/not crash

**System Information (please complete the following information):**
OS: Linux Mint 19.3 Tricia
KERNEL: 4.15.0-74-generic
CPU: AMD Ryzen 5 2600X Six-Core
GPU: NVIDIA GeForce GTX 1660 SUPER
GPU DRIVER: NVIDIA 440.44
RAM: 32 GB
HTC VIve
Used Beta, Linux Beta and non Beta versions. The -203 crash happened on all. The Multi Folder issue was tested methodically on the Linux Beta, I can't say with certainty if it occurred on the others. (Ok after I noticed the odd version number below I went back through and tried the others. They do not display the overlay at all, even with only one steam folder. Linux_Temp beta will fail to display it only if there are two folders configured).
- SteamVR version: Version 1.8.21 (1574294563) Hmmm.... This doesn't seem right. Why isn't it the latest version? OK checking on this and sure enough that is the most recent version I can get in Linux_temp Beta. Going to the regular beta I get 1.10.1. That version does not launch the overlay no matter what I do. I thought I saw report from Linux users with more recent versions. What version should I be using and is Linux_Temp deprecated? The latest version 1.10.2 announced a few hours ago doesn't seem to be available at all yet.
Steam Runtime Version:  steam-runtime_0.20191210.1

- Gist for SteamVR System Information: https://gist.github.com/GilgameshofUT/9a051b523dc4562f601827d556ebdf40

Thanks for all you guys do. I realize its still beta but it is coming along nicely.

**Note:** Commenters who are also experiencing this issue are encouraged to include the "System Information" section in their replies.

**Comment by GilgameshofUT** [comment]
Ok tried betas again today. This time the main beta let me install 1.10.2. This version does not have the same issue with multiple folders which was the primary reason I opened this bug report. The overlay shows up fine with one or two folders defined. The reliable -203 crash when attempting to open a big picture panel is still there however. Also linux_temp is still serving up version 1.8.21. You should probably remove that beta if it is deprecated. I see very recent posts online (within the last few days) of people recommending Linux users use that version.
If you want to track the -203 error in this ticket, great. If not feel free to close it and I will give any updates in the other thread.

**Comment by kisak-valve** [comment]
Hello @GilgameshofUT, glad to hear this issue is resolved for you. Please open a new issue report for the follow up issue so it can be tracked properly.
