### ISSUE TITLE
'Restart SteamVR' button does not work

### ISSUE THREAD

**Issue by jyemeier** [ValveSoftware/SteamVR-for-Linux#291]
#### Your system information
* Steam client version (build number or date): 1579298022:  Jan 17 2020 at 18:55:17
* Distribution (e.g. Ubuntu): Ubuntu 18.04
* Graphics driver version (run nvidia-settings): 440.44
* Gist for SteamVR System Information: https://gist.github.com/jyemeier/21f8a2203dcde79388a644b81b55aab2
* Opted into Steam client beta?: [Yes/No] yes
* Opted into SteamVR beta?: [Yes/No] yes
* Have you checked for system updates?: [Yes/No] yes

#### Please describe your issue in as much detail as possible:
When changing display refresh rate, steamvr settings present a 'Restart SteamVR' button and ask you to restart steamvr for the settings to take effect.  This does not work.  Instead, I get this on STDOUT:

`
+++ dirname /home/jye/.local/share/Steam/steamapps/common/SteamVR/bin/linux64/../vrmonitor.sh
++ cd /home/jye/.local/share/Steam/steamapps/common/SteamVR/bin/linux64/../
++ pwd
+ VRBINDIR=/home/jye/.local/share/Steam/steamapps/common/SteamVR/bin
+ [[ -n /home/jye/.local/share/Steam/steamapps/common/SteamVR/bin/vrenv.sh ]]
+ case $(uname) in
++ uname
+ VRMONITOR=/home/jye/.local/share/Steam/steamapps/common/SteamVR/bin/linux64/vrmonitor
+ exec /home/jye/.local/share/Steam/steamapps/common/SteamVR/bin/linux64/vrmonitor vrmonitor://restartsystem
/home/jye/.local/share/Steam/steamapps/common/SteamVR/bin/linux64/vrmonitor: error while loading shared libraries: libsteam_api.so: cannot open shared object file: No such file or directory
`
I expect steam to restart

#### Steps for reproducing this issue:
1. Launch Steam
2. Launch SteamVR
3. Open settings
4. Click 'Video'
5. Change refresh rate to some thing different
6 Click 'Restart SteamVR' button.

**Comment by Zamundaaa** [comment]
Can confirm. Calling ~/.local/share/Steam/steamapps/common/SteamVR/bin/linux64/vrmonitor vrmonitor://restartsystem also gives the same error.
Calling ~/.local/share/Steam/steamapps/common/SteamVR/bin/vrmonitor.sh vrmonitor://restartsystem however does work perfectly.

**Comment by Zamundaaa** [comment]
Most interesting is that I had SteamVR start in safe mode and when turning it off it prompted that it needs to restart for that. That restart button actually worked just fine.

**Comment by Zamundaaa** [comment]
Fixed with 1.10.8 :+1:

**Comment by edwin-v** [comment]
I just tried it in 1.10.21 and it didn't do anything. Actually, I don't think I've ever seen SteamVR actually restart properly, but the button from the settings menu doesn't even respond to anything.

**Comment by kisak-valve** [comment]
Hello @edwin-v, if you're seeing an issue similar to this one, it'll need a separate investigation. Please retest with the current SteamVR beta and open a new issue report if needed.

Closing as fixed in SteamVR 1.10.8.
