### ISSUE TITLE
Room Setup instantly crashes

### ISSUE THREAD

**Issue by thesbros** [ValveSoftware/SteamVR-for-Linux#3]
Running Room Setup shows the window for a second, then closes.

Log:
```bash
Found path: /home/oden/.local/share/Steam/steamapps/common/SteamVR/tools/steamvr_room_setup/linux64/steamvr_room_setup
Mono path[0] = '/home/oden/.local/share/Steam/steamapps/common/SteamVR/tools/steamvr_room_setup/linux64/steamvr_room_setup_Data/Managed'
Mono path[1] = '/home/oden/.local/share/Steam/steamapps/common/SteamVR/tools/steamvr_room_setup/linux64/steamvr_room_setup_Data/Mono'
Mono config path = '/home/oden/.local/share/Steam/steamapps/common/SteamVR/tools/steamvr_room_setup/linux64/steamvr_room_setup_Data/Mono/etc'
Preloaded 'ScreenSelector.so'
Preloaded 'libopenvr_api.so'

```

**Comment by johnv-valve** [comment]
Did you start room setup from the VR status monitor or directly from the command line? It needs to be run in the Steam Runtime.

**Comment by thesbros** [comment]
@johnv-valve I tried both the SteamVR window and from command line.

**Comment by thesbros** [comment]
After trying to launch a few more times, I got an assert error:

```bash
Found path: /home/oden/.local/share/Steam/steamapps/common/SteamVR/tools/steamvr_room_setup/linux64/steamvr_room_setup
Mono path[0] = '/home/oden/.local/share/Steam/steamapps/common/SteamVR/tools/steamvr_room_setup/linux64/steamvr_room_setup_Data/Managed'
Mono path[1] = '/home/oden/.local/share/Steam/steamapps/common/SteamVR/tools/steamvr_room_setup/linux64/steamvr_room_setup_Data/Mono'
Mono config path = '/home/oden/.local/share/Steam/steamapps/common/SteamVR/tools/steamvr_room_setup/linux64/steamvr_room_setup_Data/Mono/etc'
Preloaded 'ScreenSelector.so'
Preloaded 'libopenvr_api.so'
Assert( Assertion Failed: m_pModule ):/home/buildbot/buildslave/vrpanorama_main_ubuntu64_linux/build/src/public/tier1/interface.h:264

assert_20170221210511_5.dmp[18342]: Uploading dump (out-of-process)
/tmp/dumps/assert_20170221210511_5.dmp
```

Dump is attached.

[assert_20170221211016_5.zip](https://github.com/ValveSoftware/SteamVR-for-Linux/files/792281/assert_20170221211016_5.zip)

**Comment by thesbros** [comment]
Fixed by reinstalling the NVIDIA Developer drivers.

**Comment by koreldan** [comment]
have you reinstalled them using the PPA repository ?

**Comment by thesbros** [comment]
@koreldan I used the run file, but the PPA is better if you're on Ubuntu.

**Comment by Conzar** [comment]
@thesbros which NVIDIA Developer drivers did you re-install?

**Comment by thesbros** [comment]
@Conzar The latest version of the Vulkan Developer Beta. It's linked in the README.

**Comment by Conzar** [comment]
Thanks, I didn't realise there was a PPA.  I can't seem to install the PPA drivers ...
```
sudo apt-get install --reinstall nvidia-375
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Reinstallation of nvidia-375 is not possible, it cannot be downloaded.
```
I added the ppa and remove a previous ppa for nvidia graphics.

**Comment by Conzar** [comment]
I think I still need the graphics-driver ppa for the vulkin utils right?

**Comment by thesbros** [comment]
I'm not sure. The readme says **if** you're also using the graphics-drivers ppa, to pin the dev ppa higher - which leads me to believe it's not required.

**Comment by Conzar** [comment]
I figured it out.  I will leave the solution here for anyone else that might need it.
Edit /etc/apt/preferences.d/nvidia-375-pin-400
```
Package:  libcuda1-375
Pin: release o=LP-PPA-mamarley-nvidia-dev
Pin-Priority: 1000

Package:  nvidia-375
Pin: release o=LP-PPA-mamarley-nvidia-dev
Pin-Priority: 1000

Package:  nvidia-375-dev
Pin: release o=LP-PPA-mamarley-nvidia-dev
Pin-Priority: 1000

Package:  nvidia-libopencl1-375
Pin: release o=LP-PPA-mamarley-nvidia-dev
Pin-Priority: 1000

Package:  nvidia-opencl-icd-375
Pin: release o=LP-PPA-mamarley-nvidia-dev
Pin-Priority: 1000
```
Than issue the following commands

```
sudo apt-get update
sudo apt-get install nvidia-375 nvidia-375-dev
```

**Comment by Conzar** [comment]
So my solution above works for the setup but the tutorial crashes with the same error.  Anyone else having this issue?

**Comment by thesbros** [comment]
Try quitting Steam and then running it through command line with:

`STEAM_RUNTIME_PREFER_HOST_LIBRARIES=0 steam`

**Comment by Conzar** [comment]
@thesbros steamvr doesn't recognise my hmd if I do that.
