### ISSUE TITLE
[BUG] Proton games don't start if steam vr is already running

### ISSUE THREAD

**Issue by Matombo** [ValveSoftware/SteamVR-for-Linux#300]
**Describe the bug**
If SteamVR is running several games run through proton dodn't start with the error message in the steam console output:
```
GameAction [AppID 692690, ActionID 6] : LaunchApp failed with WaitingOpenVRAppQuit with "104"
GameAction [AppID 692690, ActionID 6] : LaunchApp changed task to Failed with ""
```
Starting the games without steamvr running starts steamvr and the game as expected.

Tested SteamVR versions: Beta 1.10.3, 1.9.16

Affected games: The Gallery - Episode 1, The Gallery - Episode 2, Dance Collider

NOT affected games: SUPERHOT VR

Last time i used steam vr the day before yesterday the issue wasn't there, but since then i both updated my system (manjaro linux roling release distro) and steam vr beta 1.10.3 was installed.

**To Reproduce**
1. Start Steam VR
2. Start one of the affected games
3. Game immediatly quits, steam console output says
```
GameAction [AppID 692690, ActionID 6] : LaunchApp failed with WaitingOpenVRAppQuit with "104"
GameAction [AppID 692690, ActionID 6] : LaunchApp changed task to Failed with ""
```

**Expected behavior**
Game launches

**System Information (please complete the following information):**
- Distribution: Manjaro
- SteamVR version: 1.9.16 & Beta 1.10.3
- Steam client version: Feb 11 2020, at 19:27:00
- Opted into Steam client beta?: No
- Graphics driver version: Mesa 19.3.3 (LLVM 9.0.1)
- Gist for SteamVR System Information: https://gist.github.com/Matombo/e89867c0e72923cedc43f29beae2d93e
- Gist for System Information: https://gist.github.com/Matombo/840bf14f73629bd9238f94870020f425

**Comment by farmboy0** [comment]
I have the same problem but it doesn't seem to affect all games. A few start even with SteamVR already running. 
An older SteamVR version doesnt fix the problem, I think it is steam related.

**Comment by farmboy0** [comment]
This might be related to https://github.com/ValveSoftware/steam-for-linux/issues/6892

**Comment by kisak-valve** [comment]
Hello @Matombo, there's no value in splitting the discussion between multiple issue trackers. Let's continue at https://github.com/ValveSoftware/steam-for-linux/issues/6896.

**Comment by Matombo** [comment]
no problem, makes sense
