### ISSUE TITLE
[BUG] Half-Life:Alyx SteamVR Destinations do not load

### ISSUE THREAD

**Issue by jrtberlin** [ValveSoftware/SteamVR-for-Linux#304]
**Describe the bug**
Both `Half-Life: Alyx - City 17 Alleyway` and `Half-Life: Alyx - Russell's Lab` do not load with the asset-packs installed, leaving the user on the loading screen.

**To Reproduce**
1. Download `Alyx - City 17 Alleyway`, `Half-Life: Alyx - Russell's Lab` and both Asset Packs
2. Select the environment in the environment menu
3. Steam VR Home enters the loading screen
4. Never loads (or I don't have enough patience)

This also applies to Rooms that host these environments.

**Expected behavior**
Environments for SteamVR Home (that are technically a DLC for SteamVR) load on all supported platforms.

**System Information (please complete the following information):**
- Distribution: KDE neon (Ubuntu 18.04)
- SteamVR version: 1.10.23
- Steam client version: 2020-03-03
- Opted into Steam client beta?: Yes
- Graphics driver version: Nvidia 440.59 
- Gist for SteamVR System Information: https://gist.github.com/jrtberlin/feb843e533ae88455cab9d6a07645ef2

**Note:** Commenters who are also experiencing this issue are encouraged to include the "System Information" section in their replies.

**Comment by tdjb** [comment]
I'm experiencing a similar issue, steamtours is crashing once I attempt to load any HL:A add-ons.
The reverse log hints at missing files, and yes I could not `find` any of the missing files.

I tested with a random environment and that instantly worked without problems.

**System Information (please complete the following information):**
- Distribution: Debian Testing (bullseye)
- SteamVR version: 1.10.23
- Steam client version: 03.03.2020
- Opted into Steam client beta?: Yes
- Graphics driver version:  440.59
- Gist for SteamVR System Information: https://gist.github.com/tdjb/87c19dd632c46e304eb6ec57bdd390f0

**Comment by danginsburg** [comment]
Fix is on the way for this, should be in the next SteamVR beta update.

**Comment by kedodrill** [comment]
I've downloaded the update that notes that it fixes the crash, but now I encounter "MustRead(): Failed to read 4096 bytes" whenever I start SteamVR. It prevents SteamVR Home from loading.

**Comment by jean730** [comment]
I also have the "MustRead(): Failed to read 4096 bytes" error on SteamVR home launch.
The problem has shown on 1.10.24 and 1.10.25

**Comment by zaggynl** [comment]
Same on the above error, SteamVR Home no longer loads, sometimes shows the environment but freezes after the error appears.

Gist for SteamVR System Information: https://gist.githubusercontent.com/zaggynl/cb798bf2a82d65b360cbc14b6e78f81b/raw/58faca89d2a8d32a4b1fc50daf57bd2bf9e45998/gistfile1.txt

**Comment by jean730** [comment]
The mustread bug has a dedicated issue: https://github.com/ValveSoftware/SteamVR-for-Linux/issues/305

**Comment by tdjb** [comment]
This as well as #305 have been resolved for me as of SteamVR v1.10.26.

Both destinations worked really well, in City 17 the sky-box is broken, this most likely is the same issue as #299.

Thank you, I'm so glad I can peek into HL:A from Linux now.

**Comment by jrtberlin** [comment]
SteamVR v1.10.26 fixed the issue for me. Thanks for the fix!
