### ISSUE TITLE
[BUG] steam home won't load "must read()" error

### ISSUE THREAD

**Issue by rnd-ash** [ValveSoftware/SteamVR-for-Linux#305]
Since the most recent update of steamvr beta, home doesn't load, and I get a very generic error message popup on steamvr startup "must read() failed".

**To Reproduce**
1. Update to steamvr beta 1.10.25
2. Launch steamvr
3. Observe error message and lack of steam home

**System Information**
- Distribution: Arch
- SteamVR version: 1.10.25
- Steam client version: 1583545531
- Opted into Steam client beta?: Yes
- Graphics driver version:  Nvidia 440.64

**Comment by zurohki** [comment]
I actually don't get an error pop up. Home just doesn't load.

In VR the Home loading window appears, and then disappears again.

**Comment by Lyle-Tafoya** [comment]
I can confirm this bug. I also see the must read error popup. I am also using Arch Linux and the same nvidia driver version.

**Comment by tdjb** [comment]
As of SteamVR v1.10.26 the issue appears to be fixed.

**Comment by Zamundaaa** [comment]
Home doesn't have this error for me, it starts like it's supposed to.

**Comment by rnd-ash** [comment]
can confirm this works fine on 1.10.27
