### ISSUE TITLE
Launching steamVR after launching Serious Sam VR shows a never-ending updating dialog

### ISSUE THREAD

**Issue by voidplayer** [ValveSoftware/SteamVR-for-Linux#31]
#### Your system information
* Steam client version (build number or date): 24 feb 03...
* Distribution (e.g. Ubuntu): debian/testing
* Graphics driver version (run nvidia-settings): 375.27.13
* Gist for SteamVR System Information: the same as number #7 but I changed my nvidia 950 to a nvidia 1060
* Opted into Steam client beta?: Yes
* Opted into SteamVR beta?: Yes
* Have you checked for system updates?: Yes

#### Please describe your issue in as much detail as possible:

SteamVr doesnt try to update, but after launching serious sam VR, the next time you try to launch steamVR it shows the updating dialog:

"Updating SteamVR" and "preparing to launch SteamVR" with a progress dialog that does not progress

I tried to remove it, to verify integrity and all kind of things, but it doesnt work.

I also tried to opt out of the steam client beta, rm -rf ~/.local/share/Steam/SteamApps/common/SteamVR then verified integrity of the files to reinstall, then in the steamvr properties disabled cloud sync and opted into the beta again. But it only downloads the feb 24 built

I also have issue #16 so I cant really finish configuring the vive

 I believe last version is from March 1st, so it should try to update

**Comment by kisak-valve** [comment]
Hello @voidplayer, https://steamdb.info/app/250820/history/ indicates the last steamvr beta branch update was a week ago. While this is not a definitive source of information, it is a pretty strong indicator that you have the current beta version.

**Comment by voidplayer** [comment]
well, when I launch steamvr If I have previously launch serious sam vr at least once since the last time i reinstalled steamvr, i get this screen that never finish
![selection_001](https://cloud.githubusercontent.com/assets/4019910/23577911/6d566220-00cb-11e7-974b-dcfbbc528979.png)

If I click "view updates" I get this screen:
![selection_002](https://cloud.githubusercontent.com/assets/4019910/23577920/8c53cece-00cb-11e7-8b4b-3507faa187c7.png)

Which is this [url](https://steamcommunity.com/app/250820/allnews/)

If i visit that url on a browser i get different dates
![selection_251](https://cloud.githubusercontent.com/assets/4019910/23577947/f5124ed6-00cb-11e7-86f1-a92816908359.png)

So theres a bug somewhere, but not sure where or whose fault is it :)

I cant really go much further since i get #16 as I already mention

PS: your link says Last Record Update 	a day ago (March 3, 2017 – 01:02:06 UTC)

**Comment by Cheeseness** [comment]
@voidplayer If you opt out of the SteamVR beta and then back into the beta, does that then allow you to launch SteamVR after it finishes downloading?

My suspicion is that you already have the latest update and have hit a general Steam client bug.

**Comment by voidplayer** [comment]
no, I have to uninstall it and reinstall steamvr and dont launch serious sam vr

I also believe i have the latest version. What made me think I hadnt is because the date is different when I clicked update (see 2nd screenshot)

Also, this happens consistently. I can reproduce it as many times as needed :)

**Comment by Cheeseness** [comment]
Ah, if you can actually uninstall SteamVR then it's not the bug I was thinking of.

**Comment by voidplayer** [comment]
Now that you mention it, I wasnt able to uninstall it... I removed the folder manually. When clicking in uninstall, it shows the uninstall dialog, but it does steamvr is still installed at the end

I do have latest version, and switching from normal to beta, I was able to launch it again

For some reason #16 does not affect me anymore, so I was able to finish the room setup and launch serious sam vr, but it crashes after a while

After restarting steam, I have to opt out and in of beta again or it shows the "updating steamVR" dialog again

**Comment by Cheeseness** [comment]
Ah ha, perhaps it is that same bug after all. If you disable Steam Cloud support for SteamVR from the properties dialog before running SteamVR for the first time, do you continue to experience the same problem with an "Updating" dialog that never finishes? As mentioned [here](https://github.com/ValveSoftware/SteamVR-for-Linux/issues/15#issuecomment-282654134), this should prevent you hitting this bug.

**Comment by voidplayer** [comment]
Not sure if related because I had read that thread and I had cloud disabled

After todays update I reenabled it, tried serious sam vr again, it crashed again and closed everything and restarted everything and the dialog didnt show up

What fixed it or if its fixed permantly I dont know, but im going to close this because I cant reproduce it anymore :)

**Comment by ryantux** [comment]
This bug has appeared again for me regardless of the "cloud update" option

**Comment by Cheeseness** [comment]
Just to be clear, if it is having a difference, then turning off "Steam Cloud synchronization" is a preventative measure rather than something that will resolve the issue once it's happened.

**Comment by ryantux** [comment]
I'm not 100% sure what's going on as after a reboot a SteamVr update came in, steamvr and Destinations​ was running perfectly. No issues whatsoever until i loaded a different scene ( looked like a beach hut)
The scene immediately locked up and after shutting down and exiting Steam etc then launching again caused the update dialogue problem. I did kill all remaining vr related background tasks 

The window draw on the steamVr  was all messed up, unreadable and missing buttons so i was unable to determine the state after that.

I'll test again tomorrow after a reboot, I've a feeling it's an unclean shutdown from the lockup that's causing this error

**Comment by Cheeseness** [comment]
Yeah, so far as I can tell, the problem happens when stuff crashes before/during a Steam Cloud update (which seems to be happening pretty frequently with SteamVR still being not-so-stable), but you don't see the issue until the next time you try to launch the app/game.

**Comment by voidplayer** [comment]
Just to be clear, I had cloud sync turned off in steamVR and this kept happening (this dialog showing after serious sam crash)

And just to be clear, When I closed this bug, It stopped happening and I turned on steamVR cloud sync and serious sam crashed again and this didnt happen again

So maybe cloud sync is part of it, but it didnt seem my particular case much. If you carefully read my original report, you can see I had cloud disabled before reinstalling and it still happened

@ryantux I havent tried again, since theres not much to do in vr in linux right now, but feel free to reopen the bug if you can reproduce it

**Comment by ryantux** [comment]
@voidplayer I'm able to reproduce this bug every time, the only way to get steamVR to run cleanly next time is to opt out of the beta and back in again. A simple reboot doesn't help in my case.

As my system locks up pretty hard after all this it makes testing pretty slow but i guess its due to the unclean state SteamVr is left in from the previous crash, verification of the files makes no difference however.
