### ISSUE TITLE
[BUG] Valve Index base stations not detected

### ISSUE THREAD

**Issue by SuperV1234** [ValveSoftware/SteamVR-for-Linux#319]
**Describe the bug**
My SteamVR installation on Linux works and detects my headsets and controllers, however Valve Index base stations are not detected at all. Putting the headset on shows a blank grey image, and the system is obviously unusable.

**To Reproduce**
1. Open Steam
2. Start SteamVR

**Expected behavior**
I would expect the base stations to be detected and turned on. 

**System Information (please complete the following information):**
- Distribution: Arch
- SteamVR version: tried both Linux beta 1.8.21 and the latest normal beta 1.11.2
- Steam client version: Feb 11 2020
- Opted into Steam client beta?: yes
- Graphics driver version: 440.64
- Gist for SteamVR System Information: https://gist.github.com/SuperV1234/eb7a3c607a65e8e424305d9af24ceb6a

**Screenshots**
N/A

**Additional context**
Bluetooth options from Steam do not work. I tried connecting and pairing the stations with `bluetoothctl`, but I kept getting `Failed to pair: org.bluez.Error.AuthenticationTimeout`.

I use my system on Windows 10 without any issue, and base station power management is enabled there.

**Comment by kherchel** [comment]
Base station power management and Bluetooth connectivity are unsupported on Linux, I'd take a wild guess and say that's why the stations don't wake up. Try turning off this functionality in Windows.

**Comment by SuperV1234** [comment]
@kherchel: that did the trick. For some silly reason I assumed that the base station would power up regardless of the setting on Windows. Cheers.
