### ISSUE TITLE
[BUG] 1.11.5:Unable to connect to pipe errno=111

### ISSUE THREAD

**Issue by farmboy0** [ValveSoftware/SteamVR-for-Linux#324]
**Describe the bug**
After updating to 1.11.5 the dashboard doesnt open anymore and starting HL:A results in a dialog stating that SteamVR failed to initialize.

**To Reproduce**
1. Update to 1.11.5
2. Start HL:A
3. Dialog pops up with 'SteamVR has encountered a critical error.'

**Expected behavior**
The game starts normally as it did with 1.11.4.

**System Information (please complete the following information):**
- Distribution: Gentoo
- SteamVR version: 1.11.5
- Steam client version: April 3, 2020 at 22:37:13
- Opted into Steam client beta?: Yes
- Graphics driver version:  Mesa 20.0.3 (LLVM 9.0.1)
- Gist for SteamVR System Information: https://gist.github.com/farmboy0/16f79f8c08e6062bb1cf5365963499ce

**Note:** Commenters who are also experiencing this issue are encouraged to include the "System Information" section in their replies.

**Comment by spats-colombo** [comment]
I am currently experiencing the same bug, vr would start in 1.11.4, but not with 1.11.5.

I'm running:

SteamVR version : 1.11.5
Steam client version :Apr 3 2020, at 22:37:31
Steam Beta yes
Graphics Mesa 20.1 (llvm 11)

My distribution is Arch, have tried with vanilla kernel and agd5f drm-next-5.7 kernel. 

Both fail in the same way. Web console reports as above and
vrcompositor seems to fail and become a zombie process.

**Comment by spats-colombo** [comment]
Steam System info:
[https://github.com/spats-colombo/thespeakeasy/blob/master/SteamSystemInfo](url)

**Comment by spats-colombo** [comment]
Just to follow up core dump of vrcompositor caused by lib_vulkan_radeon. Downgrading arch package vulkan-git to official vulkan (and 32 lib) solves the problem for me.

**Comment by farmboy0** [comment]
Running HL:A from the command line produces the following output:
`amdgpu: The CS has been rejected, see dmesg for more information.`
`vk: error: failed to submit CS`
And dmesg says:
`[ 3778.022846] [drm:amdgpu_syncobj_lookup_and_add_to_sync] *ERROR* syncobj 20 failed to find fence @ 0 (-22)!`
`[ 3778.022849] [drm:amdgpu_cs_ioctl] *ERROR* Failed in the dependencies handling -22!
`This is with kernel 5.5.13

**Comment by spats-colombo** [comment]
There are a couple of patches in Alex Deucher's repo, in the drm-next branch that relate to CS.
[https://cgit.freedesktop.org/~agd5f/linux/commit/?h=drm-next&id=7f068a12eeb6ee85e707e8ffeb2e004286f33c5e](url)
&
[https://cgit.freedesktop.org/~agd5f/linux/commit/?h=drm-next&id=3fd59cf85bb4e59b2d8833d48e3d252f4c2abb28](url)

**Comment by farmboy0** [comment]
Was the same error as #278
