### ISSUE TITLE
[BUG] Project Cars 2 freezes loading into a race

### ISSUE THREAD

**Issue by kalrach** [ValveSoftware/SteamVR-for-Linux#325]
Description:
When attempting to load into a custom race, Project Cars 2 will load into the cockpit but then freeze unable to take any additional input. The only way to exit is to hit [Alt]-[F4] or kill the application. In some instances the game causes SteamVR itself to crash with a prompt saying that the minimum SteamVR version required is SteamVR version 1.10.1.

To Reproduce:
Attempt to load any custom race in Project Cars 2 in VR mode. Once loaded in the game will render the initial cockpit view and then freeze, not being able to take any further inputs requiring user intervention to kill the application or for the game to crash and take SteamVR with it.

System Information:
- uname -a Output: Linux helius 5.5.13-1-MANJARO #1 SMP PREEMPT Wed Mar 25 17:14:28 UTC 2020 x86_64 GNU/Linux
- Distribution: Manjaro
- SteamVR version: 1.10.32
- Steam client version:  steam-runtime_0.20200318.2
- Opted into Steam client beta?: No
- CPU: Intel Core i9-9900K
- GPU: NVIDIA RTX2080
- Ram: 16GB
- Graphics driver version: NVIDIA  440.64
- Gist for SteamVR System Information: https://gist.github.com/kalrach/2d2c5e3a17b69f926ef252a024ffb25a

Additional Notes:
The game menu only shows up on the flat monitor and requires the user to control the game from the flat monitor. Attempts to control the game from SteamVR desktop view also causes the game to freeze and crash.

**Comment by kisak-valve** [comment]
Hello @kalrach, we're tracking issues with games run with Proton in the Proton issue tracker. Addtionally, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/908#issuecomment-609408439.
