### ISSUE TITLE
SteamVR hangs/closes when selecting 'Pair Controller'

### ISSUE THREAD

**Issue by jlarison** [ValveSoftware/SteamVR-for-Linux#33]
#### Your system information
* Steam client version (build number or date): 1487812945
* Distribution (e.g. Ubuntu): Ubuntu 14.0.4
* Graphics driver version (run nvidia-settings): 375.27.13
* Gist for SteamVR System Information: https://gist.github.com/jlarison/9d3ac84862993033374840dc98736add
* Opted into Steam client beta?: Yes
* Opted into SteamVR beta?: Yes
* Have you checked for system updates?: Yes

#### Please describe your issue in as much detail as possible:
One of my vive controllers is in the 'blue' state when powered on and the other connected on the first try and is in the 'green' state.  When I right click on the greyed out controller in SteamVR and select 'Pair Controller', SteamVR either hangs or quits instantly.  The same occurs when selecting SteamVR beta > Devices > Pair Controller.

#### Steps for reproducing this issue:
1. Open SteamVR
2. Right click on an inactive controller
3. Select 'Pair Controller'

Or:

1. Open SteamVR
2. Select 'SteamVR beta' > 'Devices' > 'Pair Controller'

**Comment by Conzar** [comment]
I can confirm this happens to me too.

**Comment by kisak-valve** [comment]
Per "- SteamVR hangs/closes when selecting 'Pair Controller'" in the [2017-03-20 SteamVR update](https://steamcommunity.com/games/250820/announcements/detail/261612552476748410), this issue should be resolved.
