### ISSUE TITLE
[BUG] Half-Life Alyx View is Very Glitchy

### ISSUE THREAD

**Issue by Sgt-Schultz** [ValveSoftware/SteamVR-for-Linux#335]
**Describe the bug**
The view in the menu randomly jerks up and down and the game is basically unplayable. After I managed to click new game I found that the same problem is in the actual game too. For some reason the "click trigger to continue" rooms are normal.

**To Reproduce**
1. Launch the game

**Expected behavior**
View does not jerk around

**System Information (please complete the following information):**
- Distribution: Ubuntu 18.10
- SteamVR version: Beta 1.11.8
- Steam client version: 3/26/20
- Opted into Steam client beta?: NO
- Graphics driver version:  NVIDIA Driver Version: 390.116
- Gist for SteamVR System Information: https://gist.github.com/Sgt-Schultz/c66dfaaf85b10d99717c233701fff8fb

**Additional context**
Using Proton 5.0-5 for Half-Life Alyx. Also I was previously getting an error on launch "unable to to find a valid direct3d device" but after some looking I found that using the launch option "PROTON_USE_WINED3D=1 %command%" fixed that, not sure if it has to do with this problem.

**Note:** Commenters who are also experiencing this issue are encouraged to include the "System Information" section in their replies.

**Comment by kisak-valve** [comment]
Hello @Sgt-Schultz, Ubuntu 18.10 has been unsupported for over a year, nVidia 390 is older than the [support cutoff](https://github.com/ValveSoftware/Proton/wiki/Requirements#nvidia) for Proton, and `PROTON_USE_WINED3D=1` tells Proton to try to use wine's DirectX to OpenGL render path, which is known to come with a severe performance penalty and is considered unsupported.

Additionally, we're tracking issues with games run with Proton in the [Proton](https://github.com/ValveSoftware/Proton) issue tracker. If you still have trouble after updating to a distro release that is actively supported by the distro, a recent nVidia driver release, and drop the diagnostic env variable, please add your experience to https://github.com/ValveSoftware/Proton/issues/3681 and we can ponder it further.
