### ISSUE TITLE
[Feature Request] proton builtin "VR mode" for pancake games

### ISSUE THREAD

**Issue by frostworx** [ValveSoftware/SteamVR-for-Linux#337]
VirtualDesktop and similar programs to get pancake games into VR don't work on linux via proton.
So playing those with a Reshade Side-by-Side shader in VR is not possible (no idea if windows people still use that).
Also 3rd party tools like VorpX (are there others?) very likely (haven't tried) won't work via proton.
There are also some custom VR mods for pancake games (f.e. mothervr or a gta V mod) which use patched dxgi.dll dlls and probably never will with proton as well.
Imho an option to start any pancake game in VR directly built into wine/dxvk/proton would be a very interesting feature also outside the linux community. in theory this should be possible, shouldn't it?
sure no simple task, but hey you're valve! </my2cents>

**Comment by SketchStick** [comment]
"xrdesktop" supports KDE and Gnome, it allows you to move individual windows around in VR and the performance with flat games seemed pretty good to me.

Project: https://gitlab.freedesktop.org/xrdesktop/xrdesktop
Installation: https://gitlab.freedesktop.org/xrdesktop/xrdesktop/-/wikis/howto

**Comment by kisak-valve** [comment]
Hello @frostworx, this issue is already being tracked at #94. Closing as a duplicate.

**Comment by frostworx** [comment]
I know xrdesktop, thx. that's not what I want and imho this also is no duplicate of #94.
very likely I simply didn't express correctly.
what I meant is not a virtual screen in vr, but the feature to "recalculate" the normal default view of a pancake (3d) game to a vr view (2 cameras), so it basically feels like a real vr game. never touched vorpx and any other of menitoned 3rd party hacks to achieve this, but looks like those tools work for windows people, so I'm pretty sure this could be working even better with being closer at the "os source code" -> wine/dxvk/openvr/vrclient64

**Comment by kisak-valve** [comment]
Thanks for clarifying, this is too far outside of the scope of SteamVR or Proton to be considered.

If you dig into this and figure out how to wire it up, it most likely would need to go to a popular third party Proton build for it to reach a larger user base.

**Comment by frostworx** [comment]
thanks for the feedback, kisak-valve! I know this is "no simple task, but hey you're valve!".
I can't program this by myself and I also can live without that feature easily. I just thought it would be a 
nice unique selling point for vr-gaming under linux.

**Comment by frostworx** [comment]
just for the records, in case someone else is looking for a possible "pancake 2D games in VR on linux" solution. maybe (something like) this works:
https://github.com/DEC05EBA/vr_video_player/issues/1

**Comment by frostworx** [comment]
fyi: above vr_video_player works excellent with games with builtin SBS option
and even (kind of) works using vkbasalt with SBS shader.
I wrote a little tutorial:
https://www.reddit.com/r/SteamPlay/comments/gbdiia/playing_regular_games_in_vr_works_on_linux_finally/

**Comment by Patola** [comment]
> fyi: above vr_video_player works excellent with games with builtin SBS option
> and even (kind of) works using vkbasalt with SBS shader.
> I wrote a little tutorial:
> https://www.reddit.com/r/SteamPlay/comments/gbdiia/playing_regular_games_in_vr_works_on_linux_finally/

hey @frostworx , I admire a lot you work but it seems you deleted your tutorial? Do you have a new home for it? I'd like to mention it on an article I am writing.

**Comment by frostworx** [comment]
hi, @Patola. No sorry, I wiped all of my reddit entries without any backup.

**Comment by ChristophHaag** [comment]
There are websites that archive deleted reddit comments btw https://www.removeddit.com/r/SteamPlay/comments/gbdiia/playing_regular_games_in_vr_works_on_linux_finally/ (needs a browser with tracking protection disabled to connect to the reddit api, because reddit tracks...)

**Comment by Patola** [comment]
That was very helpful, thank you, @ChristophHaag. @frostworx, any messenger contact (telegram, signal, etc.) where I could speak to you? I think I might help on that front.

**Comment by frostworx** [comment]
I randomly (rarely) idle on IRC. Apart from that nothing. Everything and more which was covered in the manual is also implemented automated in my launcher, so it might be a good idea to browse that as well. Feel free to open an issue over there for questions.

**Comment by frostworx** [comment]
Thanks @Patola for a [very good article](https://boilingsteam.com/the-state-of-virtual-reality-on-linux)!

**Comment by purplebar0** [comment]
> fyi: above vr_video_player works excellent with games with builtin SBS option and even (kind of) works using vkbasalt with SBS shader. I wrote a little tutorial: https://www.reddit.com/r/SteamPlay/comments/gbdiia/playing_regular_games_in_vr_works_on_linux_finally/

Has anyone archived any of this? Removeddit is dead and Unddit doesn't work, and Internet Archive as well as Archive.Today have no entries.

On top of that, it seems that `vr_video_player` is gone.

Why don't people archive their stuff? ಠ_ಠ

**Comment by ChrisJAllan** [comment]
vr-video-player is [here](https://git.dec05eba.com/vr-video-player/).

But nowadays, you should probably use [WlxOverlay](https://github.com/galister/WlxOverlay) instead for wayland support and whatnot.
