### ISSUE TITLE
[BUG] Half-Life: Alyx - Crash when transitioning outside after the first floating card boxes

### ISSUE THREAD

**Issue by michael-nischt** [ValveSoftware/SteamVR-for-Linux#356]
**Describe the bug**
Half-Life: Alyx repeatedly crashes when transitioning outside after the first floating card boxes (see screenshot). Therefore preventing progressing any further in the game. (It's actually the first time the game crashes but it does always at this location.)
It might very well be a Vulkan Issue also happening on Windows (see additional context for details).

**To Reproduce**
1. Launch SteamVR
2. Launch HL: Alyx
3. Load a save game at the location the first floating card boxes appear.
4. When transitioning outside area the game crashes to desktop.

**Expected behavior**
Either a seamless transition or a loading screen. No sure what would the exact behavior be without the crash.

**System Information (please complete the following information):**
- Distribution: Ubuntu 20.04
- SteamVR version: 1.12.5
- Steam client version: May 30 2020, at 20:39:29
- Opted into Steam client beta?: Yes
- Graphics driver version:  nVidia 440.64
- Gist for SteamVR System Information: [SteamVR System Information](https://gist.github.com/michael-nischt/05d810198f1a56f7be65de2a33542b4e#file-steamvr-2020-05-31-am_11_35_07-txt)

**Screenshots**
![Screenshot from 2020-05-31 11-34-06](https://user-images.githubusercontent.com/500820/83349422-16d6ee00-a335-11ea-9f40-126290911e8a.png)

**Additional context**
I found a report on the Steam Forums from yesterday which suggest the same issue also happens on Windows when using the Vulkan API. Of course on Linux, we can't use the suggested workaround switching to Direct3D 12. [Report on Steam](https://steamcommunity.com/app/546560/discussions/0/2272575584118566549/)

Further, I launched steam via the terminal. It shows shaders loaded/pre-cached for HL: Alyx but no new output at the time of the crashes. 

**Note:** Commenters who are also experiencing this issue are encouraged to include the "System Information" section in their replies.

**Comment by yaomtc** [comment]
I'm hitting this too, on AMD graphics. (RX 5700 XT)

System Information (please complete the following information):

    Distribution: Arch Linux
    SteamVR version: 1.12.5
    Steam client version: June 1 2020, at 20:22:35
    Opted into Steam client beta?: Yes
    Graphics driver version: Mesa 20.0.7; Linux 5.7rc7
    Gist for SteamVR System Information: [SteamVR System Information](https://gist.github.com/yaomtc/936a138ccc73619a0ed1a70a0eb0c2c7)

**Comment by dikel** [comment]
I have the same problem. I tried to disable the pre-caching but it didn't fix it.
When the game was released natively for Linux I finished it so it is a recent bug

**Comment by Il-Drugo** [comment]
Same problem. 
Gist for SteamVr: [Info](https://gist.github.com/Il-Drugo/72f71bf28f34083d461d2f7881413595)

**Comment by Hafas** [comment]
Having the same issue at the same place.
But in my case my whole system just crashes - either black screen or the system restarts itself. (though that may be related with AOC enabled - I'll make an other test without AOC)

Distribution: Arch Linux
SteamVR version: 1.12.5
Steam client version: Jun 4 2020, at 05:51:01
Opted into Steam client beta?: Yes
Graphics driver version: Mesa 20.0.7
Gist for SteamVR System Information: [SteamVR System Information](https://gist.github.com/Hafas/d0f9a6507e0ba38bf37f230dc8fc0b31)

[This is what journalctl spits out](https://gist.github.com/Hafas/3adbfbc765ea2d2d6bc752d47efe0b49)

**Comment by yaomtc** [comment]
What GPU are you using, @Hafas? I can't tell from your System Information.

SteamVR has been occasionally been causing system crashes for me, but it most often happens as I start up SteamVR. I believe this is my issue, 

https://gitlab.freedesktop.org/drm/amd/-/issues/1149

though I'm not sure. There's also this issue, 

https://bugzilla.kernel.org/show_bug.cgi?id=206987

And there might be room for a third somewhere. I don't know... there seems to be some stability issues with some AMD cards on Linux right now.

**Comment by Hafas** [comment]
AMD Radeon RX 5700 XT, but SteamVR itself seems fine with me. Been playing Beat Saber (the only other VR-Game I've played so far) for two weeks without any problems.

**Comment by yaomtc** [comment]
I upgraded to 5.7.0-1-mainline this morning and haven't had a system crash yet, but I'll need to test for another couple days before I'll draw any conclusions.

If only there was a fix available for this Vulkan crash. I guess I could go back to Proton for a little bit just to get past this... but I've already played through the game once so I guess I'll just wait.

**Comment by slackerbob** [comment]
I can also confirm this happening on Arch Linux

Distribution: Arch Linux
SteamVR version: 1.13.2
Steam client version: Jun 4 2020, at 05:51:01
Opted into Steam client beta?: Yes
Graphics driver version: nvidia-dkms 440.82-2

System Information: [Gist](https://gist.github.com/slackerbob/0e636a8e5e1d2f047a7b449657947383)

**Comment by danginsburg** [comment]
Did the v1.4.1 update to HL:A that shipped yesterday fix this for you?  I was able to repro this on the previous release but not the new one so I wanted to make sure it's fixed.

**Comment by computer-whisperer** [comment]
That update fixed it for me.

Distribution: Arch Linux
SteamVR version: 1.12.5
Steam client version: Jun 15 2020, at 19:59:27
Opted into Steam client beta?: Yes
Graphics driver version: mesa 20.1.1-1

**Comment by yaomtc** [comment]
Also fixed it for me.

- Distribution: Arch Linux
- SteamVR version: 1.13.3
- Steam client version: June 15 2020, at 19:59:27
- Opted into Steam client beta?: Yes
- Graphics driver version: Mesa 20.1.1 (LLVM 10.0.0)
- [Gist for SteamVR System Information](https://gist.github.com/yaomtc/61dc7192817e3fb2bb262d3ed689dd17)

**Comment by danginsburg** [comment]
Thanks all for the confirmation.  I'll close this bug out.
