### ISSUE TITLE
[BUG] SteamVR cannot set itself as default OpenXR runtime

### ISSUE THREAD

**Issue by yaomtc** [ValveSoftware/SteamVR-for-Linux#359]
**Describe the bug**
When I launch the latest SteamVR beta, I see the following message:

> SteamVR isn't set as the default OpenXR runtime.
> This might prevent some applications from running correctly. The OpenXR runtime is not currently set.

Clicking "Set as default" doesn't seem to do anything -- there is no password prompt to modify a system file, and the message doesn't go away (unless I hit Dismiss) and it comes back the next time I start SteamVR.

This appears in the terminal output when "Set as default" is clicked:

```
OnOpenXr
OnSetAsDefaultXrRuntime
```

**To Reproduce**
1. Launch SteamVR beta 1.13.2 _(on Arch Linux at least - not sure if Ubuntu handles this differently)_

**Expected behavior**

"Set as default" makes an observable change.

**System Information (please complete the following information):**
- Distribution: Arch Linux
- SteamVR version: 1.13.2
- Steam client version: June 4 2020, at 05:51:01
- Opted into Steam client beta?: Yes
- Graphics driver version: Mesa 20.1.0 (LLVM 10.0.0)
- Gist for SteamVR System Information: https://gist.github.com/yaomtc/4f3c4d44ad93be736fc1841dee1bb58f

**Screenshots**
![Screenshot_20200612_000859](https://user-images.githubusercontent.com/5534045/84463839-f7976500-ac40-11ea-9c69-18cd1bc66ca1.png)

**Note:** Commenters who are also experiencing this issue are encouraged to include the "System Information" section in their replies.

**Comment by Zamundaaa** [comment]
Same problem here... I tested it with Blender and it said there was no active runtime.

**System Information:**
- Distribution: Manjaro KDE
- SteamVR version: 1.13.2
- Steam client version: 1591251555
- Opted into Steam client beta?: Yes
- Graphics driver version:  Mesa 20.1.1 (LLVM 10.0.0)
- Gist for SteamVR System Information: [SteamVR-2020-06-13-AM_12_09_59.txt](https://github.com/ValveSoftware/SteamVR-for-Linux/files/4773468/SteamVR-2020-06-13-AM_12_09_59.txt)

**Comment by lostgoat** [comment]
This bug might be due to the openxr runtime manifest directory not existing. Can you try creating the following dir and trying again:

`mkdir ~/.config/openxr/1/`

If you have your XDG configuration directory configured to a different location, then create `openxr/1` there instead.

**Comment by Zamundaaa** [comment]
Yes, that did it. Thanks!
Blender now finds the runtime but can't connect (it uses OpenGL, so no surprise there) but hello_xr with Vulkan worked without a problem.

**Comment by yaomtc** [comment]
Can also confirm this allows "set to default" to work.

In what circumstance would this directory already exist?

**Comment by DASPRiD** [comment]
> This bug might be due to the openxr runtime manifest directory not existing. Can you try creating the following dir and trying again:
> 
> `mkdir ~/.config/openxr/1/`
> 
> If you have your XDG configuration directory configured to a different location, then create `openxr/1` there instead.

This command fails if the openxr directory itself doesn't exist. Recommended command instead:

`mkdir -p ~/.config/openxr/1`

**Comment by slackerbob** [comment]
> This command fails if the openxr directory itself doesn't exist. Recommended command instead:
> 
> `mkdir -p ~/.config/openxr/1`

I can also confirm that creating these directories fixed this issue for me, on Arch Linux.

**Comment by samualblair** [comment]
This also worked for me, Ubuntu 20.04 (upgraded from previous Ubuntu 19.10 install). 
I am also curious what if anything should be creating this folder to start with?

**Comment by audunmg** [comment]
Thanks, this was puzzling me too. On Debian unstable if it matters.

**Comment by kisak-valve** [comment]
Hello, it looks like a fix for this might have slipped in under the radar. Please retest.

**Comment by yaomtc** [comment]
Yes, this is fixed! I deleted ~/.config/openxr/ then launched SteamVR. Once I clicked "set as default", the prompt went away and openxr/1/active_runtime.json was created again.

**Comment by DocMAX** [comment]
![image](https://github.com/user-attachments/assets/c4ed0186-e6d0-46fe-9289-0b1cd6a4af05)

I have /home/docmax/.config/openxr/1/active_runtime.json
```
{
    "file_format_version": "1.0.0",
    "runtime": {
        "name": "Monado",
        "library_path": "../../../lib/wivrn/libopenxr_wivrn.so",
        "MND_libmonado_path": "../../../lib/wivrn/libmonado.so"
    }
}
```
But OpenXR runtime "none". When i try to set

**Comment by T342guy** [comment]
> > This bug might be due to the openxr runtime manifest directory not existing. Can you try creating the following dir and trying again:
> > `mkdir ~/.config/openxr/1/`
> > If you have your XDG configuration directory configured to a different location, then create `openxr/1` there instead.
> 
> This command fails if the openxr directory itself doesn't exist. Recommended command instead:
> 
> `mkdir -p ~/.config/openxr/1`

haha! This worked! on bazzite, iirc is redhat based, but thanks!
