### ISSUE TITLE
Error: Installation path could not be located (110)

### ISSUE THREAD

**Issue by DiThi** [ValveSoftware/SteamVR-for-Linux#36]
![image](https://cloud.githubusercontent.com/assets/1127198/23822175/4ddb57e4-0647-11e7-862e-2e343b87e01c.png)

Tracking is working but there's no video on the HMD and it's not detected by room setup. Also, room setup is in Spanish for some reason (I'm from Spain but I have everything else set to English).

Before I installed SteamVR I had the extended screen disabled, I suspect that may be related and I don't know how to enable it back. If that's the case, should I try uninstalling Nvidia drivers? Or is there a different way to enable it? (just a guess)

Intel i5 CPU, Nvidia 1070 with vulkan beta driver 375.27.13 on (k)ubuntu 16.04 x64.
Latest SteamVR beta. https://gist.github.com/DiThi/7457a794c9b4c778ce54fb71d8c3e8f4

I haven't updated the lighthouse firmware because they work perfectly on Windows, and it was the update when bluetooth power management finally worked properly. I can update them if you think it may be necessary, though.

edit: It was running with `STEAM_RUNTIME_PREFER_HOST_LIBRARIES=0`, I just tried without it, with same result.

**Comment by anoadragon453** [comment]
Are you certain you are on the latest Steam Beta Client as well? Top Left Settings>Beta Programs>Steam Client Beta.

IIRC this error changed to Error 111 then was cleared up in the latest Steam Client Beta, rather than the SteamVR Beta.

**Comment by DiThi** [comment]
Good call. I think the README should say "Make sure both Steam and SteamVR is set to the beta branch" or something like that to avoid confusion between the two.

It's taking forever with "Preparing to launch SteamVR..." with the update dialog...

**Comment by anoadragon453** [comment]
Yes, unfortunately that is another issue that's currently sitting in the open queue. 

For me going between Steam client non-beta and beta seem to fix it. You may also want to try uninstalling/reinstalling SteamVR and verifying the local files (under Right-Click SteamVR>Properties>Local Files or something similar).

**Comment by DiThi** [comment]
I had to uninstall it from non-beta, then install from beta. It works!

Performance is not great and there's no async reprojection, but at least I can develop in my favourite OS. Thanks!
