### ISSUE TITLE
[BUG] 1.13.7 broke VR completely

### ISSUE THREAD

**Issue by DASPRiD** [ValveSoftware/SteamVR-for-Linux#367]
Since the 1.13.7 update today, VR stopped working completely. Within VR, you just see it starting Steam Home for quite a long time until it just gives up and quits VR (Graceful exit). The logs get spammed with these kind of messages from different sources:

```
Excessive binding loads from vrwebhelper_pairing (21639): crc=0 lc=1 Reload=F res=0
Excessive binding loads from vrwebhelper_settings_desktop (21652): crc=0 lc=1 Reload=F res=0
Excessive binding loads from vrcompositor (20588): crc=0 lc=1 Reload=F res=0
Excessive binding loads from vrwebhelper_keyboard (21646): crc=0 lc=1 Reload=F res=0
Excessive binding loads from vrwebhelper_main (21418): crc=0 lc=1 Reload=F res=0
```

**Comment by JoeLudwig** [comment]
Hi DASPRiD. 

Sorry you're seeing this. Can you attach a system report to this issue so we can track down what's going on?

**Comment by DASPRiD** [comment]
@JoeLudwig I think this was just an unlucky incident. Apparently shortly before the SteamVR update the NVidia drivers awere updated as well. A restart solved the problem – false alarm :)
