### ISSUE TITLE
[BUG] SteamVR disables mouse & keyboard input

### ISSUE THREAD

**Issue by jmanabc** [ValveSoftware/SteamVR-for-Linux#374]
**Describe the bug**
Anytime I launch SteamVR, my mouse and keyboard stop working until I restart my computer. Headset turns on, but is not tracked

**To Reproduce**
1. Go to 'Steam'
2. Click on 'VR'
3. Scroll down to 'nothin' cause your mouse doesn't work'

**Expected behavior**
I expect when I click on SteamVR for my mouse and keyboard to remain functional while in VR.

**System Information (please complete the following information):**
- Distribution: [Arch]
- SteamVR version: [1.13.10]
- Steam client version: [Jul. 10, 2020] 
- Opted into Steam client beta?: [No]
- Graphics driver version:  [NVIDIA 450.57]
- Gist for SteamVR System Information: [See [instructions](https://github.com/ValveSoftware/SteamVR-for-Linux/blob/master/CapturingSystemReport.md)] https://gist.github.com/jmanabc/6d319bae5e16243f0442743c6d9fd020

**Screenshots**

**Additional context**
I use dwm as my window manager, which can be janky with Steam. While installing SteamVR I encountered issue #234, and applied the fix detailed there. Other than taking my input devices hostage, my headset turns on, but doesn't seem to track, as I just see the default galaxy back ground and it turns with my head, making me extremely nauseous. I have SteamPlay with Proton 5.0 enabled, and do not have anything other than SteamVR and Proton 5.0 installed on Steam. 

**Note:** Commenters who are also experiencing this issue are encouraged to include the "System Information" section in their replies.

**Comment by jmanabc** [comment]
I opted into the beta program and tried it, and was greeted with the message that due to a crash, SteamVR had disabled the gamepad add-on. One of these fixed the issue. If you encounter it, try disabling the gamepad support add-on.

**Comment by jmanabc** [comment]
Disregard above comment. Turns out this issue is just less consistent than previously thought. Now happens again every time. On the beta Steam version, with gamepad support disabled. It worked once after enabling Steam beta, and my current theory is that SteamVR's automatic crash handling fixes the issue but the next time you launch the issue reappears. While it was working, I noticed that there was no audio section in settings which I plan to file an issue for once this, more catastrophic one gets fixed

**Comment by jmanabc** [comment]
Downgrading from the beta branch fixed this issue once. I'm not going to launch it again right now as restarting my computer is pretty tedious. Switching branches and restarting steam does seem to fix the issue for at least one launch, but as this solution is in no way practical I'm leaving the issue open.

Steps to get SteamVR to launch: launch VR -> see no input working -> restart computer -> open steam -> steam settings -> opt in/out of beta -> restart steam -> launch SteamVR. Rinse-repeat.

**Comment by jmanabc** [comment]
Finally, I think I've figured it out. I think that my tiling window manager is ultimately the problem. When I try to launch it in tiled mode, SteamVR doesn't know where to put the window and freaks out. Putting Steam in floating mode and resizing it to be smaller appears to fix the issue about 1/3 of the time. This is still extremely broken. Steam clearly doesn't like tiling window managers. I'm leaving the issue open as this issue is pretty much game-breaking for anyone with an index and a tiling window manager.

**Comment by jmanabc** [comment]
Closing since I haven't seen this bug come up in over a year. If anyone else using dwm happens upon this, try using the patch for steam [here](https://dwm.suckless.org/patches/steam/)

**Comment by c4augustus** [comment]
SteamVR currently disables my keyboard whenever it runs. I do have some of my desktop Windows in a tile layout, but I am not launching SteamVR necessarily in a tile.
