### ISSUE TITLE
[BUG] Suddenly stuttery VR in Valve Index + broken overlays & VR view

### ISSUE THREAD

**Issue by WebFreak001** [ValveSoftware/SteamVR-for-Linux#377]
**Describe the bug**
Today I tried to use SteamVR and the VR view constantly very stuttery as if all framerate is halved, also without anything running and the steam overlay got broken. This is a constant issue which doesn't seem to be affected by graphics intensity. Additionally the VR view window now looks broken and trying to run applications standalone with OpenVR gives a rapid green / pink flickering of a checkerboard pattern inside the VR view.

**System Information (please complete the following information):**
- Distribution: Arch (Linux 5.7.10-zen1-1-zen, 5.7.10, 5.4.53-1-lts)
- SteamVR version: tried 1.13.10 and beta 1.14.2
- Steam client version: Jul 23 2020, at 11:01:27 
- Opted into Steam client beta?: Yes
- Graphics driver version:  Mesa 20.1.3 (LLVM 10.0.0) / AMD Radeon RX 5700 XT (NAVI10, DRM 3.37.0, 5.7.10-arch1-1, LLVM 10.0.0) with amdvlk 2020.Q3.2
- also happening with: Mesa 20.1.2 with amdvlk 2020.Q2.6
- Gist for SteamVR System Information: https://gist.github.com/WebFreak001/4e77fc8af3fd354f3aa13ee2635fc441

**Screenshots**

VR view in preview:
![broken VR view](https://wfr.moe/f62oG5.png)

In the actual display it looks fine, however it is stuttery as if all content runs at half the framerate.

(kind of visible) broken "up next" overlay:
![broken up next overlay](https://wfr.moe/f62o7z.png)

(kind of visible) broken Steam overlay:
![broken steam overlay](https://wfr.moe/f6273Q.png)

**Additional context**

I believe this might have been caused by some package in the last system updates, (however it doesn't seem like it's caused from mesa, amdvlk or kernel version) this happens both on SteamVR beta and regular SteamVR now. I have tried reinstalling SteamVR beta and reinstalling normal SteamVR which before used to fix such issues, downgrading to previously working amdvlk & mesa and (after upgrading GPU stack again) downgrading to Linux LTS, however none of those fixed the issue.

VR has worked fine about 2 weeks ago.

**Note:** Commenters who are also experiencing this issue are encouraged to include the "System Information" section in their replies.

**Comment by WebFreak001** [comment]
ok seems like I had 2 vulkan drivers installed (vulkan-radeon, amdvlk) and before it preferred vulkan-radeon, and now it seems to have switched to amdvlk for some reason. Uninstalling amdvlk fixed this for me, so it uses vulkan-radeon instead

**Comment by nydn** [comment]
Hey there, 
Can you help me out a bit? I see you have a similar setup as me (Zen CPU with an AMD GPU on Arch), but I have some problems making SteamVR work. (see #385 ) I have a feeling it's more related to Arch than SteamVR. Can you tell me which mesa packages did you installed? Thanks!

**Comment by WebFreak001** [comment]
@nydn hi I have made a big list of problems and fixes I encountered here: https://gist.github.com/WebFreak001/f8d5852c795e3b5b1fddfc1911e6babb

for the software check the README in this repository (I installed `vulkan-radeon`, `mesa`, `xf86-video-amdgpu` and the lib32 variants and NOT amdgpu-pro)

**Comment by nydn** [comment]
Thanks for the quick reply, I will head there instead, if you don't mind.
