### ISSUE TITLE
VR Tutorial: Closing the system menu does not resume the tutorial

### ISSUE THREAD

**Issue by valentindavid** [ValveSoftware/SteamVR-for-Linux#38]
#### Your system information
* Steam client version (build number or date): 1489101908
* Distribution (e.g. Ubuntu): Gentoo
* Graphics driver version (run nvidia-settings): 375.27.13
* Gist for SteamVR System Information: https://gist.github.com/valentindavid/369e8bac13dbd80a95bf36bac50a5541
* Opted into Steam client beta?: Yes
* Opted into SteamVR beta?: Yes
* Have you checked for system updates?: Yes

#### Please describe your issue in as much detail as possible:

When running the tutorial, the core asks to press to system menu to bring the dashboard. Then it asks to press it again to close it. Then the core stands there saying nothing like an idiot. I suppose the tutorial is not finished or it would be a terrible ending.

**Comment by Cheeseness** [comment]
I experience this as well. From videos of it running on Windows, it looks like that is more or less the end of the tutorial itself, with the core offering some closing dialogue and leaving you to make balloons and shoot lasers as much as you want before quitting the application yourself.

**Comment by kisak-valve** [comment]
Per "- VR Tutorial: Closing the system menu does not resume the tutorial" in the [2017-03-20 SteamVR update](https://steamcommunity.com/games/250820/announcements/detail/261612552476748410), this issue should be resolved.
