### ISSUE TITLE
[BUG] Room Setup Mono crash on startup

### ISSUE THREAD

**Issue by nydn** [ValveSoftware/SteamVR-for-Linux#385]
**Describe the bug**
Hey there,
Fresh installation of SteamVR, on startup the Room Setup tool automatically started (as expected on a new setup I assume) and after a brief second it crashes, leaving behind a zombie process. The SteamVR dialog displays "Waiting...".
When I'm trying to start anything else it just says "Could not start SteamVR ... : Another application was already starting."

**Expected behavior**
Room Setup loads properly.

**System Information (please complete the following information):**
- Distribution: Arch Linux
- SteamVR version: linux_temp 1.8.21
- Steam client version: steam-runtime_0.20200720.0
- Opted into Steam client beta?: Yes
- Graphics driver version:  Mesa 20.1.1 
- Gist for SteamVR System Information: https://gist.github.com/nydn/dc5102b459df4256845e72d8cfe24a3a

**Additional context**

```
aug 25 20:23:04 desktop systemd-coredump[5596]: [🡕] Process 5496 (steamvr_room_se) of user 1000 dumped core.
                                                 Stack trace of thread 5496:
                                                 #0  0x00007f16cc384615 raise (libc.so.6 + 0x3d615)
                                                 #1  0x00007f16cc36d862 abort (libc.so.6 + 0x26862)
                                                 #2  0x00007f167a37fdeb n/a (/home/dani/.local/share/Steam/steamapps/common/SteamVR/tools/steamvr_room_setup/linux64/steamvr_room_setup_Data/Mono/x86_64/libmono.so + 0x91deb)
```

**Note:** Commenters who are also experiencing this issue are encouraged to include the "System Information" section in their replies.

**Comment by nydn** [comment]
Managed to find the culprit. AMDVLK caused the issue, apparently SteamVR only works with libvulkan_radeon.
Had to delete "/usr/share/vulkan/icd.d/amd_icd[32|64].json files and everything works fine now.

**Comment by cmdrogogov** [comment]
I have this issue w/ Fedora, but it is not AMDVLK causing the issue as the only ICD present on the system is mesa RADV ICD's;

```
radeon_icd.i686.json
radeon_icd.x86_64.json
```
