### ISSUE TITLE
SteamVR aborts with untranslated error if a system tray is not found

### ISSUE THREAD

**Issue by brettp** [ValveSoftware/SteamVR-for-Linux#39]
#### Your system information
* Steam client version (build number or date): 14896229631
* Distribution (e.g. Ubuntu): Ubuntu 16.10, Elementary OS 0.4
* Graphics driver version (run nvidia-settings): 375.27.13
* Gist for SteamVR System Information: N/A (Crashes before a UI opens)
* Opted into Steam client beta?: Yes
* Opted into SteamVR beta?: Yes
* Have you checked for system updates?: Yes

#### Please describe your issue in as much detail as possible:
If a system tray application isn't running, SteamVR gives an untranslated message that doesn't makes it obvious what the problem is. The error should explain that a systray is needed.

#### Steps for reproducing this issue:
1. Close all system tray programs, or use one with limited support (like wingpanel in Elementary OS)
2. Open SteamVR
3. See untranslated error message (attached)

<img width="351" alt="systray_missing" src="https://cloud.githubusercontent.com/assets/43375/24024239/29e37854-0a88-11e7-970e-9e0897d07c9b.png">

**Comment by Seegras** [comment]
Same here. I got a black qt window with button `MessageBox_Continue `and that was it. I could not even see the dark-grey text.  Enabling `*.debug=true ` for QT didn't tell anything interesting either.

**Comment by johnv-valve** [comment]
should be fixed in the current steamvr beta
