### ISSUE TITLE
[Feature Request] Mirror audio

### ISSUE THREAD

**Issue by yaomtc** [ValveSoftware/SteamVR-for-Linux#392]
[There is](https://www.reddit.com/r/ValveIndex/comments/e83ptg/anyone_know_how_to_play_sound_through_the/fa90qos/) a feature on the Windows version of SteamVR that allows setting of a mirror device for sound. This does not exist on Linux. Could this possibly be due to a limitation of PulseAudio?

**To Reproduce**
1. Go to SteamVR Settings
2. No audio options
3. Open PulseAudio Preferences (paprefs)
4. In "Simultaneous Output" tab, check "Add virtual output device for simultaneous output on all local sound cards"
5. In your sound settings, choose this virtual device for sound output instead of DisplayPort going to headset
6. Observe audio lag in games

**Expected behavior**
Expected no noticeable audio latency. PulseAudio may not be capable of multiple outputs in this case without added latency. Would this require PipeWire?

**System Information (please complete the following information):**
- Distribution: Arch Linux
- SteamVR version: beta 1.15.1
- Steam client version: Oct 2 2020, at 01:51:33
- Opted into Steam client beta?: Yes
- System Information: https://gist.github.com/yaomtc/6b2a02f64a35957bfbb4b3b1b9f03c71
- SteamVR System Report: https://gist.github.com/yaomtc/1bc76d786710c20da1981ddeb5feb0b6

**Comment by Zamundaaa** [comment]
> Could this possibly be due to a limitation of PulseAudio?

No, SteamVR just has no audio management for Linux whatsoever.

It works just fine for me though with PA - it may be that one of the audio devices you're mirroring to has high latency and thus the total mirrored latency is higher.

**Comment by yaomtc** [comment]
Thanks! That helped me figure it out. I need to have the motherboard's built-in audio disabled. Leaving that on causes massive lag. Solved.
