### ISSUE TITLE
[BUG] Half-Life: Alyx - Strange pink/purple square visible out of bounds from anywhere in the area

### ISSUE THREAD

**Issue by yaomtc** [ValveSoftware/SteamVR-for-Linux#396]
**Describe the bug**
I often see this square through the game, out of bounds but still visible through the level geometry. Usually it's far enough away that I don't notice it, but sometimes it's right nearby beneath me, as is shown in the screenshot. As I watched the square, its pattern changed on an interval.

**System Information (please complete the following information):**
- Distribution: Arch Linux
- SteamVR version: 1.15.2
- Steam client version: Oct 8 2020
- Opted into Steam client beta?: Yes
- Graphics driver version: Mesa 20.2.0 (ACO)
- Gist for SteamVR System Information: https://gist.github.com/yaomtc/531d225f4bf6fd6024b0063f1da2b9b3

EDIT: I'm using a Radeon RX 5700 XT

**Screenshots**
![Screenshot_20201010_181725_](https://user-images.githubusercontent.com/5534045/95666295-4c32ea00-0b26-11eb-85d1-452e39c7e9e9.png)

**Note:** Commenters who are also experiencing this issue are encouraged to include the "System Information" section in their replies.

**Comment by kisak-valve** [comment]
Possibly a corrupt texture on the horizontal plane at the map origin, visible after a level transition.

**Comment by Fl0ux** [comment]
I also often see this king of artifact. As the original poster said,  it is usually far away. It happens in the classic story mode but also in some custom maps.

I am using Mesa too : 
Pilote : X.Org AMD Radeon RX 5700 XT (NAVI10, DRM 3.38.0, 5.8.11-1-MANJARO, LLVM 10.0.1)
Version du pilote : 4.6 (Compatibility Profile) Mesa 20.1.8

**Comment by kisak-valve** [comment]
Hello @yaomtc, @Fl0ux, have either of you seen this issue since the commentary update?

**Comment by tdjb** [comment]
I've seen the mouse pointer occasionally, and after some resets of SteamVR it turned into that pink, messy square.

This was before and after the commentary update, it may be not even related to Alyx in particular?
But I did not test to confirm that.

**Comment by yaomtc** [comment]
I just tested loading saves from several different chapters, and was unable to reproduce the issue anymore.

**Comment by kisak-valve** [comment]
Hello @tdjb, your observation doesn't sound related to the issue reported here. Feel free to open a separate issue report. In general, there shouldn't be a mouse cursor visible in the HMD at any time, unless the system is configured to have an extended desktop on the HMD and you intentionally put the cursor onto that display.

Thanks for retesting @yaomtc, closing.
