### ISSUE TITLE
Installation path could not be located (111)

### ISSUE THREAD

**Issue by anoadragon453** [ValveSoftware/SteamVR-for-Linux#4]
#### Your system information

* Steam client version (build number or date): Jan 19, 2017
* Distribution (e.g. Ubuntu): Arch Linux
* Opted into Steam client beta?: [Yes/No] Client and SteamVR
* Have you checked for system updates?: [Yes/No] Yes

#### Please describe your issue in as much detail as possible:

When starting SteamVR the compositor shows up correctly and displays full what the headset should be seeing (controllers can be seen as tracked through this window) however the headset display does not turn on. 

Shortly after the SteamVR Compositor window appears, the error message "SteamVR failed to initialized **(typo btw)** for unknown reasons. (Error: Config path could not be located (111))" shows up. The indicator light on the side of the headset is green, but its display is off.

Room setup will crash immediately after launching.

I've tried running with the Steam runtime with nvidia (378.13-2) and nvidia-beta (378.13-1) drivers, but both give the same issue.

[Log during error](https://gist.github.com/anoadragon453/cd2625349fad78847b8a6a97dc020bb1).

My setup consists of two 1440p monitors over DVI with the headset running over HDMI. I have a Nvidia GTX 970.

#### Steps for reproducing this issue:

1. Start SteamVR Beta Client
2. Watch as SteamVR Compositor appears and works correctly (albeit displaying 1080p on a 1440p monitor)
3. Error message with title "Error Starting SteamVR" appears stating: "SteamVR failed to initialized for unknown reasons. (Error: Config path could not be located (111))"

**Comment by anoadragon453** [comment]
I also get the following in dmesg:

```
[ 1823.693163] vrcompositor[7002]: segfault at 1 ip 0000000000462ea2 sp 00007ffc0a848880 error 4 in vrcompositor[400000+2a9000]
[ 1824.057823] vrserver[6991]: segfault at 2d0 ip 00007f1216f575e0 sp 00007ffece6d2fb8 error 4 in libpthread-2.24.so[7f1216f4f000+18000]
[ 1853.102891] usb 3-5.1.2: USB disconnect, device number 19
[ 1853.282471] hub 3-5.1:1.0: hub_ext_port_status failed (err = -71)
[ 1853.282547] hub 3-5.1:1.0: hub_ext_port_status failed (err = -71)
[ 1853.358896] usb 3-5.1: USB disconnect, device number 14
[ 1853.358898] usb 3-5.1.1: USB disconnect, device number 18
[ 1853.359700] usb 3-5.1.4: USB disconnect, device number 20
[ 1853.422953] usb 3-5.1.5: USB disconnect, device number 15
[ 1853.423976] usb 3-5.1.6: USB disconnect, device number 16
[ 1853.424706] usb 3-5.1.7: USB disconnect, device number 17
[ 1853.667502] [UFW BLOCK] IN=wlp9s0 OUT= MAC=01:00:5e:00:00:01:c0:56:27:7a:96:3f:08:00 SRC=192.168.1.1 DST=224.0.0.1 LEN=28 TOS=0x00 PREC=0xC0 TTL=1 ID=24390 PROTO=2 
[ 1854.079071] usb 3-5.1: new high-speed USB device number 21 using xhci_hcd
[ 1854.169824] hub 3-5.1:1.0: USB hub found
[ 1854.169877] hub 3-5.1:1.0: 7 ports detected
[ 1854.449067] usb 3-5.1.5: new full-speed USB device number 22 using xhci_hcd
[ 1854.542787] hid-generic 0003:0BB4:2C87.0011: hiddev0,hidraw4: USB HID v1.11 Device [HTC HTC Vive] on usb-0000:00:14.0-5.1.5/input0
[ 1861.308959] usb 3-5.1.6: new full-speed USB device number 23 using xhci_hcd
[ 1861.408906] hid-generic 0003:28DE:2101.0012: hiddev0,hidraw5: USB HID v1.11 Device [Valve Software Watchman Dongle] on usb-0000:00:14.0-5.1.6/input0
[ 1861.615619] usb 3-5.1.7: new full-speed USB device number 24 using xhci_hcd
[ 1861.715564] hid-generic 0003:28DE:2101.0013: hiddev0,hidraw6: USB HID v1.11 Device [Valve Software Watchman Dongle] on usb-0000:00:14.0-5.1.7/input0
[ 1861.922275] usb 3-5.1.1: new full-speed USB device number 25 using xhci_hcd
[ 1862.018801] hid-generic 0003:28DE:2000.0014: hiddev0,hidraw7: USB HID v1.01 Device [Valve Software Lighthouse FPGA RX] on usb-0000:00:14.0-5.1.1/input0
[ 1862.019931] hid-generic 0003:28DE:2000.0015: hiddev0,hidraw8: USB HID v1.01 Device [Valve Software Lighthouse FPGA RX] on usb-0000:00:14.0-5.1.1/input1
[ 1862.225610] usb 3-5.1.4: new full-speed USB device number 26 using xhci_hcd
[ 1862.326587] input: C-Media Electronics Inc. USB Audio Device as /devices/pci0000:00/0000:00:14.0/usb3/3-5/3-5.1/3-5.1.4/3-5.1.4:1.3/0003:0D8C:0012.0016/input/input27
[ 1862.382407] hid-generic 0003:0D8C:0012.0016: input,hidraw9: USB HID v1.00 Device [C-Media Electronics Inc. USB Audio Device] on usb-0000:00:14.0-5.1.4/input3
[ 1862.588935] usb 3-5.1.2: new high-speed USB device number 27 using xhci_hcd
[ 1862.680058] uvcvideo: Found UVC 1.00 device HTC Vive (0bb4:2c87)
[ 1862.705136] uvcvideo 3-5.1.2:1.0: Entity type for entity Extension 2 was not initialized!
[ 1862.705138] uvcvideo 3-5.1.2:1.0: Entity type for entity Extension 6 was not initialized!
[ 1862.705139] uvcvideo 3-5.1.2:1.0: Entity type for entity Extension 5 was not initialized!
[ 1862.705140] uvcvideo 3-5.1.2:1.0: Entity type for entity Processing 3 was not initialized!
[ 1862.705141] uvcvideo 3-5.1.2:1.0: Entity type for entity Camera 1 was not initialized!
[ 1862.705224] input: HTC Vive as /devices/pci0000:00/0000:00:14.0/usb3/3-5/3-5.1/3-5.1.2/3-5.1.2:1.0/input/input28
```

**Comment by connerbrooks** [comment]
Same error reported on my machine at startup `Config path could not be located (111)` doesn't seem to be causing an issue as SteamVR appears to be working (rendering the waiting room) and I was able to run room setup.

I am using the exact drivers specified in the readme `375.27.10` from the PPA mentioned, you can add it as shown below.

```
sudo add-apt-repository ppa:mamarley/nvidia-dev
```

Like the readme says you may need to pin this higher than the `graphics-drivers` PPA, in my case I just disabled the `graphics-drivers` PPA and installed `375.27.10` from the **Additional Drivers** menu.

**Comment by anoadragon453** [comment]
Thanks for the response, perhaps it is a driver issue then. As I said in the OP I'm running Arch Linux which is already on a later version of the driver and there isn't an LTS package for 375.27.10 that I can see. 

I can try searching for the older release, installing it may be as simple as changing the PKGBUILD but as this is my work machine I'm wary of trying to hack together nvidia driver installs.

Perhaps you could try upgrading to the latest (378.13-1/2) nvidia driver and seeing if the headset still displays content? I'm not aware of it being available in an easy to install (.deb) format yet however.

**Comment by connerbrooks** [comment]
My bad, missed that in your description, for some reason I just assume everyone is on *buntu.

I haven't messed much with Nvidia drivers on Arch (only ran on a ThinkPad), but could you just run the `.run` file from https://developer.nvidia.com/vulkan-driver. I have never had an easy time with their `.run` installer, so _beware_ I suppose.

**Comment by kkriehl** [comment]
I have the same error, but additionally the room setup crashes with `Wed Feb 22 2017 17:13:15.100534 - Failed to fetch KHX shared memory extension functions!`. I concluded that the required NVIDIA beta driver 375.27.10 is not an (outdated) typical beta release of an upcoming driver version, but a separate developer beta with still experimental and unreleased VULKAN features that are required by SteamVR. So to use SteamVR on Arch we have to install this developer beta driver. I hope that doesn't require downgrading other packages. 

The easiest way should be by using the linked PPA debian/ubuntu package and a PKGBUILD to create an AUR package (unfortunately AUR does not have a package for the developer driver). I'll see how far I'll come without X11 failing :D. If everything works I'll publish a Gist of the PKGBUILD.

**Comment by johnv-valve** [comment]
NVIDIA cards require version 375.27.10 of the NVIDIA Developer Beta Driver.

Not 378.13.

**Comment by anoadragon453** [comment]
@kkriehl Thanks for your insight, and good luck on the PKGBUILD creation. I'll do my own testing once I get home today.

@johnv-valve As @connerbrooks receives the same 111 error with the correct Nvidia driver perhaps we should keep this issue open?

**Comment by johnv-valve** [comment]
@connerbrooks issue is different as his SteamVR works fine. If you want to create a new issue for the spurious message (I think it might just be a first run thing) then do that.

**Comment by anoadragon453** [comment]
@johnv-valve I'll create a new issue if I still receive the error after installing the new driver, unless @connerbrooks wants to go ahead and do it if he's still getting the same issue.

**Comment by hcorion** [comment]
Subscribing to this thread for that PKGBUILD @kkriehl. It would be good if you posted it on the official archlinux aur as well.

**Comment by anoadragon453** [comment]
@hcorion @kkriehl I've created a thread on the SteamVR Linux forums with current PKGBUILD progress: 

https://steamcommunity.com/app/250820/discussions/5/133257959063392200/

**Comment by johnv-valve** [comment]
When you have it working, please send a pull request for README.MD in this repo with instructions.

**Comment by anoadragon453** [comment]
@johnv-valve Will do once it goes live.

**Comment by anoadragon453** [comment]
@johnv-valve PR added. No longer receiving the `Installation path` error anymore, though I'm unsure if this is related to the driver or the latest Feb 23 Steam beta.
