### ISSUE TITLE
SteamVR does not start at all

### ISSUE THREAD

**Issue by new-gen23** [ValveSoftware/SteamVR-for-Linux#40]
#### System 1: Laptop
* Steam client version (build number or date): Mar 17 2017, 1489791860
* Distribution (e.g. Ubuntu): ubuntu 16.10 64-bit
* Graphics driver version (run nvidia-settings): 375.27.13
* Gist for SteamVR System Information: WTF?
* Opted into Steam client beta?: [Yes/No] Yes
* Opted into SteamVR beta?: [Yes/No] Not possible
* Have you checked for system updates?: [Yes/No] Yes
Hardware: Nvidia Geforce 1070

#### System 2: Workstation
* Steam client version (build number or date): Mar 23 2017, 1490314264
* Distribution (e.g. Ubuntu): Debian Jessie
* Graphics driver version (run nvidia-settings): 375.27.13
* Gist for SteamVR System Information: WTF?
* Opted into Steam client beta?: [Yes/No] Yes
* Opted into SteamVR beta?: [Yes/No] Not possible
* Have you checked for system updates?: [Yes/No] Yes
Hardware: Nvidia Geforce GTX 970

#### Describtion of my issue:
I expected the Steam-VR menu to appear. But I get only an error window when I click on
View->Start SteamVR (Beta)
The error states:
An error occurred while updating SteamVR (missing executable)
See the Steam support site for more information.

I already cleaned the download cache and tried again. HTC Vive is connected and running under windows without any issues.

**Comment by kisak-valve** [comment]
Hello @new-gen23, your laptop is using the mainline nvidia driver, which does not support some experimental vulkan extensions required for SteamVR.

Are you sure you opted into the SteamVR beta branch? Right click on SteamVR -> Properties -> Betas tab -> Select the beta branch -> Click Close

**Comment by new-gen23** [comment]
I just updated the laptops driver to the the ones with vulkan support.

**Comment by hcorion** [comment]
What SteamVR are you right clicking? Is it on the desktop? kisak-valve is talking about the text inside the Steam application. If you click Library, up near Store and Community in the Steam application, and then click the VR section, if you look on the left where the games list usually is you should see SteamVR listed under tools, right click that icon.

**Comment by new-gen23** [comment]
I just updated SteamVR after my last entry annnnnnd... IT WORKS!!!! AWESOME! Whoever fixed this is my personal hero! THANKS!!! AWESOME! If there is any way I can reward you let me know! A.W.E.S.O.M.E!!!!!
