### ISSUE TITLE
[BUG] Error 108 after a month of inactivity

### ISSUE THREAD

**Issue by fabianbieler** [ValveSoftware/SteamVR-for-Linux#401]
**Describe the bug**
About a month ago I last used SteamVR with my Valve Index.
Now, when opening SteamVR I get the Error "Headset Not Detected" (108)

**To Reproduce**
1. Launch SteamVR
2. See error

**System Information:**
- Distribution: Lubuntu 20.4
- SteamVR version: 1.14.16
- Steam client version: 1600466902
- Opted into Steam client beta?: No
- Graphics driver version:  450.66
- Gist for SteamVR System Information: https://gist.github.com/fabianbieler/0ca6f6c40db3456dcf56dda226e8a280

**Additional context**
I tried
power-cycling the Headset,
multiple USB-Ports,
re-plugging all 5 connectors,
disconnecting other USB devices,
rebooting the Computer,
re-installing SteamVR,
a different computer¹,
contacting Steam Support (Ticket: HT-G55X-44M5-FTTR)
to no avail.
¹) Only USB-connectivity was tested on alternate computer, see below for details.

I can only see two USB-devices when using a USB3-port:
28de:2400 Valve Software USB5744
0424:5744 Microchip Technology, Inc. (formerly SMSC) Hub
When using a USB2-port I see no devices.
relevant dmesg snippet: https://gist.github.com/fabianbieler/c25f076338a4748b75e349f70b3269eb

I tried plugging in the Headset on a different computer with identical results, i.e. only the aforementioned two USB-devices were present. SteamVR was not tested on this computer.

A month ago, when SteamVR was working I remember there being more USB devices present.

In my Xorg.log the nvidia driver informs me: "NVIDIA(GPU-0): DP-2: Found Head Mounted Display; ignoring for use in X. See the 'AllowHMD' X configuration option for details."

The Headset's LEDs remain blue at all times.

**Note:** Commenters who are also experiencing this issue are encouraged to include the "System Information" section in their replies.

**Comment by fabianbieler** [comment]
The problem is still present. Could the missing USB-devices with multiple computers indicate a defective Headset?

**Comment by WebFreak001** [comment]
I've got the same issue since today, the headset worked fine yesterday and stopped working today.

The headset display still works (can allocate a screen with xrandr and see stuff on it) and the 3D cameras work. (as normal linux webcam device, not in SteamVR)

When trying with OpenVR I get the error 126 (Hmd Not Found Presence Failed)

System information: https://gist.github.com/WebFreak001/8dc9629e8c24f691875aa58995df718b

**Comment by WebFreak001** [comment]
I also checked now SteamVR on a separate fresh Windows Computer with the Index now where the headset was no longer recognized. I believe this might indicate defective hardware or possibly a firmware issue as camera + display still work and this suddenly happened overnight.

I also contacted Steam support for this already, will update this comment when it's resolved.

**Comment by fabianbieler** [comment]
I installed a 30-day trial of Windows on a spare drive to get help from Steam support.
The problem was a defective cable (in particular the 3-to-1 connection cable).

**Comment by WebFreak001** [comment]
same issue for me, the 3-to-1 connection cable broke for me too and got a new one via Steam support.

**Comment by HavelTheMetal** [comment]
go to C:\Program Files (x86)\Steam\steamapps\common\SteamVR\bin\win64 and run vrstartup.exe as admin. I have not found this fix anywhere so hoping it helps. it fixed my 108
