### ISSUE TITLE
NVidia Vulken driver version 375.27.14

### ISSUE THREAD

**Issue by JamesHagerman** [ValveSoftware/SteamVR-for-Linux#41]
Can anyone confirm that the 375.27.14 version of the driver works as well as 375.27.13 does?

375.27.13 seems to be impossible to download directly from NVidia at this point. Thus, it would be good to know if 375.27.14 is expected to work.

If nothing else, it'd be awesome to see a mention of 375.27.14  in the Readme of this repo!

**Comment by aronschatz** [comment]
My SteamVR has been unstable for a long while over the past month to test out the newer driver. However, I'm hoping a driver updates fixes some things. 375.27.14 is on the Vulkan beta Nvidia site and says it fixes some stuff. I'd give it a shot.

**Comment by JamesHagerman** [comment]
@aronschatz I have tried it and I could get into the "default" world, and most of the way through the setup demo.

However, there were some of the known issues such as the left eye being blurry/pixelated and it being a little glitchy.

One side issue was that I couldn't get a VR Unity build to start up in VR but I don't know if the driver version would affect that...

**Comment by JamesHagerman** [comment]
Ah, I just realized that @Plagman updated the Readme. Thanks!
