### ISSUE TITLE
[BUG] CAP_SYS_NICE+ep breaks SteamVR menus and Chaperone boundaries

### ISSUE THREAD

**Issue by Ominitay** [ValveSoftware/SteamVR-for-Linux#417]
**Describe the bug**
As instructed by the last comment in #234, I ran the command `sudo setcap CAP_SYS_NICE+ep ~/.local/share/Steam/steamapps/common/SteamVR/bin/linux64/vrcompositor-launcher` to finish setting up SteamVR. After doing this, the chaperone bounds, along with the empty space (between loading games), and menu. Also, graphical glitches occur. If I undo this command, with the command `sudo setcap CAP_SYS_NICE-ep ~/.local/share/Steam/steamapps/common/SteamVR/bin/linux64/vrcompositor-launcher`, these issues go away.

**To Reproduce**
1. Execute the command `sudo setcap CAP_SYS_NICE+ep ~/.local/share/Steam/steamapps/common/SteamVR/bin/linux64/vrcompositor-launcher`
2. Open SteamVR
3. Open menu or make chaperone show, then rotate head and see the geometry lag behind motion.

**Expected behavior**
Menu and chaperone boundaries should keep up with the motion (as all games do, regardless of the setcap).

**System Information (please complete the following information):**
- Distribution: Arch
- SteamVR version: 1.15.16
- Steam client version: 2020/12/20 23:07:25
- Opted into Steam client beta?: No (same thing happens with beta though)
- Graphics driver version:  Mesa 20.3.2
- Gist for SteamVR System Information: https://gist.github.com/Ominitay/e2cd60a8bab4891346012cf0bea954f5

**Screenshots**
I've yet to set up video recording software. The best way I can describe it is that if I look left, the chaperone bounds seem to lag to the right, and catch back up with in-game geometry when I stop moving my head.

**Additional context**
This persisted after reinstalling Arch.

**Note:** Commenters who are also experiencing this issue are encouraged to include the "System Information" section in their replies.

**Comment by kisak-valve** [comment]
Hello @Ominitay, you have described the issue being tracked at #395. Noted at https://github.com/ValveSoftware/SteamVR-for-Linux/issues/395#issuecomment-732427898, you can use the `linux_1.14` beta branch of SteamVR to workaround the issue.

Closing as a duplicate.

**Comment by Ominitay** [comment]
Thank you for pointing me to that @kisak-valve :) My searches across the internet were fruitless.
