### ISSUE TITLE
SteamVR does not find the lighthouses

### ISSUE THREAD

**Issue by awesomebytes** [ValveSoftware/SteamVR-for-Linux#42]
#### Your system information
* Steam client version (build number or date): Mar 30 2017, at 22:20:57
* Distribution (e.g. Ubuntu): Ubuntu 14.04 64b (kernel 4.4.0-31-generic )
* Graphics driver version (run nvidia-settings): 375.27.13
* Gist for SteamVR System Information: https://gist.github.com/awesomebytes/b3e8382640836560099aa79de464427e
* Opted into Steam client beta?: Yes
* Opted into SteamVR beta?: Yes
* Have you checked for system updates?: Yes

#### Please describe your issue in as much detail as possible:
I expected SteamVR to find my headset, both controllers and both lighthouses. But it never finds the lighthouses.

#### Steps for reproducing this issue:
1. Open Steam (Beta)
2. Hit play on SteamVR (Beta)
3. Plug in the Headset (if I plug it previously it gets me in Preparing to launch indefinitely many times).
4. See how the headset and the controllers are detected (the headset shows a grey screen) but the lighthouses are not (and the lighthouses don't change from the green led to another status).

**Comment by awesomebytes** [comment]
Apparently something was wrong with my lighthouses. I completely turned off all the system (computer, headset, both lighthouses) for a while. Then proceeded to start it all in windows 10, and it worked. Then I rebooted into ubuntu and it worked! I could start the tutorial even.

**Comment by rhaleblian** [comment]
I encountered the same behaviour, and a computer shutdown, restart of the lighthouses, and computer restart similarly fixed it.

    Steam client version (build number or date): Jul 17 2017 23:10:56
    Distribution (e.g. Ubuntu): CentOS 7 
    Graphics driver version (run nvidia-settings): 384.59 (negativo17 aka epel-multimedia)
    Gist for SteamVR System Information: n/a
    Opted into Steam client beta?: No
    Opted into SteamVR beta?: No
    Have you checked for system updates?: Yes
