### ISSUE TITLE
[BUG] Overlays (and more) flicker a lot, especially in the left eye. 

### ISSUE THREAD

**Issue by happysmash27** [ValveSoftware/SteamVR-for-Linux#425]
**Describe the bug**
When the SteamVR overlay is open, it will constantly flicker a lot in a very annoying way, especially in the left eye. This does not appear in the SteamVR VR View, but does in the headset itself. This also seems to happen in the mountain zone when launching SteamVR programs. 

**To Reproduce**
1. Open SteamVR overlay. 
2. If this does not work, click on a game in the main screen in SteamVR Home and click "show details. Bonus points if you play a video. This seems to make the flickering worse for me than just showing the desktop view (which seems to be broken for me, by the way, but that is an issue for another day). 
3. In addition, simply launching any program seems to be able to create this issue as well, to a lesser extent, in the mountain space between launching programs. I usually do this close enough to the edge that the edge guard shows, so doing this may help. 

**Expected behavior**
The overlay will open, and work perfectly. 

**System Information (please complete the following information):**
- Distribution: Gentoo Linux, kernel 5.9.14-gentoo with the newest Mesa drivers pulled from Git and LXDE. 
- SteamVR version: 1.16.6
- Steam client version: Dec 20 2020, 23:07:25
- Opted into Steam client beta?: For SteamVR, yes. If you mean Steam itself, no. 
- Graphics driver version:  [run `nvidia-settings` or `vulkaninfo | grep driverInfo`:

`Mesa 21.0.0-devel (git-ecac89b732) (ACO)`

- Gist for SteamVR System Information: https://gist.github.com/happysmash27/b0365a9032d5a2ca2c68517c990394b0

**Screenshots**
https://happysmash27.me/Upload/Screenshots/Videos/Bugs/SteamVR/VID_20210204_050848.webm

**Comment by kisak-valve** [comment]
Hello @happysmash27, this reads like the issue being tracked in #395. Please opt into the `linux_1.14` beta branch of SteamVR as a workaround.

**Comment by happysmash27** [comment]
This does seem to be the same issue as #395. I will close it and post my experience there. Thank you!

**Comment by happysmash27** [comment]
Also, opting into the linux_1.14 branch does indeed work as a workaround, for anyone wondering.

**Comment by DaniSeeh** [comment]
Unfortunately this is still an issue, and for me rolling back to 1.14 introduces other issues that are even worse. I hope this gets fixed soon.

**Comment by tylermurphy534** [comment]
Still an issue in dec 2022 for me
