### ISSUE TITLE
Applications lock up on boot

### ISSUE THREAD

**Issue by Vash63** [ValveSoftware/SteamVR-for-Linux#43]
#### Your system information
* Steam client version (build number or date): Mar 30 2017 at 22:20:57
* Distribution (e.g. Ubuntu): Arch Linux w/ Gnome 3.22.2
* Graphics driver version (run nvidia-settings): 375.27.15
* Gist for SteamVR System Information:  https://gist.github.com/Vash63/1b230516d6d2ea5bfd2533c6c401b0eb
* Opted into Steam client beta?: [Yes/No] Y
* Opted into SteamVR beta?: [Yes/No] Y
* Have you checked for system updates?: [Yes/No] Y

#### Please describe your issue in as much detail as possible:
Launching the tutorial, Destinations or Serious Sam VR: TSE all fail to send any video to the headset (stuck in SteamVR 'waiting for game' menu). Upon checking desktop, window is visible in Gnome with no content and frozen. Destinations required a kill -9 to stop, the other two required a normal kill -15. stdour/err from Steam shows:

```
Apr 06 02:09:53 vashnix steam.desktop[13545]: shaders/vulkan/tracked_camera_ps.spv
Apr 06 02:09:53 vashnix steam.desktop[13545]: shaders/vulkan/tracked_camera_undistort_ps.spv
Apr 06 02:09:53 vashnix steam.desktop[13545]: shaders/vulkan/tracked_camera_edgefilter_ps.spv
Apr 06 02:09:53 vashnix steam.desktop[13545]: shaders/vulkan/tracked_camera_reprojection_ps.spv
Apr 06 02:09:53 vashnix steam.desktop[13545]: shaders/vulkan/tracked_camera_lines_ps.spv
Apr 06 02:09:53 vashnix steam.desktop[13545]: DeleteFBOFreeList: Removing 7 FBO objects, total 1
Apr 06 02:10:03 vashnix steam.desktop[13545]: Warning: The game hasn't rendered a frame from us in over 10 seconds
Apr 06 02:10:14 vashnix steam.desktop[13545]: Warning: The game hasn't rendered a frame from us in over 10 seconds
Apr 06 02:10:24 vashnix steam.desktop[13545]: Warning: The game hasn't rendered a frame from us in over 10 seconds
```

This is with Destinations, output from the other two applications is similar. Desktop Vulkan applications such as Mad Max or Serious Sam Fusion work without issue.

**Comment by hcorion** [comment]
I'm also experiencing this exact issue on Arch Linux. 
I'm running the 381.09 beta with a i7-4770 and a GTX 1070.
I'm using KDE Plasma 5.9.4 w/ 4.10.8 kernel version.

I'm running Steam using the steam-runtime executable.

**Comment by Vash63** [comment]
This was fixed at some point between my first report and now. Closing.
