### ISSUE TITLE
Nvidia 381.09 beta driver supported?

### ISSUE THREAD

**Issue by yaomtc** [ValveSoftware/SteamVR-for-Linux#44]
#### Your system information
* Steam client version (build number or date): 1.0.0.54 / Mar 30, 2017 / 1490914880
* Distribution (e.g. Ubuntu): Arch Linux
* Graphics driver version (run nvidia-settings): 381.09
* Gist for SteamVR System Information: https://gist.github.com/yaomtc/96200f58216acfa53abd0103f78a9748
* Opted into Steam client beta?: Yes
* Opted into SteamVR beta?: Yes
* Have you checked for system updates?: Yes

#### Please describe your issue in as much detail as possible:
I recently installed [the latest Nvidia beta driver](https://devtalk.nvidia.com/default/topic/1002788), 381.09, which added updated Vulkan support that I thought might just work with SteamVR. Gave it a try, and it was a bit laggier than I expected, so I wasn't sure direct mode was working. ~~Sure enough, the report says it's not direct mode. So I guess the SteamVR beta doesn't yet support these new drivers for direct mode. I'll have switch to the "vulkan-beta" AUR packages in the meantime.~~ EDIT: It might have been in direct mode, missed the Known Issue. So does this driver work as well as the 375.27.xx line?

**Comment by yaomtc** [comment]
Well. I installed [those](https://aur.archlinux.org/pkgbase/nvidia-utils-vulkan-developer-beta/) other [packages](https://aur.archlinux.org/packages/nvidia-vulkan-developer-beta/), but... either direct mode is working and SteamVR isn't aware, or I actually am stuck in extended mode. It felt and looked the same, anyway.

By the way, in both of these tests, in the SteamVR Tutorial, the controllers were purple and didn't show trigger-pull/touchpad touching. The game still worked, though (though it did crash one time when I was exiting SteamVR Dashboard). Not sure if I should file a bug for either of those things, or if it's a known issue.

**Comment by kkriehl** [comment]
You're right - [SteamVR isn't aware if direct mode is working or not](https://github.com/ValveSoftware/SteamVR-for-Linux#known-issues). If direct mode isn't working you'll see a VRCompositor window popping up on the desktop. If X11 is not explicitly configured to allow HMDs as screens the Vive screens won't show anything, either.
If direct mode on Linux is working you will see the SteamVR environment only on the Vive screens. 
I think you can verify if it's working by searching for `Instance extensions available` inside the compositor logs: `.local/share/Steam/logs/vrcompositor.txt`. If the Vulkan extension `VK_EXT_direct_mode_display` is mentioned in the list below, the compositor should use direct mode even if it says `Headset display is on desktop` later in the logfile.

I'm only guessing, though. It would be great if someone with more in-depth knowledge could confirm that.

**Comment by yaomtc** [comment]
Whoops, that's what I get for not reading everything. Direct mode is probably working, then - must be just added latency of the not-well-optimized beta that was bothering me.

**Comment by roothorick** [comment]
381.09 Working flawlessly with SSVR:TFE in Ubuntu-GNOME 16.04.2 on a GTX 1070. I'm having problems with Destinations crashing but I always did.

**Comment by aronschatz** [comment]
@roothorick Destinations crashing has been a problem the entire time. But this driver seems fine from my testing with SSVR:TFE. It's still a bit slow on tracking, but that's probably SteamVR.

**Comment by eric-schleicher** [comment]
pardon my ignorance; what is SSVR:TFE?

**Comment by yaomtc** [comment]
Serious Sam VR - The First Encounter

**Comment by eric-schleicher** [comment]
Thanks!

**Comment by yaomtc** [comment]
This was fixed on the readme at some point fairly recently ("NVIDIA cards require version 381.22 of the NVIDIA Driver or above") so this can be closed now.
