### ISSUE TITLE
Can't run Room Setup

### ISSUE THREAD

**Issue by javl** [ValveSoftware/SteamVR-for-Linux#45]
#### Your system information
* Steam client version: Mar 30 2017, at 22:20:57 
* Distribution: Debian Stretch ('testing')
* Graphics driver version: 375.39
* Gist for SteamVR System Information: https://gist.github.com/javl/6e4fa8049cb9318b68e67c56611b97df (Truncated the logs to a single run directly after installing SteamVR (beta). Only 1 lighthouse connected.)
* Opted into Steam client beta?: Yes
* Opted into SteamVR beta?: Yes
* Have you checked for system updates?:  Yes
* Hardware firmware: latest (installed using Windows)

Disabled HTC VIve display using `xrandr --output HDMI-0 --off`
`nvidia-settings` confirms the screen status is `disabled`, but the system report says `Display Mode:	Extended Display`?

##### Expected:
Starting the Room Setup or Tutorial programs to setup the playing area.

##### Actual result:
A window opens from a split second, SteamVR menu shows 

    Starting SteamVR Room Setup
    (Unresponsive) SteamVR Room Setup

and the window closes. Same for the tutorial.
When starting SteamVR I do get to see the 3D environment (both on the desktop and in the headset) showing the lighthouses.

##### Steps to reproduct:
1. Start SteamVR by selecting it in the library and clicking the Play button.
2. After connecting, start Room Setup or Tutorial from the SteamVR menu.

**Comment by kisak-valve** [comment]
Hello @javl, your video driver does not support some experimental vulkan extensions which are currently required for SteamVR. You need the vulkan developer's branch of the nvidia driver (375.27.xx) or possibly the newest mainline beta (381.09) in order to use SteamVR.

**Comment by javl** [comment]
Oops... I'm so sorry. I knew about the specific driver and really thought I installed it. I've been installing all kinds of Nvidia stuff for this and deep learning, so I guessed I messed up somewhere.

I had a hard time installing the 375.27 version using the .deb package (wasn't able to run X afterwards) so in the end did a `apt-get remove "nvidia-*"` and installed it using the `.run` version from the Nvidia website. The room setup and tutorial work perfectly now!

Thank you.

**Comment by naveenT1010** [comment]
Hi, I am using nvidia driver 375.66, but I am unable to run the room setup, and the steamVR shows:
(Unresponsive) SteamVR Room Setup
I have opted for steamVR beta as well and have my vive and monitor connected to the same graphic card, but its still the same. Any suggestions @kisak-valve ?

**Comment by anoadragon453** [comment]
@naveenT1010 Per my understanding 375.66 is the mainline version of the driver without the necessary Vulkan extensions. As stated above you need the [Vulkan developer's branch](https://developer.nvidia.com/vulkan-driver) of the nvidia driver (375.27.15) or the [newest mainline driver](https://www.nvidia.com/Download/driverResults.aspx/118524/en-us) (381.22) as recommended in the readme in order to use SteamVR.

**Comment by naveenT1010** [comment]
Hi @anoadragon453 , actually I am also working on deep learning with gpu and currently have my nvidia drivers and cuda working properly. If I change my current nvidia driver, is it gonna break my cuda libraries?

**Comment by anoadragon453** [comment]
@naveenT1010 From what I can see from the [CUDA on Linux docs](http://docs.nvidia.com/cuda/cuda-installation-guide-linux/index.html) CUDA seems more tied to the gcc version/build environment than NVIDIA drivers. Did you have to install any specific NVIDIA driver to get CUDA working? If not, then using the latest mainline or the Vulkan developer driver should have no ill effects.

If you're having trouble with getting either it would be useful to know what Linux distro/version you're running and we may be able to help you.

**Comment by naveenT1010** [comment]
Okay, I am gonna try with installing the 381.22 drivers once. I am using Ubuntu 16.04.

**Comment by naveenT1010** [comment]
@anoadragon453 , I have installed the nvidia driver 381.22, now I am able to see the Room setup window which was previously not even starting up, but there is no display in my headset and I am also getting (unresponive) steamVR Home. It is also saying to change to direct mode which I am agreeing to, but after the vive reboot, if I start the steamVR again, it just repeats the same.

**Comment by anoadragon453** [comment]
@naveenT1010 I would now create a new issue with the information you have told me. 

Also be aware that SteamVR always automatically runs in direct mode on Linux where supported, even if the software is unable to tell that it is :)

**Comment by naveenT1010** [comment]
okay, also after connecting the vive, it is not showing up in the display settings as another monitor. With previous nividia driver, it was there.

**Comment by anoadragon453** [comment]
> it is not showing up in the display settings as another monitor.

This is intended as direct mode prevents it from acting as another monitor. This improves performance.

**Comment by naveenT1010** [comment]
Hi @anoadragon453, really sorry to bother you again, but I have tried many times now, most of the times I get unresponsive whatever application I use be it Home or Room Setup, tutorial. And also when I get unresponsive error, I have no display on my headset, its just blank. Sometimes when it does work and I get to see the application in headset, just after few seconds, the frame gets stuck and I am not able to move around or see anything else.
Here is my system report [Report](https://gist.github.com/naveenT1010/0cbcdc3729bf2e8aa802494a7e60b55a) if it helps.
Thanks

**Comment by anoadragon453** [comment]
@naveenT1010 Like I mentioned if you could create a new issue that would probably be the best course of action. I'm not a Valve employee nor am sure what the solution might be.
