### ISSUE TITLE
[BUG] SteamVR creates URI handler .desktop files as visible applications that show up in app menus

### ISSUE THREAD

**Issue by enveeed** [ValveSoftware/SteamVR-for-Linux#456]
#### Please describe your issue in as much detail as possible:
When installing SteamVR it will generate a few .desktop files in `.local/share/applications`, two for URI handlers and and one for the VR monitor application.

The VR monitor shows up as an application in an app menu (e.g. in GNOME or any other desktop environment with an application menu) like it is intended to, however the URI handlers do as well:

![vr](https://user-images.githubusercontent.com/25058915/127924303-7da6d37d-94f0-4d00-af33-f1029c8c7042.png)

I don't think this is intended behavior as URI and MIME type handlers added by other applications do not show up in the menu either (and the URI handlers are of no use if opened without an URI in the app menu).

The desktop entry specification contains a specific key for purposes like this which other applications make use of:

> NoDisplay means "this application exists, but don't display it in the menus".

https://specifications.freedesktop.org/desktop-entry-spec/desktop-entry-spec-latest.html

So this problem can be fixed by changing both `valve-URI-steamvr.desktop` and `valve-URI-vrmonitor.desktop`:

```diff
+ NoDisplay=true
```

Intended functionality is preserved as far as I tested.

#### Steps for reproducing this issue:
1. Install SteamVR using Steam
2. Check your favorite applications menu in your desktop environment
3. The SteamVR URI handlers will show up as applications.

**Comment by kisak-valve** [comment]
Hello @enveeed, this issue is already being tracked at https://github.com/ValveSoftware/steam-for-linux/issues/7798. Closing as a duplicate.
