### ISSUE TITLE
[BUG] SteamVR v1.19.6 no motion compensation support on NVIDIA 470 (ArchLinux)

### ISSUE THREAD

**Issue by vityafx** [ValveSoftware/SteamVR-for-Linux#459]
**Describe the bug**
I have all the latest packages from the ArchLinux repos, among which is the NVIDIA 470 driver.
The motion compensation as far as I know relies on the async reprojection support which was made available in the 470 driver release a while ago. But I can't enable it in my SteamVR.

**To Reproduce**
1. Go to SteammVR
2. Click on 'Video' and then hover over 'Motion smoothing".
4. See it is disabled and a hint "Motion smoothing is not supported on this GPU / Driver version."

**Expected behavior**
It should work, not be disabled and being able to be turned on and work.

**System Information (please complete the following information):**
- Distribution: Arch
- SteamVR version: 1.19.6 or 1.18.7
- Steam client version: Aug 4 2021 at 17:06:57
- Opted into Steam client beta?: Yes
- Graphics driver version:  [run `nvidia-settings` or `vulkaninfo | grep driverInfo`: `470.57.02`
- Gist for SteamVR System Information: https://gist.github.com/vityafx/b2e22d2137f7b9f6429cb0f72a3b3581

**Screenshots**

**Additional context**

**Note:** Commenters who are also experiencing this issue are encouraged to include the "System Information" section in their replies.

**Comment by kisak-valve** [comment]
Hello @vityafx, this issue is already being tracked at #214. Closing as a duplicate.

**Comment by vityafx** [comment]
Thanks. I am sorry I couldn't find it myself.
