### ISSUE TITLE
[Feature Request] Audio menu in SteamVR Settings

### ISSUE THREAD

**Issue by jmanabc** [ValveSoftware/SteamVR-for-Linux#460]
#### Your system information
* Steam client version (build number or date): Steam self updater won't tell me so idk
* Distribution (e.g. Ubuntu): Arch Linux
* Graphics driver version (run nvidia-settings): 470.57.02
* Gist for SteamVR System Information: 
* Opted into Steam client beta?: No
* Opted into SteamVR beta?: No
* Have you checked for system updates?: [Yes/No]

#### (Optional) Performance data:
The following fields are helpful in diagnosing performance issues:
* Gpuvis capture:
* Perf top gist:

To reach parity with the Windows version, there should be a functional audio menu in the SteamVR settings where ideally the user can easily configure the system to output to the HMD, and if desired have the audio mirror to another device. Minimally there should be an in-VR menu with similar functionality to pavucontrol, where the user can configure which HDMI/DisplayPort to send audio to.

Some solution is probably better than no solution on this one.

**Comment by kisak-valve** [comment]
Hello @jmanabc, this issue is already being tracked at #279. Closing as a duplicate.
