### ISSUE TITLE
[BUG] Async frame hallucinations OVER & UNDERshoot rotation vector below 60fps (video)

### ISSUE THREAD

**Issue by SpookySkeletons** [ValveSoftware/SteamVR-for-Linux#467]
The bug is present on both AMD and Nvidia hardware as soon as async motion smoothing is enabled.
The issue becomes apparent below 60 fps.

Improperly hallucinated frames are visible flickering both in the direction of movement as well as trailing behind, alternating seemingly at random.

- Distribution: [Gentoo]
- SteamVR version: [E.g. 1.20.2]
- Steam client version: [Sep 17, 2021] 
- Opted into Steam client beta?: [Yes]
- Graphics driver version:  [run `nvidia-settings` or `vulkaninfo | grep driverInfo`:  nvidia RTX 2070 470.63.01
- Gist for SteamVR System Information: [See [instructions](https://github.com/ValveSoftware/SteamVR-for-Linux/blob/master/CapturingSystemReport.md)]

**VIDEO**
https://www.youtube.com/watch?v=JMNXO1_dtHs
Video is poor quality phone within HMD but gets the point across, use the comma and period to navigate frame by frame, you can see the rapid jittering motion of the hallucinated frames.

**Note:** Commenters who are also experiencing this issue are encouraged to include the "System Information" section in their replies.

**Comment by kisak-valve** [comment]
Hello @SpookySkeletons, this issue is already being tracked at #269. Your feedback adds a little bit more insight, so I've transferred this issue report to https://github.com/ValveSoftware/SteamVR-for-Linux/issues/269#issuecomment-927114268.

Closing as a duplicate.
