### ISSUE TITLE
[BUG] Half-Life: Alyx closes before reaching the main menu

### ISSUE THREAD

**Issue by sankasan** [ValveSoftware/SteamVR-for-Linux#468]
**Describe the bug**
Unable to play Half-Life: Alyx on Linux. The game closes (cleanly) before it reaches the main menu. Tried both Windows version with Proton Experimental as well as native. The Windows version throws an error `"Timed out waiting for response from Mongoose. SteamVR needs to be restarted"`. The native version just closes (no crash) which might indicate the same underlying issue (tested by launching via gdb).

**To Reproduce**
1. Launch Steam
2. Launch SteamVR
3. Launch Half-Life: Alyx

**Expected behavior**
When the game launches I see the "Half-Life: Alyx" window appear on desktop showing a hourglass. The sound starts playing (female voice over speakers). Normally the game would continue to the main menu, in my case it closes.

**System Information (please complete the following information):**
- Distribution: Arch
- SteamVR version: 1.20.2 (beta)
- Steam client version: 29 September 2021
- Opted into Steam client beta?: Yes
- Graphics driver version: Mesa 21.2.2
- Gist for SteamVR System Information: https://gist.github.com/sankasan/8c2548c0c233cb6867aaf6ef284c6fdb

**Screenshots**
This is the dialog popup showing when running the Windows version using Proton Experimental.
![HLA_proton_expimental_TimedOutWaitingResponseMongoose-SteamVRNeedsRestart](https://user-images.githubusercontent.com/2207658/135328171-bfde92f2-13bd-4180-b24c-b2a041f2f9ef.png)

**Additional context**
I've gathered additional information in a Steam Support ticket. Although the people were friendly they we're not very technical minded. They were not even aware of the native version. In the end they hardly offered any actual support and redirected to the forums. If you work at Valve you might want to look up ticket `HT-2QXR-RH85-28K2` for additional information and logs.

**Note:** Commenters who are also experiencing this issue are encouraged to include the "System Information" section in their replies.

**Comment by sankasan** [comment]
Although it sounds similar I don't think this ticket is related: https://github.com/ValveSoftware/SteamVR-for-Linux/issues/370#issue-650366760

**Comment by sankasan** [comment]
I've tried minimizing a lot of errors. These include:

- verified game data
- disabling overlays for HL:A
- disabling cloudsaves for HL:A
- removing shader cahces for HL:A
- reinstalling HL:A
- reinstalling SteamVR
- switching between beta/non-beta versions of SteamVR
- switching between beta/non-beta versions of Steam
- installed local packages (64 and 32 bit) related to libpangoft2` and `libpng12` as these showed up as warnings
- reverted freetype2 as this was a known issue for steam itself (and it showed up in the log)

Probably a few additional things.

**Comment by sankasan** [comment]
The annoying part is that SteamVR seems to work (despite the known rendering issues in the home application). I can play beat saber just fine and I can use SteamVR for my work with Unreal Engine 4 and 5.

**Comment by kisak-valve** [comment]
Hello @sankasan, this issue is already being tracked at #332. Feel free to add your experience to that issue report. Closing as a duplicate.
