### ISSUE TITLE
Artefacts and crashes with nvidia

### ISSUE THREAD

**Issue by mSparks43** [ValveSoftware/SteamVR-for-Linux#470]
**Describe the bug**
Artefacts and crashes with nvidia 470 drivers

**To Reproduce**
This seems to have appeared in the NVIDIA 470 driver release, 465 drivers work fine
also posted on the nvidia forums

**Expected behavior**
No artefacts or crashes

**System Information (please complete the following information):**
- Distribution: Fedora Core 34
- SteamVR version: 1.20.3
- Steam client version: Sept 17 2021
- Opted into Steam client beta?: Yes
- Graphics driver version:  470.42 / 470.57 / 470.63 / 470.74
- Gist for SteamVR System Information: https://gist.github.com/mSparks43/9800fdf0079d85badfb2bcae1d06eff3

**Screenshots**
Video here
https://youtu.be/W3Tfqz_tiIM

**Comment by kisak-valve** [comment]
Hello @mSparks43, this issue is already being tracked at #395 / #452. Closing as a duplicate.
