### ISSUE TITLE
[PERF] Very 'jerky' headtracking

### ISSUE THREAD

**Issue by blitz-research** [ValveSoftware/SteamVR-for-Linux#477]
Hi,

I recently tried to get my HTC Vive headset working with steamvr on Manjaro again after about a year, and it works visually but the headtracking is extremely 'jerky'. As you rotate your head, the scene moves in small 'jumps' at a rate of about 10Hz-ish. It's pretty unusable.

I cranked up the advanced frame timing thing and got this:

![FrameTiming](https://user-images.githubusercontent.com/3487554/140660848-cc96a10b-c4bb-41ca-9923-91f0dba17672.png)

The steamvr 'compositor' looks like it may be doing something weird here as it spikes at about 10-hz too, although I may just be imaginging that.

After a bit of googling, I found out about the "enableLinuxVulkanAsync" setting in the steamvr.vrsettings file, and adding this seems to get rid of most of the green spikes in the frame timing, but it's still as jerky as hell, possibly even worse. Plus, my GPU starts thrashing and the fan starts going nuts, although to be honest I can't remember if it used to do that or not.

Here are some of my system specs:

System:    Host: marksibly-manjaro20 Kernel: 5.14.10-1-MANJARO x86_64 bits: 64 Desktop: Xfce 4.16.0
           Distro: Manjaro Linux
Machine:   Type: Desktop Mobo: ASUSTeK model: TUF B450-PLUS GAMING v: Rev X.0x serial: <superuser required>
           UEFI: American Megatrends v: 2008 date: 12/06/2019
CPU:       Info: 8-Core AMD Ryzen 7 3700X [MT MCP] speed: 1867 MHz min/max: 2200/3600 MHz
Graphics:  Device-1: Advanced Micro Devices [AMD/ATI] Navi 10 [Radeon RX 5600 OEM/5600 XT / 5700/5700 XT]
           driver: amdgpu v: kernel
           Device-2: HTC (High Tech ) Vive type: USB driver: snd-usb-audio,uvcvideo
           Display: x11 server: X.Org 1.20.13 driver: loaded: amdgpu,ati unloaded: modesetting,radeon
           resolution: 1920x1080~60Hz
           OpenGL: renderer: AMD Radeon RX 5700 XT (NAVI10 DRM 3.42.0 5.14.10-1-MANJARO LLVM 12.0.1)
           v: 4.6 Mesa 21.2.3
Network:   Device-1: Realtek RTL8111/8168/8411 PCI Express Gigabit Ethernet driver: r8169
Drives:    Local Storage: total: 1.36 TiB used: 1.08 TiB (79.0%)
Info:      Processes: 338 Uptime: 35m Memory: 31.29 GiB used: 3.39 GiB (10.8%) Shell: fish inxi: 3.3.08

It seems like many people have been having similar (and dissimilar!) problems with steamvr on Linux for a while now. Is it still in active development, or is it effectively dead?

Bye!
Mark

**Comment by kivoli** [comment]
Have you tried https://github.com/ValveSoftware/SteamVR-for-Linux/issues/469#issuecomment-932807351? Solved it for me …

**Comment by blitz-research** [comment]
I ended up trying to get the 'monado' openxr implementation going instead, and in the process found several bugs in the AMDVLK driver. I switched to the RADV driver at someone's suggestion and both monado and steamvr work much better with it. I think I'll stick with monado though as it was *very* useful having the source code available to poke around in!

Anyone someone can close this I guess since it looks like it's really an AMDVLK driver issue.

**Comment by Meister1593** [comment]
> I ended up trying to get the 'monado' openxr implementation going instead, and in the process found several bugs in the AMDVLK driver. I switched to the RADV driver at someone's suggestion and both monado and steamvr work much better with it. I think I'll stick with monado though as it was _very_ useful having the source code available to poke around in!
> 
> Anyone someone can close this I guess since it looks like it's really an AMDVLK driver issue.

Hello
Can i ask how can i use htc vive through Monado? I managed to recognize it as addon, but... what i can really do with it? can it fix delayed output/jerky movement?

**Comment by blitz-research** [comment]
I think all you can do with mando right know is to start writing OpenXR software with it. That's what I'm planning to do anyway...

Monado didn't fix my jerkey headtracking because that turned out to be the AMD driver I was using - changing to the RADV driver fixed both monado and steamvr for me.
