### ISSUE TITLE
Fedora 25 - room setup crashs

### ISSUE THREAD

**Issue by phobeus81** [ValveSoftware/SteamVR-for-Linux#48]
#### Your system information
* Steam client version (build number or date): SteamVR Version 2017-04-28 (1493337050)
* Distribution (e.g. Ubuntu): Fedora 25 (64 bit)
* Graphics driver version (run nvidia-settings): 375.39
* Gist for SteamVR System Information: https://gist.github.com/phobeus81/7b39ac5258373eaf4cd18fb3056f2dbd
* Opted into Steam client beta?: No
* Opted into SteamVR beta?: Yes
* Have you checked for system updates?: Yes

#### Please describe your issue in as much detail as possible:
The Steam VR application can be launched via tools and seems to be starting up correctly and able to detect the lighthouses and controllers as well as the head device. The compositor is starting and showing screen.

When launching the steam vr room setup however, just a window is opened hangs for a while and then closing. When launching the steam vr room setup from console, a seg fault occurs. Thus it is not possible to setup the room anymore.

From the console I executed the room setup using strace and uploaded the dump to https://gist.github.com/phobeus81/e20c39bf7cc396ac21df91ae56550b9c

#### Steps for reproducing this issue:
1. Launch Steam VR
2. Select "Run Room Setup" from the menu

**Comment by kisak-valve** [comment]
Hello @phobeus81, SteamVR currently requires some experimental vulkan extensions which are not in the 375.39 nvidia driver. You need to use nvidia's vulkan development branch 375.27.xx, (or 381.09 or higher) as noted at https://github.com/ValveSoftware/SteamVR-for-Linux#graphics-driver-requirements. At this moment you may have a better experience with 375.27.10 or 375.27.13.

**Comment by phobeus81** [comment]
Ah, okay ... i thought that would mean 375.27 minimum and thus I would be safe with my version. Okay, then it will be likely some graphic card issue. I'll close the issue and will reopen it, if it is not fixed by using the given version.
