### ISSUE TITLE
Serious Sam Last Hope won't verify license

### ISSUE THREAD

**Issue by pete777moen** [ValveSoftware/SteamVR-for-Linux#481]
I am trying to load Serious Sam Last Hope, but I get the error message that the license verification can't be accessed. I have run many VR games like Saints and Sinners with no problem with my Index system.  Here is a list of things that I have tried:
used 8.8.8.8, 8.8.4.4 as dns on computer
tried 8.8.8.8, 8.8.4.4 on router (not allowed)
2001:4860:4860::8888 and/or 2001:4860:4860::8844 IP6 tried
tried +gfxapi OGL launch option
tried proton version 6.3-7
tried various ways to start, desktop icon (unpacked direct x) normal, without VR on, etc.
 SamTLH.log can't find
 fire wall disabled, thought i could change it, but it was not on
![Screenshot from 2021-11-13 15-41-29](https://user-images.githubusercontent.com/94658623/142544775-ccb8de45-9c3e-41ad-94de-4f87ebf70e54.png)

Here is my system information: Computer and Steam Information. 

Manufacturer: ASRock
Model: X399 Phantom Gaming 6
Form Factor: Desktop
No Touch Input Detected
SteamVR Version:	1.21.2 (1636664637)
SteamVR Date:	2021-11-11
Steam:	Public
Steam Branch:	beta
Steam AppID:	250820
Tracking:	lighthouse
OS:	Linux version 5.11.0-40-generic (buildd@lgw01-amd64-010) (gcc (Ubuntu 9.3.0-17ubuntu1~20.04) 9.3.0, GNU ld (GNU Binutils for Ubuntu) 2.34) #44~20.04.2-Ubuntu SMP Tue Oct 26 18:07:44 UTC 2021

OS Version:	0.0.0.0
Direct Mode Vendor:	Unknown
Direct Mode Version:	
Admin:	Yes
AsyncReprojection:	Enabled
Performance drops:	20/1 6/2 2/3 2/4 553/614
Display Mode:	Direct Mode
</Report>

<Displays>
</Displays>

<Devices>
Device 1 - LHR-F65B100F Headset Index Valve
Device Path:	/devices/lighthouse/LHR-F65B100F
Best Alias:	/user/head
Firmware: 	1623823641 WMBUILD-W64$@wmbuild-w64 2021-06-15 FPGA 538(2.26/9/2) BL 1555018600
Hardware Revision: 	product 34 rev 21.65.9 lot 2000/0/0 0
Hardware Id: 	0x22154109
Watchman Firmware: 	1623823641 / 1623823641 (2021-06-15) 
Watchman FPGA: 	538 / 538 (2.26) 
VRC Version: 	1623823641 / 0 (2021-06-15) 
Camera Firmware: 	Version not available.
VSync to Photons: 	0.011375
Display Frequency:	90
User IPD (m):	0.07
Current Universe ID:	0
Previous Universe ID:	0
Dongle Version: 	0ACC1BE8E3-RYB Version: 1553895605 / 1558748372 (2019-03-29) (Update necessary)
Dongle Version: 	C250D258F1-LYM Version: 1553895605 / 1558748372 (2019-03-29) (Update necessary)
<Device1_Additional>
HMD Report:
 .version = 2
Processor Information:
CPU Vendor: AuthenticAMD
CPU Brand: AMD Ryzen Threadripper 1900X 8-Core Processor
CPU Family: 0x17
CPU Model: 0x1
CPU Stepping: 0x1
CPU Type: 0x0
Speed: 3800 Mhz
16 logical processors
8 physical processors
HyperThreading: Supported
FCMOV: Supported
SSE2: Supported
SSE3: Supported
SSSE3: Supported
SSE4a: Supported
SSE41: Supported
SSE42: Supported
AES: Supported
AVX: Supported
AVX2: Supported
AVX512F: Unsupported
AVX512PF: Unsupported
AVX512ER: Unsupported
AVX512CD: Unsupported
AVX512VNNI: Unsupported
SHA: Supported
CMPXCHG16B: Supported
LAHF/SAHF: Supported
PrefetchW: Unsupported

Operating System Version:
Ubuntu 20.04.3 LTS (64 bit)
Kernel Name: Linux
Kernel Version: 5.11.0-40-generic
X Server Vendor: The X.Org Foundation
X Server Release: 12011000
X Window Manager: GNOME Shell
Steam Runtime Version: steam-runtime_0.20211102.0

Video Card:
Driver: NVIDIA Corporation GeForce RTX 2060/PCIe/SSE2
Driver Version: 4.6.0 NVIDIA 460.91.03
OpenGL Version: 4.6
Desktop Color Depth: 24 bits per pixel
Monitor Refresh Rate: 60 Hz
VendorID: 0x10de
DeviceID: 0x1e89
Revision Not Detected
Number of Monitors: 1
Number of Logical Video Cards: 1
Primary Display Resolution: 1920 x 1080
Desktop Resolution: 1920 x 1080
Primary Display Size: 34.88" x 19.61" (40.00" diag)
88.6cm x 49.8cm (101.6cm diag)
Primary Bus: PCI Express 16x
Primary VRAM: 6144 MB
Supported MSAA Modes: 2x 4x 8x 16x

Sound card:
Audio device: Realtek ALC1220

Memory:
RAM: 15855 MB

VR Hardware:
Headset: Valve Index (lighthouse)
Base station or sensor: HTC HTC V2-XD/XE (lighthouse)
Base station or sensor: HTC HTC V2-XD/XE (lighthouse)

Miscellaneous:
UI Language: English
LANG: en_US.UTF-8
Total Hard Disk Space Available: 227081 MB
Largest Free Hard Disk Block: 109659 MB

Storage:
Number of SSDs: 0
Number of HDDs: 0**Describe the bug**

**To Reproduce**

**Expected behavior**

**System Information (please complete the following information):**
- Distribution: [Arch/Manjaro/Ubuntu/etc.]
- SteamVR version: [E.g. 1.7.2]
- Steam client version: [build number or date] 
- Opted into Steam client beta?: [Yes/No]
- Graphics driver version:  [run `nvidia-settings` or `vulkaninfo | grep driverInfo`:
- Gist for SteamVR System Information: [See [instructions](https://github.com/ValveSoftware/SteamVR-for-Linux/blob/master/CapturingSystemReport.md)]

**Screenshots**

**Additional context**

**Note:** Commenters who are also experiencing this issue are encouraged to include the "System Information" section in their replies.

**Comment by kisak-valve** [comment]
Hello @pete777moen, we're tracking issues with games run with Proton in the Proton issue tracker. Also, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/2708#issuecomment-973652716.
