### ISSUE TITLE
[BUG] "Please plug in your VR headset" even when the headset is plugged in

### ISSUE THREAD

**Issue by anriha** [ValveSoftware/SteamVR-for-Linux#483]
**Describe the bug**
I have Valve Index and after connecting it to my machine the SteamVR does not seem to recognize it. Tried different distros, replugging in everything in every possible order, different ports. Steam-devices package is installed and just to be sure I even manually added udev rules.

**To Reproduce**
1. Plug in Headset
2. Start SteamVR

**Expected behavior**

**System Information (please complete the following information):**
- Distribution: PopOS! 20.04 (but got the same result on Manjaro, Ubuntu 21.10, Ubuntu 21.04)
- SteamVR version: 1.20.4 (but tested on Beta version both newest and Linux version)
- Steam client version: Current version (11. 20. 2021)
- Opted into Steam client beta?: Yes
- Graphics driver version:  Nvidia 470.82.00
- Gist for SteamVR System Information: https://gist.github.com/anriha/88ce5884fbd7925cb6af1cfd6b6b62c9

**Note:** Commenters who are also experiencing this issue are encouraged to include the "System Information" section in their replies.

**Comment by ChrisJAllan** [comment]
The Index's usb device isn't listed, but the camera is. I've had this happen before, it was the cable gone bad. Contact Steam support and see if you can get a replacement. You will probably need to test it in Windows to confirm that the issue isn't something else.

**Comment by anriha** [comment]
After testing on Windows PC it seems that is the case. I was really hoping it would be something else but even on a Windows machine, it doesn't work. Thanks for the diagnosis.
