### ISSUE TITLE
[BUG] Room setup exits shorter after start with recent Mesa git

### ISSUE THREAD

**Issue by yshui** [ValveSoftware/SteamVR-for-Linux#484]
**Describe the bug**
After I start Room Setup, the window shows up, then turns completely black after a fraction of the second, then closes itself a couple of seconds later.

**System Information (please complete the following information):**
- Distribution: Arch
- SteamVR version: Tested with 1.21 and 1.20
- Opted into Steam client beta?: Both
- Graphics driver version:  
  - Works with: mesa commit c2d522b07f9, broken on df005c2a65f

**Comment by kisak-valve** [comment]
Hello @yshui, this issue should also be reported to your video driver vendor as a regression.

**Comment by yshui** [comment]
Hmm. So I tried to narrow down the range of git commits, but after a round of testing the problem disappeared. Could be something transient.

Closing.

Sorry for the trouble.
