### ISSUE TITLE
"Headset not detected" on Ubuntu 17.04 (GNOME)

### ISSUE THREAD

**Issue by jessedubord** [ValveSoftware/SteamVR-for-Linux#49]
#### Your system information
* Steam client version (build number or date): Apr 25, 2017 22:46:35
* Distribution (e.g. Ubuntu): Ubuntu GNOME 17.04
* Graphics driver version (run nvidia-settings): 381.09
* Gist for SteamVR System Information: [https://gist.github.com/jessedubord/81703472551990a4085a3f715ce8949a](https://gist.github.com/jessedubord/81703472551990a4085a3f715ce8949a)
* Opted into Steam client beta?: Yes
* Opted into SteamVR beta?: Yes
* Have you checked for system updates?: Yes

#### Please describe your issue in as much detail as possible:
I've installed Nvidia proprietary driver 381.09, Steam client beta, and SteamVR beta. After starting SteamVR, the status window appears saying "Not Ready". The vrmonitor window above it says in red: "Headset not detected", with some text, then prompts me to "Reboot Headset". After I click Reboot Headset, it says: "Rebooting Vive.. Service Status: Failed."

HTC Vive indicator LED on the left-side of the headset shows red all the while, with the exception of PC shutdown, in which it turns green for a second or so.

I would use the Nvidia 375 Vulkan driver, but the PPA mentioned on the SteamVR-for-Linux github page doesn't have a package for the Zesty 17.04 release of Ubuntu.

#### Steps for reproducing this issue:
1. Install Ubuntu GNOME 17.04, update system, install Nvidia 381.09 drivers from PPA, install Steam client[beta], and install SteamVR [beta]
2. Run SteamVR

**Comment by johnv-valve** [comment]
As the README says

> The latest driver in NVIDIA's stable branch has a higher version number, but will not work. You need the driver from the vulkan development branch that is at almost exactly version 375.27.xx.

**Comment by kisak-valve** [comment]
The nvidia 381.09 driver should have the required experimental vulkan extensions, but there may be other quirks happening here.

**Comment by jessedubord** [comment]
The maintainer of the PPA for the 375 Vulkan driver has expressed that there won't be a build of that driver for 17.04 because, in his words: "The
381.09 driver has been released, which should have the same VR support
as the earlier development driver, and also has a build available for
17.04 in the Graphics Drivers PPA.  Additionally, the development driver
is incompatible with the Linux kernel 4.10 used in 17.04 and would take
significant work to make it compatible again."

So... how are Ubuntu 17.04 users supposed to make this work, exactly?

**Comment by johnv-valve** [comment]
The 381.09 driver has known regressions and doesn't work with SteamVR. When there is a released driver that works, we will update the README to reflect that.

Currently if you want to run SteamVR on NVIDIA hardware, the only driver that works is 375.27.xx.

If you cannot use 375.27.xx on your distro, then you will not be able to run SteamVR. At this point your options to 'make this work' are
1. Wait for a new NVIDIA driver that works.
2. Choose another distro release that can run the 375.27.xx driver. (Ubuntu 16.04 LTS works)
3. Switch to AMD graphics and the open-source driver referenced in the README.

**Comment by jessedubord** [comment]
10-4, I do appreciate the info' @johnv-valve. Thanks! :)
