### ISSUE TITLE
[BUG] Settings Overlay does not open in SteamVR 1.21.5

### ISSUE THREAD

**Issue by fusselkater** [ValveSoftware/SteamVR-for-Linux#491]
#### Your system information
* Steam client version (build number or date): Jan 7 2022 17:58:16
* Distribution (e.g. Ubuntu): Gentoo Linux
* Graphics driver version (run nvidia-settings): Mesa 21.3.3 (AMDGPU)
* Gist for SteamVR System Information: https://gist.github.com/fusselkater/7fc01d284058c8543e880b0365509911
* Opted into Steam client beta?: Yes
* Opted into SteamVR beta?: Yes
* Have you checked for system updates?: Yes

#### Please describe your issue in as much detail as possible:
Clicking on settings button on VR Controllers of Valve Index should open the settings overlay but it doesn't. In SteamVR 1.21.4 it worked. Additionally clicking on burger menu -> Settings in SteamVR Dashboard also doesn't work.

#### Steps for reproducing this issue:
1. Start SteamVR
2. Click settings button on the VR controller
3. Nothing happens

**Comment by kisak-valve** [comment]
Hello @fusselkater, I was able to reproduce this issue. The adjustment to fix #465 is missing the `STEAM_RUNTIME_HEAVY` environment variable. You can workaround this quirk by setting SteamVR's launch options to `STEAM_RUNTIME_HEAVY="${HOME}/.steam/bin64/steam-runtime-heavy" %command%`.

It would be better to fold this into the older discussion on #465.

Closing in favor of the older issue report.
