### ISSUE TITLE
[BUG] Index rendering artifacts around edges of screen

### ISSUE THREAD

**Issue by CrispyPin** [ValveSoftware/SteamVR-for-Linux#500]
**Describe the bug**
When the headset is on a higher FOV setting, the edges of the screens are rendered as bright grey instead of just showing the game world, ruining immersion. This issue did not happen on SteamVR 1.20

**To Reproduce**
1. Open SteamVR 1.21.8
2. Move the lenses as close to your eyes as possible
3. See the artifacts in the corners

**Expected behavior**
No artifacts visible

**System Information (please complete the following information):**
- Distribution: Arch
- SteamVR version: 1.21.8
- Steam client version: latest as of 22/02/22
- Opted into Steam client beta?: No
- Graphics driver version:  Mesa 21.3.6:
- Gist for SteamVR System Information: https://gist.github.com/CrispyPin/354a2752b983d9b0a92f9caa87686d1c

**Additional context**
I updated the headset firmware and nothing changed.

**Note:** Commenters who are also experiencing this issue are encouraged to include the "System Information" section in their replies.

**Comment by kisak-valve** [comment]
Hello @CrispyPin, this sounds similar to #480. Please test if setting SteamVR's launch options to `RADV_DEBUG=zerovram %command%` acts as a workaround.

**Comment by CrispyPin** [comment]
@kisak-valve that worked, thanks

**Comment by kisak-valve** [comment]
Thanks for testing. Closing in favor of the older issue report.

**Comment by bblacher** [comment]
I'm having the same issue, however setting SteamVR's launch options to `RADV_DEBUG=zerovram %command%` doesn't help. Any ideas? @kisak-valve
