### ISSUE TITLE
[BUG] QuakeVR, Failed to read Steam VR analog/digital action data

### ISSUE THREAD

**Issue by dacobi** [ValveSoftware/SteamVR-for-Linux#502]
Not sure if this belongs here, but I've just compiled QuakeVR for Linux which uses SteamVR via OpenVR.
The game launches and works in general but no buttons or joysticks/pads work and I keep getting these errors in console:

Failed to read Steam VR analog action data, rc = 3
Failed to read Steam VR digital action data, rc = 3

As far as I can tell the controller bindings look ok.

Headset is Index.

I'm using StreamVR Beta 1.21.11 and OpenVR from git

Pop OS 21.10

Nvida driver:
	driverInfo         = 510.54
	driverInfo         = Mesa 21.2.2 (LLVM 12.0.1)

Steam report
https://gist.github.com/dacobi/7b49868dd35d7c97a6976fab593d5372

**Comment by okawo80085** [comment]
Check in the legacy binding tab if it found the right controller/if there are any bindings at all.

Also check if the game is getting initialized properly because vrinput rc=3 is VRInputError_InvalidHabdle

**Comment by dacobi** [comment]
I found the problem :) 
Path to actions.json was hardcoded to the developers original folder.
