### ISSUE TITLE
[BUG] Error 307 after disabling reprojection

### ISSUE THREAD

**Issue by Kirottu** [ValveSoftware/SteamVR-for-Linux#505]
**Describe the bug**
SteamVR fails with the error code 307, if `enableLinuxVulkanAsync` is set to false in `steamvr.vrsettings`. I would need to disable reprojection, as it severely hinders ALVR.

**To Reproduce**
1. Set `enableLinuxVulkanAsync` to `false` in `steamvr.vrsettings`
2. Start SteamVR

**Expected behavior**
I would expect it to not fail on it.

**System Information:**
- Distribution: Arch Linux
- SteamVR version: 1.21.11
- Steam client version: Latest as of today, 10.3.2022 (dd/mm/yyyy)
- Opted into Steam client beta?: No
- Graphics driver version: Mesa 21.3.7
- Gist for SteamVR System Information: https://gist.github.com/Kirottu/b6fc480e66dd09ae1616ccf59e60a742

**Screenshots**
![image](https://user-images.githubusercontent.com/56396750/157596680-e48d7813-ae94-44cb-a183-14f4d9930cc1.png)

**Additional context**
As stated before, I am using ALVR for connecting to my Oculus Quest 2 headset. For ALVR reprojection causes major issues such as flickering, jittering, instability, etc. As far as I know this problem seems to be only happening on AMD cards such as mine (RX 570).

**Note:** Commenters who are also experiencing this issue are encouraged to include the "System Information" section in their replies.

**Comment by ColdIce1605** [comment]
Please note that this has already been reported here also please update ALVR as it should be doing it automatically.
It would also be nice to tell me what version your using, also this is not a ALVR support repo so please join the discord or matrix to continue from there.
