### ISSUE TITLE
[BUG] Bright pixels in edge of right eye screen (Valve Index)

### ISSUE THREAD

**Issue by ClearlyClaire** [ValveSoftware/SteamVR-for-Linux#506]
**Describe the bug**

Starting from this week, I've been experiencing a distracting visual issue: it looks like part of the edge of the right eye's image is made of bright pixels unrelated to the displayed scene. This occurs no matter what SteamVR app is running, and I don't remember it ever happening before. The left eye is not affected.

Looking from different angles, it looks like that the part of the right screen that isn't properly covered by the lens is lit bright instead of being black. In some cases it seemed to be flickering, although inspecting it right now I can't manage to reproduce that, and instead, parts that don't seem to go through the lens are a solid unflickering white.

Last time I used SteamVR without noticing this issue was probably on 1.21.11.

**To Reproduce**

Run any SteamVR application using a Valve Index headset.

**Expected behavior**

No distracting light in peripheral vision.

**System Information (please complete the following information):**
- Distribution: Debian testing/unstable
- SteamVR version: 1.21.12
- Steam client version: Mar 14 2022, at 19:49:17
- Opted into Steam client beta?: Yes
- Graphics driver version:  Mesa 21.3.7
- Gist for SteamVR System Information: https://gist.github.com/ClearlyClaire/c6d665ff7cd4c9df53cde1dcc278de22

**Additional context**

Kernel is self-built 5.17.0-rc7 with patch to revert https://git.kernel.org/pub/scm/linux/kernel/git/stable/linux.git/commit/?h=v5.15.4&id=61d861cf478576d85d6032f864360a34b26084b1 (which breaks output on the Valve Index altogether). Tried old versions that worked without issues, with the same result.

**Comment by kisak-valve** [comment]
Hello @ClearlyClaire, this issue is already being tracked at https://github.com/ValveSoftware/SteamVR-for-Linux/issues/480.

You should be able to workaround this issue by setting SteamVR's launch options to `RADV_DEBUG="zerovram" %command%`.

Closing as a duplicate.

**Comment by ClearlyClaire** [comment]
Oh, right, seems like I updated mesa from 21.2 to 21.3 in that timeframe on my system. I can also confirm that using `RADV_DEBUG="zerovram" %command%` works around the issue. Thanks!

**Comment by Ehkad** [comment]
As of 2.0 I now still see pixels in the corner even when using RADV_DEBUG="zerovram" %command%. It is worse without the command.

**Comment by bblacher** [comment]
I do experience the same behaviour as @Ehkad
