### ISSUE TITLE
[BUG] Fish bowl/bad FOV in SteamVR Beta 1.22.1

### ISSUE THREAD

**Issue by mSparks43** [ValveSoftware/SteamVR-for-Linux#507]
**Describe the bug**
Entering Xplane 11 VR on Beta 1.22.1 the FOV becomes wrong, looking like a "fishbowl", previous none beta does not have this issue.

**To Reproduce**
1. Start Xplane 11
2. Enable VR

**Expected behavior**
normal Field of View

**System Information (please complete the following information):**
- Distribution: Fedora 35
- SteamVR version:  1.22.1 Beta
- Steam client version: March 14 2022 at 19.49:17
- Opted into Steam client beta?: Yes
- Graphics driver version:  510.47.03
- Gist for SteamVR System Information: https://gist.github.com/mSparks43/859604809ecd75f8c7eb5c9d734bde9c

**Screenshots**
SteamVR Beta 1.22.1
![image](https://user-images.githubusercontent.com/6773686/160906445-a1da5d29-55fd-40f4-98b0-1fbfa24f5d4e.png)
SteamVR 1.21.12 (expected)
![image](https://user-images.githubusercontent.com/6773686/160907239-9b91889b-e2a6-4bec-9169-948b300bc966.png)

**Note:** Commenters who are also experiencing this issue are encouraged to include the "System Information" section in their replies.

**Comment by edwin-v** [comment]
Confirmed (Index+NVidia). Not just X-Plane though, it appears to be for all native Linux games (noticed it in Groove Gunner myself). Games using proton are unaffected.

**Comment by edwin-v** [comment]
Just tested Groove Gunner on SteamVR Beta 1.22.11 and it was indeed fixed as suggested by the 1.22.10 changelog.

**Comment by kisak-valve** [comment]
Closing per the last comment.
