### ISSUE TITLE
Can't Open SteamVR beta 05/18/17 (SteamVR Home launch date)

### ISSUE THREAD

**Issue by Vash63** [ValveSoftware/SteamVR-for-Linux#51]
#### Your system information
* Steam client version (build number or date): May 19 2017, at 00:22:30
* Distribution (e.g. Ubuntu): Arch Linux
* Graphics driver version (run nvidia-settings): 381.22
* Gist for SteamVR System Information: N/A - Cannot launch
* Opted into Steam client beta?: [Yes/No] Both
* Opted into SteamVR beta?: [Yes/No] Y - stable branch is not impacted
* Have you checked for system updates?: [Yes/No] Y

#### Please describe your issue in as much detail as possible:
When opting into SteamVR beta, SteamVR no longer launches.

#### Steps for reproducing this issue:
1. Opt into beta
2. Attempt to launch SteamVR
3. 
![screenshot-20170519112651-592x193](https://cloud.githubusercontent.com/assets/3086017/26261451/15e0cba6-3c86-11e7-8a4b-f8782728669b.png)

**Comment by kkriehl** [comment]
I can confirm this problem on the same Linux distribution with the same NVIDIA driver version. I was able to start SteamVR by creating symlinks to ~/.local/share/Steam/steamapps/common/SteamVR/bin/{vrmonitor.sh,vrstartup.sh,linux32,linux64} inside ~/.local/share/Steam/steamapps/common/SteamVR/tools/bin.
I could not access the SteamVR home or dashboard - only settings. Starting SteamVR also produced the following error:
![image](https://cloud.githubusercontent.com/assets/560363/26268998/76f1ee90-3cf2-11e7-86ec-81a419281717.png)

I was unable to fix this by explicitly setting the value of $TOOLSDIR and $RUNTIME to ~/.local/share/Steam/steamapps/common/SteamVR/ in vrmonitor.sh and vrstartup.sh. The directories used for dynamic linking are all available and every generated path seems correct.

**Comment by gamerscomplete** [comment]
Same issue for me. I symlinked the vrmonitor.sh into the path it was looking for which caused the same problems as you, libs missing.

I removed ~/.local/share/Steam/steamapps/common/SteamVR/tools/bin/linux64 and replaced it with a symlink to ~/.local/share/Steam/steamapps/common/SteamVR/bin/linux64 which had the missing files. However now it is failing with

`/home/chris/.local/share/Steam/steamapps/common/SteamVR/bin/../bin/linux64/vrmonitor: relocation error: /usr/lib/x86_64-linux-gnu/libproxy.so.1: symbol _ZTTNSt7__cxx1119basic_ostringstreamIcSt11char_traitsIcESaIcEEE, version GLIBCXX_3.4.21 not defined in file libstdc++.so.6 with link time reference
`

**Comment by jessedubord** [comment]
I can also confirm this issue w/ Steam [beta] on Ubuntu (GNOME) 17.04 x64, Nvidia 381.22 proprietary drivers, GTX 1080 graphics.

![screenshot from 2017-05-25 10-43-08](https://cloud.githubusercontent.com/assets/11955519/26463950/dc52162e-413a-11e7-8edf-2a632fa92110.png)

**Comment by kisak-valve** [comment]
Please retest this issue.

**Comment by jessedubord** [comment]
Re-tested. The error is now gone, and SteamVR [beta] will start for me, but it gives a new error:

![screenshot from 2017-05-25 12-58-21](https://cloud.githubusercontent.com/assets/11955519/26468073/fe1c0468-4149-11e7-85b6-816571903ae2.png)

**Comment by kremfaen** [comment]
Can confirm the issue reported by jessedubord. I am on Arch Linux running XFCE, Nvidia 381.22 proprietary drivers, GTX 980ti.
![steamvr](https://cloud.githubusercontent.com/assets/2773103/26486383/2ef9b86c-41fb-11e7-8eea-5b8e14b41116.png)
[System Report](https://gist.github.com/kremfaen/473f04e91c2793c1fd54ee206783cd8f)

**Comment by Vash63** [comment]
It is now booting for me, but somewhat intermittently. Two of 4 tries
SteamVR started, the other two the Home failed to load or the Steam Big
Picture interface was missing. It does seem that the exact but this was
created for is now fixed though.

**Comment by johnv-valve** [comment]
vrclient not found error should be fixed in the current beta
http://steamcommunity.com/games/250820/announcements/detail/1256914311380287819
