### ISSUE TITLE
[BUG] Steam VR Error 307: Manjaro Linux

### ISSUE THREAD

**Issue by HisashiASM** [ValveSoftware/SteamVR-for-Linux#533]
**Describe the bug**
Upon new install of Manjaro Gnome, and fresh install of SteamVR, I am greeted with the beautiful Error 307 

**To Reproduce**
1. Install Manjaro
2. Install steam-native or steam-manjaro
3. Install SteamVR
4. Suffer with first booting to it not even seeing the HMD to then showing error 307 upon first reboot.

**Expected behavior**
See visuals from headset and not have to see this error.

**System Information (please complete the following information):**
- Distribution: [Manjaro Gnome]
- SteamVR version: [1.23.7] & [1.24.1]
- Steam client version: [Aug 20, 2022]
- Opted into Steam client beta?: [Yes] & [No]
- Graphics driver version:  [run `nvidia-settings` or `vulkaninfo | grep driverInfo`: 
[Link to Gist](https://gist.github.com/HisashiASM/36519b9de8f8d4df5e477460941f6681)
- Gist for SteamVR System Information: 
[Link to Gist](https://gist.github.com/HisashiASM/5a4b46164319948e11932b66a06b6e4b)

**Screenshots**
N/A

**Additional context**
I really wanna get into Linux, but no native SteamVR support killed that train really early.

**Note:** Commenters who are also experiencing this issue are encouraged to include the "System Information" section in their replies.

**Comment by earldbjr** [comment]
This seems to be related to issues with graphics drivers. Have you updated anything recently?

Quick thing to try, as this catches nvidia users off guard sometimes:
rename the file  /usr/share/vulkan/icd.d/intel_icd.x86_64.json to something else. 
I suggest appending a ".disabled" on the end.

In the event that steamvr is trying to use your motherboard's (assumedly) intel graphics, this will force it to look elsewhere: your nvidia card.

**Comment by HisashiASM** [comment]
It actually seems to be an issue with the fact that I (myself in question) am extremely blind and failed to see that GNOME in fact does start on Wayland by default.

**Comment by earldbjr** [comment]
Ahh, glad you found the issue!

**Comment by HisashiASM** [comment]
For the future me's you will need to modify ` /etc/gdm/custom.conf` and un-comment `WaylandEnable=false`.
