### ISSUE TITLE
[BUG] The Elder Scrolls V: Skyrim VR (611670) doesn't start with Steam VR beta 1.24.3

### ISSUE THREAD

**Issue by Corben78** [ValveSoftware/SteamVR-for-Linux#537]
**Describe the bug**
When using Steam VR beta 1.24.3, The Elder Scrolls V: Skyrim VR doesn't start anymore. Does start with 1.23.7.

**To Reproduce**
1. Opt into Steam VR beta
2. Install The Elder Scrolls V: Skyrim VR
3. Start game
4. Observe either Skyrim VR not starting or buttongoing back to "Play"

**Expected behavior**
Game should actually start.

**System Information (please complete the following information):**
- Distribution: Ubuntu 20.04.5 LTS
- SteamVR version: 1.24.3 beta
- Steam client version: Sep 9 2022, at 23:46:16 1662771339
- Opted into Steam client beta?: Yes
- Graphics driver version: nvidia 515.65.01
- Gist for SteamVR System Information: [Gist](https://gist.github.com/Corben78/c1c020ad482585f8bb5a9f3c52340fe5)
- Gist for Steam System Information: [Gist](https://gist.github.com/Corben78/52b079fbe6f1634eebaaec2f8145dff5)

**Additional context**
Proton Log with Steam VR beta: [steam-611670.zip](https://github.com/ValveSoftware/SteamVR-for-Linux/files/9540309/steam-611670.zip)

Steam VR System Report (stable): [Gist](https://gist.github.com/Corben78/44e6ea315df5fa54594f8ca7c74424c6)
Proton Log with Steam VR stable (game crashed Steam VR on exit, but game worked): [steam-611670.log](https://github.com/ValveSoftware/SteamVR-for-Linux/files/9540391/steam-611670.log)

**Note:** Commenters who are also experiencing this issue are encouraged to include the "System Information" section in their replies.

**Comment by kisak-valve** [comment]
Hello @Corben78, `terminate called after throwing an instance of 'std::logic_error'`
`  what():  basic_string::_S_construct null not valid` in the Proton log looks like a couple lines of interest.

**Comment by Corben78** [comment]
Looks like with current beta (1.24.5) it works now and doesn't crash.
