### ISSUE TITLE
[BUG] [Linux] After 2 years the settings menu still gets no love.

### ISSUE THREAD

**Issue by Saitek82** [ValveSoftware/SteamVR-for-Linux#544]
[ steamvr-settings window ] If your on linux then most likely the settings window is stuck to a small size.  we cant resize is can't read it... it is straight up unusuable.  this has been broken for 2 years. its slipped off the radar since its not windows steam isn't concerned, 

current problem:
![Screenshot_2022-10-18_17_25_47](https://user-images.githubusercontent.com/51499335/196570842-0903d5e8-4e99-4348-a01f-4cd60c604d0e.png)

    window is 1/6 of the size of your screen. can't see much of the window no settings are usuable
       - no scroll bars. this would help
       - sides can't be adjusted.
       - no max feature.
 it should be just one line of code in the draw window feature it should be easy to fix, its just drawing the window as a fixed frame.   all because the window is set to fixed_size

**Comment by kisak-valve** [comment]
Hello @Saitek82, this issue is already being tracked at #296. Closing as a duplicate.
