### ISSUE TITLE
[BUG] Cannot successfully use OpenXR with OpenGL

### ISSUE THREAD

**Issue by farmboy0** [ValveSoftware/SteamVR-for-Linux#546]
**Describe the bug**
I tried 3 different OpenGL+OpenXR samples that all fail to correctly run.
The samples tried are the following:
1. OpenXR-SDK's hello_xr with OpenGL as graphics parameter set
2. LWJGL3's HelloOpenXRGL demo
3. https://github.com/ChatImproVR/rust-opengl-openxr-example

The first 2 listed are suffering from the fact that they are not looking for
GL_SRGB8 or GL_SRGB8_ALPHA8 which are the only xolor formats
SteamVR's EnumerateSwapchainFormats will return.
But that it is easily fixed but will not make the samples run completely either.

**To Reproduce**
1. Run any of the samples listed above, fixing color format selection like described

**Expected behavior**
I expect the samples to run successfully or at least produce errors why they cant.

**System Information (please complete the following information):**
- Distribution: [Arch/Manjaro/Ubuntu/etc.] Gentoo
- SteamVR version: [E.g. 1.7.2] 1.24
- Steam client version: [build number or date] 19.10.2022 00:56:44
- Opted into Steam client beta?: [Yes/No] No
- Graphics driver version:  [run `nvidia-settings` or `vulkaninfo | grep driverInfo`: Mesa 22.2.2
- Gist for SteamVR System Information: [See [instructions](https://github.com/ValveSoftware/SteamVR-for-Linux/blob/master/CapturingSystemReport.md)] https://gist.github.com/farmboy0/16f79f8c08e6062bb1cf5365963499ce

**Screenshots**

**Additional context**
[xrclient_hello_xr.txt](https://github.com/ValveSoftware/SteamVR-for-Linux/files/9944001/xrclient_hello_xr.txt)
[xrclient_java.txt](https://github.com/ValveSoftware/SteamVR-for-Linux/files/9944002/xrclient_java.txt)
[xrclient_ugly_gl.txt](https://github.com/ValveSoftware/SteamVR-for-Linux/files/9944003/xrclient_ugly_gl.txt)

If there are OpenGL samples that can successfully run I would appreciate it a lot if you could provide them.

**Note:** Commenters who are also experiencing this issue are encouraged to include the "System Information" section in their replies.

**Comment by ChristophHaag** [comment]
There's this bug #421

In https://gitlab.freedesktop.org/monado/demos/openxr-simple-example I worked around it. godot_openxr does too.

**Comment by farmboy0** [comment]
@ChristophHaag Thanks alot

**Comment by cnlohr** [comment]
What version of SteamVR are you using?  We are in the process of pushing a fix for newer SteamVR.

**Comment by farmboy0** [comment]
Im on beta channel so currently running 1.25.1

**Comment by cnlohr** [comment]
@farmboy0, our fix should be in 1.25 (It was a bug from 1.16-1.24).  We are now doing the following:

```c
		m_glxDisplayToRestore = glXGetCurrentDisplay();
		m_glxContextToRestore = glXGetCurrentContext();
		m_glxDrawableToRestore = glXGetCurrentDrawable();
		if( m_glxDisplayToRestore != m_xDisplay || m_glxDrawable != m_glxDrawableToRestore || m_glxContextToRestore != m_glxContext )
			glXMakeCurrent( m_xDisplay, m_glxDrawable, m_glxContext );
```

Can you confirm that you still need to perform the `glXMakeCurrent` command in your app using the current beta?

**Comment by farmboy0** [comment]
I can confirm that
1. hello_xr works partially, it renders to the headset but the desktop window shows only artifacts.
2. The LWJGL3 sample works fine headset and desktop window
3. The rust sample doesnt run anymore with some weird error, thats a cargo error, nothing to do with OpenXR

**Comment by ChristophHaag** [comment]
> hello_xr works partially, it renders to the headset but the desktop window shows only artifacts.

fyi this is normal, the hello_xr desktop window doesn't have any output

**Comment by farmboy0** [comment]
I consider this issue to be resolved, I have no problems anymore using OpenGL with OpenXR
