### ISSUE TITLE
[BUG] Calling the xrDestroyInstance method the application hangs

### ISSUE THREAD

**Issue by pavelk0508** [ValveSoftware/SteamVR-for-Linux#567]
**Describe the bug**
Calling the xrDestroyInstance method the application hangs

**To Reproduce**
1. Download hello_xr
2. Build hello_xr
3. Start hello_xr
4. Close app
5. App is hangs

**Expected behavior**
The application closes without any problems

**System Information (please complete the following information):**
- Distribution: Ubuntu 20.04
- SteamVR version: 1.25.5
- Steam client version: mar 16 2023 
- Opted into Steam client beta?: No
- Graphics driver version:  525.85.05

**Comment by pavelk0508** [comment]
If there is no way to fix it soon, then please show me a way so that xrDestroyInstance does not hangs, if it was possible in the near future.

**Comment by kisak-valve** [comment]
Hello @pavelk0508, this issue is already being tracked at #422. Closing as a duplicate.

**Comment by pavelk0508** [comment]
@kisak-valve it's just that this bug has been around for two years and I would like to know when it will go into operation, but now at least some solution is needed

**Comment by pavelk0508** [comment]
@kisak-valve The problem is in the destructor of the vrclient.so library itself, which is causing the hang. Deleting the dlclose method inside the OpenXRLoader does not reproduce the problem, but the XrInstance is not destroyed either. Please fix it in the next patch, as it is very necessary. Most likely there is some kind of check inside the destructor, on which everything hangs. If there is no way to fix it now, then I would like to know what checks are there in order to remove everything that may cause a hang. Those solutions that were proposed regarding issue on github #422 are not suitable, since a restart of the VR session is needed.

Perhaps this is due to the created threads that are not unloaded on the dlclose
SteamThreadTools::CThreadSyncObject::~CThreadSyncObject()
CHmdSystemLastest::~CHmdSystemLatest()
SteamThreadTools::CThreadSyncObject::Wait(unsigned int)
CSyncLockThread::Run()
SteamThreadTools::CThread::ThreadProc(void*)
