### ISSUE TITLE
[BUG] SteamVR fail 307 on 1.26.1

### ISSUE THREAD

**Issue by DomiStyle** [ValveSoftware/SteamVR-for-Linux#575]
**Describe the bug**
Every single time I launch SteamVR on a KDE Wayland session SteamVR will refuse to start with error code 307.

This only happens on 1.26.1, not on 1.25.7.

**To Reproduce**
1. Update to 1.26.1 (currently in beta)
2. Start SteamVR under a KDE Plasma Wayland session
3. SteamVR won't start due to error 307

**Expected behavior**
SteamVR to launch normally.

**System Information (please complete the following information):**
- Distribution: Fedora
- SteamVR version: 1.26.1
- Steam client version: Mar 24
- Opted into Steam client beta?: No
- Graphics driver version:  [run `nvidia-settings` or `vulkaninfo | grep driverInfo`: Mesa 22.3.7 (LLVM 15.0.7)
- Gist for SteamVR System Information: https://gist.github.com/DomiStyle/82de2b7ac45d54ef64d5ae4bf22f82e1#file-gistfile1-txt

**Note:** Commenters who are also experiencing this issue are encouraged to include the "System Information" section in their replies.

**Comment by kisak-valve** [comment]
Hello @DomiStyle. `ASSERT: "unSize < 65536" at /data/src/common/vrcommon/vrrenderer/vulkanrenderer.cpp:5006` looks like a possible line of interest from vrcompositor.txt.

**Comment by DomiStyle** [comment]
@kisak-valve Thanks, I assume this is something the devs have to take a look at or can I do anything about that?

**Comment by MyBeansAreBaked** [comment]
I was experiencing a similar issue on Hyprland and NixOS, using an AMD GPU, with various combinations of Steam and SteamVR betas. I got errors 306 and 307. They went away by launching steam with environment variables:

```sh
QT_QPA_PLATFORM=xcb SDL_VIDEODRIVER=x11 steam
```

This overrides the values [recommended by Hyprland](https://wiki.hyprland.org/Configuring/Environment-variables/#toolkit-backend-variables)

Though I still experience issue #572, including no games showing up in the menus, but other than that it seems to work now.

**Comment by DomiStyle** [comment]
"Works" on KDE Wayland as well now without any environment variables, but I also run into #572.

**Comment by Danielduel** [comment]
(comming from https://github.com/ValveSoftware/SteamVR-for-Linux/issues/596)
Post-close info:
My steamvr usually worked on 2nd run (1st was always crashing - something like SteamVR Crash with restart headset button (not the 307 error)), the https://github.com/ValveSoftware/SteamVR-for-Linux/issues/575#issuecomment-1562998377 looks like a fix for this problem.

**Comment by MyBeansAreBaked** [comment]
@Danielduel

> My steamvr usually worked on 2nd run (1st was always crashing

I am also experiencing this issue, even with those env vars. First launch runs slow and then crashes every time.

> how you got info about using those flags?

Can't entirely remember, I think I might've seen one of them mentioned in the steam logs. Also reading the Hyprland docs mentions changing the SDL_VIDEODRIVER var to x11 for games with compatibility issues. I basically just tried everything I could think of changing until something worked 😅

I also since realised you can set them as launch options for SteamVR, so it just works without restarting steam or anything.

```
QT_QPA_PLATFORM=xcb SDL_VIDEODRIVER=x11 %command%
```

**Comment by Danielduel** [comment]
With this "1st crash, then works good" - I said it too early.
