### ISSUE TITLE
Is it Possible to Backtrack SteamVR Versions?

### ISSUE THREAD

**Issue by georgewsinger** [ValveSoftware/SteamVR-for-Linux#58]
The library `OSVR-Vive` is currently only compatible with [steamvr-1495066092](https://github.com/OSVR/OSVR-Vive/issues/31) until further fixes are made.

In the meantime, I was curious if it was possible to backtrack to, i.e., steamvr-1495066092 on Linux to make development easier when breaking changes are made?

**Comment by johnv-valve** [comment]
sorry this is not possible
