### ISSUE TITLE
[BUG] Unable to get compositor interface (307)

### ISSUE THREAD

**Issue by Unmoon** [ValveSoftware/SteamVR-for-Linux#580]
**Describe the bug**
SteamVR launches, and displays "SteamVR Fail" (307) error box. Headset (Index) does not display anything, and has no green LEDs. If lighthouses are powered on, tracking seems to work (seeing changes in vrcompositor window, system information below is with no lighthouses/controllers).

Occasionally seems to be able to launch vrcompositor (maybe just on SteamVR 1.25.8 release?).

**To Reproduce**
1. Launch SteamVR.
2. See error.

**Expected behavior**
SteamVR launches without errors, and displays image on the headset.

**System Information (please complete the following information):**
- Distribution: Pop! OS with 6.3.1-060301-generic kernel
- SteamVR version: 1.25.8
- Steam client version: Built: Apt 28 2023, at 18:33:22
- Opted into Steam client beta?: No
- Graphics driver version: Mesa 22.3.5 (LLVM 15.0.6)
- Gist for SteamVR System Information: https://gist.github.com/Unmoon/071dc500633c7247b6e9cb7bb7d94659

**Screenshots**
![image](https://github.com/ValveSoftware/SteamVR-for-Linux/assets/7273082/1bd56dac-4b63-4d23-b418-f2f0e4d691ed)

**Additional context**
Tried a bunch of stuff, unsure with which combinations vrcompositor launches and which doesn't, but all of these resulted in the 307 error.
- X11 or Wayland
- SteamVR release or beta
- 6.2.6 or 6.3.1 kernel (via mainline)
- Different USB ports
- Different DisplayPorts

**Note:** Commenters who are also experiencing this issue are encouraged to include the "System Information" section in their replies.

**Comment by kisak-valve** [comment]
Hello @Unmoon, `GPU Vendor: "llvmpipe (LLVM 15.0.6, 256 bits)" GPU Driver: "1"` in your log is not a healthy sign. Can you completely close Steam, then run `steam` from a terminal and check if that influences SteamVR?

**Comment by Unmoon** [comment]
Hi @kisak-valve good to know there's something obviously wrong. :) I tried running Steam from terminal - got a bit further. Now getting error -203 instead.
Headset still displays nothing, I connected the controllers, but they did not track, and room setup ran at <3FPS.

https://gist.github.com/Unmoon/c628f8f697255fc37b20a3fb7d38331a

**Comment by kisak-valve** [comment]
I would focus on
```
Thu May 11 2023 23:39:27.251206 - Looking for direct display through RandR
Thu May 11 2023 23:39:27.251213 -  - Root 0x3cb
Thu May 11 2023 23:39:27.251253 -    - Output 0x21 - 28 modes, 1 preferred
Thu May 11 2023 23:39:27.251258 -      - Mode 0 0x23 2560x1440 (looking for 2880x1600)
```
Since this is missing a display resolution expected of an HMD, it's possible there's a connection issue or maybe the video cable of the HMD is not physically connected to your video card.

**Comment by Unmoon** [comment]
I unplugged & replugged every cable (including the HMD side), with seemingly no change. It took me a few restarts of SteamVR and replugging the trident cable (which also happened on Windows for as long as I can remember). Error is not -203, but I assume you mean to not focus on that.
https://gist.github.com/Unmoon/3d0c9c8922d0402fda1e6e023ce80588

Also tried plugging HMD to 1st DisplayPort on the GPU (where my monitor was previously). That gave me some artifacting on the vrcompositor I have not noticed before.
https://gist.github.com/Unmoon/125212461d947f9e4957edc57b1c45dc
![image](https://github.com/ValveSoftware/SteamVR-for-Linux/assets/7273082/1fa647a0-1a0e-41f4-a556-f4c6500e04ff)

**Comment by Unmoon** [comment]
Just realized above was on Wayland. Switched to X11, and for a split second I got a message asking if I wanted to change refresh rate from 90, before getting the -203 error again.
https://gist.github.com/Unmoon/877dee9360e8fc340a4bbc8f5a112cdb

**Comment by kisak-valve** [comment]
This is healthier at least:
```
Fri May 12 2023 17:21:26.557194 - Looking for direct display through RandR
Fri May 12 2023 17:21:26.557205 -  - Root 0x6e9
Fri May 12 2023 17:21:26.566783 -    - Output 0x52 - 18 modes, 1 preferred
Fri May 12 2023 17:21:26.566790 -      - Mode 0 0x57 2560x1440 (looking for 2880x1600)
Fri May 12 2023 17:21:26.566806 -    - Output 0x53 - 15 modes, 1 preferred
Fri May 12 2023 17:21:26.566810 -      - Mode 0 0x69 2880x1600 (looking for 2880x1600)
Fri May 12 2023 17:21:26.566815 -        - Found matching output 83
Fri May 12 2023 17:21:26.566820 - Found candidate direct display as RandR output 0x53
Fri May 12 2023 17:21:26.585597 - Tried to find direct display through RandR: 0x202eeb0
Fri May 12 2023 17:21:26.585621 - Trying to match desired rate of 90.000000Hz.
Fri May 12 2023 17:21:26.585631 - 15 modes on display:
Fri May 12 2023 17:21:26.585639 -  - 0: 2880x1600@90.003006Hz
Fri May 12 2023 17:21:26.585647 -  - 1: 2880x1600@144.000000Hz
Fri May 12 2023 17:21:26.585654 -  - 2: 2880x1600@120.019005Hz
Fri May 12 2023 17:21:26.585661 -  - 3: 2880x1600@79.999001Hz
Fri May 12 2023 17:21:26.585667 -  - 4: 1920x1200@90.003006Hz
Fri May 12 2023 17:21:26.585673 -  - 5: 1920x1080@90.003006Hz
Fri May 12 2023 17:21:26.585679 -  - 6: 1600x1200@90.003006Hz
Fri May 12 2023 17:21:26.585685 -  - 7: 1680x1050@90.003006Hz
Fri May 12 2023 17:21:26.585691 -  - 8: 1280x1024@90.003006Hz
Fri May 12 2023 17:21:26.585698 -  - 9: 1440x900@90.003006Hz
Fri May 12 2023 17:21:26.585704 -  - 10: 1280x800@90.003006Hz
Fri May 12 2023 17:21:26.585710 -  - 11: 1280x720@90.003006Hz
Fri May 12 2023 17:21:26.585716 -  - 12: 1024x768@90.003006Hz
Fri May 12 2023 17:21:26.585722 -  - 13: 800x600@90.003006Hz
Fri May 12 2023 17:21:26.585728 -  - 14: 640x480@90.003006Hz
```

**Comment by Unmoon** [comment]
After trying again a few times, things have started working! Managed to do room setup and launch VRChat (although no audio yet).

Thanks a lot! :)
