### ISSUE TITLE
[BUG] SteamVR dashboard and home show no games

### ISSUE THREAD

**Issue by GabMus** [ValveSoftware/SteamVR-for-Linux#581]
**Describe the bug**
As the title says.

Steam beta client; issue happens in SteamVR stable and beta

Games can be started from desktop Steam and work fine

**To Reproduce**

1. Start SteamVR
2. See "No games" message, despite having several installed

**Expected behavior**

I can see the games I have installed from the dashboard

**System Information (please complete the following information):**
- Distribution: Arch
- SteamVR version: 1.25.8 beta
- Steam client version: 1683944175
- Opted into Steam client beta?: Yes
- Graphics driver version:  Mesa 23.0.3 
- Gist for SteamVR System Information: https://gist.github.com/GabMus/f421907e833b4f2329aab40d0a7ae771

**Screenshots**

![image](https://github.com/ValveSoftware/SteamVR-for-Linux/assets/1358527/2940165b-cf1d-40df-b103-186015dd2ff7)

**Additional context**

**Note:** Commenters who are also experiencing this issue are encouraged to include the "System Information" section in their replies.

**Comment by GabMus** [comment]
Update: the issue seems to be gone when opting out of the **desktop steam** beta.

I'm not referring to the SteamVR beta, but to steam proper

**Comment by Lebowski420** [comment]
Can confirm.
Same bug, same environment, same fix.

**Comment by anxest** [comment]
Distribution: Arch
SteamVR version: 1.25.8
Steam client version: native
Opted into Steam client beta?: No

Same bug, but the new steam desktop interface is out of beta now. Using the steam desktop beta branch doesn't fix this.

**Comment by anxest** [comment]
This bug is fixed for me with steamVR beta 1.26.5 (or maybe because I installed the openvr and openxr packages just before my last test)

**Comment by kisak-valve** [comment]
Closing per the last comment.
