### ISSUE TITLE
[BUG] Blank unresponsive window opens with SteamVR

### ISSUE THREAD

**Issue by ClearlyClaire** [ValveSoftware/SteamVR-for-Linux#592]
**Describe the bug**

With the new SteamVR release (1.26.5, Build ID 11591990), in addition to the SteamVR status window, SteamVR opens two windows of the same size on launch: one has the settings, the other remains blank and unresponsive and persists even after quitting and restarting SteamVR, or when exiting Steam.

**To Reproduce**

1. Start SteamVR

**Expected behavior**

SteamVR does not open more windows than necessary and closes any window on exit.

**System Information:**

- Distribution: Debian testing
- SteamVR version: 1.26.5
- Steam client version: 1688685284
- Opted into Steam client beta?: Yes
- Graphics driver version: Mesa 22.3.6
- Gist for SteamVR System Information: https://gist.github.com/ClearlyClaire/4140a24c026a9655db87e01814210f44

**Comment by kisak-valve** [comment]
Hello @ClearlyClaire, this issue is already being tracked at #577. Closing as a duplicate.

**Comment by ClearlyClaire** [comment]
I had not noticed, thanks!
