### ISSUE TITLE
relocation error

### ISSUE THREAD

**Issue by marijnfs** [ValveSoftware/SteamVR-for-Linux#60]
Running my program using the recommended:

          ~/.steam/steam/ubuntu12_32/steam-runtime/run.sh ./a.out        

gets me:
`~/.local/share/Steam/steamapps/common/SteamVR/bin/linux64/vrmonitor: relocation error: /usr/lib/x86_64-linux-gnu/libproxy.so.1: symbol _ZTTNSt7__cxx1119basic_ostringstreamIcSt11char_traitsIcESaIcEEE, version GLIBCXX_3.4.21 not defined in file libstdc++.so.6 with link time reference
`

I have the latest steamvr beta and run debian 9

**Comment by kisak-valve** [comment]
Hello @marijnfs, this error is telling you that the steam runtime's variant of libstdc++.so.6 is too old to be used with the system variant of libproxy.so.1. The quick and dirty workaround is to move or remove the steam runtime variant of libstdc++.so.6 so that it falls through to the system variant.

**Comment by marijnfs** [comment]
So if I get it, there is a supplied version of libstdc++.so.6 with steamvr which doesn't fit the libproxy? I'll try to somehow avoid it and see what happens.

**Comment by marijnfs** [comment]
Thanks, so I changed my run command to the more general

    ~/.steam/bin/steam-runtime/run.sh ./a.out

and moved the libstdc++:

    mv ~/.steam/bin/steam-runtime/amd64/usr/lib/x86_64-linux-gnu/libstdc++.so.6 ~/.steam/bin/steam-runtime/amd64/usr/lib/x86_64-linux-gnu/libstdc++.so.6.bak

And it works! At least I get tracking information, will test if image submitting works as well.
