### ISSUE TITLE
[BUG] Valve Index is completely unusable

### ISSUE THREAD

**Issue by Plarpoon** [ValveSoftware/SteamVR-for-Linux#604]
**Describe the bug**
There are several issues I have noted, will go in order of severity from least bad to worst.

- You cannot boot the computer while having the Valve Index connected.
- When running SteamVR on Wayland it says "A key component of SteamVR isn't working properly." and refuses to do anything else, with black windows that bug out when you resize them on my regular monitors.
- If you switch temporarily to X11 you get a bit further:
![SteamVR](https://github.com/ValveSoftware/SteamVR-for-Linux/assets/40299833/5f5f33fa-5129-4eaa-9d02-c516b35dd3aa)
As you can see (ignoring the Developer Settings which I opened), three random dark boxes open up, I see the preview of SteamVR Home on the desktop but if I use the headset it's completely dark inside, making the device completely unusable.

**To Reproduce**
1. Connect the Valve Index
2. Wait for Steam to download all the dependencies and runtimes
3. Press the VR icon at the top right corner next to my username on Steam
4. Be sad :(

**Expected behavior**
For the Valve Index to display picture and sound allowing me to play something.

**System Information (please complete the following information):**
- Distribution: ArchLinux
- SteamVR version: 1.26.7
- Steam client version: 1690583737 Fri, Jul 28 20:44 UTC -08:00
- Opted into Steam client beta?: No
- Graphics driver version:  Mesa 23.1.6
- Gist for SteamVR System Information: https://gist.github.com/Plarpoon/19f1449bb7b79fa24bd11673e5321ff0

**Screenshots**
I had to post it at the header to explain the issue.

**Additional context**
I never had any of these issues with my old nVidia card, could it be an AMD driver issue?

**Note:** Commenters who are also experiencing this issue are encouraged to include the "System Information" section in their replies.

**Comment by kisak-valve** [comment]
Hello @Plarpoon,

> - When running SteamVR on Wayland it says "A key component of SteamVR isn't working properly." and refuses to do anything else, with black windows that bug out when you resize them on my regular monitors.
> - If you switch temporarily to X11 you get a bit further:

It looks like you're using GNOME/Wayland. This is consistent with the note at https://help.steampowered.com/en/faqs/view/18A4-1E10-8A94-3DDA: `Notably, Gnome Wayland, the default desktop environment for Ubuntu, is not supported as it does not support DRM leasing. Users using Gnome Wayland will need to switch to an alternative window manager/compositor in order to use SteamVR.` (or use GNOME/X11)

Skimming through your system information logs, it looks like you're using an AMD Radeon RX 7900 XTX with the linux 6.4.12 kernel. This combination has been problematic for some other users over at #598. It might be interesting to test how a 6.3.x kernel behaves. Also, I've seen

**Comment by Plarpoon** [comment]
Hello @kisak-valve, so nice to hear of you again! Unfortunately I couldn't make it work, as said before I suspected that wayland could have been an issue so I tested this again on X11. I have also switched to a LTS for my kernel, specifically "Linux 6.1.47-1-lts". Unfortunately I didn't have access to versio 6.3.x that you suggested so I thought that would be the best alternative, but it resulted in a failure behaving exactly like before.. Valve Index being completely black despite pictures showing up on my monitor!

**Comment by Plarpoon** [comment]
I just discovered that I do see something if I move the head around, but both the Valve Index and the application on my monitor showing me what I would see from the Index are utterly broken.

In short terms when I move my head around the black screen breaks up showing me floating rectangles with the actual background in it. But the image is really broken and unusable...

I actually found an exact description in this issue's comments:

![image](https://github.com/ValveSoftware/SteamVR-for-Linux/assets/40299833/e1343388-b0b6-4556-8c63-689ea0f2ecb0)
https://github.com/ValveSoftware/SteamVR-for-Linux/issues/438#issue-838001731 same on desktop
https://github.com/ValveSoftware/SteamVR-for-Linux/issues/438#issuecomment-1149462001 same on Valve Index

Considering this issue has been opened in March 2021 and still has to get closed it's not reassuring for my situation at all unfortunately.. oh well..

**Comment by Plarpoon** [comment]
Since this now looks like a duplicate I am going to move everything to https://github.com/ValveSoftware/SteamVR-for-Linux/issues/438

Still, want to thank you a lot for your time @kisak-valve!
