### ISSUE TITLE
[BUG] Error 496 "Failed to connect to headset display"

### ISSUE THREAD

**Issue by CobaltSpace** [ValveSoftware/SteamVR-for-Linux#605]
**Describe the bug**
When I try to launch SteamVR, I get error 496.

**To Reproduce**
1. Plug in Valve Index
2. Launch SteamVR

**Expected behavior**
The displays on the headset to come on, and no error

**System Information (please complete the following information):**
- Distribution: Arch
- SteamVR version: 1.27.3
- Steam client version: Fri, Jul 28 11:44 AM UTC -08:00
- Opted into Steam client beta?: No
- Graphics driver version:  Mesa 23.1.6
- Gist for SteamVR System Information: https://gist.github.com/CobaltSpace/51ed8ead9740ec21876b069047235e6d
- Wayland compositor: Hyprland v0.28.0
- `uname -r`: 6.4.12-zen1-1-zen

**Screenshots**
![2023-08-26T15:59:05,418349162-07:00](https://github.com/ValveSoftware/SteamVR-for-Linux/assets/11732577/24a3aba5-0cf0-485e-9311-2f7ffda99af6)

**Additional context**
Switching from beta to non-beta SteamVR, I get the SteamVR Compositor window on my screen and am told to enable direct display mode.

- SteamVR version: 1.26.7
- Gist for SteamVR System Information: https://gist.github.com/CobaltSpace/974d7c05327be885a43c1e04b8934d11

Using the same ports, the headset works on windows. Monado is also able to use the headset. Monado was tested after collecting the system reports, not before.

**Note:** Commenters who are also experiencing this issue are encouraged to include the "System Information" section in their replies.

**Comment by CobaltSpace** [comment]
Make sure you have radv set as your driver.

**Comment by Beyley** [comment]
I am also getting this error, even with RADV set as my driver

```
System Information:
    Distribution: Arch
    SteamVR version: 1.27.5
    Steam client version: 1696019606 Fri, Sep 29 10:38 AM UTC -08:00
    Opted into Steam client beta?: No
    Graphics driver version: Mesa 23.2.1
    Gist for SteamVR System Information: https://gist.github.com/Beyley/91cd316f58738233d139355bea26581a
    Wayland compositor: Plasma 5.27.8
    uname -r: 6.5.6-zen2-1-zen
```

**Comment by AnOpenSauceDev** [comment]
Same error with ALVR too after switching to Void Linux. I'm using an NVIDIA 3060 Ti on driver 560.
