### ISSUE TITLE
[BUG] "Ghost Windows"

### ISSUE THREAD

**Issue by 2-3-5-41** [ValveSoftware/SteamVR-for-Linux#608]
**Describe the bug**
When starting steamvr, there will be entirely blank windows that spawn as steamvr starts up, I can not find them in system monitor, and htop seems to not show them either. These "ghost windows" also outlive steamvr and don't close when steamvr closes, and any attempt to manually close them does nothing as they are stuck as "not responding".

**To Reproduce**
1. Start SteamVR *beta* (may need to do this a few times)
2. Observe a blank, no title window
3. Attempt and fail to close said window
4. Try to find it in htop or system monitor (in plasma DE)

**Expected behavior**
These "ghost windows" shouldn't exist in the first place.

**System Information (please complete the following information):**
- Distribution: Arch
- SteamVR version: beta 1.27.5
- Steam client version: 1693527575 
- Opted into Steam client beta?: Yes
- Graphics driver version:  Mesa 23.1.6-arch1.4:
- Gist for SteamVR System Information: [gist](https://gist.github.com/2-3-5-41/3334ee26da4453f8af458ac0bb20bdf6)

**Screenshots**
_Screenshot shows two windows, after opening steamvr multiple times, one with no title and the other with "<2>" as it's title, both not found in any "task manager"_.
![image](https://github.com/ValveSoftware/SteamVR-for-Linux/assets/93025618/9d76f544-93d9-4961-946b-610bddf75a43)

**Additional context**
n/a

**Note:** Commenters who are also experiencing this issue are encouraged to include the "System Information" section in their replies.

**Comment by kisak-valve** [comment]
Hello @2-3-5-41, this issue is already being tracked at #577. Closing as a duplicate.
