### ISSUE TITLE
[BUG] SteamVR 2.0 Beta - still seeing the old UI

### ISSUE THREAD

**Issue by LiamDawe** [ValveSoftware/SteamVR-for-Linux#614]
**Describe the bug**
I am opting into Steam Beta and SteamVR Beta, all up to date, files verified and I'm still seeing the original UI instead of the new one built for SteamVR 2.0.

**System Information (please complete the following information):**
- Distribution: Kubuntu
- SteamVR version: 2.0.1
- Steam client version: 1695679261
- Opted into Steam client beta?: Yes
- Graphics driver version:  Mesa 23.1.8
- VR system report: 
[SteamVR-2023-09-26-AM_11_08_16.txt](https://github.com/ValveSoftware/SteamVR-for-Linux/files/12726135/SteamVR-2023-09-26-AM_11_08_16.txt)

**Comment by TTimo** [comment]
With #617 fixed, the new UI should come up now.

**Comment by DomiStyle** [comment]
@TTimo My UI is still the old one with SteamVR and Steam client beta.

I'm also getting https://github.com/ValveSoftware/SteamVR-for-Linux/issues/623 on KDE Plasma with Wayland. Proton games work but SteamVR Home and Half-Life Alyx are broken.

**Comment by LiamDawe** [comment]
Cannot retest due to it not loading at all https://github.com/ValveSoftware/SteamVR-for-Linux/issues/618

**Comment by Nullmatic** [comment]
I still cannot see the new UI on beta version 2.0.8 on my system. I was able to see it before on 2.0.1 but after that, nope.

**System Information (If needed)**
- Kernel: 6.5.8
- Distro: Arch Linux
- SteamVR: 2.0.8
- Steam Client: 1698185488
- Opted into Steam client beta?: Yep
- Graphics Driver: Mesa 23.2.1
- VR System Report: [SteamVR-2023-10-24-PM_08_17_58.txt](https://github.com/ValveSoftware/SteamVR-for-Linux/files/13155726/SteamVR-2023-10-24-PM_08_17_58.txt)

**Comment by ClearlyClaire** [comment]
I also have the old interface, as well as the following SteamVR message, despite having the latest Steam Client Beta:
![image](https://github.com/ValveSoftware/SteamVR-for-Linux/assets/384364/6009987b-8b5f-4128-b5ae-bd50ec840204)

**Comment by FriederHannenheim** [comment]
Can confirm this is happening to me as well
Distro: LMDE 6
Kernel: Linux 6.1
Desktop: XFCE4
CPU: Ryzen 5600G
GPU: Radeon 6700XT
Dual Monitor

**Comment by ThaSwapMeetPimp** [comment]
Same as ClearlyClaire, here. Old UI and Steam Beta Client message.

**Comment by 2-3-5-41** [comment]
Old UI is still shown on the stable release of 2.0.8 that came out today on Oct 25, 2023

**Comment by megagtrwrath** [comment]
Issue seems to be resolved with todays 2.0.10 update. It does have a strange colour shift, but functions properly.
Could use more testing to confirm

![image](https://github.com/ValveSoftware/SteamVR-for-Linux/assets/16152534/491652bf-a96d-44f3-88db-431e62005c76)

System Information (please complete the following information):
Distribution: Arch
SteamVR version: 2.0.10 (Beta)
Steam client version: 1698705032
Opted into Steam client beta?: Yes
Graphics driver version: 545.23.06
Gist for SteamVR System Information: https://gist.github.com/megagtrwrath/b4e6124fec30cd8dc95af43d958055e8

**Comment by LiamDawe** [comment]
Yup same, loads up now (hooray!) but also seeing the flipped colours on Kubuntu 23.10 with Mesa 23.2.1.

**Comment by siren15** [comment]
Running 2.0.10 beta as well and the new UI loads and works, it's bit choppy and has the weird colour shift as well. Haven't noticed any other bugs.

![Screenshot from 2023-11-01 15-27-03](https://github.com/ValveSoftware/SteamVR-for-Linux/assets/65129243/19726791-075d-46f1-9e21-f8439e6575c1)

**System Information:**
Distribution: Nobara 38 (Gnome DE X11 Session)
SteamVR version: 2.0.10 (beta)
Steam client version: 1698775809
Opted into Steam client beta?: Yes
Graphics driver version: 4.6.0 NVIDIA 535.113.01
SteamVR System Information:  [SteamVR-2023-11-01-PM_03_31_27.txt](https://github.com/ValveSoftware/SteamVR-for-Linux/files/13228173/SteamVR-2023-11-01-PM_03_31_27.txt)

**Comment by kisak-valve** [comment]
Closing as fixed.
