### ISSUE TITLE
[BUG] SteamVR Beta causing steam beta client to crash

### ISSUE THREAD

**Issue by megagtrwrath** [ValveSoftware/SteamVR-for-Linux#617]
**Describe the bug**
Steam VR Beta 2.0.1 and 2.0.2 cause the Steam Beta Client to crash repeatedly until SteamVR is closed.
Could be related to https://github.com/ValveSoftware/SteamVR-for-Linux/issues/614 as old UI is also showing

**To Reproduce**
1. Open Steam
2. Open SteamVR
3. Steam proceeds to crash
4. Steam proceeds to reopen itself
5. Steam crashes again
6. 3-5 repeat until SteamVR is closed

**Expected behavior**
SteamVR shows either new or old UI without causing the Steam Beta client to crash

**System Information (please complete the following information):**
- Distribution: Arch [KDE Wayland]
- SteamVR version: 2.0.1 and 2.0.2
- Steam client version: 1695679261 [Beta]
- Opted into Steam client beta?: Yes
- Graphics driver version:  535.113.0.1
- Gist for SteamVR System Information: https://gist.github.com/megagtrwrath/f85555ed9ae7d978dd862c7d7120687a

**Screenshots**

**Additional context**
Checking Journalctl, I found this record that might be of help

Process 238100 (steamwebhelper) of user 1000 dumped core.
                                                   
                                                   Stack trace of thread 238100:
                                                   #0  0x000000000050e401 n/a (/home/Mega/.local/share/Steam/ubuntu12_64/steamwebhelper>
                                                   ELF object binary architecture: AMD x86-64

It may be possible this crash is caused by the closer link between SteamVR and the Steam Client caused by the UI update.

Crash does not happen on the non-beta Steam Client with 2.0.1 or 2.0.2

**Note:** Commenters who are also experiencing this issue are encouraged to include the "System Information" section in their replies.

**Comment by mSparks43** [comment]
+1 (X11,  535.113.0.1)

Any chance of making 1.27 permanently available in place of or in addition to 1.14, 1.27 isn't perfect but it can at least be used.

very borken

Process 58788 (vrwebhelper) of user 1000 dumped core.
                                                               
                                                               Module /run/host/usr/lib64/libvulkan_radeon.so from rpm mesa-23.1.7-1.fc38.x86_64
                                                               Module /run/host/usr/lib64/libvulkan_lvp.so from rpm mesa-23.1.7-1.fc38.x86_64
                                                               Module /run/host/usr/lib64/libvulkan_intel.so from rpm mesa-23.1.7-1.fc38.x86_64
                                                               Module /run/host/usr/lib64/libvulkan_intel_hasvk.so from rpm mesa-23.1.7-1.fc38.x86_64
                                                               Module /run/host/usr/lib64/libVkLayer_MESA_device_select.so from rpm mesa-23.1.7-1.fc38.x86_64
                                                               Module /run/host/usr/lib64/libelf-0.189.so from rpm elfutils-0.189-3.fc38.x86_64
                                                               Module /run/host/usr/lib64/libedit.so.0.0.70 from rpm libedit-3.1-45.20221030cvs.fc38.x86_64
                                                               Module /run/host/usr/lib64/libunwind.so.8.0.1 from rpm libunwind-1.6.2-7.fc38.x86_64
                                                               Module /run/host/usr/lib64/libvulkan.so.1.3.243 from rpm vulkan-loader-1.3.243.0-1.fc38.x86_64
                                                               Module /run/host/usr/lib64/libdrm_amdgpu.so.1.0.0 from rpm libdrm-2.4.114-2.fc38.x86_64
                                                               Module /run/host/usr/lib64/libxshmfence.so.1.0.0 from rpm libxshmfence-1.3-12.fc38.x86_64
                                                               Module /run/host/usr/lib64/libxcb-randr.so.0.1.0 from rpm libxcb-1.13.1-11.fc38.x86_64
                                                               Module /run/host/usr/lib64/libxcb-sync.so.1.0.0 from rpm libxcb-1.13.1-11.fc38.x86_64
                                                               Module /run/host/usr/lib64/libxcb-xfixes.so.0.0.0 from rpm libxcb-1.13.1-11.fc38.x86_64
                                                               Module /run/host/usr/lib64/libxcb-present.so.0.0.0 from rpm libxcb-1.13.1-11.fc38.x86_64
                                                               Module /run/host/usr/lib64/libxcb-glx.so.0.0.0 from rpm libxcb-1.13.1-11.fc38.x86_64
                                                               Module /run/host/usr/lib64/libGLdispatch.so.0.0.0 from rpm libglvnd-1.6.0-2.fc38.x86_64
                                                               Module /run/host/usr/lib64/libGLX.so.0.0.0 from rpm libglvnd-1.6.0-2.fc38.x86_64
                                                               Module /run/host/usr/lib64/libGL.so.1.7.0 from rpm libglvnd-1.6.0-2.fc38.x86_64
                                                               Module /run/host/usr/lib64/libidn2.so.0.3.8 from rpm libidn2-2.3.4-2.fc38.x86_64
                                                               Module /run/host/usr/lib64/libxcb-shm.so.0.0.0 from rpm libxcb-1.13.1-11.fc38.x86_64
                                                               Module /run/host/usr/lib64/libzstd.so.1.5.5 from rpm zstd-1.5.5-1.fc38.x86_64
                                                               Module /run/host/usr/lib64/libpcre2-8.so.0.11.2 from rpm pcre2-10.42-1.fc38.1.x86_64
                                                               Module /run/host/usr/lib64/libselinux.so.1 from rpm libselinux-3.5-1.fc38.x86_64
                                                               Module /run/host/usr/lib64/libz.so.1.2.13 from rpm zlib-1.2.13-3.fc38.x86_64
                                                               Module /run/host/usr/lib64/libXau.so.6.0.0 from rpm libXau-1.0.11-2.fc38.x86_64
                                                               Module /run/host/usr/lib64/libdrm.so.2.4.0 from rpm libdrm-2.4.114-2.fc38.x86_64
                                                               Module /run/host/usr/lib64/libffi.so.8.1.2 from rpm libffi-3.4.4-2.fc38.x86_64
                                                               Module /run/host/usr/lib64/libexpat.so.1.8.10 from rpm expat-2.5.0-2.fc38.x86_64
                                                               Module /run/host/usr/lib64/libxcb-dri3.so.0.0.0 from rpm libxcb-1.13.1-11.fc38.x86_64
                                                               Module /run/host/usr/lib64/libX11-xcb.so.1.0.0 from rpm libX11-1.8.6-1.fc38.x86_64
                                                               Module /run/host/usr/lib64/libwayland-client.so.0.22.0 from rpm wayland-1.22.0-1.fc38.x86_64
                                                               Module /run/host/usr/lib64/libXfixes.so.3.1.0 from rpm libXfixes-6.0.0-5.fc38.x86_64
                                                               Module /run/host/usr/lib64/libXext.so.6.4.0 from rpm libXext-1.3.5-2.fc38.x86_64
                                                               Module /run/host/usr/lib64/libX11.so.6.4.0 from rpm libX11-1.8.6-1.fc38.x86_64
                                                               Module /run/host/usr/lib64/libgamemodeauto.so.0.0.0 from rpm gamemode-1.7-2.fc38.x86_64
                                                               Stack trace of thread 58788:
                                                               #0  0x00007fdff0e03824 n/a (/home/msparks/.local/share/Steam/steamapps/common/SteamVR/bin/vrwebhelper/linux64/libcef.so + 0x1c03824)
                                                               #1  0x00007fdff0e06d1d n/a (/home/msparks/.local/share/Steam/steamapps/common/SteamVR/bin/vrwebhelper/linux64/libcef.so + 0x1c06d1d)
                                                               #2  0x00007fdff0e0c3ea n/a (/home/msparks/.local/share/Steam/steamapps/common/SteamVR/bin/vrwebhelper/linux64/libcef.so + 0x1c0c3ea)
                                                               #3  0x00007fdff157e4db n/a (/home/msparks/.local/share/Steam/steamapps/common/SteamVR/bin/vrwebhelper/linux64/libcef.so + 0x237e4db)
                                                               #4  0x00007fdff1583ab6 n/a (/home/msparks/.local/share/Steam/steamapps/common/SteamVR/bin/vrwebhelper/linux64/libcef.so + 0x2383ab6)
                                                               #5  0x00007fdff1585b78 n/a (/home/msparks/.local/share/Steam/steamapps/common/SteamVR/bin/vrwebhelper/linux64/libcef.so + 0x2385b78)
                                                               #6  0x00007fdff158730f n/a (/home/msparks/.local/share/Steam/steamapps/common/SteamVR/bin/vrwebhelper/linux64/libcef.so + 0x238730f)
                                                               #7  0x00007fdff4b05b07 n/a (/home/msparks/.local/share/Steam/steamapps/common/SteamVR/bin/vrwebhelper/linux64/libcef.so + 0x5905b07)
                                                               #8  0x00007fdff4698914 n/a (/home/msparks/.local/share/Steam/steamapps/common/SteamVR/bin/vrwebhelper/linux64/libcef.so + 0x5498914)
                                                               #9  0x00007fdff469c85d n/a (/home/msparks/.local/share/Steam/steamapps/common/SteamVR/bin/vrwebhelper/linux64/libcef.so + 0x549c85d)
                                                               #10 0x00007fdff46b185e n/a (/home/msparks/.local/share/Steam/steamapps/common/SteamVR/bin/vrwebhelper/linux64/libcef.so + 0x54b185e)
                                                               #11 0x00007fdff46b171c n/a (/home/msparks/.local/share/Steam/steamapps/common/SteamVR/bin/vrwebhelper/linux64/libcef.so + 0x54b171c)
                                                               #12 0x00007fdff469fd18 n/a (/home/msparks/.local/share/Steam/steamapps/common/SteamVR/bin/vrwebhelper/linux64/libcef.so + 0x549fd18)
                                                               #13 0x00007fdff454e3e2 n/a (/home/msparks/.local/share/Steam/steamapps/common/SteamVR/bin/vrwebhelper/linux64/libcef.so + 0x534e3e2)
                                                               #14 0x00007fdff216dfe1 n/a (/home/msparks/.local/share/Steam/steamapps/common/SteamVR/bin/vrwebhelper/linux64/libcef.so + 0x2f6dfe1)
                                                               #15 0x00007fdff216a3c0 n/a (/home/msparks/.local/share/Steam/steamapps/common/SteamVR/bin/vrwebhelper/linux64/libcef.so + 0x2f6a3c0)
                                                               #16 0x00007fdff216b8da n/a (/home/msparks/.local/share/Steam/steamapps/common/SteamVR/bin/vrwebhelper/linux64/libcef.so + 0x2f6b8da)
                                                               #17 0x00007fdff4d2a77b n/a (/home/msparks/.local/share/Steam/steamapps/common/SteamVR/bin/vrwebhelper/linux64/libcef.so + 0x5b2a77b)
                                                               #18 0x00007fdff36132a6 n/a (/home/msparks/.local/share/Steam/steamapps/common/SteamVR/bin/vrwebhelper/linux64/libcef.so + 0x44132a6)
                                                               #19 0x00007fdff3623cec n/a (/home/msparks/.local/share/Steam/steamapps/common/SteamVR/bin/vrwebhelper/linux64/libcef.so + 0x4423cec)
                                                               #20 0x00007fdff35dcd27 n/a (/home/msparks/.local/share/Steam/steamapps/common/SteamVR/bin/vrwebhelper/linux64/libcef.so + 0x43dcd27)
                                                               #21 0x00007fdfee4c8e6b n/a (/usr/lib/x86_64-linux-gnu/libglib-2.0.so.0.6600.8 + 0x51e6b)
                                                               ELF object binary architecture: AMD x86-64

**Comment by Danielduel** [comment]
Freshly updated Arch, kde wayland, amd stack, latest beta steam vr with latest steam client beta.

Running SteamVR opens SteamVR, but Steam client starts a restart loop.

Resigning from steam client beta solves this issue.

**Comment by megagtrwrath** [comment]
SteamVR Beta 2.0.3 and Steam Beta Client [1696379367] no longer has crashing client issue for me, however it is now preventing my headset from connecting to SteamVR [Error 496], meaning it is still effectively unusable for me at this time.

**Comment by TTimo** [comment]
The CEF crashes are fixed in latest Steam beta client. Please make sure to report other issues separately (or find the existing reports).
