### ISSUE TITLE
[BUG] estrength error message overlay in new Dashboard with bridged networking

### ISSUE THREAD

**Issue by RedstoneLP2** [ValveSoftware/SteamVR-for-Linux#621]
**Describe the bug**
There's a (truncated version) of the "estrength" error message appearing in the horizontal bar of the new dashboard when using bridged networking

**To Reproduce**
1. Install the SteamVR beta (2.0.2 at the time of writing)
2. Have one of the network setups noted in the linked issue (in my case bridged)
3. Start SteamVR
4. Open Dashboard
5. Observe "Something went wrong" message in the horizontal bar

**Expected behavior**
Not getting the "Something went wrong" message

**System Information (please complete the following information):**
- Distribution: Arch
- SteamVR version: Beta 2.0.2
- Steam client version: 1696379367
- Opted into Steam client beta?: Yes
- Graphics driver version:  [run `nvidia-settings` or `vulkaninfo | grep driverInfo`:
`
         driverInfo      = Mesa 23.1.7-arch1.1
	 driverInfo                                           = Mesa 23.1.7-arch1.1
`
- Gist for SteamVR System Information: [See [instructions](https://github.com/ValveSoftware/SteamVR-for-Linux/blob/master/CapturingSystemReport.md)]
https://gist.github.com/RedstoneLP2/e1864f6b8d81bc135321e06da3538151

**Screenshots**

https://cdn.discordapp.com/attachments/548112051403227146/1159134010480541866/1696429462155.jpg?ex=651ec72b&is=651d75ab&hm=af5c7d0f832e0d4ca1d234e7ebb02ea36e799cbf14b1150356a17875b0f32981&

**Additional context**
This seems to be the same issue as [over on steam-for-linux](https://github.com/ValveSoftware/steam-for-linux/issues/9122).
As with that issue not using any of the network setups mentioned in the issue linked above makes the issue disappear.

**Note:** Commenters who are also experiencing this issue are encouraged to include the "System Information" section in their replies.

**Comment by kisak-valve** [comment]
Hello @RedstoneLP2, this is a Steam client issue. As long as https://github.com/ValveSoftware/steam-for-linux/issues/9122 is open, there's no point in tracking the same issue on SteamVR's side.

Closing in favor of the older issue report.
