### ISSUE TITLE
[BUG] VR Can't see my HTC vive controllers

### ISSUE THREAD

**Issue by jon-bit** [ValveSoftware/SteamVR-for-Linux#625]
**Describe the bug**

**To Reproduce**
1. use steam tinker luach on games(it did not make a difference if I did not but for the record)
2. Lunch steam VR (flatpak, X11, cinnamon, 2.0.6)
3. The controllers are on the ground in a game that starts up, but for games where they have to be configured no.
**Expected behavior**

**System Information (please complete the following information):**
- Distribution: mint(Slightly modified to my liking) 
- SteamVR version: 2.0.6
- Steam client version: Sep 29
- Opted into Steam client beta?: Yes (did not fix it)
- Graphics driver version:  Mesa 23.2.1 
- Gist for SteamVR System Information: [does not crash. Just doesn't react o my controllers]

**Additional context**
It seems to me that is just does not see the controlers but they are 100% on the steam VR menu.

**Comment by jon-bit** [comment]
UPDATE: So the room VR DID work, most of the VR games I own however DID NOT work. At this point I am very confused any ideas anyone?

**Comment by jon-bit** [comment]
UPDATE: Reinstalled steam and nothing happened.

**Comment by jon-bit** [comment]
FIX: The new proton experimental does NOT work with some VR tittles. I have fixed this. Use proton 7 or 8(But I have not tested 8 yet).

**Comment by alasky17** [comment]
@jon-bit Did you close this because VR titles are working for you with experimental again?  I just want to confirm that we already fixed the failure :)

**Comment by digitalcircuit** [comment]
I *think* I ran into this with SteamVR 2.0.8, Proton 8.x (`proton-8.0-4b`) versus Proton Experimental (`experimental-8.0-20231019`) on [Mothergunship: Forge](https://store.steampowered.com/app/1931240/MOTHERGUNSHIP_FORGE/ ). 

Proton Experimental did not show any controllers and I couldn't interact with menus, though I could look around with my headset.

Proton 8.x showed my controllers and the game worked normally.

Kubuntu 22.04 LTS, Steam installed via Debian package, HTC Vive headset (with default Vive Wands).  If there's any additional details that would help, let me know!  Or I can file a new issue if preferred.

**Comment by alasky17** [comment]
@digitalcircuit That is all the information I need, thank you!  There is already an issue for this game in the Proton tracker (which I think is the correct place for this report), so I'll ask for this to be transferred over there for future reference.  For now, I have all the info I need (unless @jon-bit was describing a different regression, in which case it would be helpful for me to still hear if this is happening for them with current experimental :)

**Comment by kisak-valve** [comment]
Hello @digitalcircuit, it looks like there's a near match to a compatibility report of a years older game in the same franchise, but not for that specific game title. Please open a new compatibility report on the Proton issue tracker for that game so that your feedback can be tracked properly.

Convenience link: https://github.com/ValveSoftware/Proton/issues/new?&template=compatibility-report.md

**Comment by alasky17** [comment]
@digitalcircuit This regression should be fixed in the most recent experimental release.  Please open a new compatibility report for the game  and tag me if you are still seeing the regression :)

**Comment by digitalcircuit** [comment]
@alasky17 A quick test with Proton Experimental `experimental-8.0-20231107` confirms Mothergunship: Forge behaves as expected - thanks!

If I run into any other issues, I'll file a new compatibility report.

**Comment by jon-bit** [comment]
@alasky17 sorry for the late reply last few weeks have been a nightmare. I have not tested with the new experimental but I will give it a try in at least the next 2 days. I got a few titles to do.
