### ISSUE TITLE
[BUG] SteamVR Beta 2.0.1 through current release does not launch, is hanging on executing vrsetup.sh

### ISSUE THREAD

**Issue by ThaSwapMeetPimp** [ValveSoftware/SteamVR-for-Linux#626]
**Describe the bug**
SteamVR Beta 2.0.1 through current release does not launch, hasnt since release. It says its running but the window never pops up. SteamVRLauncherSetup.log shows it hanging on "vrenv.sh[142517]: exec /home/[username]/.steam/debian-installation/steamapps/common/SteamVR/bin/vrsetup.sh"

**To Reproduce**
1. Go to 'SteamVR' in library, while on beta Channel for both Steam and SteamVR
2. Click on 'Launch'

**Expected behavior**
SteamVR Beta 2.0.x to launch.

**System Information (please complete the following information):**
- Distribution: Ubuntu-Studio 22.04
- SteamVR version: 2.0.1 through current release
- Steam client version: 1697508377 
- Opted into Steam client beta?: Yes
- Graphics driver version:  NVIDIA 535.113.01
- Gist for SteamVR System Information: Cant access that in 2.01 through current, as SteamVR hangs before the window pops up. Let me know if you need any of the info that would be generated in a 1.27.5 system report and I will post a gist.

**Screenshots**

**Additional context**
The fixes for some linux systems in one of the updates did not work for my system, though one time only on 2.0.4 i got it to open on Stable with a Failure to connect to window manager error and just vr space in the HMD, was able to run Contractors VR through the dashboard, and when I exited it opened SteamVR Home even though it wouldnt run it when I started the program, then it was updated the next day and stopped even doing that. 

**Note:** Commenters who are also experiencing this issue are encouraged to include the "System Information" section in their replies.

**Comment by ThaSwapMeetPimp** [comment]
Using the updated script from the other thread, now only getting failure to connect to window manager error. Closing.

**Comment by waltercool** [comment]
Can you provide that script or link to thread?
