### ISSUE TITLE
[BUG] Only play an OpenXR/VR title once.

### ISSUE THREAD

**Issue by 2-3-5-41** [ValveSoftware/SteamVR-for-Linux#627]
**Describe the bug**
When you first start SteamVR and start a game, after that game closes or crashes, you can no longer start that game back up. 

The way I've found to recover from this is to restart SteamVR before trying to restart the game that crashed or needed a restart.

**To Reproduce**
1. Go to any game.
2. Run it.
3. Let it crash, or close and restart it.
4. Notice it crashes at the point that OpenXR/VR is initialized in the game.

**Expected behavior**
The game should be able to hook back into SteamVR without crashing on start.

**System Information (please complete the following information):**
- Distribution: Arch
- SteamVR version: `1.27.5`
- Steam client version: `1697843490`
- Opted into Steam client beta?: Yes
- Graphics driver version:  [run `nvidia-settings` or `vulkaninfo | grep driverInfo`: `2023.Q3.3 (LLPC)`
- Gist for SteamVR System Information: [System Information](https://gist.github.com/2-3-5-41/ffa9005b44745d9c49c31ee26a4f81ec)

**Screenshots**

**Additional context**
Here is the backtrace from a project I was working on that uses OpenXR which lead me to believe this issue may be coming from SteamVR directly:

```
================================================================
handle_crash: Program crashed with signal 11
Engine version: Godot Engine v4.1.2.stable.arch_linux
Dumping the backtrace. Please include this when reporting the bug to the project developer.
[1] /usr/lib/libc.so.6(+0x3e710) [0x7fab7e76f710] (??:0)
[2] /home/smol/.local/share/Steam/steamapps/common/SteamVR/bin/linux64/vrclient.so(+0x268288) [0x7fab6ea68288] (??:0)
[3] /home/smol/.local/share/Steam/steamapps/common/SteamVR/bin/linux64/vrclient.so(+0x1af41a) [0x7fab6e9af41a] (??:0)
[4] /home/smol/.local/share/Steam/steamapps/common/SteamVR/bin/linux64/vrclient.so(+0x246219) [0x7fab6ea46219] (??:0)
[5] /usr/lib/libc.so.6(+0x8c9eb) [0x7fab7e7bd9eb] (??:0)
[6] /usr/lib/libc.so.6(+0x1107cc) [0x7fab7e8417cc] (??:0)
-- END OF BACKTRACE --
================================================================
```

**Note:** Commenters who are also experiencing this issue are encouraged to include the "System Information" section in their replies.

**Comment by ChristophHaag** [comment]
Not entirely clear from the backtrace without function names but it could be the same as https://github.com/ValveSoftware/SteamVR-for-Linux/issues/479

**Comment by 2-3-5-41** [comment]
This does look like a duplicate, sorry about that.
