### ISSUE TITLE
[BUG] No more SteamVR overlay

### ISSUE THREAD

**Issue by 2-3-5-41** [ValveSoftware/SteamVR-for-Linux#632]
**Describe the bug**
SteamVR overlay no longer renders.

**To Reproduce**
1. Update to SteamVR 2.0.10 (stable)

**Expected behavior**
SteamVR overlay renders, I don't care if it's the obsolete one.

**System Information (please complete the following information):**
- Distribution: Arch
- SteamVR version: 2.0.10
- Steam client version: 1698890449
- Opted into Steam client beta?: Yes
- Graphics driver version:  [run `nvidia-settings` or `vulkaninfo | grep driverInfo`: 2023.Q4.1 (LLPC)
- Gist for SteamVR System Information: [gist](https://gist.github.com/2-3-5-41/1f3a540a27086c2acbefa25bbd3327a8)

**Screenshots**

**Additional context**

**Note:** Commenters who are also experiencing this issue are encouraged to include the "System Information" section in their replies.

**Comment by 2-3-5-41** [comment]
Quick question; how long will the SteamVR team leave up the 1.27.5 temp beta branch for SteamVR? It's gonna be my only real fallback that isn't the SteamVR 1.14 branch.

**Comment by Korysovec** [comment]
Same issue, renders on 1.27.5. Works on Steam Deck, heard of same issue also on Arch from one other person.

Distribution: Arch
SteamVR version: 2.0.10
Steam client version: 1698777785
Opted into Steam client beta?: No
Graphics driver version: 23.2.1-2
Gist for SteamVR System Information: [link](https://gist.github.com/Korysovec/9bbe1de297b2b341b8af2b0abdfb029a)

**Comment by Dreaming-Codes** [comment]
I'm experiencing a related issue. Sometimes the program manages to open, but then it freezes momentarily. Steam (not SteamVR) crashes on my PC, briefly displaying the new UI on the headset before it disappears. I suspect this may be related to Nvidia hardware acceleration. Could you please add an option to force the use of the old UI?

**Comment by Danielduel** [comment]
Hello @Dreaming-Codes, @Korysovec (could you pass it to that person if you have contact to them), @2-3-5-41
I've fixed this issue using this - https://github.com/ValveSoftware/SteamVR-for-Linux/issues/637
If it fixes your issue - could you comment what compositor you are using under that issue?

**Comment by Dreaming-Codes** [comment]
> Hello @Dreaming-Codes, @Korysovec (could you pass it to that person if you have contact to them), @2-3-5-41
> I've fixed this issue using this - https://github.com/ValveSoftware/SteamVR-for-Linux/issues/637
> (no SteamVR desktop UI and no SteamVR in-vr UI)
> If it fixes your issue - could you comment what compositor you are using under that issue? 

I've fixed my issue using Nvidia prime since I'm on an Optimus laptop, I'm on hyprland.

**Comment by Dreaming-Codes** [comment]
I'm encountering this issue again

**Comment by 2-3-5-41** [comment]
Took me long enough to figure out; If You're on AMD graphics card(s), make sure steam is running under Mesa(RADV) drivers for the steam overlay to be able to use DRM. And for Nvidia graphics cards, you too should make sure steam in running under a graphics driver that allows for DRM on your GPU.

**Note:**
This will make all games also run under RADV unless you specify a different driver in the launch commands.
