### ISSUE TITLE
[BUG] Exiting SteamVR Beta 2.1.1 causes Steam client to pop up random windows

### ISSUE THREAD

**Issue by wallcarpet40** [ValveSoftware/SteamVR-for-Linux#634]
**Describe the bug**
When exiting SteamVR beta 2.1.1, it causes Steam client to pop-up random windows and sometimes causes Steam overlay to stay black with error message displayed instead.

**To Reproduce**
1. Start SteamVR Beta 2.1.1
2. Confirm by looking through headset that SteamVR is running.
3. Exit SteamVR Beta by clicking "X" on the SteamVR Monitor window with mouse
4. SteamVR will exit and causes Steam Client Beta to close for a second and come back (expected behaviour according to release notes)
5. Random windows start popping up. These windows may include:

- Blank Steam client window with error message and EULA window
- Gamepad Driver Update pop up
- Audio Driver Update pop up
- Uninstalling "selected titles from your device", even though nothing has been selected.
- Resetting Collections window pop up

**Expected behavior**
SteamVR would exit cleanly and Steam Client would not try to delete my stuff.

**System Information (please complete the following information):**
- Distribution: Fedora 39 Beta
- SteamVR version: 2.1.1 Beta
- Steam client version: Latest Beta (1699054352)
- Opted into Steam client beta?: Yes
- Graphics driver version:  Mesa 23.2.1
- Headset: Valve Index
- GPU: Radeon 6800XT
- Gist for SteamVR System Information: https://gist.github.com/wallcarpet40/0d8e37458803d51b8c8713dcde53f23e
- Gist for Steam System Information: https://gist.github.com/wallcarpet40/e523f8019d21e29c1357b1496d7e7fd5

**Screenshots**
![SteamVR-exiting](https://github.com/ValveSoftware/SteamVR-for-Linux/assets/62506375/fede497a-ea2a-4190-bf72-86a6ee5a24b6)
![SteamVR-exiting2](https://github.com/ValveSoftware/SteamVR-for-Linux/assets/62506375/198b44fb-d8d6-4cd6-94bf-d45ce6199907)
![SteamVR-exiting3](https://github.com/ValveSoftware/SteamVR-for-Linux/assets/62506375/79141ccf-7343-43d2-bbc8-407013520800)
![SteamVRexiting4](https://github.com/ValveSoftware/SteamVR-for-Linux/assets/62506375/4a0cab65-5ea1-4e8a-8ae2-7412e99e3f0e)

If this is a Steam Client bug instead of SteamVR, please move issue to correct place, thank you.

**Note:** Commenters who are also experiencing this issue are encouraged to include the "System Information" section in their replies.

**Comment by ThaSwapMeetPimp** [comment]
Same issue here, Ubuntu-Studio 22.04, though mine has only repeatedly popped up a 'gamepad driver update' window so far. Exiting VR also forces the Steam Beta Client to exit.

**Comment by caseif** [comment]
I'm experiencing this on 2.0.10 with the Steam beta client, but so far I haven't seen it on 2.1.1.

**Comment by caseif** [comment]
I'm no longer able to reproduce the issue with SteamVR 2.0.10 nor 2.1.1 with the latest Steam beta client.

**Comment by wallcarpet40** [comment]
I also can confirm that with the latest Steam Client Beta, the issue seems to have been fixed! Also not getting any errors on startup (497 or 303 or 102) and colors are not flipped anymore.  Steam Client window does not close and open at SteamVR exit. 

Most of the time, not always, but most of the time, I don't get any unkillable windows popping up either, so this release seems to have fixed a lot of stuff that isn't even mentioned in the release notes. Kudos! 

I'll play around with this over the weekend and if things work nicely, I'll close this issue by then.
