### ISSUE TITLE
[BUG] SteamVR creates unkillable windows

### ISSUE THREAD

**Issue by tmayoff** [ValveSoftware/SteamVR-for-Linux#635]
**Describe the bug**
When launching SteamVR the Status window opens, but then so does another blank window that's unkillable

**To Reproduce**
1. Launch SteamVR
2. See window

**Expected behavior**

**System Information (please complete the following information):**
- Distribution: Debian Bookworm
- SteamVR version: 2.1.1
- Steam client version: 1696019606
- Opted into Steam client beta?: Yes
- Graphics driver version:  525.125.06
- Gist for SteamVR System Information: https://gist.github.com/tmayoff/19faa0b23d28606144a6af3add2d520e

**Screenshots**

![image](https://github.com/ValveSoftware/SteamVR-for-Linux/assets/10094264/a5ee7c02-506a-47b7-93e2-a90e32b2c85b)

**Additional context**
Potentially a Gnome Issue, I didn't see the problem when running SteamVR from i3wm

**Note:** Commenters who are also experiencing this issue are encouraged to include the "System Information" section in their replies.

**Comment by kisak-valve** [comment]
Hello @tmayoff, this issue is already being tracked at #577. Closing as a duplicate.
