### ISSUE TITLE
Where is SteamVR?

### ISSUE THREAD

**Issue by DiThi** [ValveSoftware/SteamVR-for-Linux#64]
I had installed and working some weeks ago. Now it was only as "purchase". I tried uninstalling it and then it disappeared never to come back...

The "VR" icon at the corner is there but does nothing.

Using Steam Beta build Jul 14 2017, at 01:07:13

**Comment by georgewsinger** [comment]
This is also happening on my system.

**Comment by kisak-valve** [comment]
There was a general issue with the steam database that's been resolved. Restart steam or wait a while and SteamVR will re-appear in the tools section.
