### ISSUE TITLE
[BUG] SteamVR start error, sh execs are failing

### ISSUE THREAD

**Issue by Danielduel** [ValveSoftware/SteamVR-for-Linux#642]
latest everything, Arch, amd stack, `RADV_DEBUG=zerovram QT_QPA_PLATFORM=xcb %command%`

On start I get SteamVR fail (500).
Repeated runs doesn't help.

SteamVR 2.0.10 works
SteamVR 2.1.4 is breaking
SteamVR 2.1.2 (I am not sure if I've used 2.1.3 on Thursday, if yes - it was stable too) was stable

The difference between 2.0.10 and 2.1.4 is that in terminal logs it fails to call few things:
```
...
sh: 1: xdg-mime: not found
...
sh: 1: xdg-icon-resource: not found
sh: 1: xdg-mime: not found
...
```
(and sometimes it also fails to find `kill`)
It is broken for both - native and flatpack'ed steam.

**Comment by kisak-valve** [comment]
Hello @Danielduel, this issue is has better details for a SteamVR dev to ponder on #639. Closing as a duplicate.
