### ISSUE TITLE
Theater mode with SteamVR 2.1.8 is displayed upside-down

### ISSUE THREAD

**Issue by caseif** [ValveSoftware/SteamVR-for-Linux#644]
**Describe the bug**
Desktop games running in theater mode with SteamVR ~~2.1.5~~ ~~2.1.7~~ 2.1.8 are displayed upside-down. This issue persists when the game view is docked to vrdashboard or to a controller.

**To Reproduce**
1. With SteamVR running, open any desktop-mode game either through vrdashboard or the desktop Steam client
2. Observe the upside-down viewport in theater mode

**Expected behavior**
The game should display right side-up.

**System Information (please complete the following information):**
- Distribution: Arch
- SteamVR version: 2.1.5
- Steam client version: 1700272093
- Opted into Steam client beta?: Yes
- Graphics driver version:  Mesa 23.2.1-arch1.2
- Gist for SteamVR System Information: https://gist.github.com/caseif/c3404f46e0ec69a37f0efc1a3e46985f

**Screenshots**
![image](https://github.com/ValveSoftware/SteamVR-for-Linux/assets/2825606/755ed387-21da-4f5b-a902-57cf51ea52b1)

**Note:** Commenters who are also experiencing this issue are encouraged to include the "System Information" section in their replies.

**Comment by caseif** [comment]
@kisak-valve Whoops, my bad on the title. Thanks for the quick fix!

**Comment by digitalcircuit** [comment]
Same issue here, Kubuntu 22.04 LTS.

And, correct me if I'm wrong - you also appear to have the same bug I do where SteamVR Home never launches, hence the "Up next"-styled item hanging around on top until a VR game is launched.  It was broken before the 2.1.x beta series for me, I had just never gotten around to filing a bug report on it.

**Comment by jarredpickles87** [comment]
Having the same exact issue as @caseif. I'm running Mint 21.2 on kernel 6.2.0-36 cinnamon DE 5.8.4

**Comment by caseif** [comment]
This is still occurring with version 2.1.7.

**Comment by whinis** [comment]
Same, Arch version 2.1.7 still occuring

**Comment by jarredpickles87** [comment]
Also same on 2.1.7 with Mint

**Comment by CarbonNotes** [comment]
Same with 2.1.7 on Steam OS 3.5.7 + HTC Vive

**Comment by jarredpickles87** [comment]
Update again: still upside down on 2.1.8. Performance in certain games is also very stuttery.

**Comment by TTimo** [comment]
Fixed in StemVR beta 2.2.1

**Comment by caseif** [comment]
I'm unable to retest this as theater mode is no longer working at all for me in 2.2.1 as well as 2.1.10, with the "screen" being completely black. This occurs with both the beta and stable Steam clients and with both X11 and Wayland Plasma sessions.

**Comment by digitalcircuit** [comment]
SteamVR 2.1.10 stable with Steam as of Dec. 11th fixed this issue for me.

2D games/Theater Mode even work in SteamVR 2.2.1 beta and Steam beta for me, [despite SteamVR 2.2.1 breaking VR games again](https://github.com/ValveSoftware/SteamVR-for-Linux/issues/638#issuecomment-1855104212 ) for me.
