### ISSUE TITLE
[BUG] SteamVR 2.1.10: steamvr_room_setup.sh looks for run.sh and vrenv.sh in wrong directories

### ISSUE THREAD

**Issue by Owen-Benner** [ValveSoftware/SteamVR-for-Linux#662]
**Describe the bug**
After launching `vrstartup.sh` with SLR 3.0 (sniper), attempting to launch room setup gives the following error, and room setup does not launch:
`/home/buckeyeback101/.local/share/Steam/steamapps/common/SteamVR/tools/steamvr_room_setup/linux64/steamvr_room_setup.sh: line 33: /home/buckeyeback101/.steam/bin/steam-runtime/run.sh: No such file or directory`

After editing steamvr_room_setup.sh (or creating a symlink) to resolve this error, I get another error instead, and room setup still does not launch:
`/home/buckeyeback101/.local/share/Steam/steamapps/common/SteamVR/tools/steamvr_room_setup/linux64/steamvr_room_setup.sh: line 41: /home/buckeyeback101/.local/share/Steam/steamapps/common/SteamVR/tools/steamvr_room_setup/linux64/../../../runtime/bin/vrenv.sh: No such file or directory`

After editing steamvr_room_setup.sh to resolve the second error, room setup launches and runs without error.

**To Reproduce**
1. Install Steam using [the .deb file from Valve's website](https://cdn.akamai.steamstatic.com/client/installer/steam.deb) (as per [Valve's recommendation](https://help.steampowered.com/en/faqs/view/18A4-1E10-8A94-3DDA)).
2. Run Steam, install SteamVR.
3. Run SteamVR under SLR 3.0 (sniper) through the terminal: `exec ~/.steam/steamapps/common/SteamLinuxRuntime_sniper/run ~/.steam/steamapps/common/SteamVR/bin/vrstartup.sh`
4. Select `Room Setup` from the hamburger menu in the SteamVR Status window.
5. Check terminal for error.

**Expected behavior**
SteamVR Room Setup runs without error.

**System Information (please complete the following information):**
- Distribution: Pop!_OS 22.04 LTS x86_64
- SteamVR version: 2.1.10
- Steam client version: Steam Client Update - December 11th
- Opted into Steam client beta?: No
- Graphics driver version:  Mesa 23.2.1-1pop0\~1699535617\~22.04\~6cd9a72 (LLVM 15.0.7)
- Gist for SteamVR System Information: https://gist.github.com/Owen-Benner/e3aa807025802c91fad84fe795fedef5

**Additional context**
Replacing the following lines in `steamvr_room_setup.sh` allow room setup to run without error on my system.
Lines 32–33:
```
log exec "$HOME/.steam/bin/steam-runtime/run.sh" "$0" "$@"
exec "$HOME/.steam/bin/steam-runtime/run.sh" "$0" "$@"
```
Replace with:
```
log exec "$HOME/.steam/ubuntu12_32/steam-runtime/run.sh" "$0" "$@"
exec "$HOME/.steam/ubuntu12_32/steam-runtime/run.sh" "$0" "$@"
```

Line 39:
`VRBINDIR=${ROOT}/../../../runtime/bin`
Replace with:
`VRBINDIR=${ROOT}/../../../bin`

**Note:** Commenters who are also experiencing this issue are encouraged to include the "System Information" section in their replies.

**Comment by Owen-Benner** [comment]
For anyone else having this issue, as it appears `steamvr_room_setup.sh` isn't the only file with this problem, it may be better to create symlinks:
`ln -s ~/.steam/ubuntu12_32/steam-runtime ~/.steam/bin/steam-runtime`
`ln -s ~/.local/share/Steam/steamapps/common/SteamVR/bin ~/.local/share/Steam/steamapps/common/SteamVR/runtime/bin`

**Comment by kisak-valve** [comment]
Hello @Owen-Benner, with the Valve-provided Steam package, `${HOME}/.steam/bin` is expected to be a symlink to `${HOME}/.steam/bin32` and `${HOME}/.steam/bin32` is expected to be a symlink to `${HOME}/.local/share/Steam/ubuntu12_32`

The Valve-provided Steam package doesn't create a `${HOME}/.steam/ubuntu12_32` folder and historically never has done so. This is most likely from using a distro-modified variant of the Steam package, then later switching to the Valve-provided variant without moving / removing the incompatible folder layouts. This is not a SteamVR issue and the transition between the two package variants can't be supported. Ideally, the Steam client should be re-bootstrapped if you swap between the two.

Double check which Steam package is installed with something like `apt policy steam` then move or remove `~/.steam` to let Steam regenerate the folder the next time it is started.

**Comment by Owen-Benner** [comment]
> This is most likely from using a distro-modified variant of the Steam package, then later switching to the Valve-provided variant without moving / removing the incompatible folder layouts.
That checks out. I was previously using the .deb from the Pop!_OS store and then I switched to the Valve .deb. I moved .steam as you suggested and it fixed this issue. Thanks!
