### ISSUE TITLE
[BUG] SteamVR does not start "VR_Init error, exiting: Interface Not Found (105)"

### ISSUE THREAD

**Issue by Doggermelon** [ValveSoftware/SteamVR-for-Linux#664]
**Describe the bug**
SteamVR no longer starts for me after playing around with the Proton version even after returning to a previous working version. Uninstalling and reinstalling does not help.

**To Reproduce**
1. Go to SteamVR on Steam
2. Open properties...
3. Click compatibility
4. Enable the checkbox and select a different Proton version from the drop down.
5. Launch SteamVR
6. Note SteamVR goes green momentarily "Running"
7. Note it returns to white without launching.
8. Change the compatibility settings in properties back to what it was.
9. Launch SteamVR
10. Note the behavior in 6 in 7 continues.

**Expected behavior**
SteamVR starts.

**System Information (please complete the following information):**
- Distribution: Artix
- SteamVR version: 2.2.4, 2.2.3, 1.14
- Steam client version: 1702079146
- Opted into Steam client beta?: No
- Graphics driver version:  Nvidia 545.29.06
- Gist for SteamVR System Information: (unreachable)

**Additional context**
vrstartup.txt has these lines for SteamVR v2.2.x:
```
 - vrstartup.exe 2.2.3 startup with PID=304, config=Z:\home\_\.local\share\Steam\config, runtime=C:\vrclient\
 - Reset Runtime based on Executable: Z:\home\_\.local\share\ValveSteam\steamapps\common\SteamVR\bin\win32
 - New Runtime: Z:\home\_\.local\share\ValveSteam\steamapps\common\SteamVR
 - VR_Init error, exiting: Interface Not Found (105)
```
Notably when it was working the log entries had Unix style paths as well as different runtime paths:
```
 - vrstartup 2.2.3 startup with PID=26607, config=/home/_/.local/share/Steam/config, runtime=/home/_/.local/share/ValveSteam/steamapps/common/SteamVR
 - Reset Runtime based on Executable: /home/_/.local/share/ValveSteam/steamapps/common/SteamVR/bin/linux64
 - New Runtime: /home/_/.local/share/ValveSteam/steamapps/common/SteamVR
```
There's one "Error" in the log segregating the two:
```
 - Failed to associate URI: mime registration failed for steamvr
```

**Note:** Commenters who are also experiencing this issue are encouraged to include the "System Information" section in their replies.

**Comment by kisak-valve** [comment]
Hello @Doggermelon, you've described the issue being tracked at https://github.com/ValveSoftware/steam-for-linux/issues/9875.

Opt into Steam's client beta, then toggle the per-game Steam Play setting on and off to nudge the Steam client out of the misconfiguration.

Closing in favor of the older issue report.
