### ISSUE TITLE
[BUG] Core Dump On Startup

### ISSUE THREAD

**Issue by Doctor-Cpu** [ValveSoftware/SteamVR-for-Linux#668]
**Describe the bug**
When launching SteamVR vrstartup core dumps.

**To Reproduce**
1. Launch SteamVR
2. Wait until SteamVR crashes
3. See error in journalctl

**Expected behavior**
SteamVR launches

**System Information (please complete the following information):**
- Distribution: Arch
- SteamVR version: 2.3.1/1.27.5
- Steam client version: 1704760224 
- Opted into Steam client beta?: Yes
- Graphics driver version:  Mesa 23.3.2-arch1.2
- Gist for SteamVR System Information: Unable as it crashes before I can create a report.

**Additional context**
This is a fresh install of SteamVR.

**Note:** Commenters who are also experiencing this issue are encouraged to include the "System Information" section in their replies.

**Comment by Hisanatos** [comment]
Just a headsup, Linux is not Windows, Valve can't just assume anything about your system, so for them to do anything you will need to copy and paste the error you are getting in Journalctl, as if you don't we can just as a collective say "Works on my computer".

**Comment by Doctor-Cpu** [comment]
Latest updates have resolved the issue.
