### ISSUE TITLE
vrcompositor using 100% CPU

### ISSUE THREAD

**Issue by JohanAR** [ValveSoftware/SteamVR-for-Linux#67]
#### Your system information
* Steam client version (build number or date): Built Jul 26 2017 at 18:19:48
* Distribution (e.g. Ubuntu): Xubuntu 17.04
* Graphics driver version (run nvidia-settings): 381.26.08-0ubuntu0~gpu17.04.1
* Gist for SteamVR System Information: https://gist.github.com/JohanAR/bbe49aeea02299a59b62efbdbddd9009
* Opted into Steam client beta?: [Yes/No] Yes
* Opted into SteamVR beta?: [Yes/No] Yes
* Have you checked for system updates?: [Yes/No] Yes
* CPU: i7-4770k
* RAM: 8 GB
* GPU: GTX 970

#### Please describe your issue in as much detail as possible:
Seems like SteamVR is almost working: I could start room setup and got an image in my headset, but tracking stopped working and after restarting SteamVR I no longer get an image, it's all black. The whole time the process ~/.local/share/Steam/steamapps/common/SteamVR/bin/linux64/vrcompositor takes 100% CPU. Tried starting steam both with and without STEAM_RUNTIME_PREFER_HOST_LIBRARIES=0, works fine in Win10 on same hardware.

#### Steps for reproducing this issue:
1. Start SteamVR from Steam client
2. Check running processes for CPU usage, for example using htop

**Comment by JohanAR** [comment]
Appears to be fixed now

**Comment by annogram** [comment]
This is happening to me now
