### ISSUE TITLE
[BUG] SteamVR Home fails to load since 2.0 update

### ISSUE THREAD

**Issue by KczBen** [ValveSoftware/SteamVR-for-Linux#670]
**Describe the bug**
The SteamVR Home environment fails to launch since the 2.0 update. It works on the old 1.27.5 branch.
When SteamVR starts, the Home splash screen is shown idefinitely, but other games can be launched through Steam as normal. 

**To Reproduce**
1. Start SteamVR
2. If SteamVR Home is enabled in SteamVR settings, you should now see the splash screen for Home. Nothing happens no matter how long you wait.
3. If SteamVR Home is not enabled, manually start it through Steam. Here an "Unknown error" will show.

**Expected behavior**
Home environment should open like all other games do.

**System Information (please complete the following information):**
- Distribution: Debian Sid
- SteamVR version: 2.3.3
- Steam client version: 1705720677
- Opted into Steam client beta?: Yes
- Graphics driver version:  Mesa 23.3.3-3
- Gist for SteamVR System Information: https://gist.github.com/KczBen/b1d52c69a89695988d94997496e73142

**Screenshots**
(Not a particularly useful screenshot, but this is what's shown in the headset)
![Screenshot1](https://github.com/ValveSoftware/SteamVR-for-Linux/assets/134858865/cbb9366f-d60a-47f8-835e-cd1b5bfcfd4d)

**Additional context**
I tried running SteamVR Home from the command line using the following command I found online:
`cd ~/.local/share/Steam/steamapps/common/SteamVR/tools/steamvr_environments/game/ && ~/.steam/steam/ubuntu12_32/steam-runtime/run.sh ./steamtours.sh -vulkan -vr`

Doing so seems to have produced a potentially useful output:
`steamtours.sh[15533]: === Wed 24 Jan 01:10:36 GMT 2024 ===
steamtours.sh[15533]: Detected scout LDLP runtime.
Loaded file game                    engine2                    3.655 msec     8470 kb    /home/bence/.local/share/Steam/steamapps/common/SteamVR/tools/steamvr_environments/game/bin/linuxsteamrt64/libengine2.so
Loaded file game                    tier0                      0.052 msec      544 kb    /home/bence/.local/share/Steam/steamapps/common/SteamVR/tools/steamvr_environments/game/bin/linuxsteamrt64/libtier0.so
Loaded file game                    vstdlib                    0.033 msec      379 kb    /home/bence/.local/share/Steam/steamapps/common/SteamVR/tools/steamvr_environments/game/bin/linuxsteamrt64/libvstdlib.so
Loaded file game                    filesystem_stdio           0.105 msec      356 kb    /home/bence/.local/share/Steam/steamapps/common/SteamVR/tools/steamvr_environments/game/bin/linuxsteamrt64/libfilesystem_stdio.so
Loaded file game                    vr                         0.061 msec      873 kb    /home/bence/.local/share/Steam/steamapps/common/SteamVR/tools/steamvr_environments/game/bin/linuxsteamrt64/libvr.so
Loaded file game                    openvr_api                 0.021 msec      317 kb    /home/bence/.local/share/Steam/steamapps/common/SteamVR/tools/steamvr_environments/game/bin/linuxsteamrt64/libopenvr_api.so
Loaded file game                    inputsystem                0.014 msec      175 kb    /home/bence/.local/share/Steam/steamapps/common/SteamVR/tools/steamvr_environments/game/bin/linuxsteamrt64/libinputsystem.so
Loaded file game                    localize                   0.011 msec      142 kb    /home/bence/.local/share/Steam/steamapps/common/SteamVR/tools/steamvr_environments/game/bin/linuxsteamrt64/liblocalize.so
Loaded file game                    resourcesystem             0.029 msec      464 kb    /home/bence/.local/share/Steam/steamapps/common/SteamVR/tools/steamvr_environments/game/bin/linuxsteamrt64/libresourcesystem.so
Loaded file game                    schemasystem               0.025 msec      393 kb    /home/bence/.local/share/Steam/steamapps/common/SteamVR/tools/steamvr_environments/game/bin/linuxsteamrt64/libschemasystem.so
Loaded file game                    materialsystem2            0.072 msec     1104 kb    /home/bence/.local/share/Steam/steamapps/common/SteamVR/tools/steamvr_environments/game/bin/linuxsteamrt64/libmaterialsystem2.so
Loaded file game                    meshsystem                 0.076 msec     1118 kb    /home/bence/.local/share/Steam/steamapps/common/SteamVR/tools/steamvr_environments/game/bin/linuxsteamrt64/libmeshsystem.so
Loaded file game                    worldrenderer              0.070 msec     1167 kb    /home/bence/.local/share/Steam/steamapps/common/SteamVR/tools/steamvr_environments/game/bin/linuxsteamrt64/libworldrenderer.so
Loaded file game                    vscript                    0.048 msec      655 kb    /home/bence/.local/share/Steam/steamapps/common/SteamVR/tools/steamvr_environments/game/bin/linuxsteamrt64/libvscript.so
Loaded file game                    networksystem              0.273 msec     3349 kb    /home/bence/.local/share/Steam/steamapps/common/SteamVR/tools/steamvr_environments/game/bin/linuxsteamrt64/libnetworksystem.so
Loaded file game                    animationsystem            0.365 msec     3315 kb    /home/bence/.local/share/Steam/steamapps/common/SteamVR/tools/steamvr_environments/game/bin/linuxsteamrt64/libanimationsystem.so
Loaded file game                    vphysics2                  0.259 msec     3928 kb    /home/bence/.local/share/Steam/steamapps/common/SteamVR/tools/steamvr_environments/game/bin/linuxsteamrt64/libvphysics2.so
Loaded file game                    steamaudio                 0.025 msec      374 kb    /home/bence/.local/share/Steam/steamapps/common/SteamVR/tools/steamvr_environments/game/bin/linuxsteamrt64/libsteamaudio.so
Loaded file game                    phonon                     7.658 msec    17227 kb    /home/bence/.local/share/Steam/steamapps/common/SteamVR/tools/steamvr_environments/game/bin/linuxsteamrt64/libphonon.so
Loaded file game                    soundsystem                0.155 msec     1879 kb    /home/bence/.local/share/Steam/steamapps/common/SteamVR/tools/steamvr_environments/game/bin/linuxsteamrt64/libsoundsystem.so
Loaded file game                    scenesystem                0.368 msec     4017 kb    /home/bence/.local/share/Steam/steamapps/common/SteamVR/tools/steamvr_environments/game/bin/linuxsteamrt64/libscenesystem.so
Loaded file game                    v8                         8.196 msec    17771 kb    /home/bence/.local/share/Steam/steamapps/common/SteamVR/tools/steamvr_environments/game/bin/linuxsteamrt64/libv8.so
Loaded file game                    video                      0.499 msec     4840 kb    /home/bence/.local/share/Steam/steamapps/common/SteamVR/tools/steamvr_environments/game/bin/linuxsteamrt64/libvideo.so
Loaded file game                    icui18n                    0.160 msec     2909 kb    /home/bence/.local/share/Steam/steamapps/common/SteamVR/tools/steamvr_environments/game/bin/linuxsteamrt64/libicui18n.so
Loaded file game                    icuuc                      0.099 msec     1871 kb    /home/bence/.local/share/Steam/steamapps/common/SteamVR/tools/steamvr_environments/game/bin/linuxsteamrt64/libicuuc.so
Loaded file game                    particles                  0.195 msec     3742 kb    /home/bence/.local/share/Steam/steamapps/common/SteamVR/tools/steamvr_environments/game/bin/linuxsteamrt64/libparticles.so
Loaded file game                    panorama                   0.410 msec     6779 kb    /home/bence/.local/share/Steam/steamapps/common/SteamVR/tools/steamvr_environments/game/bin/linuxsteamrt64/libpanorama.so
Loaded file game                    panorama_text_pango        0.121 msec     2265 kb    /home/bence/.local/share/Steam/steamapps/common/SteamVR/tools/steamvr_environments/game/bin/linuxsteamrt64/libpanorama_text_pango.so
Loaded file game                    renderingpipelines         0.031 msec      517 kb    /home/bence/.local/share/Steam/steamapps/common/SteamVR/tools/steamvr_environments/game/bin/linuxsteamrt64/librenderingpipelines.so
Loaded file game                    scenefilecache             0.015 msec      214 kb    /home/bence/.local/share/Steam/steamapps/common/SteamVR/tools/steamvr_environments/game/bin/linuxsteamrt64/libscenefilecache.so
LoadModule Total:   23.384 msec

Loaded VPK Total:    0.018 msec

Total Preload Time:   23.403 msec
Using breakpad crash handler
[S_API] SteamAPI_Init(): Loaded '/home/bence/.local/share/Steam/linux64/steamclient.so' OK.
Setting breakpad minidump AppID = 250820
Forcing breakpad minidump interfaces to load
Looking up breakpad interfaces from steamclient
Calling BreakpadMiniDumpSystemInit
01/24 01:10:36 Init: Installing breakpad exception handler for appid(250820)/version(8389430)/tid(15549)
Looking up breakpad interfaces from steamclient
Calling BreakpadMiniDumpSystemInit
Steam_SetMinidumpSteamID:  Caching Steam ID:  76561198261234705 [API loaded yes]
Steam_SetMinidumpSteamID:  Setting Steam ID:  76561198261234705
src/tcmalloc.cc:390] Attempt to free invalid pointer: 0x58dcd7ad3950
crash_20240124011036_2.dmp[15561]: Uploading dump (out-of-process)
/tmp/dumps/crash_20240124011036_2.dmp
/home/bence/.local/share/Steam/steamapps/common/SteamVR/tools/steamvr_environments/game/steamtours.sh: line 72: 15549 Aborted                 (core dumped) ${GAME_DEBUGGER} "${GAMEROOT}"/${GAMEEXE} "$@"`

Here is the crash dump file mentioned in the output above:

[crash_20240124011036_2.tar.gz](https://github.com/ValveSoftware/SteamVR-for-Linux/files/14031509/crash_20240124011036_2.tar.gz)

**Note:** Commenters who are also experiencing this issue are encouraged to include the "System Information" section in their replies.

**Comment by kisak-valve** [comment]
Hello @KczBen, `src/tcmalloc.cc:390] Attempt to free invalid pointer: 0x58dcd7ad3950` is the line of interest in you log, and that along with the minidump telling us that your mesa build is built against llvm 17 makes this the same issue as #579.

Closing in favor of the older issue report.

**Comment by Ta11Ken** [comment]
I figured it out!  Follow my steps on this:

1) Make sure steam VR is NOT on before launching your oculus

2) Turn on your oculus, then connect to AirLink to your PC

3) Show your desktop of your primary monitor and navigate to steam

4) Launch Steam VR from the steam library

5) Your avatar should get transported to a kind of twilight looking area that you can't interact with, but steam VR home never loads.  From this situation, press the triple line button on your left Oculus controller, navigate to the Steam VR settings, go to the bottom of the steam VR settings, find the "Show" button to bring you to the advanced settings tab, then find the "Steam VR Home" toggle.  If it is off, turn it on, or if it is on, toggle it off, then on.  This should force steam vr home to launch!

Let me know if this works for you! It did for me.
