### ISSUE TITLE
Error: retrieving gpg key timed out[BUG] Issue Title

### ISSUE THREAD

**Issue by sudosl-h** [ValveSoftware/SteamVR-for-Linux#675]
**After about 20 minutes of hang time I get the following terminal output. please see below.**

~$ sudo add-apt-repository ppa:kisak/steamvr
 Experimental drivers to help test new features related to SteamVR.

All packages in this PPA are considered alpha grade. Expect quirks and limitations.

They are provided as-is without warranty of any kind. You have been warned.

This PPA provides no significant benefit to Ubuntu 22.04. The kernel build currently contains some minor performance optimizations that are nice to have, but it is not required.

Kernel bits:

sudo apt install linux-generic-steamvr-20.04

Vulkan bits:

sudo apt install mesa-vulkan-drivers mesa-vulkan-drivers:i386

Move/remove /usr/share/vulkan/icd.d/intel_icd.x86_64.json to make sure SteamVR uses the AMD gpu. This may need to be redone on every mesa update.

sudo mv /usr/share/vulkan/icd.d/intel_icd.x86_64.json /usr/share/vulkan/icd.d/intel_icd.x86_64.json.disabled

---

Package status:
libdrm: Bumping as needed for mesa
linux: Following Ubuntu mainline
linux-firmware: Following Ubuntu non-LTS as needed
llvm-toolchain: Targeting latest point release
mesa: Targeting latest point release

---

Removal:

Reboot onto a mainline kernel (or manually remove the PPA kernel afterwards)

sudo apt install ppa-purge
sudo ppa-purge ppa:kisak/steamvr
 More info: https://launchpad.net/~kisak/+archive/ubuntu/steamvr
Press [ENTER] to continue or Ctrl-c to cancel adding it.

Error: retrieving gpg key timed out.

______________________________________________________________________________________________________________________
SYSTEM INFO:
______________________________________________________________________________________________________________________

os_release:
    name:               "Zorin OS"     ###THIS IS A FORK OF THE CURRENT UBUNTU DISTRO###
    version:            "16.3"
snap_info:
    steam_revision:     171
    snapd_revision:     20671
lspci:
    0c:00.0:            Advanced Micro Devices, Inc. [AMD/ATI] Ellesmere [Radeon RX 470/480/570/570X/580/580X/590] (rev e7)
    0d:00.0:            Advanced Micro Devices, Inc. [AMD/ATI] Ellesmere [Radeon RX 470/480/570/570X/580/580X/590] (rev e7)
glxinfo:
    gpu:                POLARIS10 (radeonsi, polaris10, LLVM 15.0.7, DRM 3.42, 5.15.0-94-generic)
    gpu_version:        4.6 (Core Profile) Mesa 23.3.4 - kisak-mesa PPA
lscpu:
    model_name:         AMD Ryzen 9 5950X 16-Core Processor
xdg_current_desktop:    zorin:GNOME
desktop_session:        zorin

**Comment by kisak-valve** [comment]
Hello @sudosl-h, right now the SteamVR Experimental Graphics PPA only provides packages for Ubuntu 22.04 "Jammy". ZorinOS 16.3 looks like it's based on Ubuntu 20.04 "Focal" and this looks like a general failure because there's no packages in the PPA for your fork of Ubuntu.

**Comment by sudosl-h** [comment]
That explains quite a bit now doesnt it... Damn. Well thank you very much
for your reply. With that, youve already been more helpful than the valve
support team.
