### ISSUE TITLE
[BUG] Steam library window disappears when launching SteamVR

### ISSUE THREAD

**Issue by PhilT** [ValveSoftware/SteamVR-for-Linux#677]
**Describe the bug**

Previous version of SteamVR would load up and tile next to the Steam library window (I'm using dwm).
Latest version (2.3.5) of SteamVR makes the Steam window disappear (like it's changing video mode) so it's not possible to then start a VR game from the Steam library. I also tried running it from Lutris but nothing happens until you close SteamVR then the game tries to run but obviously won't get very far. I also tried Beta 2.4.1 and I get the same behavior.

I've switched to temp_v1.27.5 and it's working there. It was previously working on version 2.3.4.

I'm running NixOS unstable with latest updates and as mentioned, dwm window manager. 

**To Reproduce**
Go to SteamVR and Launch or start from "Enter VR mode" at the top right.

**Expected behavior**
SteamVR appears next to Steam library

**System Information (please complete the following information):**
- Distribution: NixOS
- SteamVR version: 2.3.5
- Steam client version: Thu, Feb 29 12:39 AM UTC -08:00
- Opted into Steam client beta?: No
- Graphics driver version:  550.54.14
- Gist for SteamVR System Information: https://gist.github.com/PhilT/f58d80bba304444517c700cbe62d3ae0

**Screenshots**
Version 1.27.5 as expected:
![image](https://github.com/ValveSoftware/SteamVR-for-Linux/assets/34678/469ba5e6-b9b4-42e6-be86-8ff9f31e8070)

Version 2.3.5 and 2.4.1:
![image](https://github.com/ValveSoftware/SteamVR-for-Linux/assets/34678/522dc714-e10a-43b8-a0aa-7d11ca6adeed)

**Additional context**

**Note:** Commenters who are also experiencing this issue are encouraged to include the "System Information" section in their replies.

**Comment by galister** [comment]
Experiencing this as well.

Distribution: Gentoo
SteamVR version: 2.3.5
Steam Client version: 1709846872 (Mar 6 21:28 UTC-8)
Opted into Steam client beta?: No
Graphics driver version: Mesa 24.0.2

**Comment by galister** [comment]
wiping the entirety of `~/.local/share/Steam` and re-installing fixed this for me.

**Comment by PhilT** [comment]
> wiping the entirety of `~/.local/share/Steam` and re-installing fixed this for me.

Thanks, I'll check this when I get my new HMD. I'm HMDless at the moment.

**Comment by PhilT** [comment]
Received my new HMD, cleared everything out of `.local/share/Steam` (except `steamapps/` which are a symlinked folder) but it didn't solve the issue. 
Steam UI still disappears when SteamVR opens. 

Note that closing SteamVR brings back the Steam UI/Library.

**Comment by galister** [comment]
@PhilT i think what the root cause was for me was home folder encryption. it wouldn't work in /home. my initial setup was a symlink to a folder on another disk, but that didn't work either, for some reason.

creating a steam library on a different disk and installing steamvr there, or bind mounting a non-encrypted folder to steamapps did fix it.

**Comment by PhilT** [comment]
> @PhilT i think what the root cause was for me was home folder encryption. it wouldn't work in /home. my initial setup was a symlink to a folder on another disk, but that didn't work either, for some reason.
> 
> creating a steam library on a different disk and installing steamvr there, or bind mounting a non-encrypted folder to steamapps did fix it.

Oh good shout. I'm also running on an encrypted drive so that could totally be it. I'll give that a go. Thanks.

**Comment by PhilT** [comment]
Actually my /games drive isn't encrypted. So that's that.

**Comment by galister** [comment]
ok, instead of symlinking it across, try bind mounting it. i think that eventually fixed it for me. but don't ask why.

**Comment by PhilT** [comment]
Yes! That was it. Switching the steamapps/ folder to a bind mount in NixOS and removing the symlinked one (so that NixOS was able to create the bind mount) fixed the issue. I can now see SteamVR and the Steam UI/library. 

Thanks so much for your help!! :heart:

**Comment by galister** [comment]
Ok I remember now, the encryption was a different issue; it prevented steamvr bindings from working with steamvr 2.x
