### ISSUE TITLE
[BUG] steamtours aborts in libtcmalloc

### ISSUE THREAD

**Issue by yshui** [ValveSoftware/SteamVR-for-Linux#680]
**Describe the bug**

SteamVR Home does not start, these lines are logged:

```
~/.local/share/Steam/steamapps/common/SteamVR/tools/steamvr_environments/game/steamtours.sh: line 82: 4050856 Aborted                 (core dumped) ${GAME_DEBUGGER} "${GAMEROOT}"/${GAMEEXE} "$@"
...
src/tcmalloc.cc:390] Attempt to free invalid pointer: 0x56a44665c950
```

**System Information (please complete the following information):**
- Distribution: NixOS
- SteamVR version: 2.4.4
- Steam client version: 1711147596
- Opted into Steam client beta?: Yes

**Additional context**
I think tcmalloc is probably conflicting with the system allocator, which is probably used by some system libraries. Removing `libtcmalloc_minimal.so.0` from steamtours' NEEDED (i.e. `patchelf --remove-needed ....`)  fixes this problem.

**Comment by yshui** [comment]
Stack trace:

```
                Stack trace of thread 4053326:
                #0  0x0000708e068a407c __pthread_kill_implementation (/nix/store/ksk3rnb0ljx8gngzk19jlmbjyvac4hw6-glibc-2.38-44/lib/libc.so.6 + 0x8d07c)
                #1  0x0000708e06854e06 raise (/nix/store/ksk3rnb0ljx8gngzk19jlmbjyvac4hw6-glibc-2.38-44/lib/libc.so.6 + 0x3de06)
                #2  0x0000708e0683d8f5 abort (/nix/store/ksk3rnb0ljx8gngzk19jlmbjyvac4hw6-glibc-2.38-44/lib/libc.so.6 + 0x268f5)
                #3  0x0000708e06a0dcbb n/a (~/.local/share/Steam/steamapps/common/SteamVR/tools/steamvr_environments/game/bin/linuxsteamrt64/libtcmalloc_minimal.so.0 + 0xdcbb)
```

**Comment by kisak-valve** [comment]
Hello @yshui, this issue is already being tracked at #579 and is likely https://gcc.gnu.org/bugzilla/show_bug.cgi?id=113258#c27.

Closing as a duplicate.
