### ISSUE TITLE
[BUG] Having trouble getting SteamVR working; can't play anything other than SteamVR Home

### ISSUE THREAD

**Issue by CaptainD54321** [ValveSoftware/SteamVR-for-Linux#686]
**Describe the bug**
I recently bought myself a VR headset (I got an old HTC Vive off Ebay for pretty cheap; the resolution isn't great, but the headset itself seems to be working perfectly), and have been having a lot of trouble getting it to actually work on my Linux machine. After about two days of tinkering, my situation is the following: 
* On the old Linux beta (v1.14), I can play SteamVR Home, but if I try to start any VR game from my library, it just sits on the "next up" screen for a while, then the loading popup disappears, like the game failed to launch.
*  The 1.27.5 beta gets similar results to 1.14, but after trying to launch one game, many icons on the dashboard show broken image symbols.
*  The latest beta (2.5.2) doesn't even load Home, and the dashboard doesn't show up when I try to open it. (The background darkens like the menu is open, and I can even see the laser mouse colliding with where the dashboard UI should be, but no UI is visible.

Also, whenever I switch between versions, just trying to update SteamVR gives me a "disk write error", and I have to uninstall it and re-install the new version to get it to work.

**System Information**
- Distribution: Linux Mint 21
- SteamVR version:1.14
- Steam client version: 1712795774
- Opted into Steam client beta?: Yes
- Graphics driver version:  545.29.06
- Gist for SteamVR System Information: [system information gist](https://gist.github.com/CaptainD54321/e234e0914a09afba4d31d0430f1c5630) 

**Screenshots**
I tried to take screenshots of the issues with v1.27.5 and the latest beta, but screenshots in VR didn't seem to be working either

**Note:** Commenters who are also experiencing this issue are encouraged to include the "System Information" section in their replies.

**Comment by ernstp** [comment]
Have you tried latest SteamVR stable, 2.4.4?

**Comment by CaptainD54321** [comment]
After posting this I have discovered that I can actually launch games on either the latest stable (2.4.4) or the latest beta (2.5.2) if I launch from the steam client, but I still have other issues I'm gonna make a separate issue post for, as this one was mostly about my issues with the 1.x versions and I don't want to jumble everything up in one confusing post
