### ISSUE TITLE
Headset is not sensed at startup (VR_Init failed with Connect to VR Server Failed (301))

### ISSUE THREAD

**Issue by rhaleblian** [ValveSoftware/SteamVR-for-Linux#69]
#### Your system information
* Steam client version (build number or date):
SteamVR Version:	1504061330
SteamVR Date:	2017-08-29
Steam:	Public
Steam Branch: 
* Distribution (e.g. Ubuntu): CentOS Linux release 7.3.1611 (Core) 
* Graphics driver version (run nvidia-settings): 384.59
* Gist for SteamVR System Information: https://gist.github.com/rhaleblian/82f9b0748b237a313e6ff9c98e128d04
* Opted into Steam client beta?: No
* Opted into SteamVR beta?: Yes
* Have you checked for system updates?: Yes

#### Please describe your issue in as much detail as possible:

Headset icon never goes green when starting Steam VR.
Headset LED stays red.
No video in Headset.
Status window shows Not Ready.

I expect the HMD icon to go green, then lighthouses, and green LED and video in the headset.

This said, I am running an nvidia driver newer than the version cited in the README, from negativo17's epel-multimedia repo. If i can find a good packaged way to install the exact driver, i'll retest.

#### Steps for reproducing this issue:
1. From Steam window, Start SteamVR
2. (301) A key component of SteamVR isn't working properly.
3. vrmonitor.txt  https://gist.github.com/rhaleblian/99ad30f36b79b3738550596444eb2c9f

**Comment by rhaleblian** [comment]
For comparison, under Ubuntu 16.04, with the exact driver version from README.md, the problem does not manifest.

**Comment by rhaleblian** [comment]
Issue occurs irrespective of SteamVR Beta opt-in.

**Comment by rhaleblian** [comment]
Running in the shell, i saw a crash creating a .dmp file. Wondering how post a .tar.gz of it.

**Comment by rhaleblian** [comment]
Enabled Steam Beta opt-in.
Using STEAM_RUNTIME_PREFER_HOST_LIBRARIES=0 removes this issue, replacing it with (306).

**Comment by rhaleblian** [comment]
From vrcompositor.txt
```
Fri Sep 08 2017 01:51:10.752543 - //=====================================================================================================================
Fri Sep 08 2017 01:51:10.752644 - VR compositor (v1504061330) starting up
Fri Sep 08 2017 01:51:10.752663 - RuntimePath : /home/rhalebli/.local/share/Steam/steamapps/common/SteamVR/
Fri Sep 08 2017 01:51:10.753248 - CIPCPipe::CreatePipe(VR_CompositorPipe_19768) bound to 49456
Fri Sep 08 2017 01:51:10.780628 - Events created
Fri Sep 08 2017 01:51:10.781575 - Creating CHmdWindowSDL!
Fri Sep 08 2017 01:51:10.891600 - Instance extensions available:
Fri Sep 08 2017 01:51:10.891636 -  - VK_EXT_acquire_xlib_display, version 1
Fri Sep 08 2017 01:51:10.891649 -  - VK_EXT_debug_report, version 6
Fri Sep 08 2017 01:51:10.891659 -  - VK_EXT_direct_mode_display, version 1
Fri Sep 08 2017 01:51:10.891669 -  - VK_EXT_display_surface_counter, version 1
Fri Sep 08 2017 01:51:10.891679 -  - VK_KHR_display, version 21
Fri Sep 08 2017 01:51:10.891689 -  - VK_KHR_get_physical_device_properties2, version 1
Fri Sep 08 2017 01:51:10.891699 -  - VK_KHR_get_surface_capabilities2, version 1
Fri Sep 08 2017 01:51:10.891709 -  - VK_KHR_surface, version 25
Fri Sep 08 2017 01:51:10.891718 -  - VK_KHR_xcb_surface, version 6
Fri Sep 08 2017 01:51:10.891728 -  - VK_KHR_xlib_surface, version 6
Fri Sep 08 2017 01:51:10.891738 -  - VK_KHX_device_group_creation, version 1
Fri Sep 08 2017 01:51:10.891752 - Requesting 7 instance extensions:
Fri Sep 08 2017 01:51:10.891762 -  - VK_KHR_surface
Fri Sep 08 2017 01:51:10.891772 -  - VK_KHR_xcb_surface
Fri Sep 08 2017 01:51:10.891782 -  - VK_KHR_display
Fri Sep 08 2017 01:51:10.891791 -  - VK_EXT_direct_mode_display
Fri Sep 08 2017 01:51:10.891801 -  - VK_EXT_acquire_xlib_display
Fri Sep 08 2017 01:51:10.891811 -  - VK_EXT_display_surface_counter
Fri Sep 08 2017 01:51:10.891820 -  - VK_KHR_get_physical_device_properties2
Fri Sep 08 2017 01:51:10.952342 - Requesting 5 device extensions:
Fri Sep 08 2017 01:51:10.952387 -  - VK_KHR_swapchain
Fri Sep 08 2017 01:51:10.952398 -  - VK_KHR_maintenance1
Fri Sep 08 2017 01:51:10.952407 -  - VK_KHR_dedicated_allocation
Fri Sep 08 2017 01:51:10.952415 -  - VK_KHR_get_memory_requirements2
Fri Sep 08 2017 01:51:10.952423 -  - VK_EXT_display_control
Fri Sep 08 2017 01:51:10.952431 - Attempting to enable async support...
Fri Sep 08 2017 01:51:10.952439 - Disabling async support because extension VK_EXT_queue_global_priority not found.
Fri Sep 08 2017 01:51:10.952447 - Disabling async support because no separate compute queue family found.
Fri Sep 08 2017 01:51:10.952563 - Failed to create VkDevice.
Fri Sep 08 2017 01:51:10.952580 - CHmdWindowSDL: Couldn't create Vulkan resources, initialization failure.
```
To me, this is pointing to the nvidia-driver, so i'll try harder to get another version.

**Comment by kisak-valve** [comment]
Hello @rhaleblian, StreamVR on linux requires nvidia's vulkan dev branch (381.26.xx), which has some extensions that are not yet in the mainline driver.

For reference, the attached minidump is a SIGABRT in libc-2.17.so.

**Comment by rhaleblian** [comment]
Thanks @kisak-valve , after re-reading README i get it now, installed 381.26.13 via NVIDIA .run package, and the issue goes away. I'll be sure to take any update from the Vulkan branch as well.

**Comment by h1z1** [comment]
@kisak-valve - Symbol / lib versioning was crated for things like this.  Just say'n.  I got bit by this and many others because the errors were not evident at all.
