### ISSUE TITLE
[PERF] HLA with SteamVr linux_v1.14 was fluid yesterday, the second time I tried it there is a frame drop that makes it unplayable.

### ISSUE THREAD

**Issue by Hicks79** [ValveSoftware/SteamVR-for-Linux#692]
**Describe the bug**
Uninstall SteamVr, and install SteamVr again  with linux_v1.14. 
HLA is smooth.

The second time I tried it there is a frame drop that makes it unplayable.

I find it complicated to make it fluid again.

I have tried rebooting the computer, changing the usb in different port.

Edit: i tried uninstall SteamVr, but the frames drops are there.

**System Information (please complete the following information):**

    Distribution: Ubuntu 18.04
    SteamVR version:  linux_v1.14.   (the beta version of SteamVr have a lot problems for me)
    Steam client version: 1714430836
    Opted into Steam client beta?: Yes
    Graphics driver version: NVIDIA 550.78

IMPORTANT: I can't update firmare (due to another Index bug) 
- https://gist.github.com/Hicks79/dc2ed40ce65a0774779729d38c414eb7

**Comment by kisak-valve** [comment]
Hello @Hicks79, sorry, but the SteamVR linux_v1.14 legacy branch is too far away from the actively developed code base for the SteamVR devs to do anything constructive with this feedback.
