### ISSUE TITLE
[BUG] disconnection from vrchat

### ISSUE THREAD

**Issue by MochaHusky92** [ValveSoftware/SteamVR-for-Linux#695]
when I'm on Vrchat i will only be on for 15 minutes it will say " your connection to Vrchat has been interrupted please verify your connection I've checked everything

**Comment by kisak-valve** [comment]
Hello @MochaHusky92, this reads more like a networking or Proton issue than a SteamVR issue.

We're tracking issues with games run with Proton in the Proton issue tracker. Also, we're using one issue report per unofficially supported game title, so I've gone ahead and transferred this issue report to https://github.com/ValveSoftware/Proton/issues/1199#issuecomment-2101758734.
