### ISSUE TITLE
SteamVR failed to initialized for unknown reasons. (Error: vrclient Shared Lib Not Found (102))

### ISSUE THREAD

**Issue by Techjar** [ValveSoftware/SteamVR-for-Linux#71]
* Steam client version (build number or date): 1506500000
* Distribution (e.g. Ubuntu): Antergos
* Graphics driver version (run nvidia-settings): 384.90
* Gist for SteamVR System Information: https://gist.github.com/Techjar/6cf2dbdf9cc672bd2b8ed30aa9aa84dc
* Opted into Steam client beta?: No
* Opted into SteamVR beta?: Yes
* Have you checked for system updates?: Yes

#### Please describe your issue in as much detail as possible:
SteamVR opens and immediately pops up a dialog with the error in the title. No apps will work, not even SteamVR Home or the tutorial. Not really sure what else to say beyond that, as I'm not sure what the next step of figuring this out would be. The log doesn't have anything obvious in it.

Also, I can see the SteamVR menu in the headset, but it's blank.

#### Steps for reproducing this issue:
1. Start SteamVR
2. ???
3. Profit!

**Comment by TTimo** [comment]
- Opt in to Steam client beta and try again

- If that doesn't work, try starting SteamVR from the command line and get a log:
`~/.local/share/Steam/steamapps/common/SteamVR/bin/vrmonitor.sh`

**Comment by Techjar** [comment]
Tried the Steam *and* SteamVR beta, same result. Trying to start the vrmonitor directly results in the following console spew and fails.
```
techjar@techjar-linux ~ $ ~/.local/share/Steam/steamapps/common/SteamVR/bin/vrmonitor.sh
+++ dirname /home/techjar/.local/share/Steam/steamapps/common/SteamVR/bin/vrmonitor.sh
++ cd /home/techjar/.local/share/Steam/steamapps/common/SteamVR/bin/..
++ pwd
+ TOOLSDIR=/home/techjar/.local/share/Steam/steamapps/common/SteamVR
++ cd /home/techjar/.local/share/Steam/steamapps/common/SteamVR/../runtime
/home/techjar/.local/share/Steam/steamapps/common/SteamVR/bin/vrmonitor.sh: line 3: cd: /home/techjar/.local/share/Steam/steamapps/common/SteamVR/../runtime: No such file or directory
++ pwd
+ RUNTIMEDIR=/home/techjar
+ case $(uname) in
++ uname
+ '[' -z '' ']'
+ exec /home/techjar/.steam/steam/ubuntu12_32/steam-runtime/run.sh /home/techjar/.local/share/Steam/steamapps/common/SteamVR/bin/vrmonitor.sh
/home/techjar/.local/share/Steam/steamapps/common/SteamVR/bin/vrmonitor.sh: line 14: /home/techjar/.steam/steam/ubuntu12_32/steam-runtime/run.sh: No such file or directory
```

**Comment by Techjar** [comment]
I created the missing run.sh script from the steam-runtime repository, now it runs and produces the original error. Here's the full console output: https://gist.github.com/Techjar/b7d5c4cf4fb38df1ef9e83098332ee74

**Comment by Balderick** [comment]
On windows, using non vive hardware, I've found the current beta channels constantly throw 306.   Only the stable branch of client along with stable branch of steamvr allows steamvr to start up without error.

Might be worth a try on Linux.

**Comment by TTimo** [comment]
@Techjar thanks for grabbing run.sh out of the runtime, didn't realize that would be missing in default installation (something else to investigate).

Can you grab this modified vrmonitor.sh and run again? https://gist.github.com/TTimo/b8e462be86a826bc92e9244906caad91

**Comment by kisak-valve** [comment]
If a user only uses steam with STEAM_RUNTIME=0, like is set by steam-native from Arch, then an old or missing steam runtime is the expected result.

**Comment by Techjar** [comment]
Yeah I should add that I installed Steam from the package manager, as the download on the website is a Debian package. Not particularly useful on Arch.

**Comment by Techjar** [comment]
Here's the log from your modified vrmonitor.sh: https://gist.github.com/Techjar/c6abbaf3f6846843528e1aef07831a9a

**Comment by TTimo** [comment]
Thanks @kisak-valve .. I didn't realize that Arch (and derivatives) is repackaging and modifying the Steam runtime environment setup.

@Techjar unfortunately this latest log doesn't reveal anything new. The ldd against vrclient.so in the log suggests that the runtime expected by steam in ~/.steam/steam/ubuntu12_32/steam-runtime isn't really there, and you are using your distribution's main libraries instead.

My best guess is that you are failing to load some other library (not vrclient.so), probably due to an outdated or incorrect steam-runtime.

You could maybe remove or move aside that folder to force the Steam client to refresh and download a new one. I don't know if the Arch modifications will interfere with doing that. Maybe an issue should be opened with the maintainers of Arch's steam packages instead (or you could consider using a distribution that supports the steam package as is).

**Comment by kisak-valve** [comment]
Arch should also provide a steam-runtime startup script for steam to complement the steam-native variant, which would bring the steam runtime up to the current version.

The general stance I have with systems that do not run the steam runtime is that if the steam runtime is disabled, then either the package maintainer or the user who disabled it should look after any missing dependencies.

**Comment by Techjar** [comment]
Yeah I ran steam-runtime and the issue is gone now. I never actually knew what the difference was, so I was just running steam-native. Whoops.

**Comment by Techjar** [comment]
Side note: after some testing, I have determined that SteamVR on linux is very touch-and-go.

**Comment by TTimo** [comment]
Thank you. Sounds like your immediate issue is resolved.
