### ISSUE TITLE
[BUG] No available applications to open vrmonitor://quit

### ISSUE THREAD

**Issue by anxest** [ValveSoftware/SteamVR-for-Linux#710]
**Can't exit SteamVR from dashboard**
From SteamVR dashboard, when I try to exit (to close SteamVR), the button doesn't close the application. Instead Gnome opens a windows telling there is no available application to open "vrmonitor://quit".

**To Reproduce**
1. Start SteamVR
2. From your headset, open the dashboard, and click on the menu, bottom left of the dashboard
3. Click on Exit VR from this menu
4. Get your headset off to see the windows on gnome desktops.

**Expected behavior**
Closing SteamVR after clicking in the dashboard menu instead of leaving through steam on desktop

**System Information (please complete the following information):**
Please use the latest Steam beta client and SteamVR beta for your bug reports!

* Steam client version (build number or date): beta 1718305227
* SteamVR version: beta 2.6.2
* Distribution : Archlinux (Linux 6.9.3-arch1-1) + Gnome Shell 46 (X11)
* Steam runtime diagnostics: [steam-runtime-Diagnostics](https://gist.github.com/anxest/8a3e5ccd4aeaa470e34ce9ae488f496f)
* Steam and SteamVR logs: [steam-logs.tar.gz](https://github.com/user-attachments/files/15840422/steam-logs.tar.gz)
* Minidumps: [steam-minidumps.tar.gz](https://github.com/user-attachments/files/15840437/steam-minidumps.tar.gz)

**Screenshots**
![Capture d’écran du 2024-06-14 17-07-05](https://github.com/ValveSoftware/SteamVR-for-Linux/assets/19307400/1cd88711-c781-49bc-b875-9b1438ee3982)

**Comment by anxest** [comment]
Same issue with the vrmonitor://restartsystem (if I change an option in the settings and a restart is needed for example).
![Capture d’écran du 2024-06-14 18-00-03](https://github.com/ValveSoftware/SteamVR-for-Linux/assets/19307400/2c7e40dd-6463-4cc0-a3c7-f3bc3ee869d1)

**Comment by jessy-bellanger** [comment]
Hi, I have the same problem with Pop OS 22.04, which uses GNOME 42.9.

**Comment by okawo80085** [comment]
As i mentioned in https://github.com/ValveSoftware/openvr/issues/1864, just calling `xdg-open` with the misbehaving links makes it work, at least in the case of the web console, is SteamVR not calling `xdg-open`  or is there an issue with accessing the xdg environment from SteamVR?

**Comment by fritogotlayed** [comment]
I just built a new computer and moved to Pop_OS! as jessy-bellanger and am also getting the same issue. I also noticed that things like the steam VR home wont launch / run either. I think it's called VR Home. It's the little demo-like world where you have a virtual house and can launch games from there. I'm hoping this clears up when Pop updates to 24.04 & cosmic but I'm subscribing to this issue in hopes to add some traffic and gain some traction.

**Comment by fritogotlayed** [comment]
Not sure what is different now but I ran Pop_OS! updates update (there were some system ones) and did a full reboot of my system due to some unrelated Intellij issues. I just used the exit from inside the vr menu successfully.

**Comment by anxest** [comment]
Hello, I just tried and can confirm it's no longer an issue on Arch with gnome shell. So I'm closing this issue.

**Comment by Milliw** [comment]
I have had this since ever when using SteamVR on Linux with Gnome. Still an issue for me on Nobara 40 with Gnome 46.

**Comment by KibaGasteiz** [comment]
Yes, i'm still affected by this.

**Comment by okawo80085** [comment]
Probably worth mentioning, i recently had to reinstall my distro, and the newly installed steam+ steamvr did not setup uri handlers at all, however after digging for an entire day, i managed to find the contents of the missing desktop files in this issues https://github.com/ValveSoftware/SteamVR-for-Linux/issues/457

adding those to `~/.local/share/applications` with paths relevant for my user and then setting them as the default handlers with `xdg-mime default <desktop file> 'x-scheme-handler/<vrmonitor or steamvr>'` fixed the issue for me

**Comment by okawo80085** [comment]
Going to probably also open an issue for the Void steam package, because im pretty sure other distros setup uri handlers as part of their packages
