### ISSUE TITLE
[BUG] Wrong display of the battery of Valve Index controllers

### ISSUE THREAD

**Issue by anxest** [ValveSoftware/SteamVR-for-Linux#711]
**In SteamVR, something unusual is displayed on the Index controllers' handle**
A few years ago, on the handle of the Index controllers, through my headset, I was able to see the remaining battery for each of them. Since, it's displayed in very little over some other pictures, like the video stream of the dashboard and some other windows.

**To Reproduce**
1. Start SteamVR
2. Open SteamVR dashboard from the headset
3. Look at your controllers handle

**Expected behavior**
Displaying only the remaining battery level in a readable size.

**System Information (please complete the following information):**
Please use the latest Steam beta client and SteamVR beta for your bug reports!

* Steam client version (build number or date): beta 1718305227
* SteamVR version: beta 2.6.2
* Distribution : Archlinux (Linux 6.9.3-arch1-1) + Gnome Shell 46 (X11)
* Steam runtime diagnostics: [steam-runtime-Diagnostics](https://gist.github.com/anxest/8a3e5ccd4aeaa470e34ce9ae488f496f)
* Steam and SteamVR logs: [steam-logs.tar.gz](https://github.com/user-attachments/files/15840422/steam-logs.tar.gz)
* Minidumps: [steam-minidumps.tar.gz](https://github.com/user-attachments/files/15840437/steam-minidumps.tar.gz)

**Screenshots**
![Capture d’écran du 2024-06-14 17-05-53](https://github.com/ValveSoftware/SteamVR-for-Linux/assets/19307400/3bbf12f6-d9c2-476a-8855-4838ddc6f09f)

**Comment by kisak-valve** [comment]
Hello @anxest, this issue is already being tracked at #571. Closing as a duplicate.
