### ISSUE TITLE
[BUG] Issue Title

### ISSUE THREAD

**Issue by ford220102** [ValveSoftware/SteamVR-for-Linux#717]
the point was that they were faulty and why don't you fix the kernel and the keyboard and the steamdeck pad and the system because they are already faulty DEBIAN only fedora PLEASE check them completely and it should also work for windows with steamos

NEW fixed SYSTEM error please all

**Comment by kisak-valve** [comment]
Duplicate of https://github.com/ValveSoftware/SteamOS/issues/1555, and this makes even less sense directed at SteamVR.
