### ISSUE TITLE
[BUG] [Wayland] SteamVR Setting window is a black screen and breaks inputs

### ISSUE THREAD

**Issue by Lifeismana** [ValveSoftware/SteamVR-for-Linux#720]
**Describe the bug**
SteamVR Settings window is black screen when launching SteamVR.
This issue is more problematic than it seems since it seems to break inputs when in-game 
It's worth noting that SteamVR's ui inside the headset is working fine

**To Reproduce**
1. Launch SteamVR
2. SteamVR launches and a setting window pops-up but is fully black 
3. Launch a game
4. Try any inputs (e.g: trigger press), None are registered

**Expected behavior**
The Setting window should show up correctly & in-game inputs should work 

**System Information (please complete the following information):**
Please use the latest Steam beta client and SteamVR beta for your bug reports!
* Steam client version (build number or date): 1719967667 Wed, Jul 3 00:38 UTC -08:00
* SteamVR version: beta 2.7.2; stable 2.6.2; previous 2.5.5
* Distribution (e.g. Ubuntu): Arch (KDE 6.1.2 ,Wayland, Nvidia 555.58.02)
* Steam runtime diagnostics: [runtime.txt](https://github.com/user-attachments/files/16124713/runtime.txt)
* Steam and SteamVR logs: [steam-logs.tar.gz](https://github.com/user-attachments/files/16124732/steam-logs.tar.gz)
* Minidumps: [steam-minidumps.tar.gz](https://github.com/user-attachments/files/16124743/steam-minidumps.tar.gz)

**Screenshots**
![image](https://github.com/ValveSoftware/SteamVR-for-Linux/assets/15911822/7d45601a-efd4-42b7-97ca-096f52434898)

**Additional context**
I didn't check if this was also happening under X11 yet

**Comment by LazyHatGuy** [comment]
I'm having the same problem

**Comment by Lifeismana** [comment]
i think that i finally resolved that by deleting the `vrappconfig` folder & `steamvr.vrsettings` file under `~/.local/share/Steam/config/` (might be worth it to close steam before doing that)

**Comment by kotleni** [comment]
same bug
