### ISSUE TITLE
[PERF] [BUG] severe stutter with Nvidia 555 driver

### ISSUE THREAD

**Issue by trashhead101** [ValveSoftware/SteamVR-for-Linux#723]
**Describe the bug**
After using the newest NVIDIA 555 driver (KDE Plasma), SteamVR is subject to immense stutter.
The stutter is strongly only visible when moving your head with the headset on (Looks like a frame from a few milliseconds ago is rendered on the headset). 
The lag is visible in the little SteamVR window, with the display performance graph enabled, via tons of pink markers.
(
Weirdly the strength of the stutter changes (in the SteamVR home) after what king of window is open / coveres the desktop, where the files are displayed. For example a browser with excactly reddit open reduces/deminished the stutter nearly completely, while the stutter is only slightly lowered by having a browser without a website or a website like Youtube open. You can check the pictures attached to see this.
In a real game, no matter what windows are opened, there is constant stutter and it is basically not playable.
)

**To Reproduce**
1. open SteamVR
2. See pink lines / errors in the little SteamVR window

**Expected behavior**
no stutter.

**System Information (please complete the following information):**
- Distribution: Arch
- Desktop: Plasma 6
- SteamVR version: 2.7.2 (tested on beta and normal SteamVR version / happens on both)
- Opted into Steam client beta?: No
- NVIDIA GPU: (quite strong: 4070 super)
- Graphics driver version:  NVIDIA 555.58.02 (with explicit sync)
- Gist for SteamVR System Information: https://gist.github.com/trashhead101/166a4c2d5738188498c8dd732717de03

- used vr headset: HTC vive

**Comment by kisak-valve** [comment]
Hello @trashhead101, this reads like https://github.com/ValveSoftware/SteamVR-for-Linux/issues/631#issuecomment-2209439380 and following comments. Can you test how SteamVR behaves with GSP disabled or with the NVIDIA 550 series driver?

**Comment by trashhead101** [comment]
well, the problem started with NVIDIA 555 driver, but rolling back driver would be to much trouble for me. Can you provide me a way to disable GSP?

**Comment by kisak-valve** [comment]
I don't have a better testing suggestion than https://github.com/ValveSoftware/SteamVR-for-Linux/issues/631#issuecomment-2216836976.

**Comment by trashhead101** [comment]
Ah, I got it. It works with disabled GSP:

Here the way to do it:

1. go to /etc/modprobe.d/ (`cd /etc/modprobe.d/`)

2. create a file called nvidia.conf (`sudo nano nvidia.conf`)

3. and then write `options nvidia NVreg_EnableGpuFirmware=0`

4. now on: [Rebuilding the initial ramdisk]
- Arch Linux: `sudo mkinitcpio -P`
- Fedora: (one of both, I don't know what of both) `dracut-rebuild` or `sudo dracut --force`
- Debian/Ubuntu: `sudo update-initramfs -u`
- openSUSE: `sudo mkinitrd`
- Gentoo: `sudo dracut --force`

5. reboot the pc and enjoy a smooth SteamVR

**Comment by trashhead101** [comment]
thank you @kisak-valve

**Comment by mDuo13** [comment]
Thanks @kisak-valve and @trashhead101 , that did in fact solve my problems!
