### ISSUE TITLE
> mb coz your version of steam link is older then mine?

### ISSUE THREAD

**Issue by WaldUndWiese** [ValveSoftware/SteamVR-for-Linux#728]
> mb coz your version of steam link is older then mine?

Hello. Might I ask what version of SteamVR you're using? I'm using beta as per ALVR's suggestions but I still get the compatability error.

_Originally posted by @SolAZDev in https://github.com/ValveSoftware/SteamVR-for-Linux/issues/655#issuecomment-2254302402_
            
I use SteamVR version 2.6.2 (Built: May 25, 2024) and ALVR v20.9.1. 
I do not use the ALVR option "registered drivers".
I use the start option in SteamVR ...

Add ~/.local/share/Steam/steamapps/common/SteamVR/bin/vrmonitor.sh %command% to the commandline options of SteamVR (SteamVR -> Manage/Right Click -> Properties -> General -> Launch Options).
https://github.com/alvr-org/ALVR/wiki/Linux-Troubleshooting

**Comment by kisak-valve** [comment]
Hello @WaldUndWiese, this doesn't look like a distinct and actionable issue for a SteamVR dev to ponder. Instead it looks like a reply to a comment that should have been added to #655, so I've transferred this issue report to https://github.com/ValveSoftware/SteamVR-for-Linux/issues/655#issuecomment-2254503684.
