### ISSUE TITLE
[BUG] System crash and logs off when opening non-steam VR game

### ISSUE THREAD

**Issue by Murilovsky** [ValveSoftware/SteamVR-for-Linux#730]
**Describe the bug**
Trying to play a non-steam VR game in SteamVR freezes the screen in both HMD and Monitor immediately. The computer user session ends after some time.  Happens on Native and Proton Games

**To Reproduce**
1. Download any VR game from anywhere other then Steam (Used OpenSaber as an example)
2. Add it to the game to the library as a Non-Steam game
3. Check the "Include on VR Library" toggle in game's properties
4. Run the added game

**Expected behavior**
The game opens and shows on screen, or maybe crash but without hanging the system/session

**System Information:**

- Ubuntu 24.04
- kernel 6.8.0-40-generic
- AMD RX 7600 GPU
- Mesa 24.1.5 - kisak-mesa PPA
- Ryzen 7 5700X CPU
- 32GB DDR4 RAM
- Gnome Wayland Session

* Steam client version :1721173382
* SteamVR version: Beta 2.8.2
* Distribution: Ubuntu 24.04
* Steam runtime diagnostics: https://gist.github.com/Murilovsky/9adfc2f91ca76cf98ce4144d7067948c
* Steam and SteamVR logs: [steam-logs.tar.gz](https://github.com/user-attachments/files/16575618/steam-logs.tar.gz)
* Minidumps: [steam-minidumps.tar.gz](https://github.com/user-attachments/files/16575622/steam-minidumps.tar.gz)

**Additional context**
Using ALVR to stream game from PC to Oculus Quest 2

**Comment by kisak-valve** [comment]
Hello @Murilovsky, for reference, your first crash_* minidump is a SIGABRT in libc.so.6 coming from radeonsi_drv_video.so and your second crash_* minidump is a SIGABRT in libc.so.6 coming from vrcompositor.real.

From your console-linux.txt log:
```
>>> Starting desktop stream
WARNING: Desktop capture unavailable, try running Steam with -pipewire
amdgpu: The CS has cancelled because the context is lost. This context is innocent.
crash_20240811145111_2.dmp[17881]: Uploading dump (out-of-process)
/tmp/dumps/crash_20240811145111_2.dmp
crash_20240811145111_2.dmp[17881]: Finished uploading minidump (out-of-process): success = yes
crash_20240811145111_2.dmp[17881]: response: CrashID=bp-5ef014ac-8088-4600-8c68-10eb72240811
crash_20240811145111_2.dmp[17881]: file ''/tmp/dumps/crash_20240811145111_2.dmp'', upload yes: ''CrashID=bp-5ef014ac-8088-4600-8c68-10eb72240811''
X connection to :0 broken (explicit kill or server shutdown).
```
It hints that Steam Remote Play was starting up vaapi encoding, there was a video driver issue, and X got kicked out from underneath everything. This issue should be reported to your video driver vendor.

**Comment by Murilovsky** [comment]
Okay. Thanks for clarifying!
