### ISSUE TITLE
[BUG] xrCreateInstance failed in DCS

### ISSUE THREAD

**Issue by makerio90** [ValveSoftware/SteamVR-for-Linux#734]
**Describe the bug**
when trying to open dcs in vr mode, the game crashed instantly. viewing log files shows a `xrCreateInstance failed` error

**To Reproduce**
1. dcs latest version,
2. steamvr any beta (im  using beta but still occurs on main release)
3. launch dcs
4. nothing happens, game crashes seconds later.

**Expected behavior**
game should open normally

**System Information (please complete the following information):**
Please use the latest Steam beta client and SteamVR beta for your bug reports!

* Steam client version (build number or date): 1721173382
* SteamVR version: 2.8.3
* Distribution (e.g. Ubuntu): arch
* Steam runtime diagnostics: [pastebin](https://pastebin.com/kPvVrPyU)
* Steam and SteamVR logs: [steam-logs.tar.gz](https://github.com/user-attachments/files/16681978/steam-logs.tar.gz)
* Minidumps: [steam-minidumps.tar.gz](https://github.com/user-attachments/files/16681987/steam-minidumps.tar.gz)

**Screenshots**

**Additional context**
- The game worked before, its only recently that it broke.
- other vr games work
- if the logs for dcs arent in one of those tarballs lmk i can copy-paste

**Comment by kisak-valve** [comment]
Hello @makerio90, we're tracking issues with games run with Proton in the Proton issue tracker. Also, we're using one issue report per unofficially supported game title, so I've gone ahead and  transferred this issue report to https://github.com/ValveSoftware/Proton/issues/1722#issuecomment-2299806747.
