### ISSUE TITLE
[SOLVED][BUG] SteamVR fails to start on Fresh Install of Ubuntu-Studio 24.04.1 LTS (Noble Numbat)

### ISSUE THREAD

**Issue by KawaneRio** [ValveSoftware/SteamVR-for-Linux#736]
## Summary
SteamVR was kinda working? on Fresh Install of Ubuntu-Studio 24.04.01. When I had initially installed steam (and SteamVR) right after the fresh installation of ubuntu, the SteamVR would start but would not output anything to the HMD nor will it produce a VR View. It did recognize my HMD, my 3 VIVE trackers, and my two Index controllers, as they were all shown green in the little SteamVR window.  I updated the drivers on my Valve Index Controllers and now the SteamVR does not start anymore. The VR monitor window won't even open; it just automatically stops whenever I click Play.  

I tried peeking at the [`/home/kawanerio/steam-250820.log`](https://gist.github.com/KawaneRio/fbc573cdc87aa0f71bc2aa98cfce95d6) which was created by `PROTON_LOG=1 %command%` startup option for SteamVR and found `err:steam:initialize_vr_data Could not load libopenvr_api.so.` present. Maybe it's related to [ [BUG] vrpathreg misses libopenvr_api.so in the same directory #478 ](https://github.com/ValveSoftware/SteamVR-for-Linux/issues/478)? I don't know I am a newbie ubuntu user. 

## Steps Taken
This is a list of things I've done to my machine as much as I could remember (I may produce incorrect or inaccurate output due to the nature of human brain).
1. Install fresh Ubuntu-Studio from https://ubuntustudio.org/
2. Recover backup from copy&pasted directory in storage and from deja-dup
3. Install flatpak Steam on Discover because I did not know any better
![image](https://github.com/user-attachments/assets/2234950c-7399-4a68-8856-bfa751e62ede)
![image](https://github.com/user-attachments/assets/ac96ebb8-c904-49c8-933e-55c56d244b68)
4. Also install flatpak Proton-GE (community build) because.
![image](https://github.com/user-attachments/assets/2a7c4c25-d719-4816-b1fb-e455674be20d)
5. Okay so the flatpak version of Steam is really having a hard time writing to my external HDDs and on top of that SteamVR won't go pass through "SteamVR needs superuser" dialog (it just spits an error and quits). Maybe flatpak was a mistake.
![Spectacle_20240916_015805](https://github.com/user-attachments/assets/76e6c02d-aa5e-4743-88c8-73cb8073262c)
<details><summary>Screenshots of Flatpak Steam just quitting after the superuser dialog box</summary>

![Spectacle_20240916_015524](https://github.com/user-attachments/assets/556ed291-054b-4af0-aa0f-18f50c194d1c)
![Spectacle_20240916_015753](https://github.com/user-attachments/assets/42192b0f-6795-4024-ba34-ee5fecb10633)

</details>
6. Uninstall flatpak Steam and flatpak Proton-GE using Discover.
7. install Steam (installer) from Discover (making sure to change the source to Ubuntu and not Flatpak!)
8. Something did not work, so I ran `dpkg --add-architecture i386; apt update`

<details><summary>Screenshots of me installing fresh Steam from ubuntu</summary>

Accepting Steam
![Spectacle_20240916_022657](https://github.com/user-attachments/assets/6f64cf9b-611c-4e32-a812-85a03e9ad3cd)
Installing Steam
![Spectacle_20240916_022711](https://github.com/user-attachments/assets/0a4f9c65-e459-41bf-aa0e-91a889fe3670)
Updating Steam
![Spectacle_20240916_023630](https://github.com/user-attachments/assets/d650ffd7-0948-474a-81b8-71490726c495)
Installing VRChat
![Spectacle_20240916_024024](https://github.com/user-attachments/assets/bd36b6a5-5e86-4973-9edd-64de019f4c7c)
Installing SteamVR
![Spectacle_20240916_025937](https://github.com/user-attachments/assets/d875e420-8042-442e-b837-6db6cc6749cf)
Granting Permission for SteamVR
![Spectacle_20240916_025947](https://github.com/user-attachments/assets/e8f25bdc-4e8d-41c5-bfca-264ff17509e8)

</details>

11. lots of `Target Packages is configured multiple times` warning has been coming up, perhaps due to me forcefully moving things from the backups, and it was annoying. I fixed this by commenting out the contents in `/etc/apt/sources.list.d/dvd.list`
![image](https://github.com/user-attachments/assets/1c281fca-477b-491a-92e3-5739347f898b)
12. `can't set the locale; make sure $LC_* and $LANG are correct` was also showing up since I booted the machine. I fixed this by running `sudo locale-gen ja_JP.UTF-8` and `sudo dpkg-reconfigure locales` in accordance to [this article](https://qiita.com/homoluctus/items/97a0e9f03529966ab2a4) I found.  
14. My external HDD is writable at last! and my SteamVR starts! yay! oh? my controller needs upgrading! I shall do that! (updates the drivers for both of my Valve Index controllers successfully) ![image](https://github.com/user-attachments/assets/533fe4b0-6f12-457e-8824-da33f27ab3e6)
15. (my memory gets foggy around here) I remember not getting past this screen so I gave up. 
<details>

<summary>Screenshots of Room Setup</summary>

![image](https://github.com/user-attachments/assets/e2b9274c-bb5d-45b3-b75b-b6d9ae94f9a6)
![image](https://github.com/user-attachments/assets/f5bead15-b831-4ffb-87aa-02d1a177b7b1)

</details>

16. noooo SteamVR won't start anymore whyyyy I've tried rebooting but it doesn't worrrrk :sob: 
17. Oh yeah, maybe installing Valve-Kisak mesa drivers could help!: Runs `sudo add-apt-repository ppa:kisak/kisak-mesa` and `sudo apt update`
18. Nope.
19. While writing this issue, I've tried to run SteamVR using Steam Linux Runtime 3.0 (sniper) and, well, uh, it... started??? Error 496  is still present, and still nothing is being recognized by the Room Setup, but I can generate a [report](https://gist.github.com/KawaneRio/e92be9f457b05e1b6c281540e7524609) now!
![image](https://github.com/user-attachments/assets/58057cff-6359-432d-872a-344bc4005c8c)

<details>

<summary>Screenshots of SteamVR miraclously starting with Steam Linux Runtime 3.0 (sniper)</summary>

![Spectacle_20240916_145233](https://github.com/user-attachments/assets/f4a7836a-5b81-4ecf-9fa4-7dfaaa25fd82)</details>

20. PS.2. It stopped working again. 

## Expected behavior
1. Install Ubuntu
2. Install Steam
3. Install SteamVR
4. Play VRChat

Alternatively, I would just like the Room Setup to work *just once* so I can try out OpenXR with lighthouse tracking.

## System Information
I am using the latest Steam beta client, Photon Experimental, and SteamVR beta.

### About Steam
```
Steamベータブランチ:  Steam Beta Update
Steamバージョン:  1726256783
Steamクライアントビルド日:  9月13日(金) 14:23 UTC +09:00
Steam Webビルド日:  9月12日(木) 3:53 UTC +09:00
Steam APIバージョン:  SteamClient021
```

### About SteamVR
Well, since it fails to start, I can't really write much here. I will say that I have tried to open SteamVR on beta, previous, temp, and oculus_win7and8 but none of them worked. I have also tried using Proton 9.0-2 but with no avail.

[SteamVR System Report](https://gist.github.com/KawaneRio/e92be9f457b05e1b6c281540e7524609)

## My Enviroment
I am on Ubuntu 24.04.1 using Wayland
<details>

<summary>neofetch and inxi --basic</summary>

![Spectacle_20240916_151154](https://github.com/user-attachments/assets/6b429a68-acc1-4cb4-9dcb-aff94ff2e83a)

`inxi --basic`
```
System:
  Host: KawaneLinux Kernel: 6.8.0-44-lowlatency arch: x86_64 bits: 64
  Desktop: KDE Plasma v: 5.27.11 Distro: Kubuntu 24.04.1 LTS (Noble Numbat)
Machine
  Type: Desktop System: Gigabyte product: X570 UD v: N/A
    serial: <superuser required>
  Mobo: Gigabyte model: X570 UD serial: <superuser required> UEFI: American
    Megatrends LLC. v: F36e date: 10/13/2021
CPU:
  Info: 12-core AMD Ryzen 9 5900X [MT MCP] speed (MHz): avg: 4573
    min/max: 2200/4950
Graphics:
  Device-1: AMD Navi 23 [Radeon RX 6600/6600 XT/6600M] driver: amdgpu
    v: kernel
  Device-2: AMD Ellesmere [Radeon RX 470/480/570/570X/580/580X/590]
    driver: amdgpu v: kernel
  Device-3: Valve 3D Camera driver: uvcvideo type: USB
  Display: wayland server: X.org v: 1.21.1.11 with: Xwayland v: 23.2.6
    compositor: kwin_wayland driver: X: loaded: amdgpu
    unloaded: fbdev,modesetting,radeon,vesa dri: radeonsi gpu: amdgpu,amdgpu
    resolution: 1920x1080
  API: OpenGL v: 4.6 compat-v: 4.5 vendor: amd mesa v: PPA renderer: AMD
    Radeon RX 580 Series (radeonsi polaris10 LLVM 17.0.6 DRM 3.57
    6.8.0-44-lowlatency)
Network:
  Device-1: Realtek RTL8111/8168/8211/8411 PCI Express Gigabit Ethernet
    driver: r8169
  Device-2: Intel Wi-Fi 6E AX210/AX1675 2x2 [Typhoon Peak] driver: iwlwifi
Drives:
  Local Storage: total: 20.47 TiB used: 1.17 TiB (5.7%)
Info:
  Memory: total: 48 GiB available: 46.97 GiB used: 16.4 GiB (34.9%)
  Processes: 648 Uptime: 11h 3m Shell: Bash inxi: 3.3.34
```

</details>

##  Steam Runtime Info
https://gist.github.com/KawaneRio/ab95468a1e70aab0cda4723a21bbb1f4

## Steam Logs
`tar -zcvf ~/Desktop/steam-logs.tar.gz ~/.steam/steam/logs`
[logs.tar.gz](https://usercontent.misskey.online/x8pja9wa/9615d074-1c27-4d3d-bc5b-c0301d41421a)

## Minidumps
`tar -zcvf ~/Desktop/steam-minidumps.tar.gz /tmp/dumps`
[steam-minidumps.tar.gz](https://usercontent.misskey.online/x8pja9wa/08300ce4-ee29-406b-bc90-828c0b2d53d2)

## PROTON_LOG

[steam-250820.log](https://gist.github.com/KawaneRio/fbc573cdc87aa0f71bc2aa98cfce95d6)

<details>

<summary>Screenshot that tells you where to insert the `PROTON_LOG=1 %command%` in order to collect the logs</summary>

![Spectacle_20240916_133055](https://github.com/user-attachments/assets/64a3d903-933b-44f5-a424-bec1b88f14e6) 

</details>

## Related?

#478

**Comment by KawaneRio** [comment]
I've tried using X11 instead of Wayland but did not work

**Comment by KawaneRio** [comment]
Proton 8.0-5 did not work

**Comment by KawaneRio** [comment]
GE-Proton9-13 did not work

**Comment by KawaneRio** [comment]
It seems that everytime I change my Proton to Linux Runtime 3.0 and grant superuser permissions, it works. But then when I quit and try to play SteamVR again for the second or third time, it fails :thinking:

**Comment by KawaneRio** [comment]
It works with Steam Linux Runtime 1.0 (scout) as well.
When I say "it works", it just means that SteamVR starts with an Error 496. Also, Room Setup is useless as I cannot proceed past the HMD and Controller recognition slide.

**Comment by KawaneRio** [comment]
So, um, update. 
SteamVR works now. Here is what I did:

**I unplugged my Valve Index's HDMI cable from my RX 6600 port and replugged it onto my RX 580's HDMI port.**

![image](https://github.com/user-attachments/assets/c9afe5b4-01a8-4dbc-b3a0-3d7a86af7721)

I then ran SteamVR using Steam Linux Runtime 3.0 (sniper) and, holy Doughnut Princess, my SteamVR works. I can actually see. 

I tried running SteamVR with Proton Experimental, Proton 9.0-2, Proton 8.0-5, and GE-Proton 9-13, but nall had failed; in other words, Steam Linux Runtime 3.0 (sniper) is the only one that works on my system. 

Also, SteamVR tells me that I need to upgrade my BaseStations, but it crashes midway everytime I try to upgrade my basestations. 
![Spectacle_20240917_214406](https://github.com/user-attachments/assets/c7f63748-5aa1-453e-b194-2b722ce7cba8)

```
steam[22611]: Attempting HID Open IMU: LHR-233D74F2
steam[22611]: Lighthouse IMU HID opened
steam[22611]: LHR-233D74F2: Firmware Version 1623823641 WMBUILD-W64$@wmbuild-w64 2021-06-16 FPGA 538(2.26/9/2) BL 1555018800
steam[22611]: LHR-233D74F2: Successfully fetched gyro/accelerometer range modes from the device. GyroRangeMode:1 AccelRangeMode:1
steam[22611]: Attempting HID Open Optical: LHR-233D74F2
steam[22611]: Lighthouse Optical HID opened
steam[22611]: Attempting HID Open VrController: LHR-233D74F2
steam[22611]: Lighthouse VrController HID opened
steam[22611]: LHR-233D74F2: Read config of 3097 bytes from [vid:28de, pid:2300] (LHR-233D74F2) and inflated to 9742 bytes
steam[22611]: Attempting HID Open IMU: 0ECC0F3C6E-RYB
steam[22611]: Lighthouse IMU HID opened
steam[22611]: 0ECC0F3C6E-RYB: Firmware Version 1693638519 WMBUILD-W64$@wmbuild-w64 2023-09-02 FPGA 538(2.26/10/2) BL 0
steam[22611]: LHR-8D43ACB1: Connected to receiver 0ECC0F3C6E-RYB
steam[22611]: LHR-8D43ACB1: Protocol versioning supported, requesting 1
steam[22611]: 0ECC0F3C6E-RYB: Successfully fetched gyro/accelerometer range modes from the device. GyroRangeMode:3 AccelRangeMode:2
steam[22611]: LHR-8D43ACB1: Transition to protocol version 1
steam[22611]: Attempting HID Open IMU: 43E467C198-LYM
steam[22611]: Lighthouse IMU HID opened
steam[22611]: 43E467C198-LYM: Firmware Version 1693638519 WMBUILD-W64$@wmbuild-w64 2023-09-02 FPGA 538(2.26/10/2) BL 0
steam[22611]: LHR-AE0D2AA4: Connected to receiver 43E467C198-LYM
steam[22611]: LHR-AE0D2AA4: Protocol versioning supported, requesting 1
steam[22611]: 43E467C198-LYM: Successfully fetched gyro/accelerometer range modes from the device. GyroRangeMode:3 AccelRangeMode:2
steam[22611]: LHR-8D43ACB1: Optical subprotocol changed version 0
steam[22611]: LHR-8D43ACB1: Controller subprotocol changed version 0
steam[22611]: LHR-AE0D2AA4: Transition to protocol version 1
steam[22611]: Attempting HID Open IMU: LHR-B7F1F09F
steam[22611]: Lighthouse IMU HID opened
steam[22611]: LHR-B7F1F09F: Firmware Version 1541806442 RUNNER-WATCHMAN$runner-watchman@runner-watchman 2018-11-10 FPGA 531(2.19/7/2) BL 1517470641
steam[22611]: UserData Error: Data request is out of range, request starting:0x0, ending:0x18, max address:0x3
steam[22611]: LHR-B7F1F09F: Successfully fetched gyro/accelerometer range modes from the device. GyroRangeMode:3 AccelRangeMode:2
steam[22611]: LHR-AE0D2AA4: Optical subprotocol changed version 0
steam[22611]: LHR-AE0D2AA4: Controller subprotocol changed version 0
steam[22611]: Attempting HID Open Optical: LHR-B7F1F09F
steam[22611]: Lighthouse Optical HID opened
steam[22611]: Attempting HID Open VrController: LHR-B7F1F09F
steam[22611]: Lighthouse VrController HID opened
steam[22611]: LHR-B7F1F09F: Read config of 2197 bytes from [vid:28de, pid:2300] (LHR-B7F1F09F) and inflated to 8739 bytes
steam[22611]: Attempting HID Open IMU: LHR-2FE972D6
steam[22611]: Lighthouse IMU HID opened
steam[22611]: LHR-2FE972D6: Firmware Version 1541806442 RUNNER-WATCHMAN$runner-watchman@runner-watchman 2018-11-10 FPGA 531(2.19/7/2) BL 1517470641
steam[22611]: UserData Error: Data request is out of range, request starting:0x0, ending:0x18, max address:0x3
steam[22611]: LHR-2FE972D6: Successfully fetched gyro/accelerometer range modes from the device. GyroRangeMode:3 AccelRangeMode:2
steam[22611]: Attempting HID Open Optical: LHR-2FE972D6
steam[22611]: Lighthouse Optical HID opened
steam[22611]: Attempting HID Open VrController: LHR-2FE972D6
steam[22611]: Lighthouse VrController HID opened
steam[22611]: LHR-2FE972D6: Read config of 2200 bytes from [vid:28de, pid:2300] (LHR-2FE972D6) and inflated to 8741 bytes
steam[22611]: Attempting HID Open IMU: LHR-4DD3CCCD
steam[22611]: Lighthouse IMU HID opened
steam[22611]: LHR-4DD3CCCD: Firmware Version 1541806442 RUNNER-WATCHMAN$runner-watchman@runner-watchman 2018-11-10 FPGA 531(2.19/7/2) BL 1517470641
steam[22611]: UserData Error: Data request is out of range, request starting:0x0, ending:0x18, max address:0x3
steam[22611]: LHR-4DD3CCCD: Successfully fetched gyro/accelerometer range modes from the device. GyroRangeMode:3 AccelRangeMode:2
steam[22611]: Attempting HID Open Optical: LHR-4DD3CCCD
steam[22611]: Lighthouse Optical HID opened
steam[22611]: Attempting HID Open VrController: LHR-4DD3CCCD
steam[22611]: Lighthouse VrController HID opened
steam[22611]: LHR-4DD3CCCD: Read config of 2195 bytes from [vid:28de, pid:2300] (LHR-4DD3CCCD) and inflated to 8738 bytes
```

Aside from that, I think that's all I need for now. Feel free to write what you think, or convince me to use the latest Proton.

**Comment by JaiFail** [comment]
You are so alone here, @KawaneRio ... Me, my SteamVR crashing if I'm trying to connect my headset.
