### ISSUE TITLE
[BUG] Can't open settings

### ISSUE THREAD

**Issue by Perdu** [ValveSoftware/SteamVR-for-Linux#742]
**Describe the bug**

Clicking on Settings either opens an empty window (one that just copies whatever was behind it when opened), or nothing at all. Some other actions opening windows (e.g. developer settings) do work.
I'm on i3vm (X), if that matters.

**To Reproduce**
1. Open SteamVR
2. Click on Settings

**System Information (please complete the following information):**

* Steam client version (build number or date): 1726604483, Tue, Sep 17 10:03 PM UTC -08:00
* SteamVR version: 2.7.4
* Distribution (e.g. Ubuntu): Arch Linux

(logs are pretty long, please tell me what you need exactly)

**Comment by kisak-valve** [comment]
Hello @Perdu, this issue is already being tracked at #597. Closing as a duplicate.
