### ISSUE TITLE
SteamVR settings won't open

### ISSUE THREAD

**Issue by LuNeder** [ValveSoftware/SteamVR-for-Linux#748]
#### Your system information

* Steam client version (build number or date): 1729917543
* SteamVR version: 2.8.6, as well as previous 2.5.5 and beta 2.8.6
* Distribution (e.g. Ubuntu): NixOS unstable
* Opted into Steam client beta?: Yes
* Have you checked for system updates?: Yes
* Steam Logs: [steam-logs.tar.gz](https://github.com/user-attachments/files/17534035/steam-logs.tar.gz)
* GPU: Nvidia (driver 560.35.03)
* (tested on kernel 6.11.3, 6.11.4 and 6.11.5)
* [steam-system-info.txt](https://github.com/user-attachments/files/17534050/steam-system-info.txt)

#### Please describe your issue in as much detail as possible:

SteamVR crashed, and then any subsequent openings of it launch on that (annoying af btw) safe mode. But both the "Manage add-ons" and the "settings" button do nothing at all, the settings window does not show up.
When running steam from the terminal, nothing interesting seems to be logged when the settings button is pressed.

While a fix for this isn't released, are there any ways to reset the SteamVR safe mode thing without going into its settings? Maybe a terminal flag or deleting some file? (a terminal flag to always force skip safe mode would be nice)

#### Steps for reproducing this issue:

1. Open SteamVR
2. Press the settings button on the menu thingy on SteamVR window
3. The settings window does not open

**Comment by LuNeder** [comment]
Uhhh if you uninstall SteamVR entirely and then reinstall it the settings window will open again and you can enable plugins again and etc. However: next time it crashes it will go back to not opening settings window anymore unless you reinstall.

**Comment by LuNeder** [comment]
Uhh, seems to be unrelated to this. 

Settings won't open when using "~/.local/share/Steam/steamapps/common/SteamVR/bin/vrmonitor.sh %command%" as launch args (needed for ALVR), but will when using no launch args. Used to work some weeks ago tho?

**Comment by LuNeder** [comment]
Just like with the (unrelated) ALVR issue, returning to an older nixos generation (which had the same nvidia drivers, so that's not at blame) with the same SteamVR (and ALVR) versions fixes this. I'll try to figure out what exactly changed between working and not working, but it's possible some random library broke this - maybe on other rolling release distros too.


Adding below same thing I mentioned on https://github.com/alvr-org/ALVR/issues/2476#issuecomment-2440059892:

I know this is not entirely helpful, but here's what changed between my newest working alvr system and my oldest not working alvr system: [alvr-gen-diff.txt](https://github.com/user-attachments/files/17534383/alvr-gen-diff.txt). I'll do some more precise testing later today to try to discover exactly what was the problematic package update.

Aditionally, here's a diff between the above not working alvr system and my latest also not working alvr system (just so you know what changes/rollbacks **did not** fix the problem): [alvr-gen-diff2.txt](https://github.com/user-attachments/files/17534395/alvr-gen-diff2.txt)

I'll try to come up with something more specific and useful later today.


I wonder if the same package update caused both of these problems or if they’re caused by entirely different updates. The update I did on oct20 (after previously had only updated on like sep28) broke bluez too, but that was kernel 6.11.4. Right now I’m on 6.11.3, so the kernel is unrelated. Time to do the troubleshooting and testing all over again to find the culprit. I hate myself so much for taking this long to update, this would be way easier to test if there were just a handful of packages changed between updates…

**Comment by thevinter** [comment]
Commenting on this as well. I'm not sure this is relevant to https://github.com/alvr-org/ALVR/issues/2476 as for the past few days the settings menu was (mostly) unresponsive, but I was able to play. Only today I got the "SteamVR errors when opened through ALVR" issue. 

I did some system updates in between, but ALVR was always ran through the v20.11.1 release, so i'm pretty sure it's something outside of ALVR

**Comment by LuNeder** [comment]
This was a me problem that I fixed (unlike the crashing problem which is probably also a me problem (and doesn't happen on my laptop Edit: yes it fucking does) but that I haven't fixed yet)

Oddly enough the settings problem doesn't happen on my laptop either, even tho I didn't remove from my laptops config what I removed to make it work on my desktop...
