### ISSUE TITLE
[BUG] Heavy lagging on desktop while running SteamVR under KDE Plasma Wayland

### ISSUE THREAD

**Issue by the-bukkit** [ValveSoftware/SteamVR-for-Linux#751]
**Describe the bug**
When I launch SteamVR my entire desktop only seems to update very sporadically (see spinner in top right of the video.)
Once SteamVR is closed, everything works like normal again.

**To Reproduce**
1. Launch SteamVR
2. Interact with any application 

**Expected behavior**
I expected for my system to behave about the same as prior to launching SteamVR.

**System Information (please complete the following information):**

* Steam client version (build number or date): 1731112063
* SteamVR version: Version 2.8.6 (1729556249)
* Distribution (e.g. Ubuntu): Arch Linux
* Steam runtime diagnostics: [Steam Runtime Diagnostics.txt](https://github.com/user-attachments/files/17706354/Steam.Runtime.Diagnostics.txt)
* Steam and SteamVR logs: [steam-logs.tar.gz](https://github.com/user-attachments/files/17706442/steam-logs.tar.gz)

* Minidumps: [steam-minidumps.tar.gz](https://github.com/user-attachments/files/17706443/steam-minidumps.tar.gz)

**Screenshots**

https://github.com/user-attachments/assets/ea57c8ec-0e1b-4574-b447-87220bda33ac

**Additional context**
I'm running a 3 monitor setup via a Displayport MST hub

Neither my CPU nor my GPU are fully utilized when this happens.

**Comment by wallcarpet40** [comment]
I have the same issue. I see you are also using KDE Plasma Wayland.
This might be a regression in KDE Plasma, specifically in Wayland. When I run the session in X11, it works.
There's already a bug report here: https://bugs.kde.org/show_bug.cgi?id=495400
And possible fix is pending here: https://invent.kde.org/plasma/kwin/-/merge_requests/6756

**Comment by the-bukkit** [comment]
I can confirm that it works normally under X11.
So it looks like you're right about it being an issue with KDE Plasma Wayland.

**Comment by the-bukkit** [comment]
Works normally again with KWin 6.2.4-1
