### ISSUE TITLE
[BUG] Bluetooth is not available (Ubuntu 24.04 / Nvidia)

### ISSUE THREAD

**Issue by Hicks79** [ValveSoftware/SteamVR-for-Linux#755]
**Describe the bug**
the devices are correctly connected to bluetooth, however ‘Bluetooth not available’.

**To Reproduce**

**1.-** 
![imagen](https://github.com/user-attachments/assets/e47cf2f4-3a9d-43b5-be20-04e4ffe49532)

i click YES

**2.-**
I recieve this error:
![imagen](https://github.com/user-attachments/assets/eace75e7-5f6f-45df-a78f-6a5c4e05ee6c)

**3.-**
![imagen](https://github.com/user-attachments/assets/f3614b3a-45ca-437c-99c9-5099ad38770d)

**System Information (please complete the following information):**
I use "Steam Beta Update"
* Steam client version (build number or date):
* SteamVR version: 1732590255  (API Steam:  SteamClient021)
* Distribution (e.g. Ubuntu): Ubuntu 24.04 (fresh install)
* Steam runtime diagnostics: [generate via Help -> Steam Runtime Diagnostics in the Steam client]

[diagnostics.txt](https://github.com/user-attachments/files/17924287/forHalfLifeAlyx.txt)

* Steam and SteamVR logs: 
[steam-logs.tar.gz](https://github.com/user-attachments/files/17924355/steam-logs.tar.gz)

I hope thats helps <3

**Comment by kisak-valve** [comment]
Hello @Hicks79, this issue is already being tracked at #207. Closing as a duplicate.
