### ISSUE TITLE
[BUG] Error 307, Compositor Segfault

### ISSUE THREAD

**Issue by UltraBlackLinux** [ValveSoftware/SteamVR-for-Linux#756]
**Describe the bug**
Whenever I try to launch the steamvr app I'm greeted with an error 307
The compositor segfaults and I'm seeing some broken pipe errors in the compositor logs. 
I've some issues similar to this but they don't seem to properly match up with what I'm experiencing

**To Reproduce**
Start the SteamVR app

**Expected behavior**
It should not do that

**System Information (please complete the following information):**
Please use the latest Steam beta client and SteamVR beta for your bug reports!

* Steam client version (build number or date):
* SteamVR version: 2.8.7
* Distribution (e.g. Ubuntu): Endeavor OS
* Steam runtime diagnostics: https://gist.github.com/UltraBlackLinux/4d76588049426a053a9eca13682d3556
* Steam and SteamVR logs: [logs.tar.gz](https://github.com/user-attachments/files/17935643/logs.tar.gz)
* Minidumps: [run the following command: [dumps.tar.gz](https://github.com/user-attachments/files/17935639/dumps.tar.gz)

**Comment by kisak-valve** [comment]
Hello @UltraBlackLinux, your system is configured to use AMDVLK. Can you test how SteamVR behaves with mesa/RADV?

**Comment by UltraBlackLinux** [comment]
Yes, that appears to have worked, thank you! Was there something that I missed that sais that I have to be using radv?

For whatever reason the VR app still complains about not being connected or my DE not supporting VR, even though it is clearly working...

Edit: That was solved by ultimately setting `AMD_VULKAN_ICD=RADV` in /etc/environment instead of running steam with just the environment variables set to use radv
