### ISSUE TITLE
SteamVR-for-Macos

### ISSUE THREAD

**Issue by clankill3r** [ValveSoftware/SteamVR-for-Linux#761]
Please make a SteamVR-for-Macos repository since we have issues too ;)

**Comment by kisak-valve** [comment]
Hello @clankill3r, support for SteamVR on Mac was discontinued in 2020 as posted at https://store.steampowered.com/news/app/250820/view/2216278054495230717.

**Comment by clankill3r** [comment]
I can understand with Mac having almost no gamers and apple trying to trap developers in their eco system.
Well good thing thing I have a PC :)
