### ISSUE TITLE
[BUG] Desktop View blank on wayland

### ISSUE THREAD

**Issue by BreeBreeByte** [ValveSoftware/SteamVR-for-Linux#766]
**Describe the bug**
When I go into VR for the first time after booting my computer, the desktop view does not show up. This also applies to x11, but when I restart it, the desktop view is no longer invisible. On x11 it begins to work functionally. On Wayland it is just a black screen. Although the mouse cursor appears, and my PC shows a notification of if I wish to give SteamVR permissions to give inputs. Allowing does not show the desktop.

**To Reproduce**
1. Open SteamVR on Wayland,
2. Restart so that desktop view is not invisible
3. When desktop view shows up, it is a black screen.

**Expected behavior**
To see my desktop and be able to interact with it.

**System Information:**

* Steam client version 1.0.0.81-2
* SteamVR version: Beta, 2.9.4
* Arch Linux
* 
* Steam runtime diagnostics:
[steamruntime.txt](https://github.com/user-attachments/files/18269084/steamruntime.txt)
* Steam and SteamVR logs: 
[steam-runtime-system-info-1735466662.txt](https://github.com/user-attachments/files/18269078/steam-runtime-system-info-1735466662.txt)

* Minidumps: [steam-minidumps.tar.gz](https://github.com/user-attachments/files/18269092/steam-minidumps.tar.gz)

**Additional Context**
I am aware that there is a very similar bug report to this, but it is detailed differently as I do not experience any crashing.

**Comment by kisak-valve** [comment]
Hello @BreeBreeByte, this issue is already being tracked at #693. Closing as a duplicate.

**Comment by BreeBreeByte** [comment]
I thought this is a different issue, because I do not experience any crashing while that issue reports crashing.
