### ISSUE TITLE
source code for binary missing

### ISSUE THREAD

**Issue by TheRealCuran** [ValveSoftware/SteamVR-for-Linux#8]
You've modified radv and added at least some implementations for extensions like VK_NV_dedicated_allocation or VK_KHX_external_memory. But the necessary patches have not been sent to mesa-dev@lists.freedesktop.org

Please provide the source code and/or work on upstreaming your changes which would then benefit all users of the radv stack.

(Yes, I understand that Mesa's license doesn't **force** you to release these changes, but I'd hope Valve wants to do what's right. Especially since several Valve developers are already active on the various development lists for this open driver stack.)

**Comment by Plagman** [comment]
There's nothing proprietary about the extra features in this radv build, and the patches have been written by Dave Airlie over at Red Hat, not us. The reason it's a binary-only release is that these extensions have not yet been ratified by Khronos, and so the source tree will only be available to other Khronos members until they are, at which point the changes will be submitted upstream. Thanks!

**Comment by ChristophHaag** [comment]
Should be released very soon now: https://github.com/KhronosGroup/Vulkan-Docs/commit/fd0e4c3b67dd07877eae97965e863f2945104d9e

**Comment by ChristophHaag** [comment]
http://airlied.livejournal.com/82522.html
