### ISSUE TITLE
SteamVR compositor doesn't redraw

### ISSUE THREAD

**Issue by ChristophHaag** [ValveSoftware/SteamVR-for-Linux#87]
RX 480, latest mesa radv git etc.

I've had this only since recently.

After starting up, the compositor sometimes renders correctly for a short time, but usually (?) it starts up, renders some garbage around the eyes and then stops rendering anything
![screenshot_20180104_110941](https://user-images.githubusercontent.com/781076/34558869-fcd5895c-f13f-11e7-8b16-2410f2b07098.png)

With the desktop compositor disabled you can see how it doesn't redraw damaged areas:
![screenshot_20180104_111014](https://user-images.githubusercontent.com/781076/34558920-304eb81c-f140-11e7-8614-146d689d7645.png)

The suspect is of course radv.

**Comment by lostgoat** [comment]
Getting reports of this from a few different sources.

**Comment by lostgoat** [comment]
Fixed in http://steamcommunity.com/games/250820/announcements/detail/1584570207540334594

Let me know if it still happens to you though.
