### ISSUE TITLE
SteamVR Refuses to Start and Config Path could not be located (111)

### ISSUE THREAD

**Issue by 1Presidio** [ValveSoftware/SteamVR-for-Linux#89]
#### Your system information
* Steam client version (build number or date): steam_latest
* Distribution (e.g. Ubuntu): Ubuntu 16.04
* Graphics driver version (run nvidia-settings): 387.34 with a GTX 1050 Ti 
* Opted into Steam client beta?: Yes Beta
* Opted into SteamVR beta?: Yes Beta
* Have you checked for system updates?: Yes

#### Please describe your issue in as much detail as possible:
Going to the Steam GUI, I cannot open SteamVR. When I click on it the window opens for a brief second before (probably crashing) disappearing. I am mainly trying to create a Unity App (I know it isn't officially supported but I've seen people using it). 

After attempting to run an app on Unity it says 
"XR: OpenVR Error! OpenVR failed initialization with error code VRInitError_Init_NoConfigPath: "Config path could not be located (111)"

#### Steps for reproducing this issue:
1. Download Steam for Linux
2. Download Unity for Linux
3. Create a new project and import the SteamVR Asset 
4. Delete the Main Camera and replace with the SteamVR Prefabs.
5. Add a test object and press play.
6. Build Error (See above)

I suspect SteamVR not working is causing Unity to not work. I am not sure why SteamVR isn't working. 

Any tips or pointers would be much appreciated.

**Comment by lostgoat** [comment]
I've got a bugfix on the way for a similar issue.

Can you check the following just to make sure it is the same root cause:

1. Open your ~/.config/openvr/openvrpaths.vrpath
2. Your 'config' and 'log' entries are probably set to null
3. Manually change these two fields according to this template: https://gist.github.com/lostgoat/704edb3e8e38d55f4485dfda47622a4c
4. Re-launch steamvr
5. Let me know if it worked :)

**Comment by 1Presidio** [comment]
@lostgoat 

Thank you it worked!

Do you know why it does that? Working with SteamVR previous there was no issue with this.

**Comment by aaronsnoswell** [comment]
Holy moley! I was facing the exact same issue today and @lostgoat's answer above fixed it for me!!! Thank you so much! Been ripping my hair out :P

**Comment by puzzlepaint** [comment]
Thanks. I just had this issue (trying to start SteamVR would output:
```
VR Path Registry node config is not an array
VR Path Registry node log is not an array
VR Path Registry node config is not an array
VR Path Registry node log is not an array
VR Path Registry node config is not an array
VR Path Registry node log is not an array
```
) with an up-to-date Steam beta client and a standard Vive on Ubuntu 14.04, and the solution here worked.
