### ISSUE TITLE
HMD tracking issues with SteamVR beta

### ISSUE THREAD

**Issue by ChristophHaag** [ValveSoftware/SteamVR-for-Linux#91]
I think it has been happening since http://steamcommunity.com/games/250820/announcements/detail/1598082909731919102 and maybe

> Lighthouse:
> Added system for recovering from permanently tilted world. Level should improve immediately, but in the most severe cases the first play session may take a few minutes to show improvement. Corrections are saved on the PC, so moving the HMD to another computer may briefly show the problem again.

has something to do with it (maybe not).

Video demo: https://www.youtube.com/watch?v=Qnx8jOwo3f4
The first time it looks like the whole vrcompositor freezes and the frametime graph pauses too.
The second and third time only the HMD stops tracking and the controllers can still be moved.

These might be different issues.
Both do not happen with SteamVR stable.

**Comment by h1z1** [comment]
Wonder if Valve went through layoffs or something, they don't respond really at all besides  kisak-valve assigning labels.  Maybe just stopped reading github?

**Comment by ChristophHaag** [comment]
Wow this never got closed. Hasn't been an issue for a long time.
