### ISSUE TITLE
SteamVR For Ubuntu Has been crashing, can not be opened.

### ISSUE THREAD

**Issue by ZEFLUO** [ValveSoftware/SteamVR-for-Linux#93]
System information
* Steam client version (build number or date): Jan 25 2018,21:25:07;1516948201
* Distribution (e.g. Ubuntu): Ubuntu 16.04 LTS
* Graphics driver version (run nvidia-settings):Linux-x86_64 Version390.25
* Gist for SteamVR System Information: NA
* Opted into Steam client beta?: [Yes/No]YES
* Opted into SteamVR beta?: [Yes/No]YES
* Have you checked for system updates?: [Yes/No]YES

#### Please describe your issue in as much detail as possible:
Describe what you _expected_ should happen and what _did_ happen. Please link any large code pastes as a [Github Gist](https://gist.github.com/)

#### Steps for reproducing this issue:
1. open Steam
2. open SteamVR
3. Pop-up is starting SteamVR, crash after 1 second, repeat the same problem

PS:STEAM folder found no Runtime folder, do not know how to deal with
+++ dirname ./vrstartup.sh
++ cd ./..
++ pwd
+ TOOLSDIR=/home/zef/.local/share/Steam/steamapps/common/SteamVR
++ cd /home/zef/.local/share/Steam/steamapps/common/SteamVR/../runtime
./vrstartup.sh: 第 3 行: cd: /home/zef/.local/share/Steam/steamapps/common/SteamVR/../runtime: 没有那个文件或目录
++ pwd
+ RUNTIMEDIR=/home/zef/.local/share/Steam/steamapps/common/SteamVR/bin
+ case $(uname) in
++ uname
+ '[' -z '' ']'
+ exec /home/zef/.steam/steam/ubuntu12_32/steam-runtime/run.sh ./vrstartup.sh
+++ dirname /home/zef/.local/share/Steam/steamapps/common/SteamVR/bin/vrstartup.sh
++ cd /home/zef/.local/share/Steam/steamapps/common/SteamVR/bin/..
++ pwd
+ TOOLSDIR=/home/zef/.local/share/Steam/steamapps/common/SteamVR
++ cd /home/zef/.local/share/Steam/steamapps/common/SteamVR/../runtime
/home/zef/.local/share/Steam/steamapps/common/SteamVR/bin/vrstartup.sh: 第 3 行: cd: /home/zef/.local/share/Steam/steamapps/common/SteamVR/../runtime: 没有那个文件或目录
++ pwd
+ RUNTIMEDIR=/home/zef/.local/share/Steam/steamapps/common/SteamVR/bin
+ case $(uname) in
++ uname
+ '[' -z /home/zef/.steam/steam/ubuntu12_32/steam-runtime ']'
+ VRSTARTUP=/home/zef/.local/share/Steam/steamapps/common/SteamVR/bin/linux64/vrstartup
+ QT_DIR=/home/zef/.local/share/Steam/steamapps/common/SteamVR/bin/linux64/qt
+ export LD_LIBRARY_PATH=.:/home/zef/.local/share/Steam/steamapps/common/SteamVR/bin/bin/linux64:/home/zef/.local/share/Steam/steamapps/common/SteamVR/bin/linux64/qt/lib:/home/zef/.local/share/Steam/steamapps/common/SteamVR/bin/linux64:/home/zef/.steam/steam/ubuntu12_32/steam-runtime/pinned_libs_32:/home/zef/.steam/steam/ubuntu12_32/steam-runtime/pinned_libs_64:/usr/lib/x86_64-linux-gnu/libfakeroot:/lib/i386-linux-gnu:/usr/lib/i386-linux-gnu:/usr/local/lib:/lib/x86_64-linux-gnu:/usr/lib/x86_64-linux-gnu:/usr/lib/nvidia-390:/usr/lib32/nvidia-390:/lib32:/usr/lib32:/lib:/usr/lib:/usr/lib/nvidia-390/tls:/usr/lib32/nvidia-390/tls:/home/zef/.steam/steam/ubuntu12_32/steam-runtime/i386/lib/i386-linux-gnu:/home/zef/.steam/steam/ubuntu12_32/steam-runtime/i386/lib:/home/zef/.steam/steam/ubuntu12_32/steam-runtime/i386/usr/lib/i386-linux-gnu:/home/zef/.steam/steam/ubuntu12_32/steam-runtime/i386/usr/lib:/home/zef/.steam/steam/ubuntu12_32/steam-runtime/amd64/lib/x86_64-linux-gnu:/home/zef/.steam/steam/ubuntu12_32/steam-runtime/amd64/lib:/home/zef/.steam/steam/ubuntu12_32/steam-runtime/amd64/usr/lib/x86_64-linux-gnu:/home/zef/.steam/steam/ubuntu12_32/steam-runtime/amd64/usr/lib:
+ LD_LIBRARY_PATH=.:/home/zef/.local/share/Steam/steamapps/common/SteamVR/bin/bin/linux64:/home/zef/.local/share/Steam/steamapps/common/SteamVR/bin/linux64/qt/lib:/home/zef/.local/share/Steam/steamapps/common/SteamVR/bin/linux64:/home/zef/.steam/steam/ubuntu12_32/steam-runtime/pinned_libs_32:/home/zef/.steam/steam/ubuntu12_32/steam-runtime/pinned_libs_64:/usr/lib/x86_64-linux-gnu/libfakeroot:/lib/i386-linux-gnu:/usr/lib/i386-linux-gnu:/usr/local/lib:/lib/x86_64-linux-gnu:/usr/lib/x86_64-linux-gnu:/usr/lib/nvidia-390:/usr/lib32/nvidia-390:/lib32:/usr/lib32:/lib:/usr/lib:/usr/lib/nvidia-390/tls:/usr/lib32/nvidia-390/tls:/home/zef/.steam/steam/ubuntu12_32/steam-runtime/i386/lib/i386-linux-gnu:/home/zef/.steam/steam/ubuntu12_32/steam-runtime/i386/lib:/home/zef/.steam/steam/ubuntu12_32/steam-runtime/i386/usr/lib/i386-linux-gnu:/home/zef/.steam/steam/ubuntu12_32/steam-runtime/i386/usr/lib:/home/zef/.steam/steam/ubuntu12_32/steam-runtime/amd64/lib/x86_64-linux-gnu:/home/zef/.steam/steam/ubuntu12_32/steam-runtime/amd64/lib:/home/zef/.steam/steam/ubuntu12_32/steam-runtime/amd64/usr/lib/x86_64-linux-gnu:/home/zef/.steam/steam/ubuntu12_32/steam-runtime/amd64/usr/lib:
+ export QT_PLUGIN_PATH=/home/zef/.local/share/Steam/steamapps/common/SteamVR/bin/linux64/qt/plugins
+ QT_PLUGIN_PATH=/home/zef/.local/share/Steam/steamapps/common/SteamVR/bin/linux64/qt/plugins
+ exec /home/zef/.local/share/Steam/steamapps/common/SteamVR/bin/linux64/vrstartup
VR Path Registry node config is not an array
VR Path Registry node log is not an array
VR Path Registry node config is not an array
VR Path Registry node log is not an array
VR Path Registry node config is not an array
VR Path Registry node log is not an array

**Comment by lostgoat** [comment]
See the following thread for a temporary workaround:
https://github.com/ValveSoftware/SteamVR-for-Linux/issues/89

There will be a steam client update to fix this issue.

**Comment by lostgoat** [comment]
A steam beta client update has been released with a proper fix for this issue.
